{

  "blob_title": {
    "en_US": "Buddy list ({amount})",
    "de_DE": "Freundesliste ({amount})"
  },
  "add_success": {
    "en_US": "Character <highlight>{char}<end> has been added to the buddy list for type <highlight>{type}<end>.",
    "de_DE": "Der Charakter <highlight>{char}<end> wurde der Freundesliste als <highlight>{type}<end> hinzugefügt."
  },
  "rem_all": {
    "en_US": "Removed all <highlight>{count}<end> buddies from the buddy list.",
    "de_DE": "Es wurden <highlight>{count}<end> Freunde aus der Freundesliste entfernt."
  },
  "rem_single": {
    "en_US": "Character <highlight>{char}<end> has been removed from the buddy list for type <highlight>{type}<end>.",
    "de_DE": "Der Charakter <highlight>{char}<end> ist nun nicht mehr als <highlight>{type}<end> in der Freundesliste."
  },
  "rem_orphaned": {
    "en_US": "Removed <highlight>{count}<end> orphaned buddies from the buddy list.",
    "de_DE": "Es wurden <highlight>{count}<end> verwaiste Freunde entfernt."
  },
  "search_title": {
    "en_US": "Buddy List Search Results ({amount})",
    "de_DE": "Ergebnis der Suche in der Freundesliste ({amount})"
  }
}