{

  "blob_title": {
    "en_US": "Buddy list ({amount})",
    "de_DE": "Freundesliste ({amount})"
  },
  "add_success": {
    "en_US": "Character <highlight>{char}</highlight> has been added to the buddy list for type <highlight>{type}</highlight>.",
    "de_DE": "Der Charakter <highlight>{char}</highlight> wurde der Freundesliste als <highlight>{type}</highlight> hinzugefügt."
  },
  "rem_all": {
    "en_US": "Removed all <highlight>{count}</highlight> buddies from the buddy list.",
    "de_DE": "Es wurden <highlight>{count}</highlight> Freunde aus der Freundesliste entfernt."
  },
  "rem_single": {
    "en_US": "Character <highlight>{char}</highlight> has been removed from the buddy list for type <highlight>{type}</highlight>.",
    "de_DE": "Der Charakter <highlight>{char}</highlight> ist nun nicht mehr als <highlight>{type}</highlight> in der Freundesliste."
  },
  "rem_orphaned": {
    "en_US": "Removed <highlight>{count}</highlight> orphaned buddies from the buddy list.",
    "de_DE": "Es wurden <highlight>{count}</highlight> verwaiste Freunde entfernt."
  },
  "search_title": {
    "en_US": "Buddy List Search Results ({amount})",
    "de_DE": "Ergebnis der Suche in der Freundesliste ({amount})"
  }
}
