FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN apt update && apt upgrade -y

ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then apt-get -y install gcc; fi

WORKDIR /app
COPY requirements.txt /app
RUN uv pip install --no-cache --system -r requirements.txt

RUN adduser --no-create-home --disabled-login --disabled-password --shell /bin/false --gecos "" --uid 1001 user && \
    mkdir -p /app/data && \
    chown -R user:user /app

USER user

ENV PYTHONPATH=/app

CMD ["python", "-m", "unittest", "discover", "-p", "*_test.py"]
