FROM python:3.6.6

WORKDIR /app

ADD . /app

RUN pip install  --no-cache-dir -r requirements.txt && \
    useradd user && \
    chown user conf && \
    chown user data  
USER user 

CMD ["/app/prod-start.sh"]
