DROP TABLE IF EXISTS Cluster;
CREATE TABLE Cluster (ClusterID INT NOT NULL PRIMARY KEY, EffectTypeID INT NOT NULL, LongName VARCHAR(50) NOT NULL, NPReq INT NOT NULL, AltName VARCHAR(50) NOT NULL);
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (0,1,'',0,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (2,1,'1 Handed Blunt Weapons',720,'1h Blunt');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (3,1,'1 Handed Edged Weapon',760,'1h Edged');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (4,1,'2 Handed Blunt Weapons',720,'2h Blunt');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (5,1,'2 Handed Edged Weapons',760,'2h Edged');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (6,1,'Adventuring',600,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (7,2,'Agility',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (8,1,'Aimed Shot',840,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (9,1,'Assault Rifle',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (10,16,'Biological Metamorphosis',960,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (11,1,'Body Development',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (12,1,'Bow',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (13,1,'Bow Special Attack',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (14,1,'Brawling',660,'Brawl');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (15,1,'Breaking and Entry',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (16,1,'Burst',840,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (17,3,'Chemical AC',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (18,1,'Chemistry',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (19,3,'Cold AC',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (20,1,'Computer Literacy',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (21,1,'Concealment',720,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (22,1,'Dimach',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (24,1,'Dodge Ranged Attacks',800,'Dodge Ranged');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (25,1,'Duck Explosives',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (26,1,'Electrical Engineering',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (27,3,'Energy AC',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (28,1,'Evade Close Combat',800,'Evade Close');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (29,1,'Fast Attack',760,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (30,3,'Fire AC',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (31,1,'First Aid',720,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (32,1,'Fling Shot',720,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (33,1,'Full Auto',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (34,1,'Grenade Throwing',760,'Grenade');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (35,1,'Heavy Weapons',400,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (36,3,'Projectile AC',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (37,2,'Intelligence',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (38,1,'Map Navigation',500,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (39,1,'Martial Arts',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (40,16,'Matter Creation',960,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (41,16,'Matter Metamorphosis',960,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (42,4,'Max Health',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (43,4,'Max Nano',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (44,1,'Mechanical Engineering',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (45,1,'Melee Energy Weapons',800,'Melee Energy');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (46,1,'Melee Weapons Initiative',800,'Melee Init');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (47,3,'Melee AC',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (48,1,'MG/SMG',800,'SMG');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (49,1,'Multiple Melee Weapons',900,'Multi Melee');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (50,1,'Multiple Ranged Weapons',800,'Multi Ranged');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (51,1,'Nano Initiative',800,'Nano Init');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (52,1,'Nano Pool',1200,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (53,1,'Nano Programming',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (54,1,'Nano Resistance',800,'Nano Resist');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (55,1,'Parry',840,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (56,1,'Perception',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (57,1,'Pharmaceuticals',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (58,1,'Physical Initiative',800,'Physical Init');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (59,1,'Piercing',640,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (60,1,'Pistol',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (61,2,'Psychic',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (62,16,'Psychological Modifications',960,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (63,1,'Psychology',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (64,1,'Quantum Physics',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (65,3,'Radiation AC',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (66,1,'Ranged Energy',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (67,1,'Ranged Initiative',800,'Ranged Init');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (68,1,'Rifle',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (69,1,'Riposte',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (70,1,'Run Speed',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (71,2,'Sense',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (72,16,'Sensory Improvement',880,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (73,1,'Sharp Objects',500,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (74,1,'Shotgun',680,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (75,1,'Sneak Attack',1000,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (76,2,'Stamina',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (77,2,'Strength',900,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (78,1,'Swimming',500,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (79,16,'Time and Space',960,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (80,1,'Trap Disarming',720,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (81,1,'Treatment',860,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (82,1,'Tutoring',520,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (83,1,'Vehicle Air',400,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (84,1,'Vehicle Ground',600,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (85,1,'Vehicle Water',480,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (86,1,'Weapon Smithing',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (87,15,'Nano Delta*',1,'Nano Delta');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (88,15,'Heal Delta*',1,'Heal Delta');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (89,8,'Add All Defense*',1,'Defense modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (90,9,'Add All Offense*',1,'Offense modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (91,10,'Add Max NCU*',1,'NCU Memory');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (92,5,'Add XP (%)*',1,'Experience Modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (93,12,'Nano Interrupt (%)*',1,'Nano interrupt chance');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (94,6,'Add Chemical Damage*',1,'Chemical damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (95,6,'Add Energy Damage*',1,'Energy damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (96,6,'Add Fire Damage*',1,'Fire damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (97,6,'Add Melee Damage*',1,'Melee damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (98,6,'Add Poison Damage*',1,'Poison damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (99,6,'Add Projectile Damage*',1,'Projectile damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (100,6,'Add Radiation Damage*',1,'Radiation damage modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (101,7,'Chemical Damage Shield*',1,'Shield Chemical Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (102,7,'Cold Damage Shield*',1,'Shield Cold Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (103,7,'Energy Damage Shield*',1,'Shield Energy Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (104,7,'Fire Damage Shield*',1,'Shield Fire Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (105,7,'Melee Damage Shield*',1,'Shield Melee Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (106,7,'Poison Damage Shield*',1,'Shield Poison Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (107,7,'Projectile Damage Shield*',1,'Shield Projectile Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (108,7,'Radiation Damage Shield*',1,'Shield Radiation Damage');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (109,11,'Skill Lock (%)*',1,'Skill Lock Modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (110,13,'Nano Cost (%)*',1,'Nano cost modifier');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (111,14,'Add Nano Range (%)*',1,'Nano Range');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (112,3,'Poison AC',800,'');
INSERT INTO Cluster (ClusterID, EffectTypeID, LongName, NPReq, AltName) VALUES (130,14,'Add Weapon Range (%)*',1,'');
