DROP TABLE IF EXISTS EffectValue;
CREATE TABLE EffectValue (EffectID INT NOT NULL PRIMARY KEY, Name VARCHAR(50) NOT NULL, Q200Value INT NOT NULL);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (1,'AC Faded',162);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (2,'AC Bright',243);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (3,'AC Shining',405);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (4,'AC Faded QL300',275);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (5,'AC Bright QL300',412);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (6,'AC Shining QL300',687);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (7,'Life/Nano Faded',162);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (8,'Life/Nano Bright',243);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (9,'Life/Nano Shining',405);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (10,'Life/Nano Faded QL300',220);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (11,'Life/Nano Bright QL300',330);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (12,'Life/Nano Shining QL300',550);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (13,'AddAll Faded',52);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (14,'AddAll Bright',78);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (15,'AddAll Shining',130);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (16,'AddAll Faded QL300',70);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (17,'AddAll Bright QL300',105);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (18,'AddAll Shining QL300',175);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (19,'MaxNCU Faded',12);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (20,'MaxNCU Bright',18);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (21,'MaxNCU Shining',30);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (22,'MaxNCU Faded QL300',16);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (23,'MaxNCU Bright QL300',23);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (24,'MaxNCU Shining QL300',39);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (25,'XPMod Faded',3);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (26,'XPMod Bright',4);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (27,'XPMod Shining',7);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (28,'XPMod Faded QL300',3);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (29,'XPMod Bright QL300',5);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (30,'XPMod Shining QL300',8);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (31,'Nano Interrupt Faded',-2);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (32,'Nano Interrupt Bright',-3);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (33,'Nano Interrupt Shining',-5);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (34,'Nano Interrupt Faded QL300',-3);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (35,'Nano Interrupt Bright QL300',-5);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (36,'Nano Interrupt Shining QL300',-9);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (37,'Shield Faded',8);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (38,'Shield Bright',12);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (39,'Shield Shining',20);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (40,'Shield Faded QL300',10);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (41,'Shield Bright QL300',15);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (42,'Shield Shining QL300',25);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (43,'Damage Faded',7);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (44,'Damage Bright',10);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (45,'Damage Shining',18);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (46,'Damage Faded QL300',9);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (47,'Damage Bright QL300',13);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (48,'Damage Shining QL300',22);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (49,'Range Faded',6);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (50,'Range Bright',9);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (51,'Range Shining',15);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (52,'Range Faded QL300',7);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (53,'Range Bright QL300',11);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (54,'Range Shining QL300',19);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (55,'Nano Cost Faded',-1);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (56,'Nano Cost Bright',-2);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (57,'Nano Cost Shining',-2);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (58,'Nano Cost Faded QL300',-2);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (59,'Nano Cost Bright QL300',-3);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (60,'Nano Cost Shining QL300',-5);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (61,'Skill Faded ',42);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (62,'Skill Bright',63);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (63,'Skill Shining',105);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (64,'Ability Faded',22);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (65,'Ability Bright',33);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (66,'Ability Shining',55);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (67,'Skill Faded QL300',57);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (68,'Skill Bright QL300',85);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (69,'Skill Shining QL300',141);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (70,'Ability Faded QL300',29);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (71,'Ability Bright QL300',44);
INSERT INTO EffectValue (EffectID, Name, Q200Value) VALUES (72,'Ability Shining QL300',73);
