DROP TABLE IF EXISTS ImplantType;
CREATE TABLE ImplantType (ImplantTypeID INT NOT NULL PRIMARY KEY, Name VARCHAR(20) NOT NULL, ShortName VARCHAR(10) NOT NULL);
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (1,'Eye','eye');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (2,'Head','head');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (3,'Ear','ear');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (4,'Chest','chest');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (5,'Waist','waist');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (6,'Leg','legs');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (7,'Feet','feet');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (8,'Left Arm','larm');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (9,'Left Wrist','lwrist');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (10,'Left Hand','lhand');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (11,'Right Arm','rarm');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (12,'Right Wrist','rwrist');
INSERT INTO ImplantType (ImplantTypeID, Name, ShortName) VALUES (13,'Right Hand','rhand');
