{
  "broadcast_list": {
    "en_US": "Broadcast List ({count})",
    "de_DE": "Broadcast Liste ({count})"
  },
  "add_fail": {
    "en_US": "Error! <highlight>{char}<end> already exists on the broadcast list.",
    "de_DE": "Error! <highlight>{char}<end> ist bereits auf der Broadcast Liste."
  },
  "add_success": {
    "en_US": "<highlight>{char}<end> has been added to the broadcast list.",
    "de_DE": "<highlight>{char}<end> wurde zur Broadcast Liste hinzugefügt."
  },
  "rem_fail": {
    "en_US": "Error! <highlight>{char}<end> does not exist on the broadcast list.",
    "de_DE": "Error! <highlight>{char}<end> ist nicht auf der Broadcast Liste."
  },
  "rem_success": {
    "en_US": "<highlight>{char}<end> has been removed from the broadcast list.",
    "de_DE": "<highlight>{char}<end> wurde von der Broadcast Liste entfernt."
  }
}