{
    "no_guide_id": {
        "en_US": "Could not find AO-Universe guide with id <highlight>{id}</highlight>.",
        "de_DE": "Es konnte kein AO-Universe Guide mit der ID <highlight>{id}</highlight> gefunden werden."
    },
    "guide": {
        "en_US": [
            "\n",
            "ID: {id} ({raw})\n",
            "Updated: <highlight>{updated}</highlight>\n",
            "Profession: <highlight>{profession}</highlight>\n",
            "Faction: <highlight>{faction}</highlight>\n",
            "Level: <highlight>{level}</highlight>\n",
            "Author: <highlight>{author}</highlight>\n\n",
            "{text}\n\n",
            " - <highlight>Powered by</highlight> {aou}"
        ],
        "de_DE": [
            "\n",
            "ID: {id} ({raw})\n",
            "Letztes Update: <highlight>{updated}</highlight>\n",
            "Profession: <highlight>{profession}</highlight>\n",
            "Faction: <highlight>{faction}</highlight>\n",
            "Level: <highlight>{level}</highlight>\n",
            "Autor: <highlight>{author}</highlight>\n\n",
            "{text}\n\n",
            " - <highlight>Unterstützt von</highlight> {aou}"
        ]
    },
    "no_guide_search": {
        "en_US": "Could not find any AO-Universe guides for search <highlight>{search}</highlight>.",
        "de_DE": "Die Suche nach einem AO-Universe Guide mit dem Inhalt <highlight>{search}</highlight> hatte kein Ergebnis.."
    },
    "search_guide_title":{
        "en_US": "AOU Guides containing '{search}' ({count})",
        "de_DE": "AOU Guides mit dem Inhalt '{search}' ({count})"
    },
    "search_guide_title_all":{
        "en_US": "All AOU Guides containing '{search}' ({count})",
        "de_DE": "Alle AOU Guides mit dem Inhalt '{search}' ({count})"
    }
}
