{
    "no_guide_id": {
        "en_US": "Could not find AO-Universe guide with id <highlight>{id}<end>.",
        "de_DE": "Es konnte kein AO-Universe Guide mit der ID <highlight>{id}<end> gefunden werden."
    },
    "guide": {
        "en_US": [
            "\n",
            "ID: {id}\n",
            "Updated: <highlight>{updated}<end>\n",
            "Profession: <highlight>{profession}<end>\n",
            "Faction: <highlight>{faction}<end>\n",
            "Level: <highlight>{level}<end>\n",
            "Author: <highlight>{author}<end>\n\n",
            "{text}\n\n",
            " - <highlight>Powered by<end> {aou}"
        ],
        "de_DE": [
            "\n",
            "ID: {id}\n",
            "Letztes Update: <highlight>{updated}<end>\n",
            "Profession: <highlight>{profession}<end>\n",
            "Faction: <highlight>{faction}<end>\n",
            "Level: <highlight>{level}<end>\n",
            "Autor: <highlight>{author}<end>\n\n",
            "{text}\n\n",
            " - <highlight>Unterstützt von<end> {aou}"
        ]
    },
    "no_guide_search": {
        "en_US": "Could not find any AO-Universe guides for search <highlight>{search}<end>.",
        "de_DE": "Die Suche nach einem AO-Universe Guide mit dem Inhalt <highlight>{search}<end> hatte kein Ergebnis.."
    },
    "search_guide_title":{
        "en_US": "AOU Guides containing '{search}' ({count})",
        "de_DE": "AOU Guides mit dem Inhalt '{search}' ({count})"
    },

    "search_guide_title_all":{
        "en_US": "All AOU Guides containing '{search}' ({count})",
        "de_DE": "Alle AOU Guides mit dem Inhalt '{search}' ({count})"
    }
}