{
  "invite_fail": {
    "en_US": "<highlight>{target}<end> is already in the private channel.",
    "de_DE": "Der Spieler <highlight>{target}<end> ist bereits ein MItglied des privaten Channels."
  },
  "invite_success_target": {
    "en_US": "You have been invited to the private channel by <highlight>{inviter}<end>.",
    "de_DE": "Du wurdest von <highlight>{inviter}<end> zu meinem privaten Channel eingeladen."
  },
  "invite_success_self": {
    "en_US": "You have invited <highlight>{target}<end> to the private channel.",
    "de_DE": "Du hast <highlight>{target}<end>  erfolgreich in den privaten Channel eingeladen."
  },
  "kick_success_target": {
    "en_US": "You have been kicked from the private channel by <highlight>{kicker}<end>.",
    "de_DE": "Du wurdest von <highlight>{kicker}<end> aus dem privaten Channel gekickt."
  },
  "kick_success_self": {
    "en_US": "You have kicked <highlight>{target}<end> from the private channel.",
    "de_DE": "Du hast <highlight>{target}<end> aus dem privaten Channel gekickt."
  },
  "kick_fail": {
    "en_US": "You do not have the required access level to kick <highlight>{target}<end>.",
    "de_DE": "Du hast nicht das benötigte Zugriffslevel, um <highlight>{target}<end> zu kicken."
  },
  "kick_fail_not_in_priv": {
    "en_US": "<highlight>{target}<end> is not an member of the private channel.",
    "de_DE": "<highlight>{target}<end> ist kein Mitglied des privaten Channels."
  },
  "join": {
    "en_US": "{char} has joined the private channel. {logon}",
    "de_DE": "{char} ist dem privaten Channel beigetreten. {logon}"
  },
  "leave": {
    "en_US": "<highlight>{char}<end> has left the private channel. {logoff}",
    "de_DE": "<highlight>{char}<end> hat den privaten Channel verlassen. {logoff}"
  },
  "kick_all": {
    "en_US": "Everyone will be kicked from this channel in 10 seconds. [by <highlight>{char}<end>]",
    "de_DE": "In 10 Sekunden wird jeder aus dem Channel gekickt. [von <highlight>{char}<end>]"
  },
  "mem_add_fail": {
    "en_US": "<highlight>{char}<end> is already a member.",
    "de_DE": "<highlight>{char}<end> ist bereits ein Mitglied."
  },
  "mem_add_success": {
    "en_US": "<highlight>{char}<end> has been added as a member.",
    "de_DE": "<highlight>{char}<end> wurde als Mitglied hinzugefügt."
  },
  "mem_rem_success": {
    "en_US": "<highlight>{char}<end> has been removed as a member.",
    "de_DE": "<highlight>{char}<end> wurde als Mitglied entfernt."
  },
  "mem_rem_fail": {
    "en_US": "<highlight>{char}<end> is not a member.",
    "de_DE": "<highlight>{char}<end> ist kein Mitglied."
  },
  "blob_mem_list": {
    "en_US": "Members ({amount})",
    "de_DE": "Mitglieder ({amount})"
  },
  "autoinvite_changed": {
    "en_US": "Your auto invite preference has been set to <highlight>{changedto}<end>.",
    "de_DE": "Deine Autoinvite Einstellung ist nun <highlight>{changedto}<end>"
  },
  "not_an_member": {
    "en_US": "You must be a member of this bot to set your auto invite preference.",
    "de_DE": "Du musst ein Mitglied des Bots sein, um deine Autoinvite Einstellung zu setzen."
  },
  "auto_invited": {
    "en_US": "You have been auto-invited to the private channel.",
    "de_DE": "Du wurdest automatsich in meinen privaten Channel eingeladen."
  },
  "on": {
    "en_US": "on",
    "de_DE": "an"
  },
  "off": {
    "en_US": "off",
    "de_DE": "aus"
  }
}