{
  "invite_fail": {
    "en_US": "<highlight>{target}</highlight> is already in the private channel.",
    "de_DE": "Der Spieler <highlight>{target}</highlight> ist bereits ein MItglied des privaten Channels."
  },
  "invite_success_target": {
    "en_US": "You have been invited to the private channel by <highlight>{inviter}</highlight>.",
    "de_DE": "Du wurdest von <highlight>{inviter}</highlight> zu meinem privaten Channel eingeladen."
  },
  "invite_success_self": {
    "en_US": "You have invited <highlight>{target}</highlight> to the private channel.",
    "de_DE": "Du hast <highlight>{target}</highlight>  erfolgreich in den privaten Channel eingeladen."
  },
  "kick_success_target": {
    "en_US": "You have been kicked from the private channel by <highlight>{kicker}</highlight>.",
    "de_DE": "Du wurdest von <highlight>{kicker}</highlight> aus dem privaten Channel gekickt."
  },
  "kick_success_self": {
    "en_US": "You have kicked <highlight>{target}</highlight> from the private channel.",
    "de_DE": "Du hast <highlight>{target}</highlight> aus dem privaten Channel gekickt."
  },
  "kick_fail": {
    "en_US": "You do not have the required access level to kick <highlight>{target}</highlight>.",
    "de_DE": "Du hast nicht das benötigte Zugriffslevel, um <highlight>{target}</highlight> zu kicken."
  },
  "kick_fail_not_in_priv": {
    "en_US": "<highlight>{target}</highlight> is not an member of the private channel.",
    "de_DE": "<highlight>{target}</highlight> ist kein Mitglied des privaten Channels."
  },
  "join": {
    "en_US": "{char} has joined the private channel. {logon}",
    "de_DE": "{char} ist dem privaten Channel beigetreten. {logon}"
  },
  "leave": {
    "en_US": "<highlight>{char}</highlight> has left the private channel. {logoff}",
    "de_DE": "<highlight>{char}</highlight> hat den privaten Channel verlassen. {logoff}"
  },
  "kick_all": {
    "en_US": "Everyone will be kicked from this channel in 10 seconds. [by <highlight>{char}</highlight>]",
    "de_DE": "In 10 Sekunden wird jeder aus dem Channel gekickt. [von <highlight>{char}</highlight>]"
  },
  "mem_add_fail": {
    "en_US": "<highlight>{char}</highlight> is already a member.",
    "de_DE": "<highlight>{char}</highlight> ist bereits ein Mitglied."
  },
  "mem_add_success": {
    "en_US": "<highlight>{char}</highlight> has been added as a member.",
    "de_DE": "<highlight>{char}</highlight> wurde als Mitglied hinzugefügt."
  },
  "mem_rem_success": {
    "en_US": "<highlight>{char}</highlight> has been removed as a member.",
    "de_DE": "<highlight>{char}</highlight> wurde als Mitglied entfernt."
  },
  "mem_rem_fail": {
    "en_US": "<highlight>{char}</highlight> is not a member.",
    "de_DE": "<highlight>{char}</highlight> ist kein Mitglied."
  },
  "blob_mem_list": {
    "en_US": "Members ({amount})",
    "de_DE": "Mitglieder ({amount})"
  },
  "autoinvite_changed": {
    "en_US": "Your auto invite preference has been set to <highlight>{changedto}</highlight>.",
    "de_DE": "Deine Autoinvite Einstellung ist nun <highlight>{changedto}</highlight>."
  },
  "not_an_member": {
    "en_US": "You must be a member of this bot to set your auto invite preference.",
    "de_DE": "Du musst ein Mitglied des Bots sein, um deine Autoinvite Einstellung zu setzen."
  },
  "auto_invited": {
    "en_US": "You have been auto-invited to the private channel.",
    "de_DE": "Du wurdest automatsich in meinen privaten Channel eingeladen."
  },
  "on": {
    "en_US": "on",
    "de_DE": "an"
  },
  "off": {
    "en_US": "off",
    "de_DE": "aus"
  }
}
