DROP TABLE IF EXISTS skills;
CREATE TABLE skills (id INT NOT NULL PRIMARY KEY, name VARCHAR(50) NOT NULL, common_name VARCHAR(50) NOT NULL);
INSERT INTO skills (id, name, common_name) VALUES (318, '% Add. Nano Cost', '');
INSERT INTO skills (id, name, common_name) VALUES (319, '% Add. Xp', '');
INSERT INTO skills (id, name, common_name) VALUES (102, '1h Blunt', '1 handed blunt');
INSERT INTO skills (id, name, common_name) VALUES (103, '1h Edged', '1 handed edged');
INSERT INTO skills (id, name, common_name) VALUES (107, '2h Blunt', '2 handed blunt');
INSERT INTO skills (id, name, common_name) VALUES (105, '2h Edged', '2 handed edged');
INSERT INTO skills (id, name, common_name) VALUES (277, 'Add All Def.', '');
INSERT INTO skills (id, name, common_name) VALUES (276, 'Add All Off.', '');
INSERT INTO skills (id, name, common_name) VALUES (281, 'Add. Chem. Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (311, 'Add. Cold Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (280, 'Add. Energy Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (316, 'Add. Fire Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (279, 'Add. Melee Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (315, 'Add. Nano Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (317, 'Add. Poison Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (278, 'Add. Proj. Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (282, 'Add. Rad. Dam.', '');
INSERT INTO skills (id, name, common_name) VALUES (137, 'Adventuring', '');
INSERT INTO skills (id, name, common_name) VALUES (51, 'Aggdef', '');
INSERT INTO skills (id, name, common_name) VALUES (201, 'Aggressiveness', '');
INSERT INTO skills (id, name, common_name) VALUES (17, 'Agility', '');
INSERT INTO skills (id, name, common_name) VALUES (151, 'Aimed Shot', '');
INSERT INTO skills (id, name, common_name) VALUES (116, 'Assault Rif', 'Assault Rifle');
INSERT INTO skills (id, name, common_name) VALUES (22, 'Attack rating', '');
INSERT INTO skills (id, name, common_name) VALUES (128, 'Bio Metamor', 'Biological Metamorphosis');
INSERT INTO skills (id, name, common_name) VALUES (152, 'Body Dev.', 'Body Development');
INSERT INTO skills (id, name, common_name) VALUES (111, 'Bow', '');
INSERT INTO skills (id, name, common_name) VALUES (121, 'Bow Spc Att', 'Bow Special Attack');
INSERT INTO skills (id, name, common_name) VALUES (142, 'Brawling', '');
INSERT INTO skills (id, name, common_name) VALUES (165, 'Break&Entry', 'Breaking and Entering');
INSERT INTO skills (id, name, common_name) VALUES (148, 'Burst', '');
INSERT INTO skills (id, name, common_name) VALUES (93, 'Chemical AC', '');
INSERT INTO skills (id, name, common_name) VALUES (163, 'Chemistry', '');
INSERT INTO skills (id, name, common_name) VALUES (95, 'Cold AC', '');
INSERT INTO skills (id, name, common_name) VALUES (161, 'Comp. Liter', 'Computer Literacy');
INSERT INTO skills (id, name, common_name) VALUES (164, 'Concealment', '');
INSERT INTO skills (id, name, common_name) VALUES (391, 'Critical Decrease', '');
INSERT INTO skills (id, name, common_name) VALUES (379, 'CriticalIncrease', '');
INSERT INTO skills (id, name, common_name) VALUES (35, 'Damage to Pet', '');
INSERT INTO skills (id, name, common_name) VALUES (39, 'Damage To Pet Damage Multiplier', '');
INSERT INTO skills (id, name, common_name) VALUES (383, 'Decreased Nano-Interrupt Modifier %', '');
INSERT INTO skills (id, name, common_name) VALUES (145, 'Deflect', '');
INSERT INTO skills (id, name, common_name) VALUES (144, 'Dimach', '');
INSERT INTO skills (id, name, common_name) VALUES (536, 'Direct Nano Damage Efficiency', '');
INSERT INTO skills (id, name, common_name) VALUES (96, 'Disease AC', '');
INSERT INTO skills (id, name, common_name) VALUES (154, 'Dodge-Rng', 'Dodge Range');
INSERT INTO skills (id, name, common_name) VALUES (153, 'Duck-Exp', 'Duck Explosives');
INSERT INTO skills (id, name, common_name) VALUES (126, 'Elec. Engi', 'Electrical Engineering');
INSERT INTO skills (id, name, common_name) VALUES (92, 'Energy AC', '');
INSERT INTO skills (id, name, common_name) VALUES (155, 'Evade-ClsC', 'Evade Close Combat');
INSERT INTO skills (id, name, common_name) VALUES (147, 'Fast Attack', '');
INSERT INTO skills (id, name, common_name) VALUES (97, 'Fire AC', '');
INSERT INTO skills (id, name, common_name) VALUES (123, 'First Aid', '');
INSERT INTO skills (id, name, common_name) VALUES (150, 'Fling Shot', '');
INSERT INTO skills (id, name, common_name) VALUES (45, 'Free deck slot', '');
INSERT INTO skills (id, name, common_name) VALUES (167, 'Full Auto', '');
INSERT INTO skills (id, name, common_name) VALUES (109, 'Grenade', '');
INSERT INTO skills (id, name, common_name) VALUES (689, 'Heal Reactivity', '');
INSERT INTO skills (id, name, common_name) VALUES (343, 'HealDelta', '');
INSERT INTO skills (id, name, common_name) VALUES (535, 'Healing Efficiency', '');
INSERT INTO skills (id, name, common_name) VALUES (110, 'Heavy Weapons', '');
INSERT INTO skills (id, name, common_name) VALUES (90, 'Imp/Proj AC', 'Projectile AC');
INSERT INTO skills (id, name, common_name) VALUES (19, 'Intelligence', '');
INSERT INTO skills (id, name, common_name) VALUES (100, 'Martial Arts', '');
INSERT INTO skills (id, name, common_name) VALUES (127, 'Matt.Metam', 'Matter Metamorphosis');
INSERT INTO skills (id, name, common_name) VALUES (130, 'Matter Crea', 'Matter Creation');
INSERT INTO skills (id, name, common_name) VALUES (1, 'Max Health', '');
INSERT INTO skills (id, name, common_name) VALUES (221, 'Max Nano', '');
INSERT INTO skills (id, name, common_name) VALUES (181, 'Max NCU', '');
INSERT INTO skills (id, name, common_name) VALUES (478, 'MaxReflectedChemicalDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (480, 'MaxReflectedColdDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (477, 'MaxReflectedEnergyDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (482, 'MaxReflectedFireDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (476, 'MaxReflectedMeleeDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (481, 'MaxReflectedNanoDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (483, 'MaxReflectedPoisonDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (475, 'MaxReflectedProjectileDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (479, 'MaxReflectedRadiationDmg', '');
INSERT INTO skills (id, name, common_name) VALUES (125, 'Mech. Engi', 'Mechanical Engineering');
INSERT INTO skills (id, name, common_name) VALUES (104, 'Melee Ener.', 'Melee Energy');
INSERT INTO skills (id, name, common_name) VALUES (118, 'Melee. Init.', 'Melee Initiative');
INSERT INTO skills (id, name, common_name) VALUES (91, 'Melee/ma AC', 'Melee/Martial Arts AC');
INSERT INTO skills (id, name, common_name) VALUES (114, 'MG / SMG', '');
INSERT INTO skills (id, name, common_name) VALUES (101, 'Mult. Melee', 'Multi Melee');
INSERT INTO skills (id, name, common_name) VALUES (134, 'Multi Ranged', '');
INSERT INTO skills (id, name, common_name) VALUES (132, 'Nano Pool', '');
INSERT INTO skills (id, name, common_name) VALUES (160, 'Nano Progra', 'Nano Programming');
INSERT INTO skills (id, name, common_name) VALUES (168, 'Nano Resist', '');
INSERT INTO skills (id, name, common_name) VALUES (149, 'NanoC. Init.', 'Nano Cast Initiative');
INSERT INTO skills (id, name, common_name) VALUES (364, 'NanoDelta', 'Nano Delta');
INSERT INTO skills (id, name, common_name) VALUES (136, 'Perception', '');
INSERT INTO skills (id, name, common_name) VALUES (159, 'Pharma Tech', '');
INSERT INTO skills (id, name, common_name) VALUES (120, 'Physic. Init', 'Physical Initiative');
INSERT INTO skills (id, name, common_name) VALUES (106, 'Piercing', '');
INSERT INTO skills (id, name, common_name) VALUES (112, 'Pistol', '');
INSERT INTO skills (id, name, common_name) VALUES (21, 'Psychic', '');
INSERT INTO skills (id, name, common_name) VALUES (129, 'Psycho Modi', 'Pychological Modifications');
INSERT INTO skills (id, name, common_name) VALUES (162, 'Psychology', '');
INSERT INTO skills (id, name, common_name) VALUES (157, 'Quantum FT', '');
INSERT INTO skills (id, name, common_name) VALUES (94, 'Radiation AC', '');
INSERT INTO skills (id, name, common_name) VALUES (133, 'Ranged Ener', 'Ranged Energy');
INSERT INTO skills (id, name, common_name) VALUES (119, 'Ranged. Init.', 'Ranged Initiative');
INSERT INTO skills (id, name, common_name) VALUES (381, 'RangeInc. NF', 'Ranged Increase Nano');
INSERT INTO skills (id, name, common_name) VALUES (380, 'RangeInc. Weapon', 'Ranged Increase Weapon');
INSERT INTO skills (id, name, common_name) VALUES (208, 'ReflectChemicalAC', '');
INSERT INTO skills (id, name, common_name) VALUES (217, 'ReflectColdAC', '');
INSERT INTO skills (id, name, common_name) VALUES (207, 'ReflectEnergyAC', '');
INSERT INTO skills (id, name, common_name) VALUES (219, 'ReflectFireAC', '');
INSERT INTO skills (id, name, common_name) VALUES (206, 'ReflectMeleeAC', '');
INSERT INTO skills (id, name, common_name) VALUES (218, 'ReflectNanoAC', '');
INSERT INTO skills (id, name, common_name) VALUES (225, 'ReflectPoisonAC', '');
INSERT INTO skills (id, name, common_name) VALUES (205, 'ReflectProjectileAC', '');
INSERT INTO skills (id, name, common_name) VALUES (216, 'ReflectRadiationAC', '');
INSERT INTO skills (id, name, common_name) VALUES (593, 'Regain XP Percentage', '');
INSERT INTO skills (id, name, common_name) VALUES (113, 'Rifle', '');
INSERT INTO skills (id, name, common_name) VALUES (143, 'Riposte', '');
INSERT INTO skills (id, name, common_name) VALUES (156, 'Run Speed', '');
INSERT INTO skills (id, name, common_name) VALUES (360, 'Scale', '');
INSERT INTO skills (id, name, common_name) VALUES (20, 'Sense', '');
INSERT INTO skills (id, name, common_name) VALUES (122, 'Sensory Impr', 'Sensory Improvement');
INSERT INTO skills (id, name, common_name) VALUES (108, 'Sharp Obj', 'Sharp Objects');
INSERT INTO skills (id, name, common_name) VALUES (229, 'ShieldChemicalAC', '');
INSERT INTO skills (id, name, common_name) VALUES (231, 'ShieldColdAC', '');
INSERT INTO skills (id, name, common_name) VALUES (228, 'ShieldEnergyAC', '');
INSERT INTO skills (id, name, common_name) VALUES (233, 'ShieldFireAC', '');
INSERT INTO skills (id, name, common_name) VALUES (227, 'ShieldMeleeAC', '');
INSERT INTO skills (id, name, common_name) VALUES (232, 'ShieldNanoAC', '');
INSERT INTO skills (id, name, common_name) VALUES (234, 'ShieldPoisonAC', '');
INSERT INTO skills (id, name, common_name) VALUES (226, 'ShieldProjectileAC', '');
INSERT INTO skills (id, name, common_name) VALUES (230, 'ShieldRadiationAC', '');
INSERT INTO skills (id, name, common_name) VALUES (115, 'Shotgun', '');
INSERT INTO skills (id, name, common_name) VALUES (382, 'SkillLockModifier', '');
INSERT INTO skills (id, name, common_name) VALUES (146, 'Sneak Atck', 'Sneak Attack');
INSERT INTO skills (id, name, common_name) VALUES (18, 'Stamina', '');
INSERT INTO skills (id, name, common_name) VALUES (16, 'Strength', '');
INSERT INTO skills (id, name, common_name) VALUES (138, 'Swimming', '');
INSERT INTO skills (id, name, common_name) VALUES (131, 'Time&Space', '');
INSERT INTO skills (id, name, common_name) VALUES (135, 'Trap Disarm.', '');
INSERT INTO skills (id, name, common_name) VALUES (124, 'Treatment', '');
INSERT INTO skills (id, name, common_name) VALUES (141, 'Tutoring', '');
INSERT INTO skills (id, name, common_name) VALUES (180, 'Used NCU', '');
INSERT INTO skills (id, name, common_name) VALUES (139, 'Vehicle Air', '');
INSERT INTO skills (id, name, common_name) VALUES (166, 'Vehicle Ground', '');
INSERT INTO skills (id, name, common_name) VALUES (117, 'Vehicle Water', '');
INSERT INTO skills (id, name, common_name) VALUES (158, 'Weapon Smt', 'Weapon Smithing');
