DROP TABLE IF EXISTS nanolines;
CREATE TABLE nanolines ( id INT NOT NULL PRIMARY KEY, image_id INT NOT NULL, name text, profession text );
INSERT INTO nanolines (id, image_id, name, profession) VALUES (1, 39287, '1HEdged Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (2, 16211, 'Adventuring Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (3, 44135, 'Service Tower', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (4, 101016, 'Armour Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (5, 16194, 'Cold Blooded', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (6, 44231, 'Complete Healing Line', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (7, 49685, 'DOT Adventurer (AoE)', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (8, 117896, 'Damage Buffing', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (9, 39201, 'Damage Shield Upgrades', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (10, 39201, 'Damage Shields', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (11, 16342, 'First Aid And Treatment Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (12, 44235, 'Heal', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (13, 44248, 'Heal (Team)', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (15, 39125, 'LE PvP Debuff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (16, 84203, 'Leet Charm', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (17, 84735, 'Lick Wounds', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (18, 46270, 'Mezz/Stun', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (19, 46270, 'Mezz/Stun (''Special'' AoE)', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (20, 39247, 'Multiwield Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (21, 45180, 'Nuke', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (23, 39122, 'Other Root/Snare Resist Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (24, 101030, 'Pack Hunter Base', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (25, 38988, 'Perception Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (26, 39272, 'Pistol Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (27, 84775, 'Polymorph', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (29, 38982, 'Runspeed Buffs', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (30, 118103, 'Sabretooth Damage Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (31, 84735, 'Scale Repair', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (32, 118083, 'Self Root/Snare Resist Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (33, 16306, 'Shadowlands Map', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (35, 16306, 'Wolf Vision Buff', 'Adventurer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (36, 16299, 'Anima', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (37, 100996, 'Armour Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (38, 16340, 'Beacon Warp', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (39, 16205, 'Breaking & Entry/Disarm Traps Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (40, 16210, 'Chemistry/Pharm Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (41, 39308, 'Damage Buffing', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (42, 16221, 'Damage Shields', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (43, 16220, 'Disarm Trap Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (44, 16308, 'Electrical Engineering Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (45, 38920, 'Auras', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (46, 118034, 'Debuff Auras', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (47, 16232, 'Jamming Tower Summon', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (48, 39015, 'Miniaturization', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (49, 46278, 'Pet AOE Snare Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (50, 16216, 'Pet Aura Canceler', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (51, 44135, 'Pet Dog Summon', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (52, 16216, 'Pet Root/Snare Reducer', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (53, 44135, 'Pet Summon', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (54, 39274, 'Polymorph (Self)', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (55, 39170, 'Special Attack Absorber', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (56, 16244, 'Field Quantum Physics Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (57, 16252, 'Grenade Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (58, 16250, 'Initiative Buffs', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (59, 39125, 'LE PvP Debuff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (60, 16207, 'MP Pet Initiative Buffs', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (61, 16293, 'Mechanical Engineering Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (62, 16299, 'Pet Defensive Nanos', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (63, 44234, 'Pet Heal', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (64, 100995, 'Pet Snare/Root Resistance Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (65, 16316, 'Pharmaceuticals Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (66, 101018, 'Reflect Shield', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (67, 16340, 'Shadowland Bind and Recall', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (68, 101018, 'Shadowland Reflect Base', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (69, 20880, 'Shield of the Obedient Servant', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (70, 38889, 'Special Attack Absorber Base', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (71, 16349, 'Weapon Smithing Buff', 'Engineer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (72, 16214, 'Concealment Buff', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (73, 117896, 'Damage Buffing', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (74, 39081, 'Evasion Debuffs', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (75, 16306, 'Break & Entry Combo', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (76, 16234, 'Dodge Buff Line', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (77, 117952, 'Grid', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (78, 16232, 'Jamming Aura', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (79, 44235, 'Long HoT', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (80, 16216, 'NCU Purge', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (81, 39257, 'Suppressor Buff', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (82, 117953, 'Grid (Self Instant)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (83, 117951, 'Grid (Self)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (84, 117953, 'Grid (Team Instant)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (85, 117952, 'Grid (Team)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (86, 16320, 'Grid Armor', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (87, 44248, 'Heal Over Time', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (88, 39125, 'LE PvP Debuff', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (89, 118410, 'Major Evasion Buffs', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (90, 118013, 'Major Evasion Buffs (RK Team)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (91, 38917, 'NCU Buff', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (92, 16306, 'Perception Buff', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (93, 46275, 'Root', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (94, 16216, 'Root Reducer (Self)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (95, 39158, 'Shadowlands Garden Warp (Self)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (97, 16320, 'Shadowweb Spinner', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (98, 46279, 'Snare', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (99, 84286, 'Snare (AoE)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (100, 16216, 'Snare Reducer (Other)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (101, 16216, 'Snare Reducer (Self)', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (102, 16328, 'Sneak Attack Buff', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (103, 117931, 'Summon Ammunition', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (104, 117934, 'Summon Armor', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (105, 117944, 'Summon Melee Weapon', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (106, 117947, 'Summon Ranged Weapon', 'Fixer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (107, 16313, 'Anima', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (108, 117931, 'LE Pet Proc', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (109, 117934, 'LE Pet Sacrifice', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (110, 46271, 'LE Special Calm', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (111, 16214, 'Pet ''Charm'' Summon', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (112, 44135, 'Pet Summon', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (114, 16313, 'XP Loss Reducer', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (115, 39137, 'Charm Other', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (116, 16214, 'Concealment Buff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (117, 16194, 'Cut Red Tape', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (118, 39124, 'Demotivational Speeches', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (119, 39145, 'Fear', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (120, 39137, 'General Psychic Debuff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (121, 39125, 'LE PvP Debuff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (122, 39168, 'Malaise', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (123, 46271, 'Mezz/Stun', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (124, 84278, 'Mezz/Stun (AoE)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (125, 16321, 'Nano Delta Buff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (126, 45178, 'Nuke', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (127, 16299, 'Pet Damage Over Time Resist Nanos', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (128, 16299, 'Pet Defensive Nanos', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (129, 44230, 'Pet Heal', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (130, 16309, 'Pet Taunt Buff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (131, 16310, 'Pistol Buff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (132, 16309, 'Psychology Buff', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (133, 38761, 'Red Tape', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (134, 46275, 'Root', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (135, 46275, 'Root (AoE)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (136, 16216, 'Root Reducer (Other)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (137, 16216, 'Root Reducer (Self)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (138, 38925, 'Root and Snare Reducer (AoE)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (139, 16216, 'Root and Snare Reducer (Pet)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (140, 46275, 'Snare', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (141, 46278, 'Snare (AoE)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (142, 16216, 'Snare Reducer (Other)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (143, 16216, 'Snare Reducer (Self)', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (144, 38900, 'Speech Line', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (145, 16341, 'XP Bonus', 'Bureaucrat');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (146, 44235, 'Complete Healing Line', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (147, 16222, 'DOT Strain A', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (148, 16222, 'DOT Strain B', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (149, 16222, 'DOT Strain C', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (150, 39098, 'Init Debuff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (151, 38905, 'Long HP Buffs (Team)', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (152, 39292, 'Short HP Buffs', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (153, 16216, 'Epsilon Purge', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (154, 16239, 'First Aid And Treatment Buff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (155, 117952, 'Grid (Team)', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (156, 44235, 'Heal', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (157, 44251, 'Heal (Team)', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (158, 16330, 'Heal Delta Buff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (159, 44235, 'Heal Over Time', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (160, 16250, 'Instinctive Control', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (161, 39125, 'LE PvP Debuff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (162, 16302, 'Nano AC Buff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (163, 39807, 'Nuke', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (164, 39271, 'Ransack/Deprive Resist Buff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (165, 39014, 'Strength Buff', 'Doctor');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (166, 16288, '2HEdged Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (167, 39250, 'Fury', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (168, 117961, 'Aura-Absorb/Reflect/AMS Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (169, 39028, 'Aura-Damage/Snare Reduction Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (170, 44245, 'Aura-HP and NP Heal', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (171, 39221, 'Evade/Dodge/Duck Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (172, 16235, 'Fast Attack/Sneak Attack Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (173, 16305, 'Parry/Riposte Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (174, 84197, 'Proc Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (175, 39228, 'Str/Stam/Agi Buff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (176, 39125, 'LE PvP Debuff', 'Keeper');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (177, 16775, 'Affected by True Profession', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (178, 84198, 'Damage Proc-DamageInflictSegment', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (179, 117928, 'Escape Nanos', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (180, 84198, 'Proc Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (181, 16218, 'Agility Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (182, 16186, 'Aimed Shot Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (183, 16210, 'Chemistry/Pharm Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (184, 39240, 'Concealment Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (185, 16214, 'Concealment Buff (Team)', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (186, 39171, 'Concentration Critical Line', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (187, 49686, 'DOT Strain A', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (188, 117896, 'Damage Buffing', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (189, 16230, 'De-Taunt (Self)', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (190, 39081, 'Evasion Debuffs Line 2', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (191, 117896, 'Executioner Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (192, 39158, 'Face Change', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (193, 16775, 'False Profession', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (194, 39125, 'LE PvP Debuff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (195, 16248, 'Mezz/Stun', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (196, 16328, 'Rifle Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (197, 46275, 'Root', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (198, 16216, 'Root Reducer (Other)', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (199, 16216, 'Root Reducer (Self)', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (200, 16317, 'Sense Buff', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (201, 46274, 'Snare', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (202, 46278, 'Snare (AoE)', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (203, 16216, 'Snare Reducer (Self)', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (204, 39171, 'Sureshot Critical Line', 'Agent');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (205, 101002, 'Armour Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (206, 16204, 'Brawl Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (207, 16350, 'Controlled Destruction Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (208, 16289, 'Controlled Rage Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (209, 16196, 'Critical Increase Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (210, 117896, 'Damage Buffing', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (211, 38864, 'Fear', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (212, 16303, 'Give Energy', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (213, 16246, 'Give Life', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (214, 44233, 'Heal', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (215, 39234, 'Heal (Self)', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (216, 44246, 'Heal (Team)', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (217, 16250, 'Initiative Buffs', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (218, 39125, 'LE PvP Debuff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (219, 16234, 'Major Evasion Buffs', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (220, 16242, 'Armor Buff (Team)', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (221, 16208, 'Bow Buffs', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (222, 16242, 'Damage Buff (Team)', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (223, 16234, 'Duck Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (224, 117896, 'Short-Term Damage Buff (Self)', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (225, 16243, 'Martial Arts Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (226, 16302, 'Nano Resist Buff ', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (227, 16322, 'RiposteBuff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (228, 16300, 'Runspeed Buffs', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (229, 16230, 'Single Taunt', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (230, 16324, 'Strength Buff', 'Martial Artist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (231, 16200, '1H Blunt Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (232, 100996, 'Absorb AC Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (233, 117926, 'Challenger', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (234, 16221, 'Damage Shields', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (235, 39028, 'Damage Change Series', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (236, 20881, 'Melee Energy Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (237, 16201, 'Piercing Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (238, 84198, 'Taunt Procs', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (239, 39145, 'Fear', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (240, 39012, 'HP Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (241, 16250, 'Initiative Buffs', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (242, 39125, 'LE PvP Debuff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (243, 16200, 'Melee Weapon Buff Line', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (244, 39292, 'Mongo Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (246, 39189, 'Rage', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (247, 16230, 'Single Taunt', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (248, 16324, 'Strength Buff', 'Enforcer');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (249, 39168, 'Anima', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (250, 16308, 'BioMet Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (251, 39044, 'BioMet Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (252, 16207, 'Boon of Ergo', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (253, 117943, 'Creation: 1HB', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (254, 117943, 'Creation: 2HB', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (255, 117943, 'Creation: Shield', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (257, 39168, 'DOT Strain C', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (258, 16348, 'Flying Buff (Self)', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (259, 16309, 'Interrupt Modifier', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (260, 39125, 'LE PvP Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (261, 39168, 'MP Damage Debuff Line A', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (262, 39168, 'MP Damage Debuff Line B', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (263, 16207, 'MP Pet Damage Buffs', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (264, 16207, 'MP Pet Initiative Buffs', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (265, 16234, 'Major Evasion Buffs', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (266, 16308, 'MatCrea Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (267, 39112, 'MatCrea Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (268, 16308, 'MatLoc Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (269, 39113, 'MatLoc Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (270, 16308, 'MatMet Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (271, 39114, 'MatMet Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (273, 96170, 'Attack Pet Summon', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (274, 96264, 'Heal Pet Summon', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (275, 96260, 'Mezz Pet Summon', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (276, 39168, 'Damage Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (277, 16248, 'Mezz/Stun', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (278, 16303, 'NP Cost Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (279, 39125, 'NP Cost Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (280, 16301, 'Nano Programming Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (281, 39125, 'Nano Shutdown Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (282, 39798, 'Nuke', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (283, 45177, 'Nuke (MP Debuff Line)', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (284, 16280, 'Pet Damage Over Time Resist Nanos', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (285, 16280, 'Pet Defensive Nanos', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (286, 16330, 'Pet Heal Delta', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (287, 39266, 'Psy/Int Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (288, 16308, 'PsyMod Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (289, 39138, 'PsyMod Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (290, 16216, 'Root and Snare Reducer (Pet)', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (291, 16308, 'SenseImp Buff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (292, 39029, 'SenseImp Debuff', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (293, 16340, 'Shadowland Bind and Recall', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (294, 39158, 'Shadowlands Garden Warp (Team)', 'Meta-Physicist');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (295, 100996, 'Absorb AC Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (296, 39126, 'Blindness', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (297, 38845, 'Blindness (AoE)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (298, 84514, 'Chemical AC Debuff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (299, 84722, 'DOT Nanotechnician Strain A', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (300, 16230, 'De-Taunt (Self)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (301, 118081, 'Fortify', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (302, 39125, 'HP Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (303, 38844, 'HumidityNPExtractor', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (304, 16234, 'Major Evasion Buffs', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (305, 46271, 'Mezz/Stun', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (306, 16202, 'NF Range Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (307, 16303, 'NP Cost Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (308, 118020, 'Nano Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (309, 39263, 'Nano Programming Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (310, 38860, 'Nano Shielding', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (311, 16282, 'Nuke', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (313, 16283, 'Nuke (AoE)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (314, 45190, 'Nuke (Cyberdeck)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (315, 45190, 'Nuke (LE AoE)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (316, 45190, 'Nuke (LE Double)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (317, 45190, 'Nuke (LE Triple)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (318, 45178, 'Nuke (NR Debuff)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (319, 45190, 'Nuke (Special)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (320, 118094, 'Nullity Sphere Nano', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (321, 39266, 'Psy/Int Buff', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (322, 46275, 'Root', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (323, 16216, 'Root Reducer (Self)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (324, 38925, 'Root Reducer (Team)', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (325, 39018, 'Warp to Destination', 'Nano-Technician');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (326, 39221, 'Agility Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (327, 16214, 'Concealment Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (328, 117914, 'Health Drain', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (329, 39125, 'LE PvP Heal', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (330, 39204, 'Martial Arts Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (331, 39267, 'Multiwield Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (332, 16214, 'Runspeed Buffs', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (333, 39247, 'Piercing Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (334, 84197, 'Proc Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (335, 39290, 'Sneak Attack Buff', 'Shade');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (336, 38900, 'AMS', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (337, 101016, 'Armour Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (338, 16195, 'Assault Rifle Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (339, 16196, 'Automatic Targeting buff ', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (340, 16206, 'Burst Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (341, 44245, 'Complete Healing Line', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (342, 117954, 'Damage Buffing', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (343, 100998, 'HP Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (344, 16194, 'Initiative Buffs', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (345, 39125, 'LE PvP Debuff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (346, 20882, 'LR Energy Weapon Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (347, 16234, 'Major Evasion Buffs', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (348, 16310, 'Pistol Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (349, 101018, 'Reflect Shield', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (350, 16329, 'Rifle Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (351, 101018, 'Shadowland Reflect Base', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (352, 16230, 'Single Taunt', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (353, 16242, 'Armour Buff (Team)', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (354, 39168, 'Damage Base', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (355, 16237, 'Full Auto Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (356, 39180, 'Heavy Weapons Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (357, 39234, 'One-More-Hit Healing', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (358, 16326, 'Shotgun Buff', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (359, 39180, 'Total Focus', 'Soldier');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (360, 46271, 'Charm Other', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (361, 16309, 'Computer Literacy Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (362, 117896, 'Damage Buffing', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (363, 117954, 'Damage Drain', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (364, 117903, 'Debuff NanoAC Heavy', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (365, 16308, 'Electrical Engineering Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (366, 16244, 'Field Quantum Physics Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (367, 117952, 'Grid (Team)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (368, 44235, 'Heal', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (369, 39125, 'LE PvP Debuff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (370, 16234, 'Major Evasion Buffs', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (371, 16293, 'Mechanical Engineering Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (372, 46271, 'Mezz/Stun', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (373, 16303, 'NP Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (374, 16303, 'Nano Point Heals', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (375, 118438, 'Nano Shielding', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (376, 16316, 'Pharmaceuticals Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (377, 46275, 'Root', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (378, 46274, 'Root (AoE)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (379, 16216, 'Root Reducer (Other)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (380, 16216, 'Root Reducer (Self)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (381, 39137, 'SL Nanopoint Drain', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (382, 117973, 'AC Transfer Target Buff (Redeem)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (383, 117904, 'AC Transfer Target Debuff (Draw)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (384, 117904, 'AC Transfer Target Debuff (Siphon)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (385, 16189, 'AMS/DMS', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (386, 117903, 'Debuff AC Nanos', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (387, 117903, 'Debuff NanoAC Light', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (388, 117914, 'HP Leech', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (389, 39137, 'NP Leech', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (390, 39137, 'NanoDelta Leech', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (391, 16214, 'Short-Term Pet', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (392, 117924, 'Skill Transfer Target Debuff (Deprive)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (393, 117924, 'Skill Transfer Target Debuff (Ransack)', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (394, 38953, 'Team Heals 1', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (395, 44248, 'Team Heals 10', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (396, 44248, 'Team Heals 11', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (397, 44249, 'Team Heals 12', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (398, 44249, 'Team Heals 13', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (399, 44250, 'Team Heals 14', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (400, 44250, 'Team Heals 15', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (401, 44251, 'Team Heals 16', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (402, 44251, 'Team Heals 17', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (403, 38953, 'Team Heals 2', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (404, 38953, 'Team Heals 3', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (405, 44245, 'Team Heals 4', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (406, 44245, 'Team Heals 5', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (407, 44246, 'Team Heals 6', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (408, 44246, 'Team Heals 7', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (409, 44247, 'Team Heals 8', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (410, 44247, 'Team Heals 9', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (411, 117993, 'Team Skill Wrangler Buff', 'Trader');
INSERT INTO nanolines (id, image_id, name, profession) VALUES (412, 16349, 'Weapon Smithing Buff', 'Trader');