{
  "char_not_found": {
    "en_US": "Could not find character <highlight>{char}<end>.",
    "de_DE": "Der Charakter <highlight>{char}<end> wurde nicht gefunden."
  },
  "access_denied": {
    "en_US": "Access denied.",
    "de_DE": "Zugriff verweigert."
  },
  "unknown_command": {
    "en_US": "Error! Unknown command <highlight>{cmd}<end>.",
    "de_DE": "Error! Den Befehl <highlight>{cmd}<end> kenne ich nicht."
  },
  "error_proccessing": {
    "en_US": "There was an error processing your request.",
    "de_DE": "Es gab einen Fehler beim bearbeiten deiner Anfrage."
  }
}