{
  "notify_rem_fail": {
    "en_US": "<highlight>{char}</highlight> is not on the notify list.",
    "de_DE": "Der Spieler <highlight>{char}</highlight> ist nicht auf der notify Liste."
  },
  "notify_rem_success": {
    "en_US": "<highlight>{char}</highlight> has been removed from the notify list.",
    "de_DE": "Der Spieler <highlight>{char}</highlight> wurde von der notify Liste entfernt."
  },
  "notify_add_fail": {
    "en_US": "<highlight>{char}</highlight> is already on the notify list.",
    "de_DE": "Der Spieler <highlight>{char}</highlight> ist bereits auf der notify Liste."
  },
  "notify_add_success": {
    "en_US": "<highlight>{char}</highlight> has been added to the notify list.",
    "de_DE": "Der Spieler <highlight>{char}</highlight> ist nun auf der notify Liste."
  },
  "blob_title_list": {
    "en_US": "Org Members ({amount})",
    "de_DE": "Spielerliste der Organisation ({amount})"
  }
}
