{
  "notify_rem_fail": {
    "en_US": "<highlight>{char}<end> is not on the notify list.",
    "de_DE": "Der Spieler <highlight>{char}<end> ist nicht auf der notify Liste."
  },
  "notify_rem_success": {
    "en_US": "<highlight>{char}<end> has been removed from the notify list.",
    "de_DE": "Der Spieler <highlight>{char}<end> wurde von der notify Liste entfernt."
  },
  "notify_add_fail": {
    "en_US": "<highlight>{char}<end> is already on the notify list.",
    "de_DE": "Der Spieler <highlight>{char}<end> ist bereits auf der notify Liste."
  },
  "notify_add_success": {
    "en_US": "<highlight>{char}<end> has been added to the notify list.",
    "de_DE": "Der Spieler <highlight>{char}<end> ist nun auf der notify Liste."
  },
  "blob_title_list": {
    "en_US": "Org Members ({amount})",
    "de_DE": "Spielerliste der Organisation ({amount})"
  }
}