-- tests (should return 0 results)
-- select r.name, i.highid from raid_loot r left join aodb i on r.ql = i.highql and r.name = i.name where r.high_id = 0
-- select r.name, i.name from raid_loot r left join aodb i on r.ql = i.highql and r.high_id = i.highid WHERE r.name != i.name

DROP TABLE IF EXISTS raid_loot;
CREATE TABLE raid_loot (id INT PRIMARY KEY AUTO_INCREMENT, raid VARCHAR(30) NOT NULL, category VARCHAR(50) NOT NULL, ql INT NOT NULL, name VARCHAR(255) NOT NULL, high_id int not null, comment VARCHAR(255) NOT NULL, multiloot INT NOT NULL);

-- Vortexx
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 300, 277436, 'Base NCU - Type 00 (0/6)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 300, 281157, 'Nanodeck Activation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 279447, 'Multi Colored Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 279446, 'Green Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 300, 280786, 'Xan Weapon Upgrade Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 279440, 'Xan Defense Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 279439, 'Xan Combat Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 278902, 'Xan Waist Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279019, 'Xan Waist Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279032, 'Xan Waist Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279045, 'Xan Waist Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279058, 'Xan Waist Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 278896, 'Xan Left Arm Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279013, 'Xan Left Arm Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279026, 'Xan Left Arm Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279039, 'Xan Left Arm Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279052, 'Xan Left Arm Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 278901, 'Xan Right Wrist Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279018, 'Xan Right Wrist Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279031, 'Xan Right Wrist Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279044, 'Xan Right Wrist Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279057, 'Xan Right Wrist Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 278893, 'Xan Ocular Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279010, 'Xan Ocular Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279023, 'Xan Ocular Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279036, 'Xan Ocular Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 279049, 'Xan Ocular Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279093, 'Xan Spirit of Right Wrist Offence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279094, 'Xan Spirit of Right Wrist Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279079, 'Xan Left Limb Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279080, 'Xan Left Limb Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279081, 'Xan Left Limb Spirit of Understanding - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279082, 'Xan Left Limb Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279095, 'Xan Midriff Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279096, 'Xan Midriff Spirit of Knowledge - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279097, 'Xan Midriff Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279098, 'Xan Midriff Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279173, 'Xan Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 279071, 'Xan Spirit of Discerning Weakness - Beta', '', 1);

-- Mitaar
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 300, 277436, 'Base NCU - Type 00 (0/6)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 300, 281157, 'Nanodeck Activation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 279447, 'Multi Colored Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 279446, 'Green Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 300, 280786, 'Xan Weapon Upgrade Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 279440, 'Xan Defense Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 279439, 'Xan Combat Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 278892, 'Xan Brain Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279009, 'Xan Brain Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279022, 'Xan Brain Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279035, 'Xan Brain Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279048, 'Xan Brain Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 278895, 'Xan Chest Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279012, 'Xan Chest Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279025, 'Xan Chest Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279038, 'Xan Chest Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279051, 'Xan Chest Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 278897, 'Xan Left Hand Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279014, 'Xan Left Hand Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279027, 'Xan Left Hand Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279040, 'Xan Left Hand Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279053, 'Xan Left Hand Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 278898, 'Xan Left Wrist Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279015, 'Xan Left Wrist Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279028, 'Xan Left Wrist Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279041, 'Xan Left Wrist Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 279054, 'Xan Left Wrist Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279321, 'Xan Brain Spirit of Computer Skill - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279068, 'Xan Brain Spirit of Offence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279069, 'Xan Essence Brain Spirit - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279083, 'Xan Left Hand Spirit of Defence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279084, 'Xan Left Hand Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279085, 'Xan Spirit of Left Wrist Defense - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279086, 'Xan Spirit of Left Wrist Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279075, 'Xan Heart Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279076, 'Xan Heart Spirit of Knowledge - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279077, 'Xan Heart Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279078, 'Xan Heart Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 279070,'Xan Spirit of Clear Thought - Beta', '', 1);

-- 12 man
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 1, 281095, 'Unknown Mixture', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 1, 281098, 'A piece of cloth', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 300, 277436, 'Base NCU - Type 00 (0/6)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 300, 281157, 'Nanodeck Activation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 1, 279447, 'Multi Colored Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 1, 279446, 'Green Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 300, 280786, 'Xan Weapon Upgrade Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 1, 279440, 'Xan Defense Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'General', 1, 279439, 'Xan Combat Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 278894, 'Xan Ear Symbiant, Artillery Unit Beta', 'NODROP, right click to change prof requirement', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 278903, 'Xan Thigh Symbiant, Artillery Unit Beta', 'NODROP, right click to change prof requirement', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 278899, 'Xan Right Arm Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279016, 'Xan Right Arm Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279029, 'Xan Right Arm Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279042, 'Xan Right Arm Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279055, 'Xan Right Arm Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 278900, 'Xan Right Hand Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279017, 'Xan Right Hand Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279030, 'Xan Right Hand Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279043, 'Xan Right Hand Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279056, 'Xan Right Hand Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 278904, 'Xan Feet Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279021, 'Xan Feet Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279034, 'Xan Feet Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279047, 'Xan Feet Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 279060, 'Xan Feet Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279087, 'Xan Right Limb Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279088, 'Xan Right Limb Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279089, 'Xan Right Limb Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279090, 'Xan Right Hand Defensive Spirit - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279091, 'Xan Right Hand Strength Spirit - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279092, 'Xan Spirit of Insight - Right Hand - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279101, 'Xan Spirit of Feet Defense - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279102, 'Xan Spirit of Feet Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279099, 'Xan Spirit of Defense - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279173, 'Xan Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279072, 'Xan Spirit of Essence Whispered - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279073, 'Xan Spirit of Knowledge Whispered - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 279074, 'Xan Spirit of Strength Whispered - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281213, 'Brute''s Gem', 'Enf', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281214, 'Builder''s Gem', 'Eng', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281211, 'Dictator''s Gem', 'Crat', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281210, 'Explorer''s Gem', 'Adv', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281215, 'Hacker''s Gem', 'Fix', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281212, 'Healer''s Gem', 'Doc', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281217, 'Master''s Gem', 'MA', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281222, 'Merchant''s Gem', 'Trad', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281216, 'Protecter''s Gem', 'Keep', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281209, 'Sniper''s Gem', 'Agent', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281220, 'Spirit''s Gem', 'Shade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281219, 'Techno Wizard''s Gem', 'NT', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281221, 'Warrior''s Gem', 'Sol', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 281218, 'Worshipper''s Gem', 'MP', 1);

-- APF
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 266364, 'Cell Templates', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 266357, 'Mitochondria Samples', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 266355, 'Plasmid Cultures', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 287975, 'Power Core Mainboard', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 287976, 'Power Core Stabilizer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 287974, 'Inactive Power Core', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288131, 'Basic Belt', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288130, 'Viral Belt Control Component', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288133, 'Viral Belt NCU Slots', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288135, 'Viral Belt Nanobot Power Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288106, 'Active Viral CPU Upgrade', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288125, 'Active Viral Computer Deck Range Increaser', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288129, 'Active Viral NCU Coolant Sink', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288140, 'Viral Memory Storage Unit (Damage)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288107, 'Passive Viral CPU Upgrade', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288126, 'Passive Viral Computer Deck Range Increaser', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 288128, 'Passive Viral NCU Coolant Sink', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288139, 'Viral Memory Storage Unit (XP)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288290, 'Special Edition Kyr''Ozch Axe', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288298, 'Special Edition Kyr''Ozch Cannon', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288283, 'Special Edition Kyr''Ozch Carbine', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288286, 'Special Edition Kyr''Ozch Crossbow', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288297, 'Special Edition Kyr''Ozch Energy Pistol', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288287, 'Special Edition Kyr''Ozch Energy Rapier', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288296, 'Special Edition Kyr''Ozch Grenade Gun', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288292, 'Special Edition Kyr''Ozch Hammer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288291, 'Special Edition Kyr''Ozch Nunchacko', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288293, 'Special Edition Kyr''Ozch Pistol', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288288, 'Special Edition Kyr''Ozch Rapier', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288284, 'Special Edition Kyr''Ozch Rifle', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288289, 'Special Edition Kyr''Ozch Shotgun', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288285, 'Special Edition Kyr''Ozch Sledgehammer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288295, 'Special Edition Kyr''Ozch Submachine Gun', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 288294, 'Special Edition Kyr''Ozch Sword', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 288137, 'Kyr''Ozch Storage Box', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 288138, 'Kyr''Ozch Storage Container', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 247145, 'Arithmetic Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 247137, 'Enduring Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 247143, 'Observant Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 247139, 'Strong Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 247141, 'Supple Lead Viralbots', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 275909, 'Gelatinous Lump', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 275916, 'Biotech Matrix', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 250, 257960, 'Action Probability Estimator', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 250, 257962, 'Dynamic Gas Redistribution Valves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 257533, 'Kyr''Ozch Video Processing Unit', 'All Bounties', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 257968, 'Hacker ICE-Breaker Source', 'All ICE', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 257706, 'Kyr''Ozch Helmet', '2500 Token board', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 258296, 'Kyr''Ozch Data Core', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 275912, 'Crystalline Matrix', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 275914, 'Kyr''ozch Circuitry', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 250, 257959, 'Inertial Adjustment Processing Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 250, 257963, 'Notum Amplification Coil', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 257533, 'Kyr''Ozch Video Processing Unit', 'All Bounties', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 257968, 'Hacker ICE-Breaker Source', 'All ICE', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 257706, 'Kyr''Ozch Helmet', '2500 Token board', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 258295, 'Kyr''Ozch Data Core', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 275918, 'Alpha Program Chip', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 275919, 'Beta Program Chip', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 275906, 'Odd Kyr''ozch Nanobots', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 275907, 'Kyr''ozch Processing Unit', '', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 250, 257961, 'Energy Redistribution Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 250, 257964, 'Visible Light Remodulation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 257533, 'Kyr''Ozch Video Processing Unit', 'All Bounties', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 257968, 'Hacker ICE-Breaker Source', 'All ICE', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 257706, 'Kyr''Ozch Helmet', '2500 Token board', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 258292, 'Kyr''Ozch Data Core', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - West', 250, 257959, 'Inertial Adjustment Processing Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - West', 250, 257963, 'Notum Amplification Coil', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - West', 1, 257968, 'Hacker ICE-Breaker Source', 'All ICE', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - North', 250, 257960, 'Action Probability Estimator', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - North', 250, 257962, 'Dynamic Gas Redistribution Valves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - North', 1, 257968, 'Hacker ICE-Breaker Source', 'All ICE', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - East', 250, 257961,'Energy Redistribution Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - East', 250, 257964, 'Visible Light Remodulation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - East', 1, 257968, 'Hacker ICE-Breaker Source', 'All ICE', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - Artillery Commander', 1, 262656, 'Kyr''Ozch Invasion Plan', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - Artillery Commander', 1, 260422, 'Unlearning Device', '', 5);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - Artillery Commander', 215, 275706, 'Alien Matrix Alpha Box', '', 2);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('APF', 'Sector 42 - Artillery Commander', 215, 275854, 'Alien Matrix Beta Box', '', 2);

-- Albtraum
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267737, 'Inert Knowledge Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267749, 'Energy Infused Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267704, 'Crystalised Memories of a Sniper', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267711, 'Crystalised Memories of a Defender', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267698, 'Crystalised Memories of a Technician', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267701, 'Crystalised Memories of a Mechanic', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267728, 'Crystalised Memories of a Surgeon', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267714, 'Crystalised Memories of a Engineer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267710, 'Crystalised Memories of an Instructor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267726, 'Crystalised Memories of a Doctor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267697, 'Crystalised Memories of a Warrior', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267708, 'Crystalised Memories of an Archer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 267713, 'Crystalised Memories of a Scientist', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 267744, 'Radioactive Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 267745, 'Venom Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 267742, 'Frost Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 267743, 'Acid Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 267741, 'Fire Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 267892, 'Xan Essence Crystal - Summoned Terror', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 267904, 'Xan Essence Crystal - Gruesome Misery', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 267880, 'Xan Essence Crystal - Sister Pestilence', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 267799, 'Xan Essence Crystal - Sister Merciless', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 267800, 'Xan Essence Crystal - Divided Loyalty', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267625, 'Ancient Speed Preservation Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267626, 'Ancient Vision Preservation Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267905,'Ring of Divided Loyalty', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267906, 'Ring of Gruesome Misery', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267909, 'Ring of Sister Pestilence', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267907, 'Ring of Sister Merciless', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 267911, 'Ring of Summoned Terror', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267794, 'Dormant Ancient Circuit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267709, 'Empty Ancient Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267746, 'Inactive Ancient Bracer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267677, 'Ancient Scrap of Spirit Knowledge', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267679, 'Ancient Scrap of Saturated Spirit Knowledge', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267725, 'Ancient Damage Generation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267735, 'Inactive Ancient Medical Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 267748, 'Inactive Ancient Engineering Device', '', 1);

-- Dust Brigade
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 269993, 'Enhanced Dustbrigade Combat Chestpiece', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 269994, 'Enhanced Dustbrigade Spirit-tech Chestpiece', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 269996, 'Enhanced Dustbrigade Sleeves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 270394, 'Enhanced Dustbrigade Notum Gloves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 270393, 'Enhanced Dustbrigade Chemist Gloves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 269997, 'Enhanced Dustbrigade Covering', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 270392, 'Enhanced Dustbrigade Flexible Boots', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 200, 269987, 'Enhanced Safeguarded NCU Memory Unit', 'Agi + Sen', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 200, 269986, 'Enhanced Safeguarded NCU Memory Unit', 'Str + Sta', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 200, 269985, 'Enhanced Safeguarded NCU Memory Unit', 'Int + Psy', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 200, 269990, 'Protected Safeguarded NCU Memory Unit', 'evades', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 250, 269961, 'Master Melee Program', 'Alappaa Pad Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 250, 269960, 'Master Combat Program', 'Alappaa Pad Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 250, 269959, 'Master Nano Technology Program', 'Alappaa Pad Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 274541, 'Basic Infused Dust Brigade Bracer', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 274552, 'Dust Brigade Notum Infuser', 'DB Bracer/Alb Item Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 272459, 'White Molybdenum-Matrix of Xan', 'All Molybdenum-Matrix of Xan (2 Black, 6 White Kegern/Jathos Upgrades)', 2);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 300, 274559, 'Dust Brigade Engineer Pistol', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 274558, 'Dust Brigade Solar Notum Infuser', 'Engineer Solar Pistol Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB3', 250, 292191, 'Dust Brigade Special Ops Helmet', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB3', 250, 292566, 'Dust Brigade Bracer - First Edition', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'DB3', 250, 292567, 'Advanced Dust Brigade Notum Infuser', 'Upgrades First Edition bracers', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 292607, 'Dust Brigade Barrier Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 292157, 'Dust Brigade Assault Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 292605, 'Dust Brigade Protector Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 292608, 'Dust Brigade Creator Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 292604, 'Dust Brigade Grunt Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 292606, 'Dust Brigade Escape Module', '', 1);

-- Pande
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244750, 'Sigil of Bahomet', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244716, 'Helmet of Hypocrisy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244718, 'Burden of Competence', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244713, 'Shoulderplates of Sabotage', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244717, 'Cuirass of Obstinacy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244705, 'Sleeves of Senseless Violence', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244704, 'Gauntlets of Deformation', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244712, 'Armplates of Elimination', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244715, 'Greaves of Malfeasance', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 244714, 'Boots of Concourse', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244742, 'Lord of Abandonment', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244743, 'Lady of Abandonment', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244802, 'Lord of Anger', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244801, 'Lady of Anger', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244821, 'Lord of Angst', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244820, 'Lady of Angst', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244910, 'Lord of Chaos', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244909, 'Lady of Chaos', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244779, 'Lord of Deceit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244778, 'Lady of Deceit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244843, 'Lord of Envy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244842, 'Lady of Envy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244785, 'Lord of Gluttony', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244784, 'Lady of Gluttony', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244862, 'Lord of Greed', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244859, 'Lady of Greed', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244762, 'Lord of Hatred', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244761, 'Lady of Hatred', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244914, 'Lord of Lust', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244913, 'Lady of Lust', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244783, 'Lord of Pride', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244782, 'Lady of Pride', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 244912, 'Lord of Sloth', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 244911, 'Lady of Sloth', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 200, 246813, 'Sunrise Hilt', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 200, 246814, 'Sunset Hilt', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 294000, 'Lady of Wisdom', 'atrox', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 294001, 'Lady of Wisdom', 'not atrox', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 293997, 'Lord of Wisdom', 'atrox', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 293999, 'Lord of Wisdom', 'not atrox', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244700, 'Star of Ardency', 'NT', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244693, 'Star of Enterprice', 'Fix', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244703, 'Star of Enticement', 'Shade', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244691, 'Star of Equanimity', 'MA', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244702, 'Star of Faith', 'Keep', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244690, 'Star of Fidelity', 'Sol', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244698, 'Star of Fortitude', 'End', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244695, 'Star of Freedom', 'Adv', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244692, 'Star of Ingenuity', 'Eng', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244696, 'Star of Interchange', 'Trad', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244697, 'Star of Management', 'Crat', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244701, 'Star of Moral', 'MP', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244699, 'Star of Recovery', 'Doc', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 244694, 'Star of Stealth', 'Agent', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Shadowbreeds', 1, 215442, 'The Lighter Side', 'Clan SB', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Shadowbreeds', 1, 215445, 'The Darker Side', 'Omni SB', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Shadowbreeds', 1, 215443, 'The Unknown Path', 'Neutral SB', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 300, 244989, 'Maar''s Blue Belt of Double Prudence', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 300, 244988, 'Maar''s Red Belt of Double Power', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 300, 244990, 'Maar''s Yellow Belt of Double Speed', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 200, 246818, 'Notum Seed', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 200, 246817, 'Novictum Seed', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 244542, 'Dynamic Sleeve of Aries', 'Melee', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 244541, 'Dynamic Sleeve of Aries', 'Range', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 244540, 'Aries'' Tiara of the Quick Witted', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 244469, 'Quick-Draw Holster of Aries', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 244405, 'Boon of Aries', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 244575, 'Enthusiastic Spirit Helper of the Leo', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 244574, 'Leo''s Faithful Boots of Ancient Gold', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 244573, 'Leo''s Grandiose Gold Armband of Plenty', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 244578, 'Leo''s Mellow Gold Pad of Auto-Support', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 244662, 'Virgo''s Arrow Guide', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 244665, 'Virgo''s Analytical Spirit Helper', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 244663, 'Virgo''s Practical Spirit Helper', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 244664, 'Virgo''s Modest Spirit of Faith', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 244357, 'Aquarius'' Boots of Small Steps', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 244223, 'Mediative Gloves of the Aquarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 244358, 'Intuitive Memory of the Aquarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 244376, 'Aquarius''s Multitask Calculator', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 244559, 'Cancer''s Gloves of Automatic Knowledge', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 244543, 'Cancer''s Silver Boots of the Autodidact', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 244560, 'Cancer''s Ring of Circumspection', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 244558, 'Cancer''s Time-Saving Memory', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 244566, 'Collector Pants of Gemini', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 244572, 'Gemini''s Double Band of Linked Information', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 244567, 'Cross Dimensional Gyro of Gemini', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 244565, 'Gemini''s Green Scope of Variety', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 244635, 'Libra''s Charming Assistant', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 244581, 'Urbane Pants of Libra', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 244637, 'Aim of Libra', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 244579, 'Well Balanced Spirit Helper of Libra', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Libra', 1, 262225, 'Activation Code', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 244641, 'Cosmic Guide of the Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 244639, 'Octopus Contraption of the Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 244638, 'Soul Mark of Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 244640, 'Mystery of Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 244661, 'Taurus'' Ring of the Heart', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 244659, 'Taurus'' Spirit of Patience', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 244660, 'Taurus'' Swordmaster Spirit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 244658, 'Taurus'' Spirit of Reflection', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 244564, 'Capricorn Bracer of Toxication', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 244562, 'Gloves of the Caring Capricorn', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 244561, 'Capricorn''s Reliable Memory', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 244563, 'Capricorn''s Guide to Alchemy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 244645, 'Comfort of the Sagittarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 244644, 'First Creation of the Sagittarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 244643, 'Sagittarius''s Hearty Spirit Helper', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 244647, 'Strong Mittens of the Sagittarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 244650, 'Punters of the Scorpio', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 244654, 'Scorpio''s Shell of Change', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 244655, 'Scorpio''s Aim of Anger', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 244648, 'Sash of Scorpio Strength', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 293638, 'SSC "Bastion" Back Armor - Inactive', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 293643, 'SSC "Bastion" Left Shoulder Armor - Inactive', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 293653, 'SSC "Bastion" Right Shoulder Armor - Inactive', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 250, 290780, 'NCU Infuser', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292537, 'Collatz Upgrade Plate', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292535, 'Fatou Upgrade Plate', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292536, 'Mandelbrot Upgrade Plate', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 293809, 'A Single Strand of Glowing Dark Energy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292507, 'Inert Bacteriophage', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292517, 'Pattern Conversion Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292532, 'Nickel-Cobalt Ferrous Alloy', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292533, 'Dacite Fiber', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292529, 'Sealed Packet of Bilayer Graphene Sheets', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292530, 'Mu-Negative Novictum Enriched Metamaterial', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292524, 'Compressed Silane', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292525, 'Potassium Nitrate', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292526, 'VLS Synthesis Catalyst', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292528, 'Bi-Isotropic Nano Media', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292538, 'Synchotronic Recombinator - Pocket Edition (Empty)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292514, 'Red Data Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292515, 'Blue Data Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292516, 'Green Data Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292508, 'Virus Programming: Bacteriophage Phi X 3957', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292509, 'Virus Programming: Bacteriophage M73', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pande', 'Gauntlet', 1, 292510, 'Virus Programming: Bacteriophage F9', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 300, 302926, 'Inert Sigil of Alighieri', 'Drops from Cybernetic Daemon, Azdaja the Joyous and Maiden', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 300, 302928, 'Inert Sigil of Machiavelli', 'Drops from Phobettor', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 300, 302932, 'Portable Notum Infusion Device', 'Chance of dropping from Cybernetic Daemon, Azdaja the Joyous and Maiden. 100% drop rate from Phobettor.', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 1, 302916, 'Laughing Spirit Capsule', 'Cybernetic Daemon', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 1, 302918, 'Crying Spirit Capsule', 'Azdaja the Joyous', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 1, 302917, 'Screaming Spirit Capsule', 'Maiden', 3);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 100, 302925, 'Ancient Resorative Fungus', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 300, 302931, 'Sluggish Notum Lens', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 100, 302924, 'Ancient Aggressive Webbing', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 300, 302930, 'Dense Nanite Aegis', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 100, 302923, 'Ancient Protective Drone', '', 1);

-- #########################
-- #   TOTW (Highlevel)    #
-- #########################
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Binyacht the Faithful', 300, 305521, 'Corrupted Edge', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Binyacht the Faithful', 1, 305471, 'Purified Hood of the Faithful', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Binyacht the Faithful', 1, 305465, 'Purified Robe of the Faithful', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Binyacht the Faithful', 1, 305535, 'Tattered book: Sting of the Viper (section 5)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Guardian of the Three', 1, 305495, 'Bloodthrall Ring', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Guardian of the Three', 1, 305493, 'Ring of Purifying Flame', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Guardian of the Three', 1, 305500, 'Sanguine Vambrace', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Guardian of the Three', 1, 305543, 'Tattered book: Stampede of the Boar (section 1)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Guardian of the Three', 1, 305531, 'Tattered book: Sting of the Viper (section 1)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Guardian of the Three', 1, 305535, 'Tattered book: Sting of the Viper (section 5)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Immortal Summoner', 1, 305495, 'Bloodthrall Ring', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Immortal Summoner', 1, 305524, 'Bone Staff of The Immortal Summoner', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Immortal Summoner', 1, 305556, 'Ornate Funeral Urn', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Immortal Summoner', 1, 305493, 'Ring of Purifying Flame', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Immortal Summoner', 1, 305544, 'Tattered book: Stampede of the Boar (section 2)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Immortal Summoner', 1, 305535, 'Tattered book: Sting of the Viper (section 5)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Lien the Memory-Devourer', 1, 305517, 'Lucid Nightmares', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Lien the Memory-Devourer', 1, 305516, 'Memory of Future Events', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Lien the Memory-Devourer', 1, 305518, 'Mnemonic Shard', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Lien the Memory-Devourer', 1, 305496, 'Ring of the Coiled Serpent', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Lien the Memory-Devourer', 1, 305546, 'Tattered book: Stampede of the Boar (section 4)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Loremaster', 1, 305511, 'Blessing of the Gripper', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Loremaster', 1, 305495, 'Bloodthrall Ring', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Loremaster', 1, 305527, 'Knowledge of the Immortal One', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Loremaster', 1, 305487, 'Mountain Razing Gauntlets', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Loremaster', 1, 305500, 'Sanguine Vambrace', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'The Loremaster', 1, 305532, 'Tattered book: Sting of the Viper (section 2)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 300, 305520, 'Ceremonial Blade', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305476, 'Desecrated Flesh', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 300, 305522, 'Envoy to Chaos', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 300, 305506, 'Ethereal Embrace', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305505, 'Grasp of the Immortal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305510, 'Nematet''s Third Eye', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305513, 'Notum Graft', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305491, 'Ring of Blighted Flesh', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305493, 'Ring of Purifying Flame', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305523, 'Sacred Chalice', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305478, 'Strength of the Immortal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305545, 'Tattered book: Stampede of the Boar (section 3)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305547, 'Tattered book: Stampede of the Boar (section 5)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305507, 'Vision of the Heretic', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Nematet the Subjugator of Time', 1, 305504, 'Wit of the Immortal', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aegis of Tomorrow', 1, 305519, 'Aegis Circuit Board', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aegis of Tomorrow', 1, 305495, 'Bloodthrall Ring', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aegis of Tomorrow', 1, 305033, 'Guardian Heavy Tank Armor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aegis of Tomorrow', 1, 305493, 'Ring of Purifying Flame', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aegis of Tomorrow', 1, 305500, 'Sanguine Vambrace', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aegis of Tomorrow', 1, 305535, 'Tattered book: Sting of the Viper (section 5)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Gartua the Gate Guardian', 1, 305470, 'Gartua''s Second Coat', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Gartua the Gate Guardian', 1, 305509, 'Inner Peace', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Gartua the Gate Guardian', 1, 305508, 'Keeper''s Vigor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Gartua the Gate Guardian', 1, 305493, 'Ring of Purifying Flame', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Gartua the Gate Guardian', 1, 305535, 'Tattered book: Sting of the Viper (section 5)', '', 1);


INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305495, 'Bloodthrall Ring', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 300, 305520, 'Ceremonial Blade', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305476, 'Desecrated Flesh', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 300, 305522, 'Envoy to Chaos', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305530, 'Obsidian Desecrator', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305491, 'Ring of Blighted Flesh', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305493, 'Ring of Purifying Flame', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305523, 'Sacred Chalice', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305514, 'Sacred Text of the Immortal One', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305500, 'Sanguine Vambrace', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305478, 'Strength of the Immortal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305547, 'Tattered book: Stampede of the Boar (section 5)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Aztur the Immortal', 1, 305548, 'Tattered book: Stampede of the Boar (section 6)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Khalum the Weaver of Flesh', 1, 305480, 'Fist of Heavens', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Khalum the Weaver of Flesh', 1, 305526, 'Summoner''s Staff of Dismissal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Khalum the Weaver of Flesh', 1, 305536, 'Tattered book: Sting of the Viper (section 6)', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Uklesh the Beguiling', 1, 305480, 'Fist of Heavens', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'Uklesh the Beguiling', 300, 305525, 'Uklesh''s Talon', '', 1);


INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305488, 'Notum Ring of the Three', 'green', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305489, 'Notum Ring of the Three', 'red', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305490, 'Notum Ring of the Three', 'yellow', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 206017, 'Rod of Dismissal', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305499, 'Corrupted Bloodmark', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305498, 'Corrupted Soulmark', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305485, 'Twilight Entreatment Armor (Helmet)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305484, 'Twilight Entreatment Armor (Gloves)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305486, 'Twilight Entreatment Armor (Pants)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305482, 'Twilight Entreatment Armor (Sleeves)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305483, 'Twilight Entreatment Armor (Body)', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Temple of Three Winds (HL)', 'General', 1, 305481, 'Twilight Entreatment Armor (Boots)', '', 1);

-- ####################
-- #   Subway (HL)    #
-- ####################

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305963, 'Counterfeit fr00b T-shirt', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305962, 'Fetid Vagabond Cloak', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 250, 305964, 'Fortified Construction Sleeves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305978, 'Purification Stim', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305967, 'Reinforced Bau Cyber Body Armor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305968, 'Reinforced Bau Cyber Female Body Armor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305972, 'Reinforced Bau Cyber Armor Helmet', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305970, 'Reinforced Bau Cyber Armor Pants', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305969, 'Reinforced Bau Cyber Armor Sleeves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305971, 'Reinforced Bau Cyber Armor Gloves', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'General', 1, 305973, 'Reinforced Bau Cyber Armor Boots', '', 1);


INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eliminator Shiro', 210, 305975, 'Combat Assist Wen-Wen', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eliminator Shiro', 300, 305966, 'Distraction Rifle', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eliminator Shiro', 1, 305979, 'Notum-Infused Wool Balaclava Mask', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eliminator Shiro', 1, 305974, 'Unstable Damage Augmentation Device', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eumenides', 200, 305980, 'BBI Faithful 1000', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eumenides', 1, 305983, 'Eumenides''s Omni-Pol Forest Body Armor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eumenides', 250, 305028, 'Superior Ring of the Nucleus Basalis', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eumenides', 220, 305982, 'Supreme Office Worker Suit', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Eumenides', 250, 305981, 'Technical Guidance Personal Terminal', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Queen of the Slums', 100, 305986, 'Amalgamated Research Attunement Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Queen of the Slums', 250, 305984, 'Aspect of Paralyzing Fear', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Queen of the Slums', 1, 305985, 'Illegally Augmented Ofab Mongoose', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Queen of the Slums', 200, 305987, 'Survivalist Leather Armor Legwear', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'The Psion', 250, 305984, 'Aspect of Paralyzing Fear', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'The Psion', 250, 305989, 'Eye of The Psion', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'The Psion', 300, 305991, 'Illegally Modified Dreadloch Panther', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'The Psion', 300, 305988, 'Illegally-Modified Dreadloch Tigress', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'The Psion', 200, 305990, 'Symbiotic Nanite Gloves', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Primal Bloodcreeper', 1, 306026, 'Mark of the Bloodless', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Vergil Aeneid', 305995, 1, 'Boots of Gridspace Distortion', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Vergil Aeneid', 300, 305999, 'Illegally Modified Dreadloch Remodulator', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Vergil Aeneid', 300, 305998, 'Illegally Modified Dreadloch Thrasher', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Vergil Aeneid', 200, 305993, 'Lost Blade of Elder Tsunayoshi', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Vergil Aeneid', 1, 305997, 'Vergil''s Black Trenchcoat', '', 1);

INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 250, 305984, 'Aspect of Paralyzing Fear', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 1, 306001, 'Belt of Great Justice', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 1, 306003, 'Condemned Bulwark', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 1, 305983, 'Eumenides''s Omni-Pol Forest Body Armor', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 300, 306005, 'Illegally Modified Dreadloch Obliterator', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 300, 306004, 'Illegally Modified Dreadloch Modified Shark', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 250, 305029, 'Jester''s Gift', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 100, 306002, 'Patchwork Defensive Drone', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 1, 305997, 'Vergil''s Black Trenchcoat', '', 1);
INSERT INTO raid_loot (raid, category, ql, high_id, name, comment, multiloot) VALUES ('Condemned Subway (HL)', 'Abmouth Supremus', 300, 305965, 'Vicious Support Beam of Malice', '', 1);
