DROP TABLE IF EXISTS raid_loot;
CREATE TABLE raid_loot (id INT PRIMARY KEY AUTO_INCREMENT, raid VARCHAR(30) NOT NULL, category VARCHAR(50) NOT NULL, ql INT NOT NULL, name VARCHAR(255) NOT NULL, comment VARCHAR(255) NOT NULL, multiloot INT NOT NULL);

-- Vortexx
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 300, 'Base NCU - Type 00 (0/6)', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 300, 'Nanodeck Activation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 'Multi Colored Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 'Green Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 300, 'Xan Weapon Upgrade Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 'Xan Defense Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'General', 1, 'Xan Combat Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Waist Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Waist Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Waist Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Waist Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Waist Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Left Arm Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Left Arm Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Left Arm Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Left Arm Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Left Arm Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Right Wrist Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Right Wrist Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Right Wrist Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Right Wrist Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Right Wrist Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Ocular Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Ocular Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Ocular Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Ocular Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Symbiants', 300, 'Xan Ocular Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Spirit of Right Wrist Offence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Spirit of Right Wrist Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Left Limb Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Left Limb Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Left Limb Spirit of Understanding - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Left Limb Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Midriff Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Midriff Spirit of Knowledge - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Midriff Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Midriff Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Vortexx', 'Spirits', 250, 'Xan Spirit of Discerning Weakness - Beta', '', 1);

-- Mitaar
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 300, 'Base NCU - Type 00 (0/6)', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 300, 'Nanodeck Activation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 'Multi Colored Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 'Green Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 300, 'Xan Weapon Upgrade Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 'Xan Defense Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'General', 1, 'Xan Combat Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Brain Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Brain Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Brain Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Brain Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Brain Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Chest Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Chest Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Chest Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Chest Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Chest Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Hand Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Hand Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Hand Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Hand Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Hand Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Wrist Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Wrist Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Wrist Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Wrist Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Symbiants', 300, 'Xan Left Wrist Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Brain Spirit of Computer Skill - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Brain Spirit of Offence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Essence Brain Spirit - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Left Hand Spirit of Defence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Left Hand Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Spirit of Left Wrist Defense - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Spirit of Left Wrist Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Heart Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Heart Spirit of Knowledge - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Heart Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Heart Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Mitaar', 'Spirits', 250, 'Xan Spirit of Clear Thought - Beta', '', 1);

-- 12 man
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 1, 'Unknown Mixture', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 1, 'A piece of cloth', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 300, 'Base NCU - Type 00 (0/6)', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 300, 'Nanodeck Activation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 1, 'Multi Colored Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 1, 'Green Xan Belt Tuning Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 300, 'Xan Weapon Upgrade Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 1, 'Xan Defense Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'General', 1, 'Xan Combat Merit Board Base', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Ear Symbiant, Artillery Unit Beta', 'NODROP, right click to change prof requirement', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Thigh Symbiant, Artillery Unit Beta', 'NODROP, right click to change prof requirement', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Arm Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Arm Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Arm Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Arm Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Arm Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Hand Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Hand Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Hand Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Hand Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Right Hand Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Feet Symbiant, Artillery Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Feet Symbiant, Control Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Feet Symbiant, Extermination Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Feet Symbiant, Infantry Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Symbiants', 300, 'Xan Feet Symbiant, Support Unit Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Right Limb Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Right Limb Spirit of Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Right Limb Spirit of Weakness - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Right Hand Defensive Spirit - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Right Hand Strength Spirit - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Insight - Right Hand - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Feet Defense - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Feet Strength - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Defense - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Essence - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Essence Whispered - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Knowledge Whispered - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Spirits', 250, 'Xan Spirit of Strength Whispered - Beta', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Brute''s Gem', 'Enf', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Builder''s Gem', 'Eng', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Dictator''s Gem', 'Crat', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Explorer''s Gem', 'Adv', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Hacker''s Gem', 'Fix', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Healer''s Gem', 'Doc', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Master''s Gem', 'MA', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Merchant''s Gem', 'Trad', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Protecter''s Gem', 'Keep', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Sniper''s Gem', 'Agent', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Spirit''s Gem', 'Shade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Techno Wizard''s Gem', 'NT', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Warrior''s Gem', 'Sol', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('12Man', 'Profession Gems', 1, 'Worshipper''s Gem', 'MP', 1);

-- APF
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Cell Templates', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Mitochondria Samples', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Plasmid Cultures', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 'Power Core Mainboard', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 'Power Core Stabilizer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 'Inactive Power Core', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Basic Belt', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Viral Belt Control Component', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Viral Belt NCU Slots', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Viral Belt Nanobot Power Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Active Viral CPU Upgrade', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Active Viral Computer Deck Range Increaser', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Active Viral NCU Coolant Sink', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Viral Memory Storage Unit (Damage)', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Passive Viral CPU Upgrade', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Passive Viral Computer Deck Range Increaser', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 200, 'Passive Viral NCU Coolant Sink', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Viral Memory Storage Unit (XP)', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Axe', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Cannon', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Carbine', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Crossbow', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Energy Pistol', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Energy Rapier', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Grenade Gun', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Hammer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Nunchacko', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Pistol', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Rapier', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Rifle', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Shotgun', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Sledgehammer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Submachine Gun', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 150, 'Special Edition Kyr''Ozch Sword', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 'Kyr''Ozch Storage Box', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 1, 'Kyr''Ozch Storage Container', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Arithmetic Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Enduring Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Observant Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Strong Lead Viralbots', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 7', 300, 'Supple Lead Viralbots', '', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 'Gelatinous Lump', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 'Biotech Matrix', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 250, 'Action Probability Estimator', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 250, 'Dynamic Gas Redistribution Valves', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 'Kyr''Ozch Video Processing Unit', 'All Bounties', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 'Hacker ICE-Breaker Source', 'All ICE', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 13', 1, 'Kyr''Ozch Helmet', '2500 Token board', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 'Crystalline Matrix', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 'Kyr''ozch Circuitry', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 250, 'Inertial Adjustment Processing Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 250, 'Notum Amplification Coil', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 'Kyr''Ozch Video Processing Unit', 'All Bounties', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 'Hacker ICE-Breaker Source', 'All ICE', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 28', 1, 'Kyr''Ozch Helmet', '2500 Token board', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Alpha Program Chip', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Beta Program Chip', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Odd Kyr''ozch Nanobots', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Kyr''ozch Processing Unit', '', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 250, 'Energy Redistribution Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 250, 'Visible Light Remodulation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Kyr''Ozch Video Processing Unit', 'All Bounties', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Hacker ICE-Breaker Source', 'All ICE', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('APF', 'Sector 35', 1, 'Kyr''Ozch Helmet', '2500 Token board', 1);

-- Albtraum
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Inert Knowledge Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Energy Infused Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Sniper', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Defender', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Technician', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Mechanic', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Surgeon', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Engineer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of an Instructor', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Doctor', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Warrior', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of an Archer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Crystals & Crystalised Memories', 250, 'Crystalised Memories of a Scientist', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 'Radioactive Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 'Venom Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 'Frost Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 'Acid Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Samples', 250, 'Fire Gland Sample', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 'Xan Essence Crystal - Summoned Terror', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 'Xan Essence Crystal - Gruesome Misery', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 'Xan Essence Crystal - Sister Pestilence', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 'Xan Essence Crystal - Sister Merciless', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Pocket Boss Crystals', 250, 'Xan Essence Crystal - Divided Loyalty', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ancient Speed Preservation Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ancient Vision Preservation Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ring of Divided Loyalty', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ring of Gruesome Misery', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ring of Sister Pestilence', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ring of Sister Merciless', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Rings and Preservation Units', 250, 'Ring of Summoned Terror', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Dormant Ancient Circuit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Empty Ancient Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Inactive Ancient Bracer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Ancient Scrap of Spirit Knowledge', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Ancient Scrap of Saturated Spirit Knowledge', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Ancient Damage Generation Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Inactive Ancient Medical Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Albtraum', 'Ancients', 250, 'Inactive Ancient Engineering Device', '', 1);

-- Dust Brigade
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Combat Chestpiece', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Spirit-tech Chestpiece', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Sleeves', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Notum Gloves', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Chemist Gloves', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Covering', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB Armor', 200, 'Enhanced Dustbrigade Flexible Boots', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 200, 'Enhanced Safeguarded NCU Memory Unit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 200, 'Protected Safeguarded NCU Memory Unit', 'evades', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 250, 'Master Melee Program', 'Alappaa Pad Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 250, 'Master Combat Program', 'Alappaa Pad Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB1', 250, 'Master Nano Technology Program', 'Alappaa Pad Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 'Basic Infused Dust Brigade Bracer', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 'Dust Brigade Notum Infuser', 'DB Bracer/Alb Item Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 'White Molybdenum-Matrix of Xan', 'All Molybdenum-Matrix of Xan (2 Black, 6 White Kegern/Jathos Upgrades)', 2);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 300, 'Dust Brigade Engineer Pistol', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB2', 250, 'Dust Brigade Solar Notum Infuser', 'Engineer Solar Pistol Upgrade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB3', 250, 'Dust Brigade Special Ops Helmet', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB3', 250, 'Dust Brigade Bracer - First Edition', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'DB3', 250, 'Advanced Dust Brigade Notum Infuser', 'Upgrades First Edition bracers', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 'Dust Brigade Barrier Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 'Dust Brigade Assault Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 'Dust Brigade Protector Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 'Dust Brigade Creator Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 'Dust Brigade Grunt Module', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('DustBrigade', 'Util', 250, 'Dust Brigade Escape Module', '', 1);

-- Pande
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Sigil of Bahomet', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Helmet of Hypocrisy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Burden of Competence', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Shoulderplates of Sabotage', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Cuirass of Obstinacy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Sleeves of Senseless Violence', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Gauntlets of Deformation', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Armplates of Elimination', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Greaves of Malfeasance', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Armor', 300, 'Boots of Concourse', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Abandonment', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Abandonment', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Anger', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Anger', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Angst', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Angst', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Chaos', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Chaos', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Deceit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Deceit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Envy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Envy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Gluttony', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Gluttony', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Greed', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Greed', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Hatred', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Hatred', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Lust', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Lust', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Pride', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Pride', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Sloth', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 299, 'Lady of Sloth', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 200, 'Sunrise Hilt', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 200, 'Sunset Hilt', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lady of Wisdom', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Beast Weapons', 300, 'Lord of Wisdom', '', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Ardency', 'NT', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Enterprice', 'Fix', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Enticement', 'Shade', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Equanimity', 'MA', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Faith', 'Keep', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Fidelity', 'Sol', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Fortitude', 'End', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Freedom', 'Adv', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Ingenuity', 'Eng', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Interchange', 'Trad', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Management', 'Crat', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Moral', 'MP', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Recovery', 'Doc', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Stars', 250, 'Star of Stealth', 'Agent', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Shadowbreeds', 1, 'The Lighter Side', 'Clan SB', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Shadowbreeds', 1, 'The Darker Side', 'Omni SB', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Shadowbreeds', 1, 'The Unknown Path', 'Neutral SB', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 300, 'Maar''s Blue Belt of Double Prudence', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 300, 'Maar''s Red Belt of Double Power', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 300, 'Maar''s Yellow Belt of Double Speed', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 200, 'Notum Seed', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'The Night Heart', 200, 'Novictum Seed', '', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 'Dynamic Sleeve of Aries', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 'Aries'' Tiara of the Quick Witted', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 'Quick-Draw Holster of Aries', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aries', 250, 'Boon of Aries', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 'Enthusiastic Spirit Helper of the Leo', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 'Leo''s Faithful Boots of Ancient Gold', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 'Leo''s Grandiose Gold Armband of Plenty', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Leo', 250, 'Leo''s Mellow Gold Pad of Auto-Support', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 'Virgo''s Arrow Guide', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 'Virgo''s Analytical Spirit Helper', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 'Virgo''s Practical Spirit Helper', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Virgo', 250, 'Virgo''s Modest Spirit of Faith', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 'Aquarius'' Boots of Small Steps', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 'Mediative Gloves of the Aquarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 'Intuitive Memory of the Aquarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Aquarius', 250, 'Aquarius''s Multitask Calculator', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 'Cancer''s Gloves of Automatic Knowledge', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 'Cancer''s Silver Boots of the Autodidact', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 'Cancer''s Ring of Circumspection', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Cancer', 250, 'Cancer''s Time-Saving Memory', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 'Collector Pants of Gemini', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 'Gemini''s Double Band of Linked Information', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 'Cross Dimensional Gyro of Gemini', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Gemini', 250, 'Gemini''s Green Scope of Variety', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 'Libra''s Charming Assistant', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 'Urbane Pants of Libra', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 'Aim of Libra', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Libra', 250, 'Well Balanced Spirit Helper of Libra', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Libra', 1, 'Activation Code', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 'Cosmic Guide of the Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 'Octopus Contraption of the Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 'Soul Mark of Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Pisces', 250, 'Mystery of Pisces', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 'Taurus'' Ring of the Heart', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 'Taurus'' Spirit of Patience', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 'Taurus'' Swordmaster Spirit', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Taurus', 250, 'Taurus'' Spirit of Reflection', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 'Capricorn Bracer of Toxication', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 'Gloves of the Caring Capricorn', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 'Capricorn''s Reliable Memory', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Capricorn', 250, 'Capricorn''s Guide to Alchemy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 'Comfort of the Sagittarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 'First Creation of the Sagittarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 'Sagittarius''s Hearty Spirit Helper', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Sagittarius', 250, 'Strong Mittens of the Sagittarius', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 'Punters of the Scorpio', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 'Scorpio''s Shell of Change', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 'Scorpio''s Aim of Anger', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Scorpio', 250, 'Sash of Scorpio Strength', '', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'SSC "Bastion" Back Armor - Inactive', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'SSC "Bastion" Left Shoulder Armor - Inactive', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'SSC "Bastion" Right Shoulder Armor - Inactive', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 250, 'NCU Infuser', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Collatz Upgrade Plate', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Fatou Upgrade Plate', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Mandelbrot Upgrade Plate', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'A Single Strand of Glowing Dark Energy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Inert Bacteriophage', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Pattern Conversion Device', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Nickel-Cobalt Ferrous Alloy', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Dacite Fiber', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Sealed Packet of Bilayer Graphene Sheets', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Mu-Negative Novictum Enriched Metamaterial', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Compressed Silane', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Potassium Nitrate', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'VLS Synthesis Catalyst', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Bi-Isotropic Nano Media', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Synchotronic Recombinator - Pocket Edition (Empty)', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Red Data Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Blue Data Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Green Data Crystal', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Virus Programming: Bacteriophage Phi X 3957', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Virus Programming: Bacteriophage M73', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pande', 'Bastion', 1, 'Virus Programming: Bacteriophage F9', '', 1);

INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 300, 'Inert Sigil of Alighieri', 'Drops from Cybernetic Daemon, Azdaja the Joyous and Maiden', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 300, 'Inert Sigil of Machiavelli', 'Drops from Phobettor', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 300, 'Portable Notum Infusion Device', 'Chance of dropping from Cybernetic Daemon, Azdaja the Joyous and Maiden. 100% drop rate from Phobettor.', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 1, 'Laughing Spirit Capsule', 'Cybernetic Daemon', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 1, 'Crying Spirit Capsule', 'Azdaja the Joyous', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'General', 1, 'Screaming Spirit Capsule', 'Maiden', 3);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 100, 'Ancient Resorative Fungus', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 300, 'Sluggish Notum Lens', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 100, 'Ancient Aggressive Webbing', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 300, 'Dense Nanite Aegis', '', 1);
INSERT INTO raid_loot (raid, category, ql, name, comment, multiloot) VALUES ('Pyramid of Home', 'HUD/NCU', 100, 'Ancient Protective Drone', '', 1);