DROP TABLE IF EXISTS pocketboss;
CREATE TABLE pocketboss (id INT NOT NULL PRIMARY KEY, name VARCHAR(30) NOT NULL, playfield_id INT NOT NULL, mob_type VARCHAR(255) NOT NULL, level INT NOT NULL, location VARCHAR(255) NOT NULL);
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (1, 'Adobe Suzerain', 4880, 'Eremites', 125, 'Highlands NW Incarnator N');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (2, 'Aesma Daeva', 4605, 'Ithaki & Spetses', 220, 'Incarnator QL 255');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (3, 'Ahpta', 4605, 'Named Spinetooth: Atakirh & Salahpt', 220, 'Each side of the ramp to Razor''s Lair');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (4, 'Alatyr', 4320, 'Stubby Stalker and Named', 188, 'SW Glacier Hill - SW Statue');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (5, 'Anya', 4321, 'Savvy Spinetooth Bosses: Maywakaham, Waqamawi', 185, 'SW from Spirit Palace - N from Ruins');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (6, 'Aray', 4320, 'Alonissos / Levkada', 210, 'West Brink / South from Icarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (7, 'Argil Suzerain', 4880, 'Eremites', 125, 'West Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (8, 'Ashmara Ravin', 4880, 'Arcorash and Named', 125, 'The Plundge');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (9, 'Ats (Ats`usk)', 4605, 'Isham, Spinetooths, Marsh Lizards', 220, 'Oasis - Inferno Frontier');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (10, 'Auger', 4881, 'Spiders around', 125, 'Tree of Memories');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (11, 'Awl', 4881, 'Green named Spiders', 125, 'Tree of Memories (W)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (12, 'Bagaspati', 4321, 'Named Rafter/Cat/Vadleany', 185, 'NW from Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (13, 'Beatific Spirit', 4881, 'Spirit Hunters', 125, 'Necropolis');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (14, 'Bellowing Chimera', 4880, 'Named Chimeras', 125, 'North from East Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (15, 'Bhinaji Navi', 4881, 'Chimeran Canine, Ercorash and Named(4)', 125, 'Through Earth & Stone Pyramid');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (16, 'Black Fang', 4542, 'Named Predators (4): Limping, Howling, Pained, Wounded', 80, 'Shattered Heartlands (SE from Nero)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (17, 'Blight', 4881, 'Mephitic Mynx', 125, 'Necropolis (Ergo)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (18, 'Borer', 4880, 'Weavers/Spiders', 125, 'The Eastern Passageway/Crystal River');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (19, 'Breaker Teuvo', 4320, 'Named Hiisi Steed: Shadowmane', 175, 'North from West Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (20, 'Brutal Rafter', 4321, 'Named Rafter/Cat/Vadleany', 175, 'NW from Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (21, 'Brutal Soul Dredge', 4543, 'Spirit Soul Dredge', 85, 'Linger Echo');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (22, 'Captured Spirit', 4605, 'Spirit Hunters/Ashen Viper', 220, 'Burning Marshes NW');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (23, 'Careening Blight', 4310, 'Named Weaver Boss', 45, 'North of Brawl');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (24, 'Careening Death', 4310, 'Named Weaver Boss', 45, 'North of Brawl');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (25, 'Churn', 4873, 'Whirling Rocks and Named Golems', 195, 'In the Sand');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (26, 'Circumbendibus', 4542, 'Brutish Dryad', 80, 'Southmire (SW Swamps)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (27, 'Contorted Soul Dredge', 4881, 'Soul Dredges', 125, 'Necropolis');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (28, 'Defiler of Scheol', 4881, 'Greek Named Brink Mobs', 220, 'Halls of Scheol - Eastern');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (29, 'Devourer of Scheol', 4881, '', 205, 'Eastern Micro Islands');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (30, 'Eidolean Soul Dredge', 4320, 'Exiguous&Maeger Spirit', 180, 'Corpse Sucker Cave NW');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (31, 'Exsequiae', 4605, 'Bigot Helozabasael', 220, 'North from Sorrow');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (32, 'Fester Leila', 4605, 'Distracted Snake Tamer, Beast, Estella Fire Dryad - Vortexoid / Snakes / Dryad', 220, 'East from QL 225 Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (33, 'Flinty', 4881, 'Rigid Solid Robust Girders', 125, 'The Approach (South of Necropolis)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (34, 'Glitter', 4320, 'Chimeras: Sleet/Floe, Rafters: Snappy/Hefty/River/Frosty', 188, 'Blue Mist - SW Lake in Forest');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (35, 'Gracious Soul Dredge', 4881, 'Soul Dredges', 115, 'Necropolis');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (36, 'Gunk', 4880, 'Named Rafters (4)', 125, 'Temple Bog (swamp under bridge)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (37, 'Hadur', 4321, 'Named Brink Mobs: Follegandros...', 210, 'SE from East Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (38, 'Haqa', 4605, 'Akshk''i & Tuq''usk', 220, 'N from Oasis, S from Frontier');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (39, 'Hemut', 4880, '6 Named Croakers: Thapt, Kheferu, Nabur...', 125, 'Croaker Pass & Facet Canyon (NE)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (40, 'Ho', 4605, 'Ushamaham', 220, 'N from Oasis, S from Frontier');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (41, 'Ignis Fatuus', 4881, 'Shadows and Demons', 125, 'Rock Bottom');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (42, 'Imk', 4320, 'Named Malah and Spinetooth', 185, 'Cave North from West Hollow Entrance');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (43, 'Iunmin', 4881, 'Croaker of Night', 110, 'Eastern Micro Islands');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (44, 'Juma', 4322, 'Named Hiisi Warriors (8)', 182, 'Middle/South and Sup Level');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (45, 'K', 4605, 'Named Spinetooth Bosses', 220, '225 Incarnator - East from Xark''s Lair');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (46, 'Kaleva', 4322, 'Named Hiisi Warrior Boss (8)', 182, 'In Corridors and on the South 2nd Floor');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (47, 'Kaoline Suzerain', 4880, 'Eremites', 125, 'North from West Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (48, 'Khemhet', 4880, '6 Named: Thapt, Kheferu, Nabur...', 110, 'NorthEast from Temple Bog');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (49, 'Lethargic Spirit', 4881, 'Spirits/Spirit Hunters', 125, 'Necropolis (Ergo)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (50, 'Loessial Suzerain', 4880, 'Eremites', 125, 'West Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (51, 'Loltonunon', 4881, '5 Named Hiathlin', 125, 'Hall of Scheol, The Approach');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (52, 'Lurky', 4873, 'Named Dryads (5)', 165, 'The Jaws');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (53, 'Lya', 4605, 'Maychwyawi', 220, 'WSW from QL 255 Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (54, 'Marem', 4881, 'Birds/Imps', 125, 'Eastern Side');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (55, 'Marly Suzerain', 4880, 'Eremites', 125, 'West Incarnator & NW');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (56, 'Misery', 4881, 'Noxious Minx', 125, 'Necropolis NE');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (57, 'Moochy', 4873, 'Moochy&Named Dryads', 165, 'The Jaws');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (58, 'Morrow', 4321, 'Every mobs on the Isle', 215, 'Frozen Plateu Island');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (59, 'Odqan', 4605, 'Named Spirits: Enkindled 208', 220, 'SW Yuttos Marshes');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (60, 'Old Salty', 4873, 'Named Dryads (6)', 165, 'West / North');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (61, 'Ooze', 4880, 'Named Girders: Dirty, Sloughy, ...', 125, 'The Temple Bog (Swamp under Bridge)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (62, 'Pazuzu', 4605, 'Crete, Syros, Limnos', 220, 'QL 255 Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (63, 'Quake', 4873, 'Whirling Rocks and Named Golems', 195, 'In the Sand');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (64, 'Quondam', 4321, 'Every mobs on the Isle', 215, 'Frozen Plateu Island');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (65, 'Rallies Fete', 4605, 'Tiunissik Spot', 235, 'North from Sorrow');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (66, 'Redeemed Gilthar', 4873, 'Redeemed Faction Boss & Named Redeemed', 175, 'Redeemed Temple & Outside');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (67, 'Relief Teals', 4605, 'Pyiininnik & Pyiininnik''s Shadow', 220, 'SE Xark''s Lair Inferno');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (68, 'Sabretooth Slicer', 4312, 'Sabretooths', 35, 'Wetlands');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (69, 'Sampsa', 4321, 'Slender Rafter (Dyna)', 185, 'North from Frozen Plateu');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (70, 'Satkamear', 4881, 'Asatix Caal Coal Benacen Snaahemiel', 125, 'Halls of Scheol - Bottom Level');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (71, 'Scratch', 4542, 'Named Rafters', 80, 'West of Yuttos, NE of Boneyard');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (72, 'Screech', 4542, 'Named Rafters', 80, 'NE from Boneyard, W from Yuttos');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (73, 'Shake', 4873, 'Named Slithers', 192, 'Icicle Keep (NW White Cave)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (74, 'Shake (Golem)', 4873, 'Named Golems', 195, 'Hollow Maze');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (75, 'Shiver', 4873, 'Named Slithers', 192, 'Icicle Keep (NW White Cave)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (76, 'Silver Fang', 4542, '4 Predator Cat Boss', 80, 'SE from Nero');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (77, 'Skulky', 4873, 'Skulking Dryad', 165, 'The Jaws');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (78, 'Slinky', 4873, 'Named Dryads (5)', 165, 'The Jaws');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (79, 'Smee', 4873, 'Named Dryads (6)', 165, 'West / North');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (80, 'Spiritless Soul Dredge', 4881, 'Spirit Soul Dredge', 115, 'Necropolis');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (81, 'Srahir', 4322, 'Shadows and Hiathlins', 180, 'South Shadow Camps');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (82, 'Tcheser', 4310, 'Croaker Boss all around', 48, 'Around Two Mountains');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (83, 'The Abysmal Lord', 4873, 'TripTrapTrub Named Spiders', 160, 'The Depression or 1100x1500');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (84, 'The Abyssal Widow', 4873, 'TinyTripTrapTrup Named Spiders', 165, 'Abyss SW');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (85, 'The Achbile Guardian', 4542, 'Croaker & Minx', 120, 'Just South from Ergo');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (86, 'The Adonian Soul Dredge', 4873, 'Soul Dredges', 165, 'Dead Ends Ancient Device Ark 1');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (87, 'The Adonis Spirit Master', 4873, 'Spirits/Souls/Dredges', 165, 'Sacellum & Sea of Adonis & Ark1');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (88, 'The Archbile Queen', 4542, 'Croaker & Minx', 120, 'Just South from Ergo');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (89, 'The Brobdingnagian Mother', 4320, 'Resolute Dryad', 185, 'East of Blue Mist');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (90, 'The Dredge Driver', 4872, 'Spirit Soul Dredge', 165, 'The Suburbs/The Dig');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (91, 'The Dryad Demigod', 4605, 'Apprentice Beasthandler/Scrupulous Hiathlin/Punctilious Hiathlin/Tyro Beasthandler', 220, 'East from QL 255 Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (92, 'The Dryad Shuffle', 4320, 'Named Dryads & Hollows', 185, 'Blue Mist - from S to N');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (93, 'The Dune Suzerain', 4544, 'Coiling Eremite and Others (310x1260)', 90, 'The Brink - Tinker Tower - Shell Beach');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (94, 'The Elysian Soul Dredge', 4543, 'Spirit Soul Dredge', 90, 'Linger Echo');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (95, 'The Enrapt One', 4542, 'Mortiig bosses', 120, 'SW Elysium');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (96, 'The Indomitable Chimera', 4605, 'Chimera Mornitor/Trainer/Driver', 220, 'Burning Marshes - Misty Marshes Statue');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (97, 'The Infernal Soul Dredge', 4605, 'Named Spirits', 220, '???');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (98, 'The Maggot Lord', 4320, 'Named Eremites', 205, 'N of Blue Mist - South of The Pipe');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (99, 'The Numb One', 4542, 'Mortiig bosses', 120, 'Elysium (SW ?)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (100, 'The Penumbral Spirit Hunter', 4321, 'Vamoosing/Skedaddling Spirit', 165, 'Spirit Ruins');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (101, 'The Peristaltic Abomination', 4873, 'Eremites and Named', 172, 'Worlmhole');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (102, 'The Peristaltic Aversion', 4873, 'Eremites and Named', 172, 'Worlmhole');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (103, 'The Proprietrix', 4872, 'Soul Dredges', 165, 'The Suburbs/The Dig');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (104, 'The Scheolian Soul Dredge', 4881, 'Spirits/Spirit Hunters', 125, 'Necropolis (Ergo)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (105, 'The Stupendous Breeder', 4320, 'Named Dryads & Hollows', 185, 'East Frozen Lakes from S to N');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (106, 'The Talus Suzerain', 4544, 'Coiling Eremite and Named (310x1260)', 90, 'The Brink - Tinker Tower - Shell Beach');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (107, 'The Watchdog', 4873, 'Spirits/Souls', 165, 'Sacellum & Sea of Adonis');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (108, 'The Worm King', 4320, 'Death Wing & Named Slithers', 202, 'Muktuk Area SW from NW Red Temple');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (109, 'Thunderous Chimera', 4880, 'Chimera', 125, 'Marble Orchards, East Passage');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (110, 'Toss', 4873, 'Named Golems', 195, 'Hollow Maze');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (111, 'Tough', 4881, 'Rigid Solid Robust Girders', 125, 'The Approach (South of Necropolis)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (112, 'Ungulera', 4543, 'Named Hiathlin', 90, 'Fission Fissure');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (113, 'Upenpet', 4310, 'Croaker Boss all around', 48, 'Around Two Mountains');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (114, 'Ushqa', 4605, 'Maychwaham, Ushamaham', 220, 'Oasis, south from Inferno Frontier');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (115, 'Viscious Visitant', 4873, 'Spirits', 165, 'The Suburbs');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (116, 'Wacky Suzerain', 4880, 'Named Eremites: Coiling, Sparkling, Bending...', 125, 'NW from West Incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (117, 'White', 4540, 'Chill Spider & 2 Named Bosses', 120, 'White Pass (The Scoop)');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (118, 'Xark the Battletoad', 4320, 'Death Wing, Slithers, Maar...', 255, 'South from Purity');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (119, 'Zoetic Oak', 4320, 'Stubby Stalker and Named', 180, 'SW Glacier Hill - SW Statue');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (120, 'Shullat', 4605, 'Tinos, Astypalia, Phatmos', 255, 'Clan Sanctuary Exit: Razor''s Lair');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (121, 'Taille Frees', 4605, 'Aniitap''s Shadow/Aniitap(250)/Wicked Shadow', 220, 'Path to the Redeemed Temple - Aniitap Spot');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (122, 'Waqa', 4005, 'Natsmaahpt, Sanatsimk', 220, 'South of Xark''s Lair - North from Yuttos');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (123, 'Arch Bigot Biap', 4605, 'Obsolete Soul Dredge', 220, 'North from Incarnator 255');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (124, 'Asase Ya', 4005, 'Asase''s Drudge, Nyame''s Abettor, Asase''s Child', 255, 'SW limits of Inferno by Sorrow South');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (125, 'Canceroid Cupid', 4311, 'Named Cripplers', 40, 'Steppe of Dispair');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (126, 'Sasabonsam', 4605, 'Anansi''s Disciple', 220, 'Dark Hills - SE from 255 incarnator');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (127, 'Circumbendibum', 4542, 'Named Dryads', 80, 'Southmire');
INSERT INTO pocketboss (id, name, playfield_id, mob_type, level, location) VALUES (128, 'Agent of Decay', 4605, 'Eremites East from Hebiel & Ahomac', 255, 'Near 225 Incarnator (Eremites)');