DROP TABLE IF EXISTS pocketboss_loot;
CREATE TABLE pocketboss_loot (pocketboss_id INT NOT NULL, symb_type VARCHAR(25) NOT NULL, slot VARCHAR(25) NOT NULL, line VARCHAR(25) NOT NULL, item_id INT NOT NULL);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Artillery', 'Ocular', 'Active', 219135);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Infantry', 'Thigh', 'Active', 235792);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Infantry', 'Feet', 'Surviving', 235825);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Infantry', 'Feet', 'Working', 235826);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Infantry', 'Feet', 'Active', 235827);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Extermination', 'Ocular', 'Surviving', 235842);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (1, 'Artillery', 'Left Hand', 'Operative', 235586);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (2, 'Infantry', 'Left Arm', 'Vital', 235711);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (3, 'Artillery', 'Feet', 'Excited', 235612);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (3, 'Control', 'Ocular', 'Cognizant', 236297);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (3, 'Control', 'Brain', 'Excited', 236312);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (3, 'Control', 'Brain', 'Cognizant', 236313);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (3, 'Support', 'Thigh', 'Excited', 236250);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Artillery', 'Left Arm', 'Awakened', 235487);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Infantry', 'Ocular', 'Living', 235625);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Support', 'Right Arm', 'Awakened', 236117);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Support', 'Right Arm', 'Enduring', 236118);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Support', 'Right Arm', 'Living', 236119);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Support', 'Chest', 'Awakened', 236136);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (4, 'Support', 'Left Arm', 'Awakened', 236157);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Artillery', 'Right Hand', 'Vigorous', 235559);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Infantry', 'Left Hand', 'Enduring', 235810);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Infantry', 'Left Hand', 'Vigorous', 235812);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Artillery', 'Brain', 'Growing', 235417);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Infantry', 'Left Hand', 'Growing', 235811);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Infantry', 'Feet', 'Enduring', 235828);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (5, 'Extermination', 'Ocular', 'Growing', 235844);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Artillery', 'Ear', 'Vital', 235438);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Artillery', 'Right Hand', 'Effective', 235560);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Artillery', 'Left Hand', 'Effective', 235592);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Extermination', 'Waist', 'Effective', 235964);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Extermination', 'Waist', 'Excited', 235965);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Extermination', 'Waist', 'Vital', 235966);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (6, 'Extermination', 'Chest', 'Vital', 235916);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (7, 'Artillery', 'Waist', 'Vibrating', 235516);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (7, 'Control', 'Right Arm', 'Residing', 236342);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (7, 'Control', 'Chest', 'Operative', 236357);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (7, 'Control', 'Chest', 'Running', 236358);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (7, 'Control', 'Chest', 'Surviving', 236359);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (7, 'Control', 'Right Arm', 'Breathing', 236341);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Extermination', 'Feet', 'Operative', 236048);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Support', 'Right Arm', 'Breathing', 236113);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Artillery', 'Right Arm', 'Breathing', 235450);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Infantry', 'Brain', 'Vibrating', 235638);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Extermination', 'Feet', 'Vibrating', 236047);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Support', 'Ocular', 'Breathing', 236065);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (8, 'Extermination', 'Feet', 'Residing', 236049);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (9, 'Infantry', 'Right Wrist', 'Vital', 235726);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (10, 'Artillery', 'Brain', 'Residing', 235414);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (10, 'Extermination', 'Right Arm', 'Prevailing', 235892);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (10, 'Extermination', 'Right Arm', 'Surviving', 235893);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (10, 'Extermination', 'Chest', 'Residing', 235909);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (10, 'Artillery', 'Feet', 'Vibrating', 235604);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (10, 'Extermination', 'Chest', 'Active', 235911);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Artillery', 'Brain', 'Running', 235415);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Artillery', 'Feet', 'Residing', 235605);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Extermination', 'Chest', 'Running', 235910);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Extermination', 'Chest', 'Active', 235911);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Extermination', 'Left Arm', 'Prevailing', 235927);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Extermination', 'Left Arm', 'Working', 235928);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (11, 'Extermination', 'Left Arm', 'Active', 235929);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Artillery', 'Right Arm', 'Enduring', 235455);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Extermination', 'Right Wrist', 'Vigorous', 235950);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Extermination', 'Waist', 'Vigorous', 235963);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Extermination', 'Right Hand', 'Enduring', 236000);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Artillery', 'Thigh', 'Vigorous', 235574);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Artillery', 'Left Hand', 'Persisting', 235591);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (12, 'Extermination', 'Ear', 'Vigorous', 235880);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Artillery', 'Ear', 'Running', 235434);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Artillery', 'Feet', 'Active', 235607);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Extermination', 'Waist', 'Active', 235962);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Extermination', 'Left Wrist', 'Residing', 235978);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Extermination', 'Left Wrist', 'Active', 235979);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Extermination', 'Right Hand', 'Prevailing', 235995);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Extermination', 'Right Hand', 'Running', 235997);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (13, 'Extermination', 'Left Wrist', 'Prevailing', 235977);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Artillery', 'Right Wrist', 'Residing', 235501);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Artillery', 'Right Wrist', 'Surviving', 235503);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Infantry', 'Right Arm', 'Residing', 235671);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Control', 'Ear', 'Running', 236322);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Control', 'Ear', 'Surviving', 236323);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Control', 'Ear', 'Working', 236324);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Control', 'Ear', 'Active', 236325);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (14, 'Control', 'Right Arm', 'Vibrating', 236340);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (15, 'Support', 'Waist', 'Surviving', 236196);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (15, 'Support', 'Waist', 'Prevailing', 236194);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (15, 'Support', 'Left Wrist', 'Vibrating', 236209);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (15, 'Infantry', 'Ear', 'Residing', 235654);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (15, 'Support', 'Waist', 'Residing', 236195);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Artillery', 'Ocular', 'Animated', 219130);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Artillery', 'Ocular', 'Breathing', 219132);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Artillery', 'Right Arm', 'Moving', 235449);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Infantry', 'Ocular', 'Animated', 235621);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Infantry', 'Right Wrist', 'Animated', 235719);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Infantry', 'Right Wrist', 'Moving', 235720);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Infantry', 'Waist', 'Lulled', 235734);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Infantry', 'Waist', 'Animated', 235735);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (16, 'Infantry', 'Left Wrist', 'Lulled', 235752);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Artillery', 'Right Hand', 'Working', 235555);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Infantry', 'Brain', 'Running', 235641);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Support', 'Right Arm', 'Prevailing', 236114);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Support', 'Right Arm', 'Breathing', 236113);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Support', 'Right Arm', 'Active', 236116);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Support', 'Right Arm', 'Working', 236115);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (17, 'Support', 'Ear', 'Working', 236103);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Artillery', 'Ear', 'Residing', 235433);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Extermination', 'Right Wrist', 'Prevailing', 235947);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Extermination', 'Waist', 'Prevailing', 235960);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Extermination', 'Waist', 'Surviving', 235961);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Extermination', 'Right Wrist', 'Active', 235949);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Extermination', 'Right Wrist', 'Working', 235948);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (18, 'Artillery', 'Feet', 'Working', 235606);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Artillery', 'Feet', 'Enduring', 235608);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Extermination', 'Right Hand', 'Living', 236001);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Extermination', 'Right Hand', 'Persisting', 236002);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Extermination', 'Thigh', 'Awakened', 236018);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Extermination', 'Thigh', 'Growing', 236019);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Extermination', 'Left Hand', 'Awakened', 236033);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (19, 'Artillery', 'Right Arm', 'Persisting', 235456);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Artillery', 'Right Arm', 'Awakened', 235454);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Artillery', 'Right Arm', 'Enduring', 235455);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Artillery', 'Left Hand', 'Persisting', 235591);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Extermination', 'Left Wrist', 'Awakened', 235980);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Extermination', 'Chest', 'Growing', 235913);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Extermination', 'Chest', 'Persisting', 235914);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Extermination', 'Left Arm', 'Enduring', 235931);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Extermination', 'Left Wrist', 'Enduring', 235981);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (20, 'Extermination', 'Left Wrist', 'Growing', 235982);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Artillery', 'Ear', 'Moving', 235430);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Extermination', 'Ear', 'Moving', 235872);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Extermination', 'Ear', 'Vibrating', 235873);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Extermination', 'Right Arm', 'Animated', 235891);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Extermination', 'Chest', 'Breathing', 235907);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Artillery', 'Right Wrist', 'Animated', 235499);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (21, 'Extermination', 'Brain', 'Breathing', 235856);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (22, 'Infantry', 'Waist', 'Living', 235741);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (23, 'Extermination', 'Ocular', 'Lulled', 235839);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (23, 'Extermination', 'Chest', 'Lulled', 235906);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (23, 'Extermination', 'Ear', 'Lulled', 235871);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (23, 'Extermination', 'Left Arm', 'Lulled', 235924);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (23, 'Artillery', 'Ear', 'Sluggish', 235428);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (23, 'Infantry', 'Feet', 'Lulled', 235820);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (24, 'Artillery', 'Right Arm', 'Sluggish', 235445);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (24, 'Extermination', 'Feet', 'Sluggish', 236044);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (24, 'Extermination', 'Right Hand', 'Sleeping', 235991);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (25, 'Infantry', 'Right Arm', 'Vigorous', 235677);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (25, 'Infantry', 'Right Arm', 'Effective', 235678);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (25, 'Control', 'Left Arm', 'Persisting', 236378);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (25, 'Control', 'Right Wrist', 'Persisting', 236397);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (25, 'Control', 'Right Wrist', 'Vigorous', 236398);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (25, 'Artillery', 'Left Wrist', 'Vigorous', 235540);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Artillery', 'Right Arm', 'Lulled', 235447);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Infantry', 'Right Arm', 'Moving', 235667);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Infantry', 'Chest', 'Moving', 235686);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Infantry', 'Right Wrist', 'Lulled', 235718);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Artillery', 'Ocular', 'Vibrating', 219131);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Infantry', 'Left Arm', 'Moving', 235704);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (26, 'Infantry', 'Left Arm', 'Animated', 235703);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Artillery', 'Chest', 'Running', 235467);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Artillery', 'Waist', 'Operative', 235517);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Infantry', 'Ear', 'Breathing', 235653);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Support', 'Right Wrist', 'Operative', 236175);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Support', 'Right Wrist', 'Running', 236176);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Support', 'Right Wrist', 'Active', 236178);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Support', 'Waist', 'Breathing', 236192);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (27, 'Support', 'Waist', 'Operative', 236193);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (28, 'Artillery', 'Ocular', 'Vigorous', 219137);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (29, 'Artillery', 'Ocular', 'Enduring', 219136);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (29, 'Artillery', 'Ear', 'Cognizant', 235439);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (29, 'Infantry', 'Brain', 'Alert', 235644);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (29, 'Infantry', 'Ear', 'Alert', 235662);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (30, 'Infantry', 'Left Wrist', 'Awakened', 235759);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (31, 'Infantry', 'Left Wrist', 'Effective', 235761);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (32, 'Artillery', 'Left Hand', 'Cognizant', 235595);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (32, 'Support', 'Left Arm', 'Cognizant', 236162);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (32, 'Support', 'Right Wrist', 'Vital', 236182);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (32, 'Support', 'Left Wrist', 'Cognizant', 236217);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (32, 'Support', 'Right Hand', 'Vital', 236233);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (32, 'Support', 'Right Hand', 'Cognizant', 236234);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (33, 'Support', 'Thigh', 'Residing', 236243);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (33, 'Support', 'Left Hand', 'Breathing', 236259);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (33, 'Support', 'Left Hand', 'Operative', 236260);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (33, 'Support', 'Left Hand', 'Prevailing', 236261);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (33, 'Support', 'Thigh', 'Active', 236244);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (34, 'Infantry', 'Left Wrist', 'Growing', 235760);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Artillery', 'Ocular', 'Running', 219133);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Infantry', 'Right Hand', 'Running', 235773);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Infantry', 'Right Hand', 'Working', 235774);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Infantry', 'Left Hand', 'Prevailing', 235805);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Artillery', 'Left Hand', 'Moving', 235584);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Infantry', 'Thigh', 'Surviving', 235790);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (35, 'Infantry', 'Thigh', 'Working', 235791);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Artillery', 'Right Wrist', 'Residing', 235501);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Infantry', 'Right Arm', 'Breathing', 235669);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Support', 'Feet', 'Prevailing', 236276);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Support', 'Feet', 'Active', 236277);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Control', 'Ocular', 'Residing', 236291);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Control', 'Ocular', 'Running', 236292);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (36, 'Control', 'Ocular', 'Working', 236293);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (37, 'Extermination', 'Thigh', 'Effective', 236020);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (37, 'Extermination', 'Feet', 'Vital', 236054);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (37, 'Artillery', 'Left Hand', 'Excited', 235593);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (38, 'Infantry', 'Ocular', 'Vital', 235629);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (38, 'Control', 'Right Wrist', 'Vital', 236399);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (38, 'Control', 'Chest', 'Cognizant', 236364);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (38, 'Control', 'Left Arm', 'Vital', 236382);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (38, 'Control', 'Left Arm', 'Excited', 236381);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (39, 'Artillery', 'Chest', 'Vibrating', 235465);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (39, 'Support', 'Chest', 'Vibrating', 236131);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (39, 'Support', 'Chest', 'Operative', 236132);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (39, 'Support', 'Chest', 'Prevailing', 236133);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (39, 'Support', 'Chest', 'Running', 236134);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (40, 'Infantry', 'Waist', 'Effective', 235744);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Artillery', 'Ear', 'Surviving', 235435);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Extermination', 'Right Hand', 'Residing', 235996);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Extermination', 'Right Hand', 'Running', 235997);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Extermination', 'Right Hand', 'Working', 235998);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Extermination', 'Thigh', 'Running', 236015);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Infantry', 'Ocular', 'Prevailing', 235622);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (41, 'Extermination', 'Right Hand', 'Active', 235999);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Artillery', 'Left Arm', 'Persisting', 235488);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Infantry', 'Ocular', 'Persisting', 235626);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Support', 'Left Arm', 'Living', 236158);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Support', 'Right Wrist', 'Enduring', 236179);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Support', 'Right Wrist', 'Persisting', 236180);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Support', 'Right Wrist', 'Vigorous', 236181);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (42, 'Support', 'Waist', 'Persisting', 236198);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Artillery', 'Left Hand', 'Surviving', 235589);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Extermination', 'Ocular', 'Active', 235843);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Extermination', 'Brain', 'Prevailing', 235857);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Extermination', 'Brain', 'Surviving', 235858);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Artillery', 'Brain', 'Prevailing', 235413);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Extermination', 'Brain', 'Active', 235859);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (43, 'Extermination', 'Ear', 'Prevailing', 235874);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Artillery', 'Left Arm', 'Vigorous', 235489);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Infantry', 'Ocular', 'Vigorous', 235627);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Support', 'Left Wrist', 'Awakened', 236215);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Support', 'Left Wrist', 'Persisting', 236216);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Support', 'Right Hand', 'Awakened', 236231);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Support', 'Right Hand', 'Vigorous', 236232);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (44, 'Support', 'Thigh', 'Awakened', 236245);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (45, 'Extermination', 'Left Arm', 'Cognizant', 235933);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (45, 'Extermination', 'Feet', 'Cognizant', 236055);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (45, 'Extermination', 'Left Wrist', 'Cognizant', 235985);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (45, 'Artillery', 'Left Wrist', 'Cognizant', 235541);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Artillery', 'Right Wrist', 'Living', 235504);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Infantry', 'Brain', 'Awakened', 235643);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Support', 'Thigh', 'Awakened', 236245);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Support', 'Thigh', 'Growing', 236246);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Support', 'Thigh', 'Living', 236247);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Support', 'Thigh', 'Vigorous', 236248);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Support', 'Left Hand', 'Enduring', 236265);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (46, 'Support', 'Left Hand', 'Living', 236266);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Infantry', 'Chest', 'Active', 235689);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Control', 'Left Wrist', 'Running', 236428);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Control', 'Right Hand', 'Breathing', 236445);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Control', 'Right Hand', 'Operative', 236446);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Control', 'Right Hand', 'Residing', 236447);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Artillery', 'Waist', 'Working', 235520);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (47, 'Control', 'Right Hand', 'Surviving', 236448);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Artillery', 'Chest', 'Residing', 235466);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Support', 'Left Arm', 'Prevailing', 236154);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Support', 'Left Arm', 'Residing', 236155);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Support', 'Left Arm', 'Surviving', 236156);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Support', 'Right Wrist', 'Operative', 236175);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Infantry', 'Ear', 'Vibrating', 235652);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (48, 'Support', 'Left Arm', 'Breathing', 236153);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Artillery', 'Right Arm', 'Prevailing', 235451);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Support', 'Ocular', 'Prevailing', 236066);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Support', 'Ocular', 'Surviving', 236067);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Support', 'Ocular', 'Working', 236068);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Support', 'Ocular', 'Active', 236069);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Infantry', 'Brain', 'Operative', 235639);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (49, 'Support', 'Brain', 'Prevailing', 236082);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (50, 'Artillery', 'Waist', 'Operative', 235517);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (50, 'Control', 'Left Arm', 'Vibrating', 236372);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (50, 'Control', 'Left Arm', 'Breathing', 236373);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (50, 'Control', 'Left Arm', 'Operative', 236374);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (50, 'Control', 'Left Arm', 'Surviving', 236375);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (51, 'Infantry', 'Waist', 'Operative', 235737);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Artillery', 'Right Hand', 'Working', 235555);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Control', 'Left Hand', 'Growing', 236485);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Control', 'Feet', 'Working', 236499);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Control', 'Feet', 'Enduring', 236500);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Infantry', 'Chest', 'Growing', 235691);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Control', 'Feet', 'Growing', 236501);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (52, 'Infantry', 'Chest', 'Living', 235692);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (53, 'Infantry', 'Right Arm', 'Excited', 235679);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (54, 'Infantry', 'Ocular', 'Running', 235623);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (54, 'Extermination', 'Left Hand', 'Breathing', 236030);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (54, 'Extermination', 'Left Hand', 'Operative', 236031);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (54, 'Extermination', 'Thigh', 'Active', 236017);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (54, 'Extermination', 'Left Hand', 'Surviving', 236032);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (55, 'Artillery', 'Left Arm', 'Vibrating', 235484);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (55, 'Infantry', 'Ear', 'Running', 235655);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (55, 'Support', 'Left Wrist', 'Breathing', 236210);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (55, 'Support', 'Left Wrist', 'Operative', 236211);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (55, 'Support', 'Left Wrist', 'Running', 236212);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (55, 'Support', 'Left Wrist', 'Surviving', 236213);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (56, 'Support', 'Ear', 'Vibrating', 236099);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (56, 'Support', 'Ear', 'Breathing', 236100);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (56, 'Support', 'Ear', 'Surviving', 236102);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (56, 'Artillery', 'Right Arm', 'Residing', 235452);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (56, 'Support', 'Ear', 'Operative', 236101);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (56, 'Infantry', 'Brain', 'Residing', 235640);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (57, 'Artillery', 'Right Hand', 'Living', 235557);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (57, 'Infantry', 'Left Arm', 'Living', 235709);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Artillery', 'Brain', 'Vital', 235420);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Extermination', 'Ear', 'Awakened', 235876);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Extermination', 'Ear', 'Enduring', 235877);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Extermination', 'Ear', 'Growing', 235878);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Artillery', 'Right Hand', 'Effective', 235560);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Extermination', 'Brain', 'Vigorous', 235863);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (58, 'Extermination', 'Brain', 'Excited', 235864);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (59, 'Infantry', 'Waist', 'Persisting', 235742);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Artillery', 'Waist', 'Active', 235521);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Infantry', 'Ear', 'Living', 235659);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Support', 'Feet', 'Awakened', 236278);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Support', 'Feet', 'Living', 236279);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Control', 'Ocular', 'Living', 236294);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Control', 'Brain', 'Growing', 236310);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Control', 'Ear', 'Awakened', 236326);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Control', 'Ear', 'Enduring', 236327);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Control', 'Right Arm', 'Persisting', 236344);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (60, 'Infantry', 'Ear', 'Growing', 235658);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (61, 'Artillery', 'Waist', 'Prevailing', 235518);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (61, 'Infantry', 'Chest', 'Vibrating', 235687);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (61, 'Control', 'Right Wrist', 'Vibrating', 236392);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (61, 'Control', 'Right Wrist', 'Surviving', 236393);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (61, 'Control', 'Waist', 'Operative', 236411);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (62, 'Infantry', 'Chest', 'Cognizant', 235695);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Artillery', 'Left Arm', 'Effective', 235490);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Artillery', 'Right Wrist', 'Effective', 235506);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Infantry', 'Right Arm', 'Vigorous', 235677);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Control', 'Ear', 'Persisting', 236328);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Control', 'Right Arm', 'Persisting', 236344);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Control', 'Right Arm', 'Vigorous', 236345);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Control', 'Chest', 'Effective', 236362);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Support', 'Ear', 'Effective', 236107);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Support', 'Thigh', 'Effective', 236249);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Control', 'Right Arm', 'Effective', 236346);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (63, 'Control', 'Left Arm', 'Vigorous', 236379);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Artillery', 'Brain', 'Excited', 235419);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Artillery', 'Waist', 'Vital', 235524);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Infantry', 'Thigh', 'Vital', 235796);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Infantry', 'Feet', 'Vital', 235830);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Extermination', 'Ocular', 'Effective', 235845);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Extermination', 'Brain', 'Awakened', 235860);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Extermination', 'Brain', 'Growing', 235861);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (64, 'Extermination', 'Brain', 'Persisting', 235862);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (65, 'Artillery', 'Waist', 'Alert', 235525);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (65, 'Extermination', 'Left Wrist', 'Alert', 235986);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (66, 'Artillery', 'Ear', 'Active', 235436);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (67, 'Support', 'Right Arm', 'Cognizant', 236122);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (67, 'Support', 'Chest', 'Excited', 236139);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (67, 'Support', 'Chest', 'Vital', 236140);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (67, 'Artillery', 'Left Hand', 'Vital', 235594);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (68, 'Artillery', 'Chest', 'Lethargic', 235461);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (68, 'Artillery', 'Right Wrist', 'Neglectful', 235497);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (68, 'Artillery', 'Waist', 'Neglectful', 235512);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Artillery', 'Brain', 'Awakened', 235416);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Artillery', 'Right Hand', 'Persisting', 235558);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Infantry', 'Right Hand', 'Enduring', 235775);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Infantry', 'Right Hand', 'Living', 235776);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Infantry', 'Right Hand', 'Persisting', 235777);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Infantry', 'Thigh', 'Awakened', 235793);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (69, 'Infantry', 'Thigh', 'Persisting', 235794);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (70, 'Infantry', 'Waist', 'Breathing', 235736);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (71, 'Artillery', 'Chest', 'Animated', 235463);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (71, 'Infantry', 'Right Hand', 'Lulled', 235769);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (71, 'Infantry', 'Right Hand', 'Moving', 235771);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (71, 'Artillery', 'Brain', 'Lulled', 235409);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (71, 'Infantry', 'Left Wrist', 'Animated', 235753);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (71, 'Infantry', 'Right Hand', 'Animated', 235770);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (72, 'Artillery', 'Brain', 'Moving', 235410);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (72, 'Artillery', 'Chest', 'Moving', 235464);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (72, 'Infantry', 'Thigh', 'Moving', 235786);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (72, 'Infantry', 'Left Hand', 'Moving', 235804);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (72, 'Infantry', 'Thigh', 'Vibrating', 235787);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (72, 'Infantry', 'Right Hand', 'Breathing', 235772);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (73, 'Artillery', 'Ocular', 'Persisting', 219140);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (73, 'Control', 'Feet', 'Persisting', 236502);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (73, 'Infantry', 'Left Arm', 'Persisting', 235710);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (73, 'Control', 'Thigh', 'Persisting', 236470);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Support', 'Ear', 'Effective', 236107);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Support', 'Chest', 'Effective', 236137);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Artillery', 'Left Arm', 'Effective', 235490);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Artillery', 'Feet', 'Effective', 235611);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Support', 'Right Arm', 'Effective', 236120);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Support', 'Left Arm', 'Effective', 236159);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (74, 'Support', 'Thigh', 'Effective', 236249);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Infantry', 'Chest', 'Persisting', 235693);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Control', 'Waist', 'Persisting', 236417);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Control', 'Left Wrist', 'Persisting', 236431);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Control', 'Left Wrist', 'Vigorous', 236432);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Control', 'Right Hand', 'Persisting', 236453);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Artillery', 'Chest', 'Growing', 235471);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (75, 'Control', 'Left Wrist', 'Effective', 236433);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Artillery', 'Ocular', 'Animated', 219130);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Infantry', 'Ocular', 'Lulled', 235620);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Infantry', 'Ear', 'Animated', 235651);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Artillery', 'Ear', 'Lulled', 235429);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Artillery', 'Feet', 'Moving', 235603);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Infantry', 'Ocular', 'Animated', 235621);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (76, 'Infantry', 'Brain', 'Lulled', 235637);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (77, 'Artillery', 'Right Hand', 'Active', 235556);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (77, 'Infantry', 'Chest', 'Awakened', 235690);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (77, 'Infantry', 'Chest', 'Living', 235692);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Artillery', 'Left Wrist', 'Living', 235539);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Control', 'Thigh', 'Active', 236466);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Control', 'Thigh', 'Awakened', 236467);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Control', 'Thigh', 'Growing', 236468);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Control', 'Thigh', 'Living', 236469);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Infantry', 'Chest', 'Awakened', 235690);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (78, 'Control', 'Left Hand', 'Working', 236484);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Artillery', 'Waist', 'Enduring', 235522);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Infantry', 'Ear', 'Living', 235659);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Control', 'Brain', 'Growing', 236310);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Control', 'Ear', 'Enduring', 236327);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Control', 'Right Arm', 'Growing', 236343);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Control', 'Chest', 'Awakened', 236361);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Control', 'Left Arm', 'Growing', 236377);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (79, 'Control', 'Right Wrist', 'Enduring', 236395);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Artillery', 'Ocular', 'Surviving', 219134);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Artillery', 'Left Hand', 'Vibrating', 235585);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Infantry', 'Left Hand', 'Residing', 235806);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Infantry', 'Left Hand', 'Running', 235807);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Artillery', 'Right Arm', 'Breathing', 235450);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Infantry', 'Feet', 'Prevailing', 235824);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (80, 'Infantry', 'Left Hand', 'Surviving', 235808);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Artillery', 'Chest', 'Enduring', 235470);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Artillery', 'Chest', 'Growing', 235471);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Artillery', 'Feet', 'Living', 235610);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Extermination', 'Feet', 'Active', 236050);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Extermination', 'Feet', 'Persisting', 236052);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Support', 'Ocular', 'Surviving', 236067);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Support', 'Ocular', 'Growing', 236070);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Support', 'Ocular', 'Living', 236071);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Support', 'Brain', 'Enduring', 236084);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (81, 'Support', 'Brain', 'Living', 236085);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (82, 'Control', 'Right Arm', 'Lulled', 236339);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (82, 'Control', 'Chest', 'Sluggish', 236355);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (82, 'Artillery', 'Right Hand', 'Sluggish', 235550);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (82, 'Control', 'Ear', 'Sluggish', 236319);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (82, 'Control', 'Right Arm', 'Sluggish', 236338);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (83, 'Infantry', 'Left Wrist', 'Residing', 235756);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (84, 'Infantry', 'Waist', 'Awakened', 235740);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (85, 'Infantry', 'Left Wrist', 'Breathing', 235755);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (86, 'Infantry', 'Right Wrist', 'Residing', 235722);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (86, 'Artillery', 'Thigh', 'Enduring', 235571);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (87, 'Artillery', 'Left Hand', 'Prevailing', 235587);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (87, 'Infantry', 'Waist', 'Residing', 235738);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Artillery', 'Left Wrist', 'Breathing', 235535);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Infantry', 'Left Arm', 'Vibrating', 235705);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Control', 'Thigh', 'Vibrating', 236463);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Control', 'Thigh', 'Residing', 236464);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Control', 'Thigh', 'Running', 236465);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Control', 'Left Hand', 'Vibrating', 236480);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (88, 'Control', 'Left Hand', 'Breathing', 236481);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (89, 'Infantry', 'Left Wrist', 'Surviving', 235757);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (90, 'Artillery', 'Thigh', 'Living', 235573);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (90, 'Infantry', 'Right Wrist', 'Living', 235724);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (91, 'Infantry', 'Chest', 'Vital', 235694);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (92, 'Artillery', 'Chest', 'Awakened', 235469);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (92, 'Extermination', 'Left Hand', 'Enduring', 236034);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (92, 'Extermination', 'Right Hand', 'Vigorous', 236003);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (92, 'Artillery', 'Feet', 'Growing', 235609);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (92, 'Extermination', 'Feet', 'Enduring', 236051);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (92, 'Extermination', 'Left Hand', 'Growing', 236035);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (93, 'Extermination', 'Ocular', 'Operative', 235841);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (93, 'Artillery', 'Brain', 'Operative', 235412);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (93, 'Artillery', 'Right Hand', 'Moving', 235552);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (93, 'Extermination', 'Left Arm', 'Vibrating', 235925);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (93, 'Extermination', 'Chest', 'Operative', 235908);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (93, 'Infantry', 'Feet', 'Operative', 235823);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (94, 'Extermination', 'Thigh', 'Animated', 236011);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (94, 'Extermination', 'Thigh', 'Moving', 236012);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (94, 'Extermination', 'Thigh', 'Breathing', 236014);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (94, 'Extermination', 'Left Hand', 'Animated', 236029);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (94, 'Artillery', 'Right Arm', 'Animated', 235448);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (94, 'Artillery', 'Thigh', 'Operative', 235569);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (95, 'Artillery', 'Right Hand', 'Breathing', 235553);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (95, 'Infantry', 'Left Arm', 'Running', 235708);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (96, 'Infantry', 'Right Wrist', 'Excited', 235725);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (97, 'Infantry', 'Waist', 'Vigorous', 235743);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Infantry', 'Right Hand', 'Excited', 235778);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Infantry', 'Right Hand', 'Vital', 235779);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Infantry', 'Thigh', 'Excited', 235795);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Infantry', 'Thigh', 'Vital', 235796);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Artillery', 'Brain', 'Persisting', 235418);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Artillery', 'Right Wrist', 'Excited', 235507);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (98, 'Infantry', 'Feet', 'Effective', 235829);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (99, 'Artillery', 'Left Wrist', 'Surviving', 235537);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (99, 'Infantry', 'Left Arm', 'Operative', 235707);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Artillery', 'Left Hand', 'Living', 235590);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Extermination', 'Ear', 'Living', 235879);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Extermination', 'Right Arm', 'Growing', 235895);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Extermination', 'Chest', 'Awakened', 235912);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Extermination', 'Chest', 'Growing', 235913);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Extermination', 'Left Arm', 'Awakened', 235930);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (100, 'Artillery', 'Ear', 'Awakened', 235437);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Artillery', 'Left Wrist', 'Enduring', 235538);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Infantry', 'Right Arm', 'Living', 235675);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Control', 'Left Wrist', 'Living', 236430);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Control', 'Right Hand', 'Growing', 236452);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Control', 'Right Hand', 'Working', 236449);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Control', 'Right Hand', 'Active', 236450);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (101, 'Control', 'Right Hand', 'Awakened', 236451);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Artillery', 'Waist', 'Living', 235523);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Infantry', 'Right Arm', 'Awakened', 235674);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Control', 'Waist', 'Awakened', 236414);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Control', 'Waist', 'Enduring', 236415);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Control', 'Waist', 'Growing', 236416);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Control', 'Left Wrist', 'Enduring', 236429);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (102, 'Control', 'Left Wrist', 'Living', 236430);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (103, 'Artillery', 'Left Hand', 'Residing', 235588);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (103, 'Infantry', 'Waist', 'Active', 235739);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Artillery', 'Waist', 'Surviving', 235519);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Infantry', 'Chest', 'Running', 235688);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Control', 'Waist', 'Surviving', 236413);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Control', 'Left Wrist', 'Prevailing', 236426);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Control', 'Left Wrist', 'Vibrating', 236425);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Control', 'Left Wrist', 'Residing', 236427);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (104, 'Control', 'Waist', 'Running', 236412);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (105, 'Infantry', 'Left Wrist', 'Working', 235758);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (106, 'Extermination', 'Right Wrist', 'Animated', 235943);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (106, 'Extermination', 'Right Wrist', 'Moving', 235944);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (106, 'Extermination', 'Right Wrist', 'Vibrating', 235945);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (106, 'Artillery', 'Ear', 'Breathing', 235431);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (107, 'Artillery', 'Thigh', 'Growing', 235572);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (107, 'Infantry', 'Right Wrist', 'Surviving', 235723);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (108, 'Extermination', 'Right Arm', 'Effective', 235896);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (108, 'Extermination', 'Chest', 'Excited', 235915);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (108, 'Artillery', 'Chest', 'Excited', 235472);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (108, 'Artillery', 'Thigh', 'Excited', 235575);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Artillery', 'Right Wrist', 'Residing', 235501);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Control', 'Brain', 'Running', 236307);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Control', 'Brain', 'Working', 236308);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Control', 'Brain', 'Active', 236309);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Artillery', 'Right Wrist', 'Running', 235502);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Infantry', 'Right Arm', 'Prevailing', 235670);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Control', 'Brain', 'Operative', 236306);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (109, 'Control', 'Ear', 'Operative', 236321);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Artillery', 'Right Wrist', 'Vigorous', 235505);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Support', 'Left Wrist', 'Persisting', 236216);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Support', 'Feet', 'Effective', 236280);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Control', 'Ocular', 'Persisting', 236295);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Infantry', 'Right Arm', 'Persisting', 235676);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Support', 'Left Hand', 'Persisting', 236267);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (110, 'Control', 'Ocular', 'Effective', 236296);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (111, 'Artillery', 'Left Arm', 'Breathing', 235485);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (111, 'Support', 'Right Hand', 'Vibrating', 236225);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (111, 'Support', 'Right Hand', 'Breathing', 236226);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (111, 'Support', 'Right Hand', 'Operative', 236227);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (111, 'Support', 'Right Hand', 'Residing', 236228);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (111, 'Support', 'Right Hand', 'Running', 236229);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (112, 'Extermination', 'Right Hand', 'Moving', 235993);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (112, 'Artillery', 'Ear', 'Operative', 235432);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (112, 'Artillery', 'Thigh', 'Moving', 235568);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (112, 'Extermination', 'Waist', 'Vibrating', 235959);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (112, 'Extermination', 'Left Wrist', 'Vibrating', 235975);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (113, 'Control', 'Left Arm', 'Sluggish', 236371);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (113, 'Control', 'Right Hand', 'Sluggish', 236443);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (113, 'Control', 'Waist', 'Sluggish', 236407);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (114, 'Infantry', 'Ocular', 'Excited', 235628);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (114, 'Control', 'Ear', 'Vital', 236329);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (114, 'Control', 'Chest', 'Excited', 236363);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (114, 'Control', 'Right Arm', 'Vital', 236347);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (115, 'Artillery', 'Thigh', 'Surviving', 235570);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (115, 'Infantry', 'Right Wrist', 'Prevailing', 235721);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (116, 'Artillery', 'Right Wrist', 'Breathing', 235500);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (116, 'Infantry', 'Right Arm', 'Vibrating', 235668);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (116, 'Support', 'Left Hand', 'Prevailing', 236261);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (116, 'Support', 'Left Hand', 'Running', 236262);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (116, 'Support', 'Left Hand', 'Surviving', 236263);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (116, 'Support', 'Feet', 'Breathing', 236275);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (117, 'Infantry', 'Left Arm', 'Operative', 235707);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (117, 'Control', 'Left Hand', 'Residing', 236483);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (117, 'Control', 'Feet', 'Residing', 236498);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (117, 'Control', 'Feet', 'Prevailing', 236497);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (117, 'Infantry', 'Left Arm', 'Breathing', 235706);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (118, 'Artillery', 'Left Wrist', 'Alert', 235542);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (118, 'Support', 'Waist', 'Alert', 236199);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Artillery', 'Chest', 'Awakened', 235469);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Artillery', 'Chest', 'Growing', 235471);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Infantry', 'Ocular', 'Growing', 235624);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Support', 'Brain', 'Persisting', 236086);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Support', 'Brain', 'Vigorous', 236087);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Support', 'Ear', 'Awakened', 236104);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Support', 'Ear', 'Growing', 236105);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (119, 'Support', 'Ear', 'Persisting', 236106);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (120, 'Control', 'Ocular', 'Alert', 236298);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (120, 'Support', 'Feet', 'Alert', 236282);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (121, 'Infantry', 'Ear', 'Excited', 235660);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (121, 'Control', 'Left Wrist', 'Excited', 236434);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (122, 'Support', 'Brain', 'Excited', 236088);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (122, 'Support', 'Right Arm', 'Vital', 236121);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (122, 'Artillery', 'Thigh', 'Cognizant', 235576);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (122, 'Support', 'Ocular', 'Excited', 236072);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (122, 'Support', 'Ocular', 'Vital', 236073);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (122, 'Support', 'Brain', 'Vital', 236089);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (123, 'Infantry', 'Left Arm', 'Cognizant', 235712);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (124, 'Support', 'Brain', 'Alert', 236090);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (125, 'Extermination', 'Right Arm', 'Sleeping', 235889);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (125, 'Extermination', 'Right Wrist', 'Sluggish', 235941);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (126, 'Infantry', 'Ear', 'Cognizant', 235661);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Artillery', 'Brain', 'Breathing', 235411);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Infantry', 'Feet', 'Moving', 235821);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Artillery', 'Left Arm', 'Moving', 235483);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Extermination', 'Ocular', 'Animated', 235840);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Extermination', 'Brain', 'Animated', 235854);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Extermination', 'Brain', 'Vibrating', 235855);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (127, 'Infantry', 'Feet', 'Vibrating', 235822);
INSERT INTO pocketboss_loot (pocketboss_id, symb_type, slot, line, item_id) VALUES (128, 'Extermination', 'Ocular', 'Alert', 235847);