
{
  "list": {
    "en_US": "Alts of {char} ({amount})",
    "de_DE": "Alts von {char} ({amount})"
  },
  "new_main": {
    "en_US": "<highlight>{char}<end> character has been set as your main.",
    "de_DE": "Dein neuer Main ist <highlight>{char}<end>."
  },
  "not_an_alt": {
    "en_US": "Error! This character cannot be set as your main since you do not have any alts",
    "de_DE": "Error! Da du keine Alts hast, kannst du auch keinen Main Charakter setzen."
  },
  "already_main": {
    "en_US": "Error! This character is already set as your main.",
    "de_DE": "Error! Dieser Charakter ist bereits dein Main."
  },
  "add_fail_self": {
    "en_US": "Error! You cannot register yourself as an alt.",
    "de_DE": "Error! Du kannst dich nicht als dein eigener Alt registrieren."
  },
  "add_success_target": {
    "en_US": "<highlight>{char}<end> has added you as an alt.",
    "de_DE": "<highlight>{char}<end> hat dich als seinen Alt hinzugefügt."
  },
  "add_success_self": {
    "en_US": "<highlight>{char}<end> has been added as your alt.",
    "de_DE": "<highlight>{char}<end> wurde zu deinen Alts hinzugefügt."
  },
  "add_fail_already": {
    "en_US": "Error! <highlight>{char}<end> already has alts.",
    "de_DE": "Error! <highlight>{char}<end> hat bereits alts."
  },
  "rem_success": {
    "en_US": "<highlight>{char}<end> has been removed as your alt.",
    "de_DE": "<highlight>{char}<end> wurde von deinen Alts entfernt."
  },
  "rem_fail_not": {
    "en_US": "Error! <highlight>{char}<end> is not your alt.",
    "de_DE": "Error! <highlight>{char}<end> ist kein Alt von dir."
  },
  "rem_fail_main": {
    "en_US": "Error! You cannot remove your main.",
    "de_DE": "Error! Du kannst deinen Main nicht entfernen."
  },
  "altadmin_add_same": {
    "en_US": "Error! alt and main are identical.",
    "de_DE": "Error! Der Alt und Main Charakter sind identisch."
  },
  "altadmin_add_success": {
    "en_US": "The Toon <highlight>{alt}<end> got added as an alt of <highlight>{main}<end> successfully.",
    "de_DE": "Der Charakter <highlight>{alt}<end> ist nun ein Alt von <highlight>{main}<end>."
},
  "altadmin_rem_success": {
    "en_US": "<highlight>{alt}<end> is nolonger an alt of <highlight>{main}<end>.",
    "de_DE": "<highlight>{alt}<end> ist nun kein Alt von <highlight>{main}<end> mehr."
  },
  "altadmin_rem_fail_not": {
    "en_US": "Error! <highlight>{alt}<end> is not an alt of <highlight>{main}<end>.",
    "de_DE": "Error! <highlight>{alt}<end> ist kein Alt von <highlight>{main}<end>."
  },
  "altadmin_rem_fail_main": {
    "en_US": "Error! Main Characters may not get removed from their alt list.",
    "de_DE": "Error! Du kannst keinen Main von seiner Altliste entfernen."
  },
  "altadmin": {
    "en_US": "",
    "de_DE": ""
  }
}
