{
  "alias_blob_title": {
    "en_US": "Aliases ({amount}}",
    "de_DE": "Alias Liste ({amount}"
  },
  "alias_add_success": {
    "en_US": "Alias <highlight>{alias}<end> for command <highlight>{cmd}<end> added successfully.",
    "de_DE": "Der Alias <highlight>{alias}<end> für den Befehl <highlight>{cmd}<end> wurde erfolgreich hinzugefuegt."
  },
  "alias_add_fail": {
    "en_US": "Cannot add alias <highlight>{alias}<end> since there is already an active alias with that name.",
    "de_DE": "Der Alias <highlight>{alias}<end> konnte nicht hinzugefuegt werden, da bereits einer mit selbigem Alias existiert."
  },
  "alias_rem_success": {
    "en_US": "Alias <highlight>{alias}<end> has been removed successfully.",
    "de_DE": "Der Alias <highlight>{alias}<end> wurde erfolgreich entfernt."
  },
  "alias_rem_fail": {
    "en_US": "Could not find alias <highlight>{alias}<end>",
    "de_DE": "Der Alias <highlight>{alias}<end> konnte nicht gefunden werden."
  },
  "cmdlist_commands": {
    "en_US": "Commands ({amount}",
    "de_DE": "Befehlsliste ({amount})"
  }
}