{
  "alias_blob_title": {
    "en_US": "Aliases ({amount})",
    "de_DE": "Alias Liste ({amount})"
  },
  "alias_add_success": {
    "en_US": "Alias <highlight>{alias}</highlight> for command <highlight>{cmd}</highlight> added successfully.",
    "de_DE": "Der Alias <highlight>{alias}</highlight> für den Befehl <highlight>{cmd}</highlight> wurde erfolgreich hinzugefügt."
  },
  "alias_add_fail": {
    "en_US": "Cannot add alias <highlight>{alias}</highlight> since there is already an active alias with that name.",
    "de_DE": "Der Alias <highlight>{alias}</highlight> konnte nicht hinzugefügt werden, da bereits einer mit selbigem Alias existiert."
  },
  "alias_rem_success": {
    "en_US": "Alias <highlight>{alias}</highlight> has been removed successfully.",
    "de_DE": "Der Alias <highlight>{alias}</highlight> wurde erfolgreich entfernt."
  },
  "alias_rem_fail": {
    "en_US": "Could not find alias <highlight>{alias}</highlight>",
    "de_DE": "Der Alias <highlight>{alias}</highlight> konnte nicht gefunden werden."
  },
  "cmdlist_commands": {
    "en_US": "Commands ({amount})",
    "de_DE": "Befehlsliste ({amount})"
  },
  "cmd_unknown_channel": {
    "en_US": "Unknown command channel <highlight>{channel}</highlight>.",
    "de_DE": "Der Befehlschannel <highlight>{channel}</highlight> existiert nicht."
  },
  "cmd_unknown_for_channel": {
    "en_US": "Could not find command <highlight>{cmd}</highlight> for channel <highlight>{channel}</highlight>.",
    "de_DE": "Der Befehl <highlight>{cmd}</highlight> für den Channel <highlight>{channel}</highlight> wurde nicht gefunden."
  },
  "enabled_low": {
    "en_US": "enabled",
    "de_DE": "aktiviert"
  },
  "disabled_low": {
    "en_US": "disabled",
    "de_DE": "deaktiviert"
  },
  "run": {
    "en_US": "run",
    "de_DE": "ausgeführt"
  },
  "enabled_high": {
    "en_US": "<green>Enabled<end>",
    "de_DE": "<green>Aktiviert<end>"
  },
  "disabled_high": {
    "en_US": "<red>Disabled<end>",
    "de_DE": "<red>Deaktiviert<end>"
  },
  "enable": {
    "en_US": "Enable",
    "de_DE": "Aktivieren"
  },
  "disable": {
    "en_US": "Disable",
    "de_DE": "Deaktivieren"
  },
  "partial": {
    "en_US": "Partial",
    "de_DE": "Teilweise aktiviert"
  },
  "config": {
  "en_US": "Config ({count})",
  "de_DE": "Einstellungen ({count})"
  },
  "cmd_toggle_success": {
    "en_US": "Command <highlight>{cmd}</highlight> has been <highlight>{changedto}</highlight> successfully.",
    "de_DE": "Der Befehl <highlight>{cmd}</highlight> ist nun <highlight>{changedto}</highlight>"
  },
  "cmd_toggle_channel_success": {
    "en_US": "Command <highlight>{cmd}</highlight> for channel <highlight>{channel}</highlight> has been <highlight>{changedto}</highlight> successfully.",
    "de_DE": "Der Befehl <highlight>{cmd}</highlight> ist im channel <highlight>{channel}</highlight> nun <highlight>{changedto}</highlight>."
  },
  "unknown_accesslevel": {
    "en_US": "Unknown access level <highlight>{al}</highlight>.",
    "de_DE": "Unbekanntes Rechtelevel: <highlight>{al}</highlight>"
  },
  "set_accesslevel_success": {
    "en_US": "Access level <highlight>{al}</highlight> for command <highlight>{cmd}</highlight> has been set successfully.",
    "de_DE": "Für den Befehl <highlight>{cmd}</highlight> wurden die Zugriffsreche erfolgreich auf <highlight>{al}</highlight> geändert."
  },
  "set_accesslevel_fail": {
    "en_US": "Access level <highlight>{al}</highlight> for command <highlight>{cmd}</highlight> on channel <highlight>{channel}</highlight> has been set successfully.",
    "de_DE": "Der Befehl <highlight>{cmd}</highlight> benötigt im channel <highlight>{channel}</highlight> nun den Rang <highlight>{al}</highlight>."
  },
  "access_level": {
    "en_US": "Access Level",
    "de_DE": "Zugriffslevel"
  },
  "no_cmd": {
    "en_US": "Could not find command <highlight>{cmd}</highlight>.",
    "de_DE": "Der Befehl <highlight>{cmd}</highlight> ist mir unbekannt."
  },
  "settings": {
    "en_US": "<header2>Settings</header2>\n",
    "de_DE": "<header2>Einstellungen</header2>\n"
  },
  "commands": {
    "en_US": "\n<header2>Commands</header2>\n",
    "de_DE": "\n<header2>Befehle</header2>\n"
  },
  "events": {
    "en_US": "Events",
    "de_DE": "Events"
  },
  "hidden_events": {
    "en_US": "Hidden Events",
    "de_DE": "Verstecke Events"
  },
  "mod_title": {
    "en_US": "Module ({mod})",
    "de_DE": "Modul ({mod})"
  },
  "mod_not_found": {
    "en_US": "Could not find module <highlight>{mod}</highlight>",
    "de_DE": "Das Modul <highlight>{mod}</highlight> wurde nicht gefunden."
  },
  "no_new_value": {
    "en_US": "Error! New value required to update setting.",
    "de_DE": "Error! Es muss eine neue Option eingegeben werden, um die Einstellung zu ändern."
  },
  "set_clr": {
    "en_US": "Setting <highlight>{setting}</highlight> has been cleared.",
    "de_DE": "Die Einstellung <highlight>{setting}</highlight> wurde geleert."
  },
  "set_new": {
    "en_US": "Setting <highlight>{setting}</highlight> has been set to {value}.",
    "de_DE": "Die Einstellung <highlight>{setting}</highlight> hat nun den Wert: {value}"
  },
  "setting_not_found": {
    "en_US": "Could not find setting <highlight>{setting}</highlight>.",
    "de_DE": "Die Einstellung <highlight>{setting}</highlight> wurde nicht gefunden."
  },
  "current_value": {
    "en_US": "Current Value: <highlight>{value}</highlight>\n",
    "de_DE": "Aktueller Wert: <highlight>{value}</highlight>\n"
  },
  "description": {
    "en_US": "Description: <highlight>{desc}</highlight>\n\n",
    "de_DE": "Beschreibung: <highlight>{desc}</highlight>\n\n"
  },
  "setting": {
    "en_US": "Setting ({setting})",
    "de_DE": "Einstellung ({setting})"
  },
  "settinglist_title": {
    "en_US": "Settings ({count})",
    "de_DE": "Einstellungen ({count})"
  },
  "unknown_event": {
    "en_US": "Unknown event type <highlight>{type}</highlight>.",
    "de_DE": "Unbekannter Eventtyp: <highlight>{type}</highlight>"
  },
  "event_enable_fail": {
    "en_US": "Could not find event for type <highlight>{type}</highlight> and handler <highlight>{handler}</highlight>.",
    "de_DE": "Es konnte kein Event des types <highlight>{type}</highlight> mit dem Handler <highlight>{handler}</highlight> gefunden werden."
  },
  "event_enable_success": {
    "en_US": "Event type <highlight>{type}</highlight> for handler <highlight>{handler}</highlight> has been <highlight>{changedto}</highlight> successfully.",
    "de_DE": "Für den Eventtyp <highlight>{type}</highlight> wurde der handler <highlight>{handler}</highlight> erfolgreich <highlight>{changedto}</highlight>."
  },
  "event_manual": {
    "en_US": "Only <highlight>timer</highlight> events can be run manually.",
    "de_DE": "Es können nur <highlight>timer</highlight> Events manuell angestoßen werden."
  },
  "blob_events": {
    "en_US": "Events ({amount})",
    "de_DE": "Events ({amount})"
  },
  "hidden": {
    "en_US": "hidden",
    "de_DE": "versteckt"
  },
  "include_hidden_events": {
    "en_US": "Include hidden events",
    "de_DE": "Versteckte Events anzeigen"
  }
}
