{
  "alias_blob_title": {
    "en_US": "Aliases ({amount}}",
    "de_DE": "Alias Liste ({amount}"
  },
  "alias_add_success": {
    "en_US": "Alias <highlight>{alias}<end> for command <highlight>{cmd}<end> added successfully.",
    "de_DE": "Der Alias <highlight>{alias}<end> für den Befehl <highlight>{cmd}<end> wurde erfolgreich hinzugefügt."
  },
  "alias_add_fail": {
    "en_US": "Cannot add alias <highlight>{alias}<end> since there is already an active alias with that name.",
    "de_DE": "Der Alias <highlight>{alias}<end> konnte nicht hinzugefügt werden, da bereits einer mit selbigem Alias existiert."
  },
  "alias_rem_success": {
    "en_US": "Alias <highlight>{alias}<end> has been removed successfully.",
    "de_DE": "Der Alias <highlight>{alias}<end> wurde erfolgreich entfernt."
  },
  "alias_rem_fail": {
    "en_US": "Could not find alias <highlight>{alias}<end>",
    "de_DE": "Der Alias <highlight>{alias}<end> konnte nicht gefunden werden."
  },
  "cmdlist_commands": {
    "en_US": "Commands ({amount}",
    "de_DE": "Befehlsliste ({amount})"
  },
  "cmd_unknown_channel": {
    "en_US": "Unknown command channel <highlight>{channel}<end>.",
    "de_DE": "Der Befehlschannel <highlight>{channel}<end> existiert nicht."
  },
  "cmd_unknown_for_channel": {
    "en_US": "Could not find command <highlight>{cmd}<end> for channel <highlight>{channel}<end>.",
    "de_DE": "Der Befehl <highlight>{cmd}<end> für den Channel <highlight>{channel}<end> wurde nicht gefunden."
  },
  "enabled_low": {
    "en_US": "enabled",
    "de_DE": "aktiviert"
  },
  "disabled_low": {
    "en_US": "disabled",
    "de_DE": "deaktiviert"
  },
  "enabled_high": {
    "en_US": "<green>Enabled<end>",
    "de_DE": "<green>Aktiviert<end>"
  },
  "disabled_high": {
    "en_US": "<red>Disabled<end>",
    "de_DE": "<red>Deaktiviert<end>"
  },
  "enable": {
    "en_US": "Enable",
    "de_DE": "Aktivieren"
  },
  "disable": {
    "en_US": "Disable",
    "de_DE": "Deaktivieren"
  },
  "partial": {
    "en_US": "Partial",
    "de_DE": "Teilweise aktiviert"
  },
  "config": {
  "en_US": "config ({count})",
  "de_DE": "Einstellungen ({count})"
  },
  "cmd_toggle_success": {
    "en_US": "Command <highlight>{cmd}<end> has been <highlight>{changedto}<end> successfully.",
    "de_DE": "Der Befehl <highlight>{cmd}<end> ist nun <highlight>{changedto}<end>"
  },
  "cmd_toggle_channel_success": {
    "en_US": "Command <highlight>{cmd}<end> for channel <highlight>{channel}<end> has been <highlight>{changedto}<end> successfully.",
    "de_DE": "Der Befehl <highlight>{cmd}<end> ist im channel <highlight>{channel}<end> nun <highlight>{changedto}<end>."
  },
  "unknown_accesslevel": {
    "en_US": "Unknown access level <highlight>{al}<end>.",
    "de_DE": "Unbekanntes Rechtelevel: <highlight>{al}<end>"
  },
  "set_accesslevel_success": {
    "en_US": "Access level <highlight>{al}<end> for command <highlight>{cmd}<end> has been set successfully.",
    "de_DE": "Für den Befehl <highlight>{cmd}<end> wurden die Zugriffsreche erfolgreich auf <highlight>{al}<end> geändert."
  },
  "set_accesslevel_fail": {
    "en_US": "Access level <highlight>{al}<end> for command <highlight>{cmd}<end> on channel <highlight>{channel}<end> has been set successfully.",
    "de_DE": "Der Befehl <highlight>{cmd}<end> benötigt im channel <highlight>{channel}<end> nun den Rang <highlight>{al}<end>."
  },
  "access_level": {
    "en_US": "Access Level",
    "de_DE": "Zugriffslevel"
  },
  "no_cmd": {
    "en_US": "Could not find command <highlight>{cmd}<end>.",
    "de_DE": "Der Befehl <highlight>{cmd}<end> ist mir unbekannt."
  },
  "settings": {
    "en_US": "<header2>Settings<end>\n",
    "de_DE": "<header2>Einstellungen<end>\n"
  },
  "commands": {
    "en_US": "\n<header2>Commands<end>\n",
    "de_DE": "\n<header2>Befehle<end>\n"
  },
  "events": {
    "en_US": "\n<header2>Events<end>\n",
    "de_DE": "\n<header2>Events<end>\n"
  },
  "mod_title": {
    "en_US": "Module ({mod})",
    "de_DE": "Modul ({mod})"
  },
  "mod_not_found": {
    "en_US": "Could not find module <highlight>{mod}<end>",
    "de_DE": "Das Modul <highlight>{mod}<end> wurde nicht gefunden."
  },
  "no_new_value": {
    "en_US": "Error! New value required to update setting.",
    "de_DE": "Error! Es muss eine neue Option eingegeben werden, um die Einstellung zu ändern."
  },
  "set_clr": {
    "en_US": "Setting <highlight>{setting}<end> has been cleared.",
    "de_DE": "Die Einstellung <highlight>{setting}<end> wurde geleert. "
  },
  "set_new": {
    "en_US": "Setting <highlight>{setting}<end> has been set to {value}.",
    "de_DE": "Die Einstellung <highlight>{setting}<end> hat nun den Wert: {value}"
  },
  "setting_not_found": {
    "en_US": "Could not find setting <highlight>{setting}<end>.",
    "de_DE": "Die Einstellung <highlight>{setting}<end> wurde nicht gefunden."
  },
  "current_value": {
    "en_US": "Current Value: <highlight>{value}<end>\n",
    "de_DE": "Aktueller Wert: <highlight>{value}<end>\n"
  },
  "description": {
    "en_US": "Description: <highlight>{desc}<end>\n\n",
    "de_DE": "Beschreibung: <highlight>{desc}<end>\n\n"
  },
  "setting": {
    "en_US": "Setting ({setting})",
    "de_DE": "Einstellung ({setting})"
  },
  "unknown_event": {
    "en_US": "Unknown event type <highlight>{type}<end>.",
    "de_DE": "Unbekannter Eventtyp: <highlight>{type}<end>"
  },
  "event_enable_fail": {
    "en_US": "Could not find event for type <highlight>{type}<end> and handler <highlight>{handler}<end>.",
    "de_DE": "Es konnte kein Event des types <highlight>{type}<end> mit dem Handler <highlight>{handler}<end> gefunden werden."
  },
  "event_enable_success": {
    "en_US": "Event type <highlight>{type}<end> for handler <highlight>{handler}<end> has been <highlight>{changedto}<end> successfully.",
    "de_DE": "Für den Eventtyp <highlight>{type}<end> wurde der handler <highlight>{handler}<end> erfolgreich <highlight>{changedto}<end>."
  },
  "event_manual": {
    "en_US": "Only <highlight>timer<end> events can be run manually.",
    "de_DE": "Es können nur <highlight>timer<end> Event manuell angestoßen werden."
  },
  "blob_events": {
    "en_US": "Events ({amount})",
    "de_DE": "Events ({amount})"
  }
}