{
  "ai_armor": {
    "en_US": [
      "<highlight>Normal Armor:<end>\n",
      " - {strong}\n",
      " - {supple}\n",
      " - {enduring}\n",
      " - {observant}\n",
      " - {arithmetic}\n",
      " - {spiritual}\n\n",
      "<highlight>Combined Armor:<end>\n",
      " - {cc}\n",
      " - {cm}\n",
      " - {co}\n",
      " - {cp}\n",
      " - {css}\n"
    ],
    "de_DE": [
      "<highlight>Normale Rüstung:<end>\n",
      " - {strong}\n",
      " - {supple}\n",
      " - {enduring}\n",
      " - {observant}\n",
      " - {arithmetic}\n",
      " - {spiritual}\n\n",
      "<highlight>Kombinierte Rüstung:<end>\n",
      " - {cc}\n",
      " - {cm}\n",
      " - {co}\n",
      " - {cp}\n",
      " - {css}\n"
    ]
  },
  "ai_armor_title":{
    "en_US": "Alien Armor",
    "de_DE": "Alien Rüstung"
  },
  "ai_armor_ts_title": {
    "en_US": "Building process for {ql} {name}",
    "de_DE": "Rezept für die {name} Rüstung - QL {ql}"
  },
  "ai_armor_ts": {
    "en_US": [
      "Note: All tradeskill processes are based on the lowest QL items usable.\n\n",
      "<header2>You need the following items to build {armor_type} Armor:<end>\n",
      "- {text_viralbots} (QL{vb_ql})\n",
      "- {text_step1_tool}\n",
      "- {text_solid_clump} (QL{ql})\n",
      "- {text_vb_bot} (QL{vb_ql})\n\n",

      "<header2>Step 1<end>\n",
      "<tab>{icon_viralbots}<tab>+<tab>{icon_step1_tool}<tab>=<tab>{icon_memory_wiped_viralbots}\n\n",
      "<tab>(QL{vb_ql})<tab><tab><tab><tab><tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_viralbots} (QL{vb_ql}) (<highlight>Drops from Alien City Generals<end>)\n",
      " + <tab>{text_step1_tool}\n",
      " = <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {step1_CL} Computer Literacy\n",
      "- {step1_NP} Nano Programming\n\n",

      "<header2>Step 2<end>\n",
      "<tab>{icon_NPI}<tab>+<tab>{icon_memory_wiped_viralbots}<tab>=<tab>{icon_formatted_viralbots}\n\n",
      "<tab><tab><tab><tab> <tab>(QL{vb_ql})<tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_NPI} (<highlight>Can be bought in General Shops<end>)\n",
      " + <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      " = <tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {step2_CL} Computer Literacy\n",
      "- {step2_NP} Nano Programming\n\n",

      "<header2>Step 3<end>\n",
      "<tab>{icon_structural_analyser}<tab>+<tab>{icon_solid_clump}<tab>=<tab>{icon_mutated_material}<tab><highlight>OR<end><tab>{icon_pristine_material} \n\n",
      "<tab><tab> <tab><tab><tab>(QL{ql})<tab><tab><tab>(QL{ql})<tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_structural_analyser}\n",
      " + <tab>{text_solid_clump} (QL{ql})\n",
      " = <tab>{text_mutated_material} (QL{ql})<tab><highlight><br><tab><tab>OR<end><tab>{text_pristine_material} (QL{ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {step3_chem} Chemistry (Both require the same amount)\n\n",

      "<header2>Step 4<end>\n",
      "<tab>{icon_mutated_material}<tab><highlight>OR<end><tab>{icon_pristine_material}<tab>+<tab>{icon_bazzit_generic_nano_solvent}<tab>=<tab>{icon_dna_soup} \n\n",
      "<tab>(QL{ql})<tab>  <tab> (QL{ql})<tab> <tab><tab><tab><tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_mutated_material} (QL{ql})<tab><br><tab><tab><highlight>OR<end><tab>{text_pristine_material} (QL{ql})\n",
      " + <tab>{text_bazzit_generic_nano_solvent}\n",
      " = <tab>{text_dna_soup} (QL{ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {chem_prist} Chemistry(for Pristine)\n",
      "- {chem_mutat} Chemistry(for Mutated)\n\n",

      "<header2>Step 5<end>\n",
      "<tab>{icon_dna_soup}<tab>+<tab>{icon_human_dna}<tab>=<tab>{icon_dna_cocktail} \n\n",
      "<tab>(QL{ql})<tab> <tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_dna_soup} (QL{ql})\n",
      " + <tab>{text_human_dna}\n",
      " = <tab>{text_dna_cocktail} (QL{ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Step 6<end>\n",
      "<tab>{icon_formatted_viralbots}<tab>+<tab>{icon_dna_cocktail}<tab>=<tab>{icon_formatted_viralbot_solution} \n\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      " + <tab>{text_dna_cocktail} (QL{ql})\n",
      " = <tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Step 7<end>\n",
      "<tab>{icon_formatted_viralbot_solution}<tab>+<tab>{icon_basic_fashion_vest}<tab>=<tab>{icon_formatted_viralbot_vest} \n\n",
      "<tab>(QL{ql})<tab><tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      " + <tab>{text_basic_fashion_vest}\n",
      " = <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Step 8<end>\n",
      "<tab>{icon_vb_bot}<tab>+<tab>{icon_formatted_viralbot_vest}<tab>=<tab>{icon_armor}\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_vb_bot} (QL{vb_ql}) (<highlight>Rare Drop off Alien City Generals<end>)\n",
      " + <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      " = <tab>{text_armor} (QL{ql})\n",
      "<highlight>Required Skills:<end>\n",
      "- {psycho} Psychology"
    ],
    "de_DE": [
      "Hinweis: Bei Allen Tradeskill Vorgängen ist jeweils das minimale nötige QL angegeben, welches für das gewünschte Ergebnis notwendig ist.\n\n",
      "<header2>Zum bauen der {armor_type} Armor werden folgende Items benötigt:<end>\n",
      "- {text_viralbots} (QL{vb_ql})\n",
      "- {text_step1_tool}\n",
      "- {text_solid_clump} (QL{ql})\n",
      "- {text_vb_bot} (QL{vb_ql})\n\n",

      "<header2>Teil 1<end>\n",
      "<tab>{icon_viralbots}<tab>+<tab>{icon_step1_tool}<tab>=<tab>{icon_memory_wiped_viralbots}\n\n",
      "<tab>(QL{vb_ql})<tab><tab><tab><tab><tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_viralbots} (QL{vb_ql}) (<highlight>Droppt von Alien City Generals<end>)\n",
      " + <tab>{text_step1_tool}\n",
      " = <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {step1_CL} Computer Literacy\n",
      "- {step1_NP} Nano Programming\n\n",

      "<header2>Teil 2<end>\n",
      "<tab>{icon_NPI}<tab>+<tab>{icon_memory_wiped_viralbots}<tab>=<tab>{icon_formatted_viralbots}\n\n",
      "<tab><tab><tab><tab> <tab>(QL{vb_ql})<tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_NPI} (<highlight>Kann in General Shops gekauft werden<end>)\n",
      " + <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      " = <tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {step2_CL} Computer Literacy\n",
      "- {step2_NP} Nano Programming\n\n",

      "<header2>Teil 3<end>\n",
      "<tab>{icon_structural_analyser}<tab>+<tab>{icon_solid_clump}<tab>=<tab>{icon_mutated_material}<tab><highlight>ODER<end><tab>{icon_pristine_material} \n\n",
      "<tab><tab> <tab><tab><tab>(QL{ql})<tab><tab><tab>(QL{ql})<tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_structural_analyser}\n",
      " + <tab>{text_solid_clump} (QL{ql})\n",
      " = <tab>{text_mutated_material} (QL{ql})<tab><br><tab><tab><highlight>ODER<end><tab>{text_pristine_material} (QL{ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {step3_chem} Chemistry (Pristine/Mutated haben die gleichen Skill Anforderungen)\n\n",

      "<header2>Teil 4<end>\n",
      "<tab>{icon_mutated_material}<tab><highlight>ODER<end><tab>{icon_pristine_material}<tab>+<tab>{icon_bazzit_generic_nano_solvent}<tab>=<tab>{icon_dna_soup} \n\n",
      "<tab>(QL{ql})<tab><tab><tab> (QL{ql})<tab> <tab><tab><tab><tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_mutated_material} (QL{ql})<tab><br><tab><tab><highlight>ODER<end><tab>{text_pristine_material} (QL{ql})\n",
      " + <tab>{text_bazzit_generic_nano_solvent}\n",
      " = <tab>{text_dna_soup} (QL{ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {chem_prist} Chemistry(mit Pristine)\n",
      "- {chem_mutat} Chemistry(mit Mutated)\n\n",

      "<header2>Teil 5<end>\n",
      "<tab>{icon_dna_soup}<tab>+<tab>{icon_human_dna}<tab>=<tab>{icon_dna_cocktail} \n\n",
      "<tab>(QL{ql})<tab> <tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_dna_soup} (QL{ql})\n",
      " + <tab>{text_human_dna}\n",
      " = <tab>{text_dna_cocktail} (QL{ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Teil 6<end>\n",
      "<tab>{icon_formatted_viralbots}<tab>+<tab>{icon_dna_cocktail}<tab>=<tab>{icon_formatted_viralbot_solution} \n\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      " + <tab>{text_dna_cocktail} (QL{ql})\n",
      " = <tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Teil 7<end>\n",
      "<tab>{icon_formatted_viralbot_solution}<tab>+<tab>{icon_basic_fashion_vest}<tab>=<tab>{icon_formatted_viralbot_vest} \n\n",
      "<tab>(QL{ql})<tab><tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      " + <tab>{text_basic_fashion_vest}\n",
      " = <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Teil 8<end>\n",
      "<tab>{icon_vb_bot}<tab>+<tab>{icon_formatted_viralbot_vest}<tab>=<tab>{icon_armor}\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_vb_bot} (QL{vb_ql}) (<highlight>Seltener drop von Alien City Generals<end>)\n",
      " + <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      " = <tab>{text_armor} (QL{ql})\n",
      "<highlight>Notwendige Skills:<end>\n",
      "- {psycho} Psychology"
    ]
  },

  "ai_armor_combined_title": {
    "en_US": "Building process for QL{ql} {type}",
    "de_DE": "Rezept für die {type} - QL {ql}"
  },
  "ai_armor_combined": {
    "en_US": [
      "<header2>Tradeskill Process<end>\n\n",
      "<tab>{icon_source}<tab>+<tab>{icon_target}<tab>=<tab>{icon_result}\n",
      "<tab>(QL{s_ql})<tab> <tab>(QL{t_ql})<tab> <tab>(QL{t_ql})\n\n",
      "<tab><tab>{text_source} (QL{s_ql}) - ({ts_process_source})\n",
      " + <tab>{text_target} (QL{t_ql}) - ({ts_process_target})\n",
      " = <tab>{text_result} (QL{t_ql})\n"],
    "de_DE": [
      "<header2>Bauanleitung<end>\n\n",
      "<tab>{icon_source}<tab>+<tab>{icon_target}<tab>=<tab>{icon_result}\n",
      "<tab>(QL{s_ql})<tab> <tab>(QL{t_ql})<tab> <tab>(QL{t_ql})\n\n",
      "<tab><tab>{text_source} (QL{s_ql}) - ({ts_process_source})\n",
      " + <tab>{text_target} (QL{t_ql}) - ({ts_process_target})\n",
      " = <tab>{text_result} (QL{t_ql})\n"]
  },
  "ai_armor_ts_process": {
    "en_US": "Tradeskill process for this item",
    "de_DE": "Bauanleitung für dieses Item"
  },
  "ai_armor_combined_unknown": {
    "en_US": "Unknown armor type <highlight>{type}<end>",
    "de_DE": "Unbekannter Rüstungs Typ: <highlight>{type}<end>"
  },

  "bioinfo_list": {
    "en_US": [
      "\n<header2>OFAB Armor Types<end>\n",
      "{ofab_armor}",
      "\n<header2>OFAB Weapon Types<end>\n",
      "{ofab_weap}",
      "\n<header2>AI Armor Types<end>\n",
      "{ai_armor}",
      "\n<header2>AI Weapon Typen<end>\n",
      "{ai_weap}",
      "\n<header2>Serum Typen<end>\n",
      "{serum}"],
    "de_DE": [
      "\n<header2>OFAB Rüstung - Typen<end>\n",
      "{ofab_armor}",
      "\n<header2>OFAB Waffen - Typen<end>\n",
      "{ofab_weap}",
      "\n<header2>Alien Rüstung - Typen<end>\n",
      "{ai_armor}",
      "\n<header2>Alien Waffen - Typen<end>\n",
      "{ai_weap}",
      "\n<header2>Serum - Typen<end>\n",
      "{serum}"]
  },
  "bioinfo_list_title": {
    "en_US": "Bio-Material Types",
    "de_DE": "Bio-Material Typen"
  },
  "bioinfo_unknown_type": {
    "en_US": "Unknown bio-material type <highlight>{type}<end>.",
    "de_DE": "Unbekannter Bio-Material Typ: <highlight>{type}<end>."
  },
  "bioinfo_type_title": {
    "en_US": "{name} (QL {ql})",
    "de_DE": "{name} (QL {ql})"
  },
  "ofab_armor_bio": {
    "en_US": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrades Ofab Armor for:<end>\n",
      "{upgrades}"
    ],
    "de_DE": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrade für folgende Ofab Rüstungen:<end>\n",
      "{upgrades}"
    ]
  },
  "ofab_weapon_bio": {
    "en_US": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrades Ofab Weapons for:<end>\n",
      "{upgrades}"
    ],
    "de_DE": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrade für folgende Ofab Waffen:<end>\n",
      "{upgrades}"
    ]
  },
  "alien_armor_bio": {
    "en_US": [
      "{item}\n\n",
      "It will take <highlight>{ee_cl_req} EE & CL<end> (<highlight>4.5 * QL<end>) to analyze the Bio-Material.\n\n",

      "Used to build Alien Armor\n\n",
      "The following tradeskill amounts are required to make <highlight>QL {ql}<end>\n",
      "strong/arithmetic/enduring/spiritual/supple/observant armor:\n\n",
      "Computer Literacy - <highlight>{cl_req}<end> (<highlight>4.5 * QL<end>)\n",
      "Chemistry - <highlight>{chem_req}<end> (<highlight>{chem_info}<end>) {chem_extra_info}\n",
      "Nano Programming - <highlight>{nano_prog_req}<end> (<highlight>6 * QL<end>)\n",
      "Pharma Tech - <highlight>{pt_req}<end> (<highlight>6 * QL<end>)\n",
      "Psychology - <highlight>{psyco_req}<end> (<highlight>6 * QL<end>)\n\n",
      "Note: Tradeskill requirements are based off the lowest QL items needed throughout the entire process.",

      "\n\nFor Supple, Arithmetic, or Enduring:\n\n",
      "When completed, the armor piece can have as low as <highlight>QL {min_ql}<end> combined into it, depending on available tradeskill options.\n\n",
      "Does not change QL's, therefore takes <highlight>{psyco_req} Psychology<end> for available combinations.<end>\n\n",
      "For Spiritual, Strong, or Observant:\n\n",
      "When completed, the armor piece can combine up to <highlight>QL {max_ql}<end>, depending on available tradeskill options.\n\n",
      "Changes QL depending on targets QL. ",
      "The max combination is: (<highlight>QL {max_ql}<end>) (<highlight>{max_psyco} Psychology<end> required for this combination)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)<end>"
    ],
    "de_DE": [
      "{item}\n\n",
      "Es wird <highlight>{ee_cl_req} EE & CL<end> (<highlight>4.5 * QL<end>)benötigt, um Bio-Material zu analysieren.\n\n",

      "Es wird genutzt, um Alien Rüstung herzustellen.\n\n",
      "Um eine strong/arithmetic/enduring/spiritual/supple/observant Rüstung\n",
      "mit dem QL<highlight>QL {ql}<end> herzustellen, werden folgende Tradeskills benötigt:\n\n",
      "Computer Literacy - <highlight>{cl_req}<end> (<highlight>4.5 * QL<end>)\n",
      "Chemistry - <highlight>{chem_req}<end> (<highlight>{chem_info}<end>) {chem_extra_info}\n",
      "Nano Programming - <highlight>{nano_prog_req}<end> (<highlight>6 * QL<end>)\n",
      "Pharma Tech - <highlight>{pt_req}<end> (<highlight>6 * QL<end>)\n",
      "Psychology - <highlight>{psyco_req}<end> (<highlight>6 * QL<end>)\n\n",
      "Hinweis: die Tradeskill anforderungen basieren auf dem Item mit dem niedrigstem QL, welches im gesamten Tradeskill Prozess evrwendet wird.",

      "\n\nFür eine Supple, Arithmetic, oder Enduring Rüstung:\n\n",
      "Am Ende kann das Rüstungsteil mit Teilen ab dem QL <hightlight>QL {min_ql}<end> kombiniert werden. Dies ist abhängig von den verfügbaren Tradeskill optionen.\n\n",
      "Das QL wird hierbei nicht verändert, wodurch <highlight>{psyco_req} Psychology<end> benötigt wird.\n\n",
      "Für Spiritual, Strong, oder Observant:\n\n",
      "Am Ende lässt sich das Rüstungsteil mit anderen Typen bis  <highlight>QL {max_ql}<end> kombinieren. Dies ist abhängig von den verfügbaren Tradeskill optionen.\n\n",
      "Das QL verändert sich dem dem Ziel-QL entsprechend. ",
      "Die Maximale Kombination ist: (<highlight>QL {max_ql}<end>) ( Es wird <highlight>{max_psyco} Psychology<end> benötigt)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)<end>"
    ]
  },
  "alien_armor_bio_extra_info_mutated": {
    "en_US": "more tradeskill requirements then pristine",
    "de_DE": "höhere Tradeskill Anforderungen als pristine"
  },
  "alien_armor_bio_extra_info_pristine": {
    "en_US": "less tradeskill requirements then mutated",
    "de_DE": "niedrigere Tradeskill Anforderungen als Mutated"
  },
  "alien_weapon_bio": {
    "en_US": [
      "{item_display}\n\n",
      "It will take <highlight>{ee_cl_req}<end> EE & CL (<highlight>4.5 * QL<end>) to analyze the Bio-Material.\n\n",
      "<highlight>Adds {specials} to:<end>\n",
      "{display_blob}",
      "{weapon_info}",
      "\n\n<yellow>Tradeskilling info added by Mdkdoc420<end>"

    ],
    "de_DE": [
      "{item_display}\n\n",
      "Es wird <highlight>{ee_cl_req}<end> EE & CL (<highlight>4.5 * QL<end>) benötigt um Bio-Material zu analysieren.\n\n",
      "<highlight>Fügt {specials} zu folgenden Waffen hinzu:<end>\n",
      "{display_blob}",
      "{weapon_info}",
      "\n\n<yellow>Tradeskilling info added by Mdkdoc420<end>"

    ]
  },
  "serum_bio": {
    "en_US": [
      "{item_display}\n\n",
      "It will take <highlight>{ee_cl_req} EE & CL<end> (<highlight>4.5 * QL<end>) to analyze the Bio-Material.\n\n",
      "Used to build city buildings\n\n",
      "The following are the required skills throughout the process of making a building:\n\n",
      "Quantum FT - <highlight>400<end> (<highlight>Static<end>)\n",
      "Pharma Tech - <highlight>{pt_req}<end> (<highlight>3.5 * QL<end>) 400 is minimum requirement\n",
      "Chemistry - <highlight>{chem_me_req}<end> (<highlight>4 * QL<end>) 400 is minimum requirement\n",
      "Mechanical Engineering - <highlight>{chem_me_req}<end> (<highlight>4 * QL<end>)\n",
      "Electrical Engineering - <highlight>{ee_cl_req}<end> (<highlight>4.5 * QL<end>)\n",
      "Comp Liter - <highlight>{cl_req}<end> (<highlight>5 * QL<end>)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)<end>"
    ],
    "de_DE": [
      "{item_display}\n\n",
      "Es wird <highlight>{ee_cl_req}<end> EE & CL (<highlight>4.5 * QL<end>) benötigt um Bio-Material zu analysieren.\n\n",
      "Wird verwendet um City Gebäude herzustellen\n\n",
      "Die folgenden Skills werden im Tradeskill Prozess benötigt:\n\n",
      "Quantum FT - <highlight>400<end> (<highlight>Static<end>)\n",
      "Pharma Tech - <highlight>{pt_req}<end> (<highlight>3.5 * QL<end>) 400 ist das minimum\n",
      "Chemistry - <highlight>{chem_me_req}<end> (<highlight>4 * QL<end>) 400 ist das minimum\n",
      "Mechanical Engineering - <highlight>{chem_me_req}<end> (<highlight>4 * QL<end>)\n",
      "Electrical Engineering - <highlight>{ee_cl_req}<end> (<highlight>4.5 * QL<end>)\n",
      "Comp Liter - <highlight>{cl_req}<end> (<highlight>5 * QL<end>)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)<end>"
    ]
  },
  "weapon_info": {
    "en_US": [
      "\n\n<highlight>QL {ql}<end> is the highest weapon this type will combine into.",
      "{bump}",
      "\n\nIt will take <highlight>{me_ws_req}<end> ME & WS (<highlight>6 * QL<end>) to combine with a <highlight>QL {ql}<end> Kyr'ozch Weapon."
    ],
    "de_DE": [
      "\n\nDie Waffe darf maximal das <highlight>QL {ql}<end> haben, um mit diesem Bio-Material kombiniert zu werden.",
      "{bump}",
      "\n\nEs werden <highlight>{me_ws_req}<end> ME & WS (<highlight>6 * QL<end>) zum kombinieren mit einer <highlight>QL {ql}<end> Kyr'ozch Weapon benötigt."
    ]
  },
  "weapon_bump": {
    "en_US": "\nNote: <highlight>The weapon can bump several QL's.<end>",
    "de_DE": "\nHinweis: <highlight>Die Waffe kann um einige QL gelevelt werden.<end>"
  },
  "ai_gen_list_title": {
    "en_US": "Alien Generals",
    "de_DE": "Alien General"

  },
  "ai_gen_list": {
    "en_US": [
      "&nbsp;- <a href='chatcmd:///tell <myname> aigen Ankari'>Ankari</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Ilari'>Ilari</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Rimah'>Rimah</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Jaax'>Jaax</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Xoch'>Xoch</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Cha'>Cha</a>\n"
    ],
    "de_DE": [
      "&nbsp;- <a href='chatcmd:///tell <myname> aigen Ankari'>Ankari</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Ilari'>Ilari</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Rimah'>Rimah</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Jaax'>Jaax</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Xoch'>Xoch</a>\n",
      " - <a href='chatcmd:///tell <myname> aigen Cha'>Cha</a>\n"
    ]
  },
  "ai_gen_": {
    "en_US": []
  }
}
