{
  "ai_armor": {
    "en_US": [
      "<highlight>Normal Armor:</highlight>\n",
      " - {strong}\n",
      " - {supple}\n",
      " - {enduring}\n",
      " - {observant}\n",
      " - {arithmetic}\n",
      " - {spiritual}\n\n",
      "<highlight>Combined Armor:</highlight>\n",
      " - {cc}\n",
      " - {cm}\n",
      " - {co}\n",
      " - {cp}\n",
      " - {css}\n"
    ],
    "de_DE": [
      "<highlight>Normale Rüstung:</highlight>\n",
      " - {strong}\n",
      " - {supple}\n",
      " - {enduring}\n",
      " - {observant}\n",
      " - {arithmetic}\n",
      " - {spiritual}\n\n",
      "<highlight>Kombinierte Rüstung:</highlight>\n",
      " - {cc}\n",
      " - {cm}\n",
      " - {co}\n",
      " - {cp}\n",
      " - {css}\n"
    ]
  },
  "ai_armor_title":{
    "en_US": "Alien Armor",
    "de_DE": "Alien Rüstung"
  },
  "ai_armor_ts_title": {
    "en_US": "Building process for QL {ql} {type}",
    "de_DE": "Rezept für die {type} - QL {ql}"
  },
  "ai_armor_ts": {
    "en_US": [
      "Note: All tradeskill processes are based on the lowest QL items usable.\n\n",
      "<header2>You need the following items to build {armor_type} Armor:</header2>\n",
      "- {text_viralbots} (QL{vb_ql})\n",
      "- {text_step1_tool}\n",
      "- {text_solid_clump} (QL{ql})\n",
      "- {text_vb_bot} (QL{vb_ql})\n\n",

      "<header2>Step 1</header2>\n",
      "<tab>{icon_viralbots}<tab>+<tab>{icon_step1_tool}<tab>=<tab>{icon_memory_wiped_viralbots}\n\n",
      "<tab>(QL{vb_ql})<tab><tab><tab><tab><tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_viralbots} (QL{vb_ql}) (<highlight>Drops from Alien City Generals</highlight>)\n",
      " + <tab>{text_step1_tool}\n",
      " = <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {step1_CL} Computer Literacy\n",
      "- {step1_NP} Nano Programming\n\n",

      "<header2>Step 2</header2>\n",
      "<tab>{icon_NPI}<tab>+<tab>{icon_memory_wiped_viralbots}<tab>=<tab>{icon_formatted_viralbots}\n\n",
      "<tab><tab><tab><tab> <tab>(QL{vb_ql})<tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_NPI} (<highlight>Can be bought in General Shops</highlight>)\n",
      " + <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      " = <tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {step2_CL} Computer Literacy\n",
      "- {step2_NP} Nano Programming\n\n",

      "<header2>Step 3</header2>\n",
      "<tab>{icon_structural_analyser}<tab>+<tab>{icon_solid_clump}<tab>=<tab>{icon_mutated_material}<tab><highlight>OR</highlight><tab>{icon_pristine_material} \n\n",
      "<tab><tab> <tab><tab><tab>(QL{ql})<tab><tab><tab>(QL{ql})<tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_structural_analyser}\n",
      " + <tab>{text_solid_clump} (QL{ql})\n",
      " = <tab>{text_mutated_material} (QL{ql})<tab><highlight>\n<tab><tab>OR</highlight><tab>{text_pristine_material} (QL{ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {step3_chem} Chemistry (Both require the same amount)\n\n",

      "<header2>Step 4</header2>\n",
      "<tab>{icon_mutated_material}<tab><highlight>OR</highlight><tab>{icon_pristine_material}<tab>+<tab>{icon_bazzit_generic_nano_solvent}<tab>=<tab>{icon_dna_soup} \n\n",
      "<tab>(QL{ql})<tab>  <tab> (QL{ql})<tab> <tab><tab><tab><tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_mutated_material} (QL{ql})<tab><br><tab><tab><highlight>OR</highlight><tab>{text_pristine_material} (QL{ql})\n",
      " + <tab>{text_bazzit_generic_nano_solvent}\n",
      " = <tab>{text_dna_soup} (QL{ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {chem_prist} Chemistry(for Pristine)\n",
      "- {chem_mutat} Chemistry(for Mutated)\n\n",

      "<header2>Step 5</header2>\n",
      "<tab>{icon_dna_soup}<tab>+<tab>{icon_human_dna}<tab>=<tab>{icon_dna_cocktail} \n\n",
      "<tab>(QL{ql})<tab> <tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_dna_soup} (QL{ql})\n",
      " + <tab>{text_human_dna}\n",
      " = <tab>{text_dna_cocktail} (QL{ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Step 6</header2>\n",
      "<tab>{icon_formatted_viralbots}<tab>+<tab>{icon_dna_cocktail}<tab>=<tab>{icon_formatted_viralbot_solution} \n\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      " + <tab>{text_dna_cocktail} (QL{ql})\n",
      " = <tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Step 7</header2>\n",
      "<tab>{icon_formatted_viralbot_solution}<tab>+<tab>{icon_basic_fashion_vest}<tab>=<tab>{icon_formatted_viralbot_vest} \n\n",
      "<tab>(QL{ql})<tab><tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      " + <tab>{text_basic_fashion_vest}\n",
      " = <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Step 8</header2>\n",
      "<tab>{icon_vb_bot}<tab>+<tab>{icon_formatted_viralbot_vest}<tab>=<tab>{icon_armor}\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_vb_bot} (QL{vb_ql}) (<highlight>Rare Drop off Alien City Generals</highlight>)\n",
      " + <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      " = <tab>{text_armor} (QL{ql})\n",
      "<highlight>Required Skills:</highlight>\n",
      "- {psycho} Psychology"
    ],
    "de_DE": [
      "Hinweis: Bei Allen Tradeskill Vorgängen ist jeweils das minimale nötige QL angegeben, welches für das gewünschte Ergebnis notwendig ist.\n\n",
      "<header2>Zum bauen der {armor_type} Armor werden folgende Items benötigt:</header2>\n",
      "- {text_viralbots} (QL{vb_ql})\n",
      "- {text_step1_tool}\n",
      "- {text_solid_clump} (QL{ql})\n",
      "- {text_vb_bot} (QL{vb_ql})\n\n",

      "<header2>Teil 1</header2>\n",
      "<tab>{icon_viralbots}<tab>+<tab>{icon_step1_tool}<tab>=<tab>{icon_memory_wiped_viralbots}\n\n",
      "<tab>(QL{vb_ql})<tab><tab><tab><tab><tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_viralbots} (QL{vb_ql}) (<highlight>Droppt von Alien City Generals</highlight>)\n",
      " + <tab>{text_step1_tool}\n",
      " = <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {step1_CL} Computer Literacy\n",
      "- {step1_NP} Nano Programming\n\n",

      "<header2>Teil 2</header2>\n",
      "<tab>{icon_NPI}<tab>+<tab>{icon_memory_wiped_viralbots}<tab>=<tab>{icon_formatted_viralbots}\n\n",
      "<tab><tab><tab><tab> <tab>(QL{vb_ql})<tab><tab><tab>(QL{vb_ql})\n\n",
      "<tab><tab>{text_NPI} (<highlight>Kann in General Shops gekauft werden</highlight>)\n",
      " + <tab>{text_memory_wiped_viralbots} (QL{vb_ql})\n",
      " = <tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {step2_CL} Computer Literacy\n",
      "- {step2_NP} Nano Programming\n\n",

      "<header2>Teil 3</header2>\n",
      "<tab>{icon_structural_analyser}<tab>+<tab>{icon_solid_clump}<tab>=<tab>{icon_mutated_material}<tab><highlight>ODER</highlight><tab>{icon_pristine_material} \n\n",
      "<tab><tab> <tab><tab><tab>(QL{ql})<tab><tab><tab>(QL{ql})<tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_structural_analyser}\n",
      " + <tab>{text_solid_clump} (QL{ql})\n",
      " = <tab>{text_mutated_material} (QL{ql})<tab>\n<tab><tab><highlight>ODER</highlight><tab>{text_pristine_material} (QL{ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {step3_chem} Chemistry (Pristine/Mutated haben die gleichen Skill Anforderungen)\n\n",

      "<header2>Teil 4</header2>\n",
      "<tab>{icon_mutated_material}<tab><highlight>ODER</highlight><tab>{icon_pristine_material}<tab>+<tab>{icon_bazzit_generic_nano_solvent}<tab>=<tab>{icon_dna_soup} \n\n",
      "<tab>(QL{ql})<tab><tab><tab> (QL{ql})<tab> <tab><tab><tab><tab><tab>  (QL{ql})\n\n",
      "<tab><tab>{text_mutated_material} (QL{ql})<tab><br><tab><tab><highlight>ODER</highlight><tab>{text_pristine_material} (QL{ql})\n",
      " + <tab>{text_bazzit_generic_nano_solvent}\n",
      " = <tab>{text_dna_soup} (QL{ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {chem_prist} Chemistry(mit Pristine)\n",
      "- {chem_mutat} Chemistry(mit Mutated)\n\n",

      "<header2>Teil 5</header2>\n",
      "<tab>{icon_dna_soup}<tab>+<tab>{icon_human_dna}<tab>=<tab>{icon_dna_cocktail} \n\n",
      "<tab>(QL{ql})<tab> <tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_dna_soup} (QL{ql})\n",
      " + <tab>{text_human_dna}\n",
      " = <tab>{text_dna_cocktail} (QL{ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Teil 6</header2>\n",
      "<tab>{icon_formatted_viralbots}<tab>+<tab>{icon_dna_cocktail}<tab>=<tab>{icon_formatted_viralbot_solution} \n\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbots} (QL{vb_ql})\n",
      " + <tab>{text_dna_cocktail} (QL{ql})\n",
      " = <tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Teil 7</header2>\n",
      "<tab>{icon_formatted_viralbot_solution}<tab>+<tab>{icon_basic_fashion_vest}<tab>=<tab>{icon_formatted_viralbot_vest} \n\n",
      "<tab>(QL{ql})<tab><tab><tab><tab><tab><tab><tab>(QL{ql})\n\n",
      "<tab><tab>{text_formatted_viralbot_solution} (QL{ql})\n",
      " + <tab>{text_basic_fashion_vest}\n",
      " = <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {pharma} Pharma Tech\n\n",

      "<header2>Teil 8</header2>\n",
      "<tab>{icon_vb_bot}<tab>+<tab>{icon_formatted_viralbot_vest}<tab>=<tab>{icon_armor}\n",
      "<tab>(QL{vb_ql})<tab> <tab>(QL{ql})<tab> <tab>(QL{ql})\n\n",
      "<tab><tab>{text_vb_bot} (QL{vb_ql}) (<highlight>Seltener drop von Alien City Generals</highlight>)\n",
      " + <tab>{text_formatted_viralbot_vest} (QL{ql})\n",
      " = <tab>{text_armor} (QL{ql})\n",
      "<highlight>Notwendige Skills:</highlight>\n",
      "- {psycho} Psychology"
    ]
  },

  "ai_armor_combined": {
    "en_US": [
      "<header2>Tradeskill Process</header2>\n\n",
      "<tab>{icon_source}<tab>+<tab>{icon_target}<tab>=<tab>{icon_result}\n",
      "<tab>(QL{s_ql})<tab> <tab>(QL{t_ql})<tab> <tab>(QL{t_ql})\n\n",
      "<tab><tab>{text_source} (QL{s_ql}) - ({ts_process_source})\n",
      " + <tab>{text_target} (QL{t_ql}) - ({ts_process_target})\n",
      " = <tab>{text_result} (QL{t_ql})\n"],
    "de_DE": [
      "<header2>Bauanleitung</header2>\n\n",
      "<tab>{icon_source}<tab>+<tab>{icon_target}<tab>=<tab>{icon_result}\n",
      "<tab>(QL{s_ql})<tab> <tab>(QL{t_ql})<tab> <tab>(QL{t_ql})\n\n",
      "<tab><tab>{text_source} (QL{s_ql}) - ({ts_process_source})\n",
      " + <tab>{text_target} (QL{t_ql}) - ({ts_process_target})\n",
      " = <tab>{text_result} (QL{t_ql})\n"]
  },
  "ai_armor_ts_process": {
    "en_US": "Tradeskill process for this item",
    "de_DE": "Bauanleitung für dieses Item"
  },
  "ai_armor_combined_unknown": {
    "en_US": "Unknown armor type <highlight>{type}</highlight>",
    "de_DE": "Unbekannter Rüstungs Typ: <highlight>{type}</highlight>"
  },

  "bioinfo_list": {
    "en_US": [
      "\n<header2>OFAB Armor Types</header2>\n",
      "{ofab_armor}",
      "\n<header2>OFAB Weapon Types</header2>\n",
      "{ofab_weap}",
      "\n<header2>AI Armor Types</header2>\n",
      "{ai_armor}",
      "\n<header2>AI Weapon Typen</header2>\n",
      "{ai_weap}",
      "\n<header2>Serum Typen</header2>\n",
      "{serum}"],
    "de_DE": [
      "\n<header2>OFAB Rüstung - Typen</header2>\n",
      "{ofab_armor}",
      "\n<header2>OFAB Waffen - Typen</header2>\n",
      "{ofab_weap}",
      "\n<header2>Alien Rüstung - Typen</header2>\n",
      "{ai_armor}",
      "\n<header2>Alien Waffen - Typen</header2>\n",
      "{ai_weap}",
      "\n<header2>Serum - Typen</header2>\n",
      "{serum}"]
  },
  "bioinfo_list_title": {
    "en_US": "Bio-Material Types",
    "de_DE": "Bio-Material Typen"
  },
  "bioinfo_unknown_type": {
    "en_US": "Unknown bio-material type <highlight>{type}</highlight>.",
    "de_DE": "Unbekannter Bio-Material Typ: <highlight>{type}</highlight>."
  },
  "bioinfo_type_title": {
    "en_US": "{name} (QL {ql})",
    "de_DE": "{name} (QL {ql})"
  },
  "ofab_armor_bio": {
    "en_US": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrades Ofab Armor for:</highlight>\n",
      "{upgrades}"
    ],
    "de_DE": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrade für folgende Ofab Rüstungen:</highlight>\n",
      "{upgrades}"
    ]
  },
  "ofab_weapon_bio": {
    "en_US": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrades Ofab Weapons for:</highlight>\n",
      "{upgrades}"
    ],
    "de_DE": [
      "Kyr'Ozch Bio-Material - Type {type}",
      "{icon}\n{text}\n\n",
      "<highlight>Upgrade für folgende Ofab Waffen:</highlight>\n",
      "{upgrades}"
    ]
  },
  "alien_armor_bio": {
    "en_US": [
      "{item}\n\n",
      "It will take <highlight>{ee_cl_req} EE & CL</highlight> (<highlight>4.5 * QL</highlight>) to analyze the Bio-Material.\n\n",

      "Used to build Alien Armor\n\n",
      "The following tradeskill amounts are required to make <highlight>QL {ql}</highlight>\n",
      "strong/arithmetic/enduring/spiritual/supple/observant armor:\n\n",
      "Computer Literacy - <highlight>{cl_req}</highlight> (<highlight>4.5 * QL</highlight>)\n",
      "Chemistry - <highlight>{chem_req}</highlight> (<highlight>{chem_info}</highlight>) {chem_extra_info}\n",
      "Nano Programming - <highlight>{nano_prog_req}</highlight> (<highlight>6 * QL</highlight>)\n",
      "Pharma Tech - <highlight>{pt_req}</highlight> (<highlight>6 * QL</highlight>)\n",
      "Psychology - <highlight>{psyco_req}</highlight> (<highlight>6 * QL</highlight>)\n\n",
      "Note: Tradeskill requirements are based off the lowest QL items needed throughout the entire process.",

      "\n\nFor Supple, Arithmetic, or Enduring:\n\n",
      "When completed, the armor piece can have as low as <highlight>QL {min_ql}</highlight> combined into it, depending on available tradeskill options.\n\n",
      "Does not change QL's, therefore takes <highlight>{psyco_req} Psychology</highlight> for available combinations.\n\n",
      "For Spiritual, Strong, or Observant:\n\n",
      "When completed, the armor piece can combine up to <highlight>QL {max_ql}</highlight>, depending on available tradeskill options.\n\n",
      "Changes QL depending on targets QL. ",
      "The max combination is: (<highlight>QL {max_ql}</highlight>) (<highlight>{max_psyco} Psychology</highlight> required for this combination)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)</yellow>"
    ],
    "de_DE": [
      "{item}\n\n",
      "Es wird <highlight>{ee_cl_req} EE & CL</highlight> (<highlight>4.5 * QL</highlight>)benötigt, um Bio-Material zu analysieren.\n\n",

      "Es wird genutzt, um Alien Rüstung herzustellen.\n\n",
      "Um eine strong/arithmetic/enduring/spiritual/supple/observant Rüstung\n",
      "mit dem QL<highlight>QL {ql}</highlight> herzustellen, werden folgende Tradeskills benötigt:\n\n",
      "Computer Literacy - <highlight>{cl_req}</highlight> (<highlight>4.5 * QL</highlight>)\n",
      "Chemistry - <highlight>{chem_req}</highlight> (<highlight>{chem_info}</highlight>) {chem_extra_info}\n",
      "Nano Programming - <highlight>{nano_prog_req}</highlight> (<highlight>6 * QL</highlight>)\n",
      "Pharma Tech - <highlight>{pt_req}</highlight> (<highlight>6 * QL</highlight>)\n",
      "Psychology - <highlight>{psyco_req}</highlight> (<highlight>6 * QL</highlight>)\n\n",
      "Hinweis: die Tradeskill anforderungen basieren auf dem Item mit dem niedrigstem QL, welches im gesamten Tradeskill Prozess evrwendet wird.",

      "\n\nFür eine Supple, Arithmetic, oder Enduring Rüstung:\n\n",
      "Am Ende kann das Rüstungsteil mit Teilen ab dem QL <highlight>QL {min_ql}</highlight> kombiniert werden. Dies ist abhängig von den verfügbaren Tradeskill optionen.\n\n",
      "Das QL wird hierbei nicht verändert, wodurch <highlight>{psyco_req} Psychology</highlight> benötigt wird.\n\n",
      "Für Spiritual, Strong, oder Observant:\n\n",
      "Am Ende lässt sich das Rüstungsteil mit anderen Typen bis  <highlight>QL {max_ql}</highlight> kombinieren. Dies ist abhängig von den verfügbaren Tradeskill optionen.\n\n",
      "Das QL verändert sich dem dem Ziel-QL entsprechend. ",
      "Die Maximale Kombination ist: (<highlight>QL {max_ql}</highlight>) ( Es wird <highlight>{max_psyco} Psychology</highlight> benötigt)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)</yellow>"
    ]
  },
  "alien_armor_bio_extra_info_mutated": {
    "en_US": "more tradeskill requirements then pristine",
    "de_DE": "höhere Tradeskill Anforderungen als pristine"
  },
  "alien_armor_bio_extra_info_pristine": {
    "en_US": "less tradeskill requirements then mutated",
    "de_DE": "niedrigere Tradeskill Anforderungen als Mutated"
  },
  "alien_weapon_bio": {
    "en_US": [
      "{item_display}\n\n",
      "It will take <highlight>{ee_cl_req}</highlight> EE & CL (<highlight>4.5 * QL</highlight>) to analyze the Bio-Material.\n\n",
      "<highlight>Adds {specials} to:</highlight>\n",
      "{display_blob}",
      "{weapon_info}",
      "\n\n<yellow>Tradeskilling info added by Mdkdoc420</yellow>"

    ],
    "de_DE": [
      "{item_display}\n\n",
      "Es wird <highlight>{ee_cl_req}</highlight> EE & CL (<highlight>4.5 * QL</highlight>) benötigt um Bio-Material zu analysieren.\n\n",
      "<highlight>Fügt {specials} zu folgenden Waffen hinzu:</highlight>\n",
      "{display_blob}",
      "{weapon_info}",
      "\n\n<yellow>Tradeskilling info added by Mdkdoc420</yellow>"

    ]
  },
  "serum_bio": {
    "en_US": [
      "{item_display}\n\n",
      "It will take <highlight>{ee_cl_req} EE & CL</highlight> (<highlight>4.5 * QL</highlight>) to analyze the Bio-Material.\n\n",
      "Used to build city buildings\n\n",
      "The following are the required skills throughout the process of making a building:\n\n",
      "Quantum FT - <highlight>400</highlight> (<highlight>Static</highlight>)\n",
      "Pharma Tech - <highlight>{pt_req}</highlight> (<highlight>3.5 * QL</highlight>) 400 is minimum requirement\n",
      "Chemistry - <highlight>{chem_me_req}</highlight> (<highlight>4 * QL</highlight>) 400 is minimum requirement\n",
      "Mechanical Engineering - <highlight>{chem_me_req}</highlight> (<highlight>4 * QL</highlight>)\n",
      "Electrical Engineering - <highlight>{ee_cl_req}</highlight> (<highlight>4.5 * QL</highlight>)\n",
      "Comp Liter - <highlight>{cl_req}</highlight> (<highlight>5 * QL</highlight>)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)</yellow>"
    ],
    "de_DE": [
      "{item_display}\n\n",
      "Es wird <highlight>{ee_cl_req}</highlight> EE & CL (<highlight>4.5 * QL</highlight>) benötigt um Bio-Material zu analysieren.\n\n",
      "Wird verwendet um City Gebäude herzustellen\n\n",
      "Die folgenden Skills werden im Tradeskill Prozess benötigt:\n\n",
      "Quantum FT - <highlight>400</highlight> (<highlight>Static</highlight>)\n",
      "Pharma Tech - <highlight>{pt_req}</highlight> (<highlight>3.5 * QL</highlight>) 400 ist das minimum\n",
      "Chemistry - <highlight>{chem_me_req}</highlight> (<highlight>4 * QL</highlight>) 400 ist das minimum\n",
      "Mechanical Engineering - <highlight>{chem_me_req}</highlight> (<highlight>4 * QL</highlight>)\n",
      "Electrical Engineering - <highlight>{ee_cl_req}</highlight> (<highlight>4.5 * QL</highlight>)\n",
      "Comp Liter - <highlight>{cl_req}</highlight> (<highlight>5 * QL</highlight>)",

      "\n\n<yellow>Tradeskilling info added by Mdkdoc420 (RK2)</yellow>"
    ]
  },
  "weapon_info": {
    "en_US": [
      "\n\n<highlight>QL {ql}</highlight> is the highest weapon this type will combine into.",
      "{bump}",
      "\n\nIt will take <highlight>{me_ws_req}</highlight> ME & WS (<highlight>6 * QL</highlight>) to combine with a <highlight>QL {ql}</highlight> Kyr'ozch Weapon."
    ],
    "de_DE": [
      "\n\nDie Waffe darf maximal das <highlight>QL {ql}</highlight> haben, um mit diesem Bio-Material kombiniert zu werden.",
      "{bump}",
      "\n\nEs werden <highlight>{me_ws_req}</highlight> ME & WS (<highlight>6 * QL</highlight>) zum kombinieren mit einer <highlight>QL {ql}</highlight> Kyr'ozch Weapon benötigt."
    ]
  },
  "weapon_bump": {
    "en_US": "\nNote: <highlight>The weapon can bump several QL's.</highlight>",
    "de_DE": "\nHinweis: <highlight>Die Waffe kann um einige QL gelevelt werden.</highlight>"
  },
  "ai_gen_list_title": {
    "en_US": "Alien Generals",
    "de_DE": "Alien General"

  }
}
