DROP TABLE IF EXISTS ofab_armor;
CREATE TABLE ofab_armor (profession VARCHAR(30) NOT NULL, name VARCHAR(150) NOT NULL, slot VARCHAR(30) NOT NULL, lowid INT NOT NULL, highid INT NOT NULL, upgrade INT NOT NULL);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Ofab Adventurer Body Armor', 'body', 264202, 264203, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Ofab Adventurer Boots', 'boots', 264200, 264201, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Ofab Adventurer Pants', 'pants', 264198, 264199, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Ofab Adventurer Sleeves', 'sleeves', 264204, 264205, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Ofab Adventurer Gloves', 'gloves', 264206, 264207, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Ofab Adventurer Helmet', 'helmet', 264208, 264209, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Jayde''s Odyssey ring', 'ring', 267560, 267561, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Ofab Agent Body Armor', 'body', 264305, 264306, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Ofab Agent Boots', 'boots', 264311, 264312, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Ofab Agent Pants', 'pants', 264317, 264318, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Ofab Agent Sleeves', 'sleeves', 264299, 264300, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Ofab Agent Gloves', 'gloves', 264293, 264294, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Ofab Agent Helmet', 'helmet', 264287, 264288, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Agents'' Ring of Aim', 'ring', 267582, 267583, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Ofab Bureaucrat Vest', 'body', 264521, 264522, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Ofab Bureaucrat Boots', 'boots', 264527, 264528, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Ofab Bureaucrat Pants', 'pants', 264533, 264534, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Ofab Bureaucrat Sleeves', 'sleeves', 264515, 264516, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Ofab Bureaucrat Gloves', 'gloves', 264509, 264510, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Ofab Bureaucrat Headgear', 'helmet', 264503, 264504, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Bureaucrats'' Ring of Order', 'ring', 268307, 268308, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Ofab Doctor Body', 'body', 264668, 264669, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Ofab Doctor Boots', 'boots', 264674, 264675, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Ofab Doctor Pants', 'pants', 264680, 264681, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Ofab Doctor Sleeves', 'sleeves', 264662, 264663, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Ofab Doctor Gloves', 'gloves', 264656, 264657, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Ofab Doctor Helmet', 'helmet', 264650, 264651, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Sheffy''s Micro Coil', 'ring', 267562, 267563, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Ofab Enforcer Breastplate', 'body', 264223, 264224, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Ofab Enforcer Boots', 'boots', 264217, 264218, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Ofab Enforcer Pants', 'pants', 264211, 264212, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Ofab Enforcer Sleeves', 'sleeves', 264229, 264230, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Ofab Enforcer Gauntlets', 'gloves', 264235, 264236, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Ofab Enforcer Helmet', 'helmet', 264241, 264242, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Band of Bravery', 'ring', 267564, 267565, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Ofab Engineer Body', 'body', 264596, 264597, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Ofab Engineer Boots', 'boots', 264602, 264603, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Ofab Engineer Pants', 'pants', 264608, 264609, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Ofab Engineer Sleeves', 'sleeves', 264590, 264591, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Ofab Engineer Gloves', 'gloves', 264581, 264582, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Ofab Engineer Helmet', 'helmet', 264575, 264576, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Rusty''s Ring of Bolts', 'ring', 267566, 267567, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Ofab Fixer Body Armor', 'body', 264485, 264486, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Ofab Fixer Boots', 'boots', 264491, 264492, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Ofab Fixer Pants', 'pants', 264497, 264498, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Ofab Fixer Sleeves', 'sleeves', 264479, 264480, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Ofab Fixer Gloves', 'gloves', 264473, 264474, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Ofab Fixer Helmet', 'helmet', 264467, 264468, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Fixers'' Ring of Breaking', 'ring', 267568, 267569, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Ofab Keeper Body Armor', 'body', 264632, 264633, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Ofab Keeper Boots', 'boots', 264638, 264639, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Ofab Keeper Pants', 'pants', 264644, 264645, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Ofab Keeper Sleeves', 'sleeves', 264626, 264627, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Ofab Keeper Gloves', 'gloves', 264620, 264621, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Ofab Keeper Helmet', 'helmet', 264614, 264615, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Knights'' Ring of Honour', 'ring', 267570, 267571, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Ofab Martial Artist Body Armor', 'body', 264341, 264342, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Ofab Martial Artist Boots', 'boots', 264347, 264348, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Ofab Martial Artist Pants', 'pants', 264353, 264354, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Ofab Martial Artist Sleeves', 'sleeves', 264335, 264336, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Ofab Martial Artist Gloves', 'gloves', 264329, 264330, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Ofab Martial Artist Helmet', 'helmet', 264323, 264324, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Engelen''s Ring of Damage', 'ring', 267572, 267573, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Ofab Metaphysicist Body Armor', 'body', 264377, 264378, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Ofab Metaphysicist Boots', 'boots', 264383, 264384, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Ofab Metaphysicist Pants', 'pants', 264389, 264390, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Ofab Metaphysicist Sleeves', 'sleeves', 264371, 264372, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Ofab Metaphysicist Gloves', 'gloves', 264365, 264366, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Ofab Metaphysicist Headgear', 'helmet', 264359, 264360, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'XtremTech''s Ring of Casting', 'ring', 268305, 268306, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Ofab Nano Technician Body Armor', 'body', 264413, 264414, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Ofab Nano Technician Boots', 'boots', 264419, 264420, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Ofab Nano Technician Pants', 'pants', 264425, 264426, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Ofab Nano Technician Sleeves', 'sleeves', 264407, 264408, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Ofab Nano Technician Gloves', 'gloves', 264401, 264402, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Ofab Nano Technician Helmet', 'helmet', 264395, 264396, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'NTs'' Ring of NanoTechnic', 'ring', 267574, 267575, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Ofab Soldier Body Armor', 'body', 264449, 264450, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Ofab Soldier Boots', 'boots', 264455, 264456, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Ofab Soldier Pants', 'pants', 264461, 264462, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Ofab Soldier Sleeves', 'sleeves', 264443, 264444, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Ofab Soldier Gloves', 'gloves', 264437, 264438, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Ofab Soldier Helmet', 'helmet', 264431, 264432, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Soldiers'' Ring of Focus', 'ring', 267578, 267579, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Ofab Trader Body Armor', 'body', 264269, 264270, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Ofab Trader Boots', 'boots', 264281, 264282, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Ofab Trader Pants', 'pants', 264275, 264276, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Ofab Trader Sleeves', 'sleeves', 264263, 264264, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Ofab Trader Gloves', 'gloves', 264257, 264258, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Ofab Trader Helmet', 'helmet', 264251, 264252, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Baffle''s Ring of Fling', 'ring', 267580, 267581, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Ofab Shade Body Armor', 'body', 264557, 264558, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Ofab Shade Boots', 'boots', 264563, 264564, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Ofab Shade Pants', 'pants', 264569, 264570, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Ofab Shade Sleeves', 'sleeves', 264551, 264552, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Ofab Shade Gloves', 'gloves', 264545, 264546, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Ofab Shade Headgear', 'helmet', 264539, 264540, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Shades'' Ring of Shadows', 'ring', 267576, 267577, 0);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Improved Ofab Adventurer Body Armor', 'body', 264190, 264191, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Improved Ofab Adventurer Boots', 'boots', 264188, 264189, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Improved Ofab Adventurer Pants', 'pants', 264186, 264187, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Improved Ofab Adventurer Sleeves', 'sleeves', 264192, 264193, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Improved Ofab Adventurer Gloves', 'gloves', 264194, 264195, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Improved Ofab Adventurer Helmet', 'helmet', 264196, 264197, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Improved Ofab Agent Body Armor', 'body', 264303, 264304, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Improved Ofab Agent Boots', 'boots', 264309, 264310, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Improved Ofab Agent Pants', 'pants', 264315, 264316, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Improved Ofab Agent Sleeves', 'sleeves', 264297, 264298, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Improved Ofab Agent Gloves', 'gloves', 264291, 264292, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Improved Ofab Agent Helmet', 'helmet', 264285, 264286, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Improved Ofab Bureaucrat Vest', 'body', 264519, 264520, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Improved Ofab Bureaucrat Boots', 'boots', 264525, 264526, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Improved Ofab Bureaucrat Pants', 'pants', 264531, 264532, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Improved Ofab Bureaucrat Sleeves', 'sleeves', 264513, 264514, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Improved Ofab Bureaucrat Gloves', 'gloves', 264507, 264508, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Improved Ofab Bureaucrat Headgear', 'helmet', 264501, 264502, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Improved Ofab Doctor Body', 'body', 264666, 264667, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Improved Ofab Doctor Boots', 'boots', 264672, 264673, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Improved Ofab Doctor Pants', 'pants', 264678, 264679, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Improved Ofab Doctor Sleeves', 'sleeves', 264660, 264661, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Improved Ofab Doctor Gloves', 'gloves', 264654, 264655, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Improved Ofab Doctor Helmet', 'helmet', 264648, 264649, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Improved Ofab Enforcer Breastplate', 'body', 264225, 264226, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Improved Ofab Enforcer Boots', 'boots', 264219, 264220, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Improved Ofab Enforcer Pants', 'pants', 264213, 264214, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Improved Ofab Enforcer Sleeves', 'sleeves', 264231, 264232, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Improved Ofab Enforcer Gauntlets', 'gloves', 264237, 264238, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Improved Ofab Enforcer Helmet', 'helmet', 264243, 264244, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Improved Ofab Engineer Body', 'body', 264594, 264595, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Improved Ofab Engineer Boots', 'boots', 264600, 264601, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Improved Ofab Engineer Pants', 'pants', 264606, 264607, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Improved Ofab Engineer Sleeves', 'sleeves', 264585, 264586, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Improved Ofab Engineer Gloves', 'gloves', 264579, 264580, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Improved Ofab Engineer Helmet', 'helmet', 264573, 264574, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Improved Ofab Fixer Body Armor', 'body', 264483, 264484, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Improved Ofab Fixer Boots', 'boots', 264489, 264490, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Improved Ofab Fixer Pants', 'pants', 264495, 264496, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Improved Ofab Fixer Sleeves', 'sleeves', 264477, 264478, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Improved Ofab Fixer Gloves', 'gloves', 264471, 264472, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Improved Ofab Fixer Helmet', 'helmet', 264465, 264466, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Improved Ofab Keeper Body Armor', 'body', 264630, 264631, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Improved Ofab Keeper Boots', 'boots', 264636, 264637, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Improved Ofab Keeper Pants', 'pants', 264642, 264643, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Improved Ofab Keeper Sleeves', 'sleeves', 264624, 264625, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Improved Ofab Keeper Gloves', 'gloves', 264618, 264619, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Improved Ofab Keeper Helmet', 'helmet', 264612, 264613, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Improved Ofab Martial Artist Body Armor', 'body', 264339, 264340, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Improved Ofab Martial Artist Boots', 'boots', 264345, 264346,1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Improved Ofab Martial Artist Pants', 'pants', 264351, 264352,1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Improved Ofab Martial Artist Sleeves', 'sleeves', 264333, 264334, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Improved Ofab Martial Artist Gloves', 'gloves', 264327, 264328, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Improved Ofab Martial Artist Helmet', 'helmet', 264321, 264322, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Improved Ofab Metaphysicist Body Armor', 'body', 264375, 264376, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Improved Ofab Metaphysicist Boots', 'boots', 264381, 264382, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Improved Ofab Metaphysicist Pants', 'pants', 264387, 264388, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Improved Ofab Metaphysicist Sleeves', 'sleeves', 264369, 264370, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Improved Ofab Metaphysicist Gloves', 'gloves', 264363, 264364,1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Improved Ofab Metaphysicist Headgear', 'helmet', 264357, 264358,1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Improved Ofab Nano Technician Body Armor', 'body', 264411, 264412, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Improved Ofab Nano Technician Boots', 'boots', 264417, 264418, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Improved Ofab Nano Technician Pants', 'pants', 264423, 264424, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Improved Ofab Nano Technician Sleeves', 'sleeves', 264405, 264406, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Improved Ofab Nano Technician Gloves', 'gloves', 264399, 264400, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Improved Ofab Nano Technician Helmet', 'helmet', 264393, 264394, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Improved Ofab Soldier Body Armor', 'body', 264447, 264448, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Improved Ofab Soldier Boots', 'boots', 264453, 264454, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Improved Ofab Soldier Pants', 'pants', 264459, 264460, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Improved Ofab Soldier Sleeves', 'sleeves', 264441, 264442, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Improved Ofab Soldier Gloves', 'gloves', 264435, 264436, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Improved Ofab Soldier Helmet', 'helmet', 264429, 264430, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Improved Ofab Trader Body Armor', 'body', 264267, 264268, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Improved Ofab Trader Boots', 'boots', 264279, 264280, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Improved Ofab Trader Pants', 'pants', 264273, 264274, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Improved Ofab Trader Sleeves', 'sleeves', 264261, 264262, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Improved Ofab Trader Gloves', 'gloves', 264255, 264256, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Improved Ofab Trader Helmet', 'helmet', 264249, 264250, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Improved Ofab Shade Body Armor', 'body', 264555, 264556, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Improved Ofab Shade Boots', 'boots', 264561, 264562, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Improved Ofab Shade Pants', 'pants', 264567, 264568, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Improved Ofab Shade Sleeves', 'sleeves', 264549, 264550, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Improved Ofab Shade Gloves', 'gloves', 264543, 264544, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Improved Ofab Shade Headgear', 'helmet', 264537, 264538, 1);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Penultimate Ofab Adventurer Body Armor', 'body', 264178, 264179, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Penultimate Ofab Adventurer Boots', 'boots', 264176, 264177, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Penultimate Ofab Adventurer Pants', 'pants', 264174, 264175, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Penultimate Ofab Adventurer Sleeves', 'sleeves', 264180, 264181, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Penultimate Ofab Adventurer Gloves', 'gloves', 264182, 264183, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Penultimate Ofab Adventurer Helmet', 'helmet', 264184, 264185, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Penultimate Ofab Agent Body Armor', 'body', 264301, 264302, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Penultimate Ofab Agent Boots', 'boots', 264307, 264308, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Penultimate Ofab Agent Pants', 'pants', 264313, 264314, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Penultimate Ofab Agent Sleeves', 'sleeves', 264295, 264296, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Penultimate Ofab Agent Gloves', 'gloves', 264289, 264290, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Penultimate Ofab Agent Helmet', 'helmet', 264283, 264284, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Penultimate Ofab Bureaucrat Vest', 'body', 264517, 264518, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Penultimate Ofab Bureaucrat Boots', 'boots', 264523, 264524, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Penultimate Ofab Bureaucrat Pants', 'pants', 264529, 264530, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Penultimate Ofab Bureaucrat Sleeves', 'sleeves', 264511, 264512, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Penultimate Ofab Bureaucrat Gloves', 'gloves', 264505, 264506, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Penultimate Ofab Bureaucrat Headgear', 'helmet', 264499, 264500, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Penultimate Ofab Doctor Body', 'body', 264664, 264665, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Penultimate Ofab Doctor Boots', 'boots', 264670, 264671, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Penultimate Ofab Doctor Pants', 'pants', 264676, 264677, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Penultimate Ofab Doctor Sleeves', 'sleeves', 264658, 264659, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Penultimate Ofab Doctor Gloves', 'gloves', 264652, 264653, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Penultimate Ofab Doctor Helmet', 'helmet', 264646, 264647, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Penultimate Ofab Enforcer Breastplate', 'body', 264227, 264228, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Penultimate Ofab Enforcer Boots', 'boots', 264221, 264222, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Penultimate Ofab Enforcer Pants', 'pants', 264215, 264216, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Penultimate Ofab Enforcer Sleeves', 'sleeves', 264233, 264234, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Penultimate Ofab Enforcer Gauntlets', 'gloves', 264239, 264240, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Penultimate Ofab Enforcer Helmet', 'helmet', 264245, 264246, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Penultimate Ofab Engineer Body', 'body', 264592, 264593, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Penultimate Ofab Engineer Boots', 'boots', 264598, 264599, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Penultimate Ofab Engineer Pants', 'pants', 264604, 264605, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Penultimate Ofab Engineer Sleeves', 'sleeves', 264583, 264584, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Penultimate Ofab Engineer Gloves', 'gloves', 264577, 264578, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Penultimate Ofab Engineer Helmet', 'helmet', 264571, 264572, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Penultimate Ofab Fixer Body Armor', 'body', 264481, 264482, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Penultimate Ofab Fixer Boots', 'boots', 264487, 264488, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Penultimate Ofab Fixer Pants', 'pants', 264493, 264494, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Penultimate Ofab Fixer Sleeves', 'sleeves', 264475, 264476, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Penultimate Ofab Fixer Gloves', 'gloves', 264469, 264470, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Penultimate Ofab Fixer Helmet', 'helmet', 264463, 264464, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Penultimate Ofab Keeper Body Armor', 'body', 264628, 264629, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Penultimate Ofab Keeper Boots', 'boots', 264634, 264635, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Penultimate Ofab Keeper Pants', 'pants', 264640, 264641, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Penultimate Ofab Keeper Sleeves', 'sleeves', 264622, 264623, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Penultimate Ofab Keeper Gloves', 'gloves', 264616, 264617, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Penultimate Ofab Keeper Helmet', 'helmet', 264610, 264611, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Penultimate Ofab Martial Artist Body Armor', 'body', 264337, 264338, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Penultimate Ofab Martial Artist Boots', 'boots', 264343, 264344, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Penultimate Ofab Martial Artist Pants', 'pants', 264349, 264350, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Penultimate Ofab Martial Artist Sleeves', 'sleeves', 264331, 264332, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Penultimate Ofab Martial Artist Gloves', 'gloves', 264325, 264326, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Penultimate Ofab Martial Artist Helmet', 'helmet', 264319, 264320, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Penultimate Ofab Metaphysicist Body Armor', 'body', 264373, 264374, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Penultimate Ofab Metaphysicist Boots', 'boots', 264379, 264380, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Penultimate Ofab Metaphysicist Pants', 'pants', 264385, 264386, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Penultimate Ofab Metaphysicist Sleeves', 'sleeves', 264367, 264368, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Penultimate Ofab Metaphysicist Gloves', 'gloves', 264361, 264362, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Penultimate Ofab Metaphysicist Headgear', 'helmet', 264355, 264356, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Penultimate Ofab Nano Technician Body Armor', 'body', 264409, 264410, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Penultimate Ofab Nano Technician Boots', 'boots', 264415, 264416, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Penultimate Ofab Nano Technician Pants', 'pants', 264421, 264422, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Penultimate Ofab Nano Technician Sleeves', 'sleeves', 264403, 264404, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Penultimate Ofab Nano Technician Gloves', 'gloves', 264397, 264398, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Penultimate Ofab Nano Technician Helmet', 'helmet', 264391, 264392, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Penultimate Ofab Soldier Body Armor', 'body', 264445, 264446, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Penultimate Ofab Soldier Boots', 'boots', 264451, 264452, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Penultimate Ofab Soldier Pants', 'pants', 264457, 264458, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Penultimate Ofab Soldier Sleeves', 'sleeves', 264439, 264440, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Penultimate Ofab Soldier Gloves', 'gloves', 264433, 264434, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Penultimate Ofab Soldier Helmet', 'helmet', 264427, 264428, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Penultimate Ofab Trader Body Armor', 'body', 264265, 264266, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Penultimate Ofab Trader Boots', 'boots', 264277, 264278, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Penultimate Ofab Trader Pants', 'pants', 264271, 264272, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Penultimate Ofab Trader Sleeves', 'sleeves', 264259, 264260, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Penultimate Ofab Trader Gloves', 'gloves', 264253, 264254, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Penultimate Ofab Trader Helmet', 'helmet', 264247, 264248, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Penultimate Ofab Shade Body Armor', 'body', 264553, 264554, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Penultimate Ofab Shade Boots', 'boots', 264559, 264560, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Penultimate Ofab Shade Pants', 'pants', 264565, 264566, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Penultimate Ofab Shade Sleeves', 'sleeves', 264547, 264548, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Penultimate Ofab Shade Gloves', 'gloves', 264541, 264542, 2);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Penultimate Ofab Shade Headgear', 'helmet', 264535, 264536, 2);

INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'Special Edition Ofab Adventurer Helmet', 'specialhelmet', 267353, 267354, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'Special Edition Ofab Agent Helmet', 'specialhelmet', 267356, 267357, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'Special Edition Ofab Bureaucrat Headgear', 'specialhelmet', 267363, 267364, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'Special Edition Ofab Doctor Helmet', 'specialhelmet', 267351, 267352, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'Special Edition Ofab Enforcer Helmet', 'specialhelmet', 267365, 267366, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'Special Edition Ofab Engineer Helmet', 'specialhelmet', 267369, 267370, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'Special Edition Ofab Fixer Helmet', 'specialhelmet', 267367, 267368, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'Special Edition Ofab Keeper Helmet', 'specialhelmet', 267375, 267376, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'Special Edition Ofab Martial Artist Helmet', 'specialhelmet', 267371, 267372, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'Special Edition Ofab Metaphysicist Headgear', 'specialhelmet', 267373, 267374, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'Special Edition Ofab Nano Technician Helmet', 'specialhelmet', 267383, 267384, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'Special Edition Ofab Soldier Helmet', 'specialhelmet', 267379, 267380, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'Special Edition Ofab Trader Helmet', 'specialhelmet', 267381, 267382, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'Special Edition Ofab Shade Headgear', 'specialhelmet', 267377, 267378, 3);

INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'OFAB Adventurer Protective Gear', 'back', 267931, 267931, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'OFAB Agent Protective Gear', 'back', 267509, 267509, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'OFAB Bureaucrat Protective Gear', 'back', 267932, 267932, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'OFAB Doctor Protective Gear', 'back', 267933, 267933, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'OFAB Enforcer Protective Gear', 'back', 267510, 267510, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'OFAB Engineer Protective Gear', 'back', 267936, 267936, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'OFAB Fixer Protective Gear', 'back', 267512, 267512, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'OFAB Keeper Protective Gear', 'back', 267513, 267513, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'OFAB Martial Artist Protective Gear', 'back', 267937, 267937, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'OFAB Meta-Physicist Protective Gear', 'back', 267515, 267515, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'OFAB Nano Technician Protective Gear', 'back', 267938, 267938, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'OFAB Soldier Protective Gear', 'back', 267939, 267939, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'OFAB Trader Protective Gear', 'back', 267935, 267935, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'OFAB Shade Protective Gear', 'back', 267934, 267934, 3);

INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Adventurer', 'OFAB Adventurer Shoulder Wear', 'shoulder', 301693, 301693, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Agent', 'OFAB Agent Shoulder Wear', 'shoulder', 301698, 301698, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Bureaucrat', 'OFAB Bureaucrat Shoulder Wear', 'shoulder', 301696, 301696, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Doctor', 'OFAB Doctor Shoulder Wear', 'shoulder', 301697, 301697, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Enforcer', 'OFAB Enforcer Shoulder Wear', 'shoulder', 267511, 267511, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Engineer', 'OFAB Engineer Shoulder Wear', 'shoulder', 268003, 268003, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Fixer', 'OFAB Fixer Shoulder Wear', 'shoulder', 301694, 301694, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Keeper', 'OFAB Keeper Shoulder Wear', 'shoulder', 267514, 267514, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Martial Artist', 'OFAB Martial Artist Shoulder Wear', 'shoulder', 268004, 268004, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Meta-Physicist', 'OFAB Metaphysicist Shoulder Wear', 'shoulder', 301695, 301695, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Nano-Technician', 'OFAB Nano Technician Shoulder Wear', 'shoulder', 268081, 268081, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Soldier', 'OFAB Soldier Shoulder Wear', 'shoulder', 268186, 268186, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Trader', 'OFAB Trader Shoulder Wear', 'shoulder', 268006, 268006, 3);
INSERT INTO ofab_armor (profession, name, slot, lowid, highid, upgrade) VALUES ('Shade', 'OFAB Shade Shoulder Wear', 'shoulder', 268005, 268005, 3);

DROP TABLE IF EXISTS ofab_armor_cost;
CREATE TABLE ofab_armor_cost (slot varchar(30) NOT NULL, ql INT NOT NULL, vp INT NOT NULL);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 1, 100);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 25, 78);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 25, 73);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 25, 73);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 25, 49);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 25, 49);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 25, 78);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 25, 253);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 50, 323);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 50, 302);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 50, 302);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 50, 202);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 50, 202);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 50, 323);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 50, 741);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 75, 736);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 75, 690);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 75, 690);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 75, 460);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 75, 460);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 75, 736);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 75, 1563);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 100, 1316);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 100, 1234);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 100, 1234);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 100, 823);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 100, 823);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 100, 1316);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 100, 2719);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 125, 2064);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 125, 1935);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 125, 1935);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 125, 1290);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 125, 1290);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 125, 2064);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 125, 4210);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 150, 2980);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 150, 2794);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 150, 2794);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 150, 1863);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 150, 1863);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 150, 2980);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 150, 6035);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 175, 4064);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 175, 3810);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 175, 3810);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 175, 2540);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 175, 2540);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 175, 4064);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 175, 8193);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 200, 5316);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 200, 4984);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 200, 4984);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 200, 3322);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 200, 3322);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 200, 5316);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 200, 10687);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 225, 6735);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 225, 6313);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 225, 6313);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 225, 4209);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 225, 4209);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 225, 6735);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 225, 13513);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 250, 8321);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 250, 7802);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 250, 7802);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 250, 5201);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 250, 5201);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 250, 8321);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 250, 16674);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 275, 10077);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 275, 9446);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 275, 9446);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 275, 6298);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 275, 6298);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 275, 10077);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 275, 20171);

INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('body', 300, 12000);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('boots', 300, 11250);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('pants', 300, 11250);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('sleeves', 300, 7500);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('gloves', 300, 7500);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('helmet', 300, 12000);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('ring', 300, 24000);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('specialhelmet', 300, 30000);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('back', 300, 30000);
INSERT INTO ofab_armor_cost (slot, ql, vp) VALUES ('shoulder', 300, 12000);

DROP TABLE IF EXISTS ofab_armor_type;
CREATE TABLE ofab_armor_type (type SMALLINT NOT NULL, profession VARCHAR(30) NOT NULL);
INSERT INTO ofab_armor_type (type, profession) VALUES (64, 'Doctor');
INSERT INTO ofab_armor_type (type, profession) VALUES (64, 'Engineer');
INSERT INTO ofab_armor_type (type, profession) VALUES (64, 'Keeper');
INSERT INTO ofab_armor_type (type, profession) VALUES (64, 'Meta-Physicist');
INSERT INTO ofab_armor_type (type, profession) VALUES (295, 'Adventurer');
INSERT INTO ofab_armor_type (type, profession) VALUES (295, 'Enforcer');
INSERT INTO ofab_armor_type (type, profession) VALUES (295, 'Martial Artist');
INSERT INTO ofab_armor_type (type, profession) VALUES (295, 'Soldier');
INSERT INTO ofab_armor_type (type, profession) VALUES (468, 'Bureaucrat');
INSERT INTO ofab_armor_type (type, profession) VALUES (468, 'Nano-Technician');
INSERT INTO ofab_armor_type (type, profession) VALUES (468, 'Trader');
INSERT INTO ofab_armor_type (type, profession) VALUES (935, 'Agent');
INSERT INTO ofab_armor_type (type, profession) VALUES (935, 'Fixer');
INSERT INTO ofab_armor_type (type, profession) VALUES (935, 'Shade');
