DROP TABLE IF EXISTS boss;
CREATE TABLE boss (id INT PRIMARY KEY,name VARCHAR(50) NOT NULL);
INSERT INTO boss VALUES (1,'Afreet Ellis');
INSERT INTO boss VALUES (2,'Akshki'); 
INSERT INTO boss VALUES (3,'Alpha Skincrawler');
INSERT INTO boss VALUES (4,'Anansi''s Left Hand');
INSERT INTO boss VALUES (5,'Anansi''s Right Hand');
INSERT INTO boss VALUES (6,'Anansi''s Abettor');
INSERT INTO boss VALUES (7,'Anansi''s Favorite');
INSERT INTO boss VALUES (8,'Aniitaps Shadow');
INSERT INTO boss VALUES (9,'Apprentice Beasthandler');
INSERT INTO boss VALUES (10,'Aquarius');
INSERT INTO boss VALUES (11,'Aries');
INSERT INTO boss VALUES (12,'Asperous Imp');
INSERT INTO boss VALUES (13,'Astypalia');
INSERT INTO boss VALUES (14,'Atakirh');
INSERT INTO boss VALUES (15,'Athlar');
INSERT INTO boss VALUES (16,'Bane');
INSERT INTO boss VALUES (17,'Bending Eremite');
INSERT INTO boss VALUES (18,'Bigot Inmodeah');
INSERT INTO boss VALUES (19,'Black');
INSERT INTO boss VALUES (20,'Brutish Dryad');
INSERT INTO boss VALUES (21,'Cacophonous Imp');
INSERT INTO boss VALUES (22,'Cancer');
INSERT INTO boss VALUES (23,'Cantankerous Golem');
INSERT INTO boss VALUES (24,'Capricorn');
INSERT INTO boss VALUES (25,'Catervauling Minx');
INSERT INTO boss VALUES (26,'Cenobite Shadow');
INSERT INTO boss VALUES (27,'Cerubin The Rejected');
INSERT INTO boss VALUES (28,'Chimera Monitor');
INSERT INTO boss VALUES (29,'Chimera Trainer');
INSERT INTO boss VALUES (30,'Clan Modified A-4000');
INSERT INTO boss VALUES (31,'Clan Modified A-4001');
INSERT INTO boss VALUES (32,'Chimera Trainer');
INSERT INTO boss VALUES (33,'Colonel Frank Kaehler');
INSERT INTO boss VALUES (34,'Comatosed Soul');
INSERT INTO boss VALUES (35,'Commander Kelly Frederickson');
INSERT INTO boss VALUES (36,'Conflagrant Spirit');
INSERT INTO boss VALUES (37,'Corrupt Spirit');
INSERT INTO boss VALUES (38,'Crabby Golem');
INSERT INTO boss VALUES (39,'Cranky Golem');
INSERT INTO boss VALUES (40,'Creepy Spider');
INSERT INTO boss VALUES (41,'Crete');
INSERT INTO boss VALUES (42,'Cuty');
INSERT INTO boss VALUES (43,'Daria Marie Walzer');
INSERT INTO boss VALUES (44,'Daring Dryad');
INSERT INTO boss VALUES (45,'Dauntless Dryad');
INSERT INTO boss VALUES (46,'Delinquent Spirit');
INSERT INTO boss VALUES (47,'Devoted Spirit Hunter');
INSERT INTO boss VALUES (48,'Diamondine Soldier');
INSERT INTO boss VALUES (49,'Diamondine Trainee');
INSERT INTO boss VALUES (50,'Ding');
INSERT INTO boss VALUES (51,'Disturbing Imp');
INSERT INTO boss VALUES (52,'Elian Zuwadza');
INSERT INTO boss VALUES (53,'Enkindled Spirit');
INSERT INTO boss VALUES (54,'Escaped Gargantula');
INSERT INTO boss VALUES (55,'Fanatic Spirit Hunter');
INSERT INTO boss VALUES (56,'Fearless Dryad');
INSERT INTO boss VALUES (57,'Fiery Soldier');
INSERT INTO boss VALUES (58,'Forefather');
INSERT INTO boss VALUES (59,'Gemini');
INSERT INTO boss VALUES (60,'General Kaehler Jr');
INSERT INTO boss VALUES (61,'General Kronillis');
INSERT INTO boss VALUES (62,'General Nirtox');
INSERT INTO boss VALUES (63,'General Vivyan');
INSERT INTO boss VALUES (64,'George');
INSERT INTO boss VALUES (65,'Hawqana');
INSERT INTO boss VALUES (66,'High Commander Frederickson');
INSERT INTO boss VALUES (67,'Howling Minx');
INSERT INTO boss VALUES (68,'Howling Predator');
INSERT INTO boss VALUES (69,'Ian Warr');
INSERT INTO boss VALUES (70,'Incandescent Spirit');
INSERT INTO boss VALUES (71,'Irascible Golem');
INSERT INTO boss VALUES (72,'Iron Reet');
INSERT INTO boss VALUES (73,'Isham');
INSERT INTO boss VALUES (74,'Ishimkimk');
INSERT INTO boss VALUES (75,'Ithaki');
INSERT INTO boss VALUES (76,'Joo');
INSERT INTO boss VALUES (77,'Jukes');
INSERT INTO boss VALUES (78,'Lab Director');
INSERT INTO boss VALUES (79,'Leo');
INSERT INTO boss VALUES (80,'Libra');
INSERT INTO boss VALUES (81,'Limber Dryad');
INSERT INTO boss VALUES (82,'Limnos');
INSERT INTO boss VALUES (83,'Limping Predator');
INSERT INTO boss VALUES (84,'Ljotur The Lunatic');
INSERT INTO boss VALUES (85,'Lord Of The Void');
INSERT INTO boss VALUES (86,'Lost Soul');
INSERT INTO boss VALUES (87,'Lurking Dryad');
INSERT INTO boss VALUES (88,'Mantis Queen');
INSERT INTO boss VALUES (89,'Marcus Robicheaux');
INSERT INTO boss VALUES (90,'Maychwaham');
INSERT INTO boss VALUES (91,'Mick Nugget McMullet');
INSERT INTO boss VALUES (92,'Mooching Dryad');
INSERT INTO boss VALUES (93,'Morgan Le Faye');
INSERT INTO boss VALUES (94,'Morty');
INSERT INTO boss VALUES (95,'Mull');
INSERT INTO boss VALUES (96,'Neleb The Deranged');
INSERT INTO boss VALUES (97,'Nelly Johnson');
INSERT INTO boss VALUES (98,'Notum Soldier');
INSERT INTO boss VALUES (99,'Notum Trainee');
INSERT INTO boss VALUES (100,'Obediency Inspector');
INSERT INTO boss VALUES (101,'Omni-Pol Command Juggernaut');
INSERT INTO boss VALUES (102,'Oscar');
INSERT INTO boss VALUES (103,'Ossuz');
INSERT INTO boss VALUES (104,'Ownz');
INSERT INTO boss VALUES (105,'Pained Predator');
INSERT INTO boss VALUES (106,'Patricia Johnson');
INSERT INTO boss VALUES (107,'Peristaltic Abomination');
INSERT INTO boss VALUES (108,'Peristaltic Aversion');
INSERT INTO boss VALUES (109,'Peter Lee');
INSERT INTO boss VALUES (110,'Phatmos');
INSERT INTO boss VALUES (111,'Pisces');
INSERT INTO boss VALUES (112,'Pit Demon');
INSERT INTO boss VALUES (113,'Polly');
INSERT INTO boss VALUES (114,'Polymorphed Lunatic');
INSERT INTO boss VALUES (115,'Powa');
INSERT INTO boss VALUES (116,'Professor Van Horn');
INSERT INTO boss VALUES (117,'Punctilious Hiathlin');
INSERT INTO boss VALUES (118,'Putrid Eremite');
INSERT INTO boss VALUES (119,'R-2000 Vermin Disposal Unit');
INSERT INTO boss VALUES (120,'Ris Lee');
INSERT INTO boss VALUES (121,'Rotting Eremite');
INSERT INTO boss VALUES (122,'Sadistic Soul Dredge');
INSERT INTO boss VALUES (123,'Sagittarius');
INSERT INTO boss VALUES (124,'Salahpt');
INSERT INTO boss VALUES (125,'Scary Spider');
INSERT INTO boss VALUES (126,'Scorpio');
INSERT INTO boss VALUES (127,'Scratching Soul Dredge');
INSERT INTO boss VALUES (128,'Screeching Imp');
INSERT INTO boss VALUES (129,'Scrupulous Hiathlin');
INSERT INTO boss VALUES (130,'Sinful Soul Dredge');
INSERT INTO boss VALUES (131,'Skulking Dryad');
INSERT INTO boss VALUES (132,'Skylight');
INSERT INTO boss VALUES (133,'Slinking Dryad');
INSERT INTO boss VALUES (134,'Snatching Soul Dredge');
INSERT INTO boss VALUES (135,'Special Agent Lamb');
INSERT INTO boss VALUES (136,'Spetses');
INSERT INTO boss VALUES (137,'Splintered Girder');
INSERT INTO boss VALUES (138,'Stark');
INSERT INTO boss VALUES (139,'Steele Filar');
INSERT INTO boss VALUES (140,'Stumpy');
INSERT INTO boss VALUES (141,'Supply Master Eel');
INSERT INTO boss VALUES (142,'Supply Master Smug');
INSERT INTO boss VALUES (143,'Swirling Eremite');
INSERT INTO boss VALUES (144,'T.I.M.');
INSERT INTO boss VALUES (145,'Tarasque');
INSERT INTO boss VALUES (146,'Taurus');
INSERT INTO boss VALUES (147,'Tdecin');
INSERT INTO boss VALUES (148,'The Beast');
INSERT INTO boss VALUES (149,'The Nightheart');
INSERT INTO boss VALUES (150,'The Obediency Enforcer');
INSERT INTO boss VALUES (151,'The One (Babyface)');
INSERT INTO boss VALUES (152,'The Pest');
INSERT INTO boss VALUES (153,'Tinos');
INSERT INTO boss VALUES (154,'Tiunissik');
INSERT INTO boss VALUES (155,'Torrid Spirit');
INSERT INTO boss VALUES (156,'Torrith The Ancient');
INSERT INTO boss VALUES (157,'Tri Plumbo');
INSERT INTO boss VALUES (158,'Tuqusk');
INSERT INTO boss VALUES (159,'Turk');
INSERT INTO boss VALUES (160,'Tyro Beasthandler');
INSERT INTO boss VALUES (161,'Ushamaham');
INSERT INTO boss VALUES (162,'Virgo');
INSERT INTO boss VALUES (163,'Waning Soul');
INSERT INTO boss VALUES (164,'Wounded Predator');
INSERT INTO boss VALUES (165,'Zias');
INSERT INTO boss VALUES (166,'Xark the Battletoad');
INSERT INTO boss VALUES (167,'Inobak the Gelid');
INSERT INTO boss VALUES (168,'Hezak The Immortal');
INSERT INTO boss VALUES (169,'Dominus Facut the Bloodless');
INSERT INTO boss VALUES (170,'Dominus Ummoh the Pedagogue');
INSERT INTO boss VALUES (171,'Dominus Jiannu');
INSERT INTO boss VALUES (172,'Iskop the Idolator');
INSERT INTO boss VALUES (173,'Jeuru the Defiler');
INSERT INTO boss VALUES (174,'Wicked Soul Dredge');
INSERT INTO boss VALUES (175,'Numiel');
INSERT INTO boss VALUES (176,'Asanon');
INSERT INTO boss VALUES (177,'Ahomac');
INSERT INTO boss VALUES (178,'Hebial');
INSERT INTO boss VALUES (179,'Primus Scrap Pillager');
INSERT INTO boss VALUES (180,'Primus Outlaw');
INSERT INTO boss VALUES (181,'Distracted Snake Tamer');
INSERT INTO boss VALUES (182,'First Brood Champion');
INSERT INTO boss VALUES (183,'Second Brood Champion');
INSERT INTO boss VALUES (184,'Third Brood Champion');
INSERT INTO boss VALUES (185,'Fourth Brood Champion');
INSERT INTO boss VALUES (186,'Fifth Brood Champion');
INSERT INTO boss VALUES (187,'Sixth Brood Champion');
INSERT INTO boss VALUES (188,'Seventh Brood Champion');
INSERT INTO boss VALUES (189,'Eighth Brood Champion');
INSERT INTO boss VALUES (190,'Ninth Brood Champion');
INSERT INTO boss VALUES (191,'Tenth Brood Champion');
INSERT INTO boss VALUES (192,'The Hollow Island Suzerain');
INSERT INTO boss VALUES (193,'The Brood Mother');
INSERT INTO boss VALUES (194,'Hollow Island Weed');
INSERT INTO boss VALUES (195,'Algid Slither');
INSERT INTO boss VALUES (196,'Brumal Slither');
INSERT INTO boss VALUES (197,'Chilly Slither');
INSERT INTO boss VALUES (198,'Cold Slither');
INSERT INTO boss VALUES (199,'Nippy Slither');
INSERT INTO boss VALUES (200,'Gashing Soul Dredge');
INSERT INTO boss VALUES (201,'Iced Slither');
INSERT INTO boss VALUES (202,'Iniquitous Spirit');
INSERT INTO boss VALUES (203,'Tiny');
INSERT INTO boss VALUES (204,'Trup');
INSERT INTO boss VALUES (205,'Vile Spirit');
INSERT INTO boss VALUES (206,'Jack Legchopper');
INSERT INTO boss VALUES (207,'Trash King');
INSERT INTO boss VALUES (209,'Lord Ghasap');
INSERT INTO boss VALUES (210,'Eumenides');
INSERT INTO boss VALUES (211,'Vergil Aeneid');
INSERT INTO boss VALUES (212,'Abmouth Supremus');
INSERT INTO boss VALUES (213,'General Serverus');
INSERT INTO boss VALUES (214,'Eradicator Deimos');
INSERT INTO boss VALUES (215,'Techleader Praetor');
INSERT INTO boss VALUES (216,'Augmented Cyborg Hellfury');
INSERT INTO boss VALUES (217,'Prototype Inferno');
INSERT INTO boss VALUES (218,'Commander Jocasta');
INSERT INTO boss VALUES (219,'Defender Of The Three');
INSERT INTO boss VALUES (220,'The Curator');
INSERT INTO boss VALUES (221,'Nematet The Custodian Of Time');
INSERT INTO boss VALUES (222,'The Re-animator');
INSERT INTO boss VALUES (223,'Lien the Memorystalker');
INSERT INTO boss VALUES (224,'Guardian Of Tomorrow');
INSERT INTO boss VALUES (225,'Uklesh The Frozen');
INSERT INTO boss VALUES (226,'Aztur The Immortal');
INSERT INTO boss VALUES (227,'Gartua The Doorkeeper');
INSERT INTO boss VALUES (228,'Windcaller Yatilla');
INSERT INTO boss VALUES (229,'Den Smuggler Pilot');
INSERT INTO boss VALUES (230, 'Anansi''s Disciple');
INSERT INTO boss VALUES (231, 'Aniitap''s Shadow');
INSERT INTO boss VALUES (232, 'Akshk''i');
INSERT INTO boss VALUES (233, 'Bia''s Favorite');
INSERT INTO boss VALUES (234, 'Bigot Helozabasael');
INSERT INTO boss VALUES (235, 'Bigot Nzaemihiel');
INSERT INTO boss VALUES (237, 'Estella Fire');
INSERT INTO boss VALUES (238, 'Fetid Eremite');
INSERT INTO boss VALUES (239, 'Hebiel');
INSERT INTO boss VALUES (240, 'Ishimk''Imk');
INSERT INTO boss VALUES (241, 'Malah-Fulcifera');
INSERT INTO boss VALUES (242, 'Maychwyawi');
INSERT INTO boss VALUES (243, 'Medusa Philanderer');
INSERT INTO boss VALUES (244, 'Natsmaahpt');
INSERT INTO boss VALUES (245, 'Noxious Eremite');
INSERT INTO boss VALUES (246, 'Obsolete Soul Dredge');
INSERT INTO boss VALUES (247, 'Paxos');
INSERT INTO boss VALUES (248, 'Punctlious Hiathlin');
INSERT INTO boss VALUES (249, 'Pursued Spirit');
INSERT INTO boss VALUES (250, 'Pyiininnik');
INSERT INTO boss VALUES (251, 'Razor the Battletoad');
INSERT INTO boss VALUES (252, 'Sanatsimk');
INSERT INTO boss VALUES (253, 'Silent Spider');
INSERT INTO boss VALUES (254, 'Syros');
INSERT INTO boss VALUES (255, 'Tuq''usk');
INSERT INTO boss VALUES (256, 'Ushap''ing');
INSERT INTO boss VALUES (257, 'Waywaqa');
INSERT INTO boss VALUES (258, 'Ground Chief Vortexx');
INSERT INTO boss VALUES (259, 'Mitaar Hero');
INSERT INTO boss VALUES (260, '12-man');
INSERT INTO boss VALUES (261, 'M.A.G.S');
INSERT INTO boss VALUES (262, 'Lord of Sand');
INSERT INTO boss VALUES (263, 'Prime Evolution Huzzum');
INSERT INTO boss VALUES (264, 'Wardog');
INSERT INTO boss VALUES (265, 'Cyborg Executioner');
INSERT INTO boss VALUES (266, 'SANDSTORM Control Tower');
INSERT INTO boss VALUES (267, 'Warchief Skawt');
INSERT INTO boss VALUES (268, 'Entvined General');
INSERT INTO boss VALUES (269, 'High Commander Riker');
INSERT INTO boss VALUES (270, 'Abandoned Hope');