DROP TABLE IF EXISTS boss_loot;
CREATE TABLE boss_loot (boss_id INT NOT NULL, item_name VARCHAR(100) NOT NULL);
INSERT INTO boss_loot VALUES (1,'Massive Bolt Charger');
INSERT INTO boss_loot VALUES (2,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (2,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (2,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (2,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (2,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (2,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (2,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (3,'Brother''s Brass Knuckles');
INSERT INTO boss_loot VALUES (3,'Crawler Armor Boots');
INSERT INTO boss_loot VALUES (3,'Crawler Armor Gloves');
INSERT INTO boss_loot VALUES (3,'Crawler Armor Hood');
INSERT INTO boss_loot VALUES (3,'Crawler Armor Pants');
INSERT INTO boss_loot VALUES (3,'Crawler Armor Shoulder Pad');
INSERT INTO boss_loot VALUES (3,'Crawler Armor Sleeves');
INSERT INTO boss_loot VALUES (3,'Crawler Body Armor');
INSERT INTO boss_loot VALUES (4,'Subspace Mesh');
INSERT INTO boss_loot VALUES (4,'Meta-Cerebellum Ring');
INSERT INTO boss_loot VALUES (5,'Meta-Cerebellum Ring');
INSERT INTO boss_loot VALUES (6,'Two-Dimensional Hole');
INSERT INTO boss_loot VALUES (6,'Maiden''s Gloves');
INSERT INTO boss_loot VALUES (7,'Short Circuited Spiritech Circlet');
INSERT INTO boss_loot VALUES (7,'Short Circuited Spiritech Circlet');
INSERT INTO boss_loot VALUES (8,'Piercing Evil');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (9,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (9,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (9,'Master''s Eye');
INSERT INTO boss_loot VALUES (9,'Lava capsule');
INSERT INTO boss_loot VALUES (10,'Aquarius'' Boots of Small Steps');
INSERT INTO boss_loot VALUES (10,'Aquarius''s Multitask Calculator');
INSERT INTO boss_loot VALUES (10,'Intuitive Memory of the Aquarius');
INSERT INTO boss_loot VALUES (10,'Mediative Gloves of the Aquarius');
INSERT INTO boss_loot VALUES (11,'Aries'' Tiara of the Quick Witted');
INSERT INTO boss_loot VALUES (11,'Boon of Aries');
INSERT INTO boss_loot VALUES (11,'Dynamic Sleeve of Aries');
INSERT INTO boss_loot VALUES (11,'Quick-Draw Holster of Aries');
INSERT INTO boss_loot VALUES (12,'Elysian Protector''s Cuirass');
INSERT INTO boss_loot VALUES (12,'Focus-Funneling Spirit');
INSERT INTO boss_loot VALUES (13,'Blood-Soaked Cloak of Dishonour');
INSERT INTO boss_loot VALUES (14,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (14,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (14,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (14,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (14,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (14,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (14,'Pernicious Body Armor');
INSERT INTO boss_loot VALUES (14,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (15,'Spirit Ring of Self-Education');
INSERT INTO boss_loot VALUES (15,'Spirit Training Program');
INSERT INTO boss_loot VALUES (16,'Bracer of Recondite Flames');
INSERT INTO boss_loot VALUES (16,'Human Skin Hood');
INSERT INTO boss_loot VALUES (17,'Eremite Macro Sensor');
INSERT INTO boss_loot VALUES (17,'Eremite Macro Sensor');
INSERT INTO boss_loot VALUES (17,'Eremite Psychic Sensor');
INSERT INTO boss_loot VALUES (18,'Bigot''s Armband of Sacrifice');
INSERT INTO boss_loot VALUES (18,'Bigot''s Bracer of Sacrifice');
INSERT INTO boss_loot VALUES (18,'Bigot''s Earring of Sacrifice');
INSERT INTO boss_loot VALUES (18,'Bigot''s Necklace of Sacrifice');
INSERT INTO boss_loot VALUES (18,'Bigot''s Ring of Sacrifice');
INSERT INTO boss_loot VALUES (19,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (19,'Hood of Black Waters');
INSERT INTO boss_loot VALUES (20,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (21,'Elysian Protector''s Cuirass');
INSERT INTO boss_loot VALUES (21,'Focus-Funneling Spirit');
INSERT INTO boss_loot VALUES (22,'Cancer''s Gloves of Automatic Knowledge');
INSERT INTO boss_loot VALUES (22,'Cancer''s Ring of Circumspection');
INSERT INTO boss_loot VALUES (22,'Cancer''s Silver Boots of the Autodidact');
INSERT INTO boss_loot VALUES (22,'Cancer''s Time-Saving Memory');
INSERT INTO boss_loot VALUES (23,'Cantankerous''s Headwear');
INSERT INTO boss_loot VALUES (23,'Spirit Tech Apparatus: Double Barrel');
INSERT INTO boss_loot VALUES (23,'Spirit Tech Apparatus: Long Muzzle');
INSERT INTO boss_loot VALUES (23,'Spirit Tech Apparatus: Short Muzzle');
INSERT INTO boss_loot VALUES (23,'Fingerspitzgefuhl');
INSERT INTO boss_loot VALUES (24,'Capricorn Bracer of Toxication');
INSERT INTO boss_loot VALUES (24,'Capricorn''s Guide to Alchemy');
INSERT INTO boss_loot VALUES (24,'Capricorn''s Reliable Memory');
INSERT INTO boss_loot VALUES (24,'Gloves of the Caring Capricorn');
INSERT INTO boss_loot VALUES (25,'Shuffling Finger');
INSERT INTO boss_loot VALUES (26,'Blackbird');
INSERT INTO boss_loot VALUES (26,'Blackbird');
INSERT INTO boss_loot VALUES (26,'Chiroptera');
INSERT INTO boss_loot VALUES (26,'Chiroptera');
INSERT INTO boss_loot VALUES (26,'Howlet');
INSERT INTO boss_loot VALUES (26,'Howlet');
INSERT INTO boss_loot VALUES (27,'Focus-Funneling Device');
INSERT INTO boss_loot VALUES (27,'Gamboling Master''s Wear');
INSERT INTO boss_loot VALUES (27,'Jagged Claw');
INSERT INTO boss_loot VALUES (27,'Shapeshifter''s Vest');
INSERT INTO boss_loot VALUES (27,'Spirit Tech Circlet of Cerubin');
INSERT INTO boss_loot VALUES (27,'Grasping Ring');
INSERT INTO boss_loot VALUES (27,'Neck Eye');
INSERT INTO boss_loot VALUES (28,'Monitor Smoking Suit');
INSERT INTO boss_loot VALUES (29,'Shroud of Darkest Night');
INSERT INTO boss_loot VALUES (30,'Modified A-4000 NCU-sheet');
INSERT INTO boss_loot VALUES (30,'Modified A-4000 Sensory Panel');
INSERT INTO boss_loot VALUES (31,'Modified A-4000 NCU-sheet');
INSERT INTO boss_loot VALUES (31,'Modified A-4000 Sensory Panel');
INSERT INTO boss_loot VALUES (32,'Eremite Macro Sensor');
INSERT INTO boss_loot VALUES (32,'Eremite Micro Sensor');
INSERT INTO boss_loot VALUES (32,'Eremite Psychic Sensor');
INSERT INTO boss_loot VALUES (33,'Kaehler Uniform Sleeves');
INSERT INTO boss_loot VALUES (33,'Mendix Biomech AR-2');
INSERT INTO boss_loot VALUES (34,'Problem Avoiding Device');
INSERT INTO boss_loot VALUES (34,'Problem Seeking Device');
INSERT INTO boss_loot VALUES (34,'Problem Solving Device');
INSERT INTO boss_loot VALUES (35,'Frederickson Cumulus model');
INSERT INTO boss_loot VALUES (35,'Frederickson Micro-kinetic Sleeves');
INSERT INTO boss_loot VALUES (35,'Frederickson''s Kinetic Sleeves');
INSERT INTO boss_loot VALUES (36,'Syndicate Messenger Gun');
INSERT INTO boss_loot VALUES (37,'Lindgren Spirit');
INSERT INTO boss_loot VALUES (38,'Spirit Tech Apparatus: Double Barrel');
INSERT INTO boss_loot VALUES (38,'Spirit Tech Apparatus: Long Muzzle');
INSERT INTO boss_loot VALUES (38,'Spirit Tech Apparatus: Short Muzzle');
INSERT INTO boss_loot VALUES (38,'Doubleknit Pants');
INSERT INTO boss_loot VALUES (38,'The Cause of Headache');
INSERT INTO boss_loot VALUES (39,'Commander''s Ceremonial Chest Plate');
INSERT INTO boss_loot VALUES (39,'Cranky Golem Eye');
INSERT INTO boss_loot VALUES (39,'Spirit Tech Apparatus: Double Barrel');
INSERT INTO boss_loot VALUES (39,'Spirit Tech Apparatus: Long Muzzle');
INSERT INTO boss_loot VALUES (39,'Spirit Tech Apparatus: Short Muzzle');
INSERT INTO boss_loot VALUES (40,'Slippers of Screaming');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Grail of the White Feather');
INSERT INTO boss_loot VALUES (41,'Conflagrant Syndicate Messenger Gun');
INSERT INTO boss_loot VALUES (41,'Grail of the Antlered King');
INSERT INTO boss_loot VALUES (41,'Head Symbiant of the Love Child');
INSERT INTO boss_loot VALUES (42,'Candy Cord');
INSERT INTO boss_loot VALUES (43,'Kevlar Armbands');
INSERT INTO boss_loot VALUES (43,'The Third Eye of Daria');
INSERT INTO boss_loot VALUES (43,'Very Very Very Cool Top');
INSERT INTO boss_loot VALUES (43,'Very Very Very Hot Pants');
INSERT INTO boss_loot VALUES (44,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (45,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (46,'Spirit of the Innocent');
INSERT INTO boss_loot VALUES (47,'Fanatic''s Jacket');
INSERT INTO boss_loot VALUES (48,'Diamond-Matrix Mesh');
INSERT INTO boss_loot VALUES (48,'Kick Pistol');
INSERT INTO boss_loot VALUES (48,'Titan Viper Tattoo');
INSERT INTO boss_loot VALUES (49,'Diamond-Matrix Mesh');
INSERT INTO boss_loot VALUES (49,'Kick Pistol');
INSERT INTO boss_loot VALUES (50,'Counterfeit Omni Epaulet');
INSERT INTO boss_loot VALUES (51,'Elysian Protector''s Cuirass');
INSERT INTO boss_loot VALUES (51,'Focus-Funneling Spirit');
INSERT INTO boss_loot VALUES (52,'Blackshirt of Zuwadza');
INSERT INTO boss_loot VALUES (52,'Cheeping Flamethrower of Zuwadza');
INSERT INTO boss_loot VALUES (52,'Stinging Snake Tattoo');
INSERT INTO boss_loot VALUES (53,'Enkindled Spirit Focus');
INSERT INTO boss_loot VALUES (54,'Gift of the Old Gargantula');
INSERT INTO boss_loot VALUES (55,'Fanatic''s Jacket');
INSERT INTO boss_loot VALUES (56,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (57,'Beeping Backpack');
INSERT INTO boss_loot VALUES (57,'Junior Master of Combustion');
INSERT INTO boss_loot VALUES (58,'Fleshchopper');
INSERT INTO boss_loot VALUES (58,'Notum Focus');
INSERT INTO boss_loot VALUES (58,'Spirit Focus');
INSERT INTO boss_loot VALUES (58,'Toothpicker');
INSERT INTO boss_loot VALUES (59,'Collector Pants of Gemini');
INSERT INTO boss_loot VALUES (59,'Cross Dimensional Gyro of Gemini');
INSERT INTO boss_loot VALUES (59,'Gemini''s Double Band of Linked Information');
INSERT INTO boss_loot VALUES (59,'Gemini''s Green Scope of Variety');
INSERT INTO boss_loot VALUES (60,'Longshot');
INSERT INTO boss_loot VALUES (60,'Superior Sentinel Armor Boots');
INSERT INTO boss_loot VALUES (60,'Superior Sentinel Armor Gloves');
INSERT INTO boss_loot VALUES (60,'Superior Sentinel Armor Pants');
INSERT INTO boss_loot VALUES (60,'Superior Sentinel Armor Sleeves');
INSERT INTO boss_loot VALUES (60,'Superior Sentinel Body Armor');
INSERT INTO boss_loot VALUES (61,'Dust Collector');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Commander Boots');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Commander Chestpiece');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Commander Gloves');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Commander Skirt');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Commander Sleeves');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Trooper Boots');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Trooper Chestpiece');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Trooper Gloves');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Trooper Pants');
INSERT INTO boss_loot VALUES (61,'Dustbrigade Trooper Sleeves');
INSERT INTO boss_loot VALUES (61,'Mother Nitrogena');
INSERT INTO boss_loot VALUES (61,'Explorer Boots');
INSERT INTO boss_loot VALUES (61,'Pants of Participation');
INSERT INTO boss_loot VALUES (61,'Safeguarded NCU Memory Unit');
INSERT INTO boss_loot VALUES (61,'Specialized Dustbrigade Vambrace - Atrox Breed');
INSERT INTO boss_loot VALUES (61,'Specialized Dustbrigade Vambrace - Nano Breed');
INSERT INTO boss_loot VALUES (61,'Specialized Dustbrigade Vambrace - Opifex Breed');
INSERT INTO boss_loot VALUES (61,'Threatening Trousers');
INSERT INTO boss_loot VALUES (62,'Dust Collector');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Commander Boots');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Commander Chestpiece');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Commander Gloves');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Commander Skirt');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Commander Sleeves');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Trooper Boots');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Trooper Chestpiece');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Trooper Gloves');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Trooper Pants');
INSERT INTO boss_loot VALUES (62,'Dustbrigade Trooper Sleeves');
INSERT INTO boss_loot VALUES (62,'Mother Nitrogena');
INSERT INTO boss_loot VALUES (62,'Explorer Boots');
INSERT INTO boss_loot VALUES (62,'Pants of Participation');
INSERT INTO boss_loot VALUES (62,'Specialized Dustbrigade Vambrace - Nano Breed');
INSERT INTO boss_loot VALUES (62,'Specialized Dustbrigade Vambrace - Opifex Breed');
INSERT INTO boss_loot VALUES (62,'Threatening Trousers');
INSERT INTO boss_loot VALUES (63,'Dust Collector');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Commander Boots');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Commander Chestpiece');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Commander Gloves');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Commander Skirt');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Commander Sleeves');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Trooper Boots');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Trooper Chestpiece');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Trooper Gloves');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Trooper Pants');
INSERT INTO boss_loot VALUES (63,'Dustbrigade Trooper Sleeves');
INSERT INTO boss_loot VALUES (63,'Mother Nitrogena');
INSERT INTO boss_loot VALUES (63,'Explorer Boots');
INSERT INTO boss_loot VALUES (63,'Pants of Participation');
INSERT INTO boss_loot VALUES (62,'Safeguarded NCU Memory Unit');
INSERT INTO boss_loot VALUES (62,'Specialized Dustbrigade Vambrace - Atrox Breed');
INSERT INTO boss_loot VALUES (63,'Safeguarded NCU Memory Unit');
INSERT INTO boss_loot VALUES (63,'Specialized Dustbrigade Vambrace - Opifex Breed');
INSERT INTO boss_loot VALUES (63,'Specialized Dustbrigade Vambrace - Atrox Breed');
INSERT INTO boss_loot VALUES (63,'Specialized Dustbrigade Vambrace - Nano Breed');
INSERT INTO boss_loot VALUES (63,'Threatening Trousers');
INSERT INTO boss_loot VALUES (64,'Standard Medical Epaulet');
INSERT INTO boss_loot VALUES (65,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (65,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (65,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (65,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (65,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (65,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (65,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (66,'Longshot');
INSERT INTO boss_loot VALUES (66,'Omni-Armed Forces Armor');
INSERT INTO boss_loot VALUES (66,'Omni-Armed Forces Boots');
INSERT INTO boss_loot VALUES (66,'Omni-Armed Forces Gloves');
INSERT INTO boss_loot VALUES (66,'Omni-Armed Forces Pants');
INSERT INTO boss_loot VALUES (66,'Omni-Armed Forces Sleeves');
INSERT INTO boss_loot VALUES (67,'Shuffling Finger');
INSERT INTO boss_loot VALUES (68,'Predator Armband');
INSERT INTO boss_loot VALUES (68,'Predator Armor Boots');
INSERT INTO boss_loot VALUES (68,'Predator Armor Facemask');
INSERT INTO boss_loot VALUES (68,'Predator Armor Gloves');
INSERT INTO boss_loot VALUES (68,'Predator Armor Pants');
INSERT INTO boss_loot VALUES (68,'Predator Armor Vest');
INSERT INTO boss_loot VALUES (68,'Predator''s Circlet');
INSERT INTO boss_loot VALUES (69,'Average Gloves');
INSERT INTO boss_loot VALUES (69,'Blood-Stained Bat');
INSERT INTO boss_loot VALUES (69,'Blood-Stained Mace');
INSERT INTO boss_loot VALUES (69,'Boots of Azure Reveries');
INSERT INTO boss_loot VALUES (69,'Breastplate of Azure Reveries');
INSERT INTO boss_loot VALUES (69,'Flaxen Notum Pants');
INSERT INTO boss_loot VALUES (69,'Gloves of Azure Reveries');
INSERT INTO boss_loot VALUES (69,'Helmet of Azure Reveries');
INSERT INTO boss_loot VALUES (69,'Pants of Azure Reveries');
INSERT INTO boss_loot VALUES (69,'Pioneer of Jobe Cloak');
INSERT INTO boss_loot VALUES (69,'Rust-pitted Ring');
INSERT INTO boss_loot VALUES (69,'Sleeves of Azure Reveries');
INSERT INTO boss_loot VALUES (69,'Stone Samurai Boots');
INSERT INTO boss_loot VALUES (70,'Compagnero');
INSERT INTO boss_loot VALUES (71,'Golem''s Warm Notum Hood');
INSERT INTO boss_loot VALUES (71,'Spirit Tech Apparatus: Double Barrel');
INSERT INTO boss_loot VALUES (71,'Spirit Tech Apparatus: Long Muzzle');
INSERT INTO boss_loot VALUES (71,'Spirit Tech Apparatus: Short Muzzle');
INSERT INTO boss_loot VALUES (71,'Spirit of Opportunity');
INSERT INTO boss_loot VALUES (72,'Droid Control-device');
INSERT INTO boss_loot VALUES (72,'Modified Aggression Enhancer');
INSERT INTO boss_loot VALUES (73,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (73,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (73,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (73,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (73,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (73,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (73,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (74,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (74,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (74,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (74,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (74,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (74,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (74,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (74,'Mark of the Fisher King');
INSERT INTO boss_loot VALUES (75,'Maul of Gwyddawg');
INSERT INTO boss_loot VALUES (75,'Conflagrant Syndicate Messenger Gun');
INSERT INTO boss_loot VALUES (75,'Maul of Menestyr');
INSERT INTO boss_loot VALUES (76,'White Sack');
INSERT INTO boss_loot VALUES (77,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (77,'Floating Bag of Jukes');
INSERT INTO boss_loot VALUES (78,'Customized IMI Desert Reet 1000');
INSERT INTO boss_loot VALUES (78,'Sealed Order BLCG-7791');
INSERT INTO boss_loot VALUES (78,'Sealed Order FPGA-202');
INSERT INTO boss_loot VALUES (78,'Sealed Order XITL-0127');
INSERT INTO boss_loot VALUES (79,'Enthusiastic Spirit Helper of the Leo');
INSERT INTO boss_loot VALUES (79,'Leo''s Faithful Boots of Ancient Gold');
INSERT INTO boss_loot VALUES (79,'Leo''s Grandiose Gold Armband of Plenty');
INSERT INTO boss_loot VALUES (79,'Leo''s Mellow Gold Pad of Auto-Support');
INSERT INTO boss_loot VALUES (80,'Aim of Libra');
INSERT INTO boss_loot VALUES (80,'Libra''s Charming Assistant');
INSERT INTO boss_loot VALUES (80,'Urbane Pants of Libra');
INSERT INTO boss_loot VALUES (80,'Well Balanced Spirit Helper of Libra');
INSERT INTO boss_loot VALUES (81,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (81,'Pelisse of the Elysian Nymph');
INSERT INTO boss_loot VALUES (82,'Mystical Green Hood');
INSERT INTO boss_loot VALUES (83,'Predator Armband');
INSERT INTO boss_loot VALUES (83,'Predator Armor Boots');
INSERT INTO boss_loot VALUES (83,'Predator Armor Facemask');
INSERT INTO boss_loot VALUES (83,'Predator Armor Gloves');
INSERT INTO boss_loot VALUES (83,'Predator Armor Pants');
INSERT INTO boss_loot VALUES (83,'Predator Armor Vest');
INSERT INTO boss_loot VALUES (83,'Predator''s Circlet');
INSERT INTO boss_loot VALUES (84,'Eleet Doll');
INSERT INTO boss_loot VALUES (84,'Eye of the Hunter');
INSERT INTO boss_loot VALUES (84,'Ljotur Beets of Clamping');
INSERT INTO boss_loot VALUES (84,'Ljotur Pants of Cornucopia');
INSERT INTO boss_loot VALUES (84,'Mirror Mask of Ljotur');
INSERT INTO boss_loot VALUES (84,'NanoCrystal (Candycane)');
INSERT INTO boss_loot VALUES (84,'Twelve-Fingered Graspers of Ljotur');
INSERT INTO boss_loot VALUES (84,'Unbecoming Sleeves of Ljotur');
INSERT INTO boss_loot VALUES (84,'Upper Part of Ljotur');
INSERT INTO boss_loot VALUES (85,'Bloodlust');
INSERT INTO boss_loot VALUES (85,'Eye of the Evening Star');
INSERT INTO boss_loot VALUES (85,'Pensive Spirit Phulakterion');
INSERT INTO boss_loot VALUES (85,'Ring of Computing');
INSERT INTO boss_loot VALUES (85,'Ring of Divine Teardrops');
INSERT INTO boss_loot VALUES (85,'Silver Spider Knuckledusters');
INSERT INTO boss_loot VALUES (85,'Spear of Forbidden Ceremonies');
INSERT INTO boss_loot VALUES (85,'Stock of Bacam-Xum');
INSERT INTO boss_loot VALUES (85,'Watchful Spirit Phulakterion');
INSERT INTO boss_loot VALUES (86,'Problem Avoiding Device');
INSERT INTO boss_loot VALUES (86,'Problem Seeking Device');
INSERT INTO boss_loot VALUES (86,'Problem Solving Device');
INSERT INTO boss_loot VALUES (87,'Jobe City Guard Personal Pistol');
INSERT INTO boss_loot VALUES (87,'Jobe Surveyor Personal Pistol');
INSERT INTO boss_loot VALUES (87,'Jobe City Guard Personal Pistol');
INSERT INTO boss_loot VALUES (87,'Jobe Surveyor Personal Pistol');
INSERT INTO boss_loot VALUES (88,'Mantis Egg');
INSERT INTO boss_loot VALUES (88,'Queen Blade');
INSERT INTO boss_loot VALUES (88,'Mantis Scissors');
INSERT INTO boss_loot VALUES (89,'Poetic Pants');
INSERT INTO boss_loot VALUES (89,'Poetic Sleeves');
INSERT INTO boss_loot VALUES (89,'Poetic Stretch-band');
INSERT INTO boss_loot VALUES (90,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (90,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (90,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (90,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (90,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (90,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (90,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (91,'Energized Carbonan Oven Mittens');
INSERT INTO boss_loot VALUES (91,'Shades of Lucubration');
INSERT INTO boss_loot VALUES (92,'Chief Cook Cleaver');
INSERT INTO boss_loot VALUES (92,'Chief Cook Cleaver');
INSERT INTO boss_loot VALUES (92,'Ring that Turns Rocks');
INSERT INTO boss_loot VALUES (92,'Longsword of the Illuminated');
INSERT INTO boss_loot VALUES (92,'Sword of the Illuminated');
INSERT INTO boss_loot VALUES (93,'Gutting Hook');
INSERT INTO boss_loot VALUES (93,'Torturing Tool');
INSERT INTO boss_loot VALUES (94,'Whistle-box');
INSERT INTO boss_loot VALUES (95,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (96,'Fractured Sanity');
INSERT INTO boss_loot VALUES (96,'Neleb''s Nano-circuit Robe');
INSERT INTO boss_loot VALUES (96,'Neleb''s Notum Battlerod');
INSERT INTO boss_loot VALUES (96,'Fractured Sanity');
INSERT INTO boss_loot VALUES (96,'Cortex of the Executioner');
INSERT INTO boss_loot VALUES (96,'Brainchopper');
INSERT INTO boss_loot VALUES (96,'Galahad Inc. Cinnamon Scout');
INSERT INTO boss_loot VALUES (97,'Anything');
INSERT INTO boss_loot VALUES (97,'Boots of Azure Reveries');
INSERT INTO boss_loot VALUES (97,'Breastplate of Azure Reveries');
INSERT INTO boss_loot VALUES (97,'Gloves of Azure Reveries');
INSERT INTO boss_loot VALUES (97,'Helmet of Azure Reveries');
INSERT INTO boss_loot VALUES (97,'Nelly Johnsons Little Black Dress');
INSERT INTO boss_loot VALUES (97,'Pants of Azure Reveries');
INSERT INTO boss_loot VALUES (97,'Sleeves of Azure Reveries');
INSERT INTO boss_loot VALUES (98,'Nophex Plasma Destroyer I');
INSERT INTO boss_loot VALUES (98,'Notum Infused Kevlar Armor Boots');
INSERT INTO boss_loot VALUES (98,'Notum Infused Kevlar Armor Gloves');
INSERT INTO boss_loot VALUES (98,'Notum Infused Kevlar Armor Pants');
INSERT INTO boss_loot VALUES (98,'Notum Infused Kevlar Armor Sleeves');
INSERT INTO boss_loot VALUES (98,'Notum Infused Kevlar Body Armor');
INSERT INTO boss_loot VALUES (98,'Pulsing Notum Disruptor');
INSERT INTO boss_loot VALUES (99,'Erratic Notum Disruptor');
INSERT INTO boss_loot VALUES (100,'Fluctuating Anti-Matter Generator');
INSERT INTO boss_loot VALUES (101,'Anti-Gravity Unit');
INSERT INTO boss_loot VALUES (101,'Flower Guard Gofleprod');
INSERT INTO boss_loot VALUES (101,'Flower Guard Triplate Metal Armor Cloak');
INSERT INTO boss_loot VALUES (101,'Flower Guard Triplate Metal Boots');
INSERT INTO boss_loot VALUES (101,'Flower Guard Triplate Metal Gauntlets');
INSERT INTO boss_loot VALUES (101,'Flower Guard Triplate Metal Helmet');
INSERT INTO boss_loot VALUES (101,'Rusted Juggernaut Rear Mitrailleuse');
INSERT INTO boss_loot VALUES (101,'Standard Juggernaut Nano Containment Module');
INSERT INTO boss_loot VALUES (102,'Metallic Hoop');
INSERT INTO boss_loot VALUES (103,'Spirit Ring of Self-Education');
INSERT INTO boss_loot VALUES (103,'Spirit Training Program');
INSERT INTO boss_loot VALUES (104,'Capsule of Thin Blood');
INSERT INTO boss_loot VALUES (105,'Predator Armband');
INSERT INTO boss_loot VALUES (105,'Predator Armor Boots');
INSERT INTO boss_loot VALUES (105,'Predator Armor Facemask');
INSERT INTO boss_loot VALUES (105,'Predator Armor Gloves');
INSERT INTO boss_loot VALUES (105,'Predator Armor Pants');
INSERT INTO boss_loot VALUES (105,'Predator Armor Vest');
INSERT INTO boss_loot VALUES (105,'Predator''s Circlet');
INSERT INTO boss_loot VALUES (106,'Boots of Azure Reveries');
INSERT INTO boss_loot VALUES (106,'Pain of Patricia');
INSERT INTO boss_loot VALUES (106,'Breastplate of Azure Reveries');
INSERT INTO boss_loot VALUES (106,'Gloves of Azure Reveries');
INSERT INTO boss_loot VALUES (106,'Helmet of Azure Reveries');
INSERT INTO boss_loot VALUES (106,'Luxurious Rubber Pants');
INSERT INTO boss_loot VALUES (106,'Luxurious Rubber Shirt');
INSERT INTO boss_loot VALUES (106,'Luxurious Rubber Sleeves');
INSERT INTO boss_loot VALUES (106,'Un-repairable Pain of Patricia');
INSERT INTO boss_loot VALUES (106,'Pants of Azure Reveries');
INSERT INTO boss_loot VALUES (106,'Reign of Patricia');
INSERT INTO boss_loot VALUES (106,'Sleeves of Azure Reveries');
INSERT INTO boss_loot VALUES (107,'Blackpack');
INSERT INTO boss_loot VALUES (107,'Doctor''s Pill Pack');
INSERT INTO boss_loot VALUES (107,'Syndicate Shades');
INSERT INTO boss_loot VALUES (108,'Blackpack');
INSERT INTO boss_loot VALUES (108,'Doctor''s Pill Pack');
INSERT INTO boss_loot VALUES (108,'Syndicate Shades');
INSERT INTO boss_loot VALUES (109,'Boots of Azure Reveries');
INSERT INTO boss_loot VALUES (109,'Breastplate of Azure Reveries');
INSERT INTO boss_loot VALUES (109,'Gloves of Azure Reveries');
INSERT INTO boss_loot VALUES (109,'Heavy Notum Tank Armor');
INSERT INTO boss_loot VALUES (109,'Helmet of Azure Reveries');
INSERT INTO boss_loot VALUES (109,'Light Notum Tank Armor');
INSERT INTO boss_loot VALUES (109,'Medium Notum Tank Armor');
INSERT INTO boss_loot VALUES (109,'Pants of Azure Reveries');
INSERT INTO boss_loot VALUES (109,'Sleeves of Azure Reveries');
INSERT INTO boss_loot VALUES (110,'Phatmos'' Booty');
INSERT INTO boss_loot VALUES (111,'Cosmic Guide of the Pisces');
INSERT INTO boss_loot VALUES (111,'Mystery of Pisces');
INSERT INTO boss_loot VALUES (111,'Octopus Contraption of the Pisces');
INSERT INTO boss_loot VALUES (111,'Octopus Contraption of the Pisces');
INSERT INTO boss_loot VALUES (112,'Hood of Wicked Inspiration');
INSERT INTO boss_loot VALUES (112,'Pit Demon Heart');
INSERT INTO boss_loot VALUES (112,'Pit Demon Spit');
INSERT INTO boss_loot VALUES (113,'Support Wire');
INSERT INTO boss_loot VALUES (114,'Nano Crystal (Team Beacon Warp)');
INSERT INTO boss_loot VALUES (114,'Nano Crystal (Nullity Sphere MK II)');
INSERT INTO boss_loot VALUES (115,'Starched Armbands');
INSERT INTO boss_loot VALUES (116,'Journeyman Durable Boost');
INSERT INTO boss_loot VALUES (116,'The Expensive Kevlar Vest of Professor Jones');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (117,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (118,'Sword of Curiosity');
INSERT INTO boss_loot VALUES (118,'Sword of Wonder');
INSERT INTO boss_loot VALUES (119,'Disposal Unit Electrical Toolset');
INSERT INTO boss_loot VALUES (119,'Rat Catcher Goggles');
INSERT INTO boss_loot VALUES (120,'Boots of Azure Reveries');
INSERT INTO boss_loot VALUES (120,'Breastplate of Azure Reveries');
INSERT INTO boss_loot VALUES (120,'Fancy Stethoscopic Glasses');
INSERT INTO boss_loot VALUES (120,'Gloves of Azure Reveries');
INSERT INTO boss_loot VALUES (120,'Helmet of Azure Reveries');
INSERT INTO boss_loot VALUES (120,'Pants of Azure Reveries');
INSERT INTO boss_loot VALUES (120,'Sleeves of Azure Reveries');
INSERT INTO boss_loot VALUES (121,'Sword of Curiosity');
INSERT INTO boss_loot VALUES (121,'Sword of Wonder');
INSERT INTO boss_loot VALUES (121,'Suzerain''s Political Chief Headwear');
INSERT INTO boss_loot VALUES (122,'Spirit Training Program');
INSERT INTO boss_loot VALUES (123,'Comfort of the Sagittarius');
INSERT INTO boss_loot VALUES (123,'First Creation of the Sagittarius');
INSERT INTO boss_loot VALUES (123,'Sagittarius''s Hearty Spirit Helper');
INSERT INTO boss_loot VALUES (123,'Strong Mittens of the Sagittarius');
INSERT INTO boss_loot VALUES (124,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (124,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (124,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (124,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (124,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (124,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (124,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (125,'Short Circuited Spiritech Circlet');
INSERT INTO boss_loot VALUES (126,'Punters of the Scorpio');
INSERT INTO boss_loot VALUES (126,'Sash of Scorpio Strength');
INSERT INTO boss_loot VALUES (126,'Scorpio''s Aim of Anger');
INSERT INTO boss_loot VALUES (126,'Scorpio''s Shell of Change');
INSERT INTO boss_loot VALUES (127,'Taurus'' Spirit of Patience');
INSERT INTO boss_loot VALUES (127,'JAME Blaster Prototype XII');
INSERT INTO boss_loot VALUES (127,'JAME Blaster Prototype IV');
INSERT INTO boss_loot VALUES (127,'Heavy Bracer');
INSERT INTO boss_loot VALUES (128,'Elysian Protector''s Cuirass');
INSERT INTO boss_loot VALUES (128,'Focus-Funneling Spirit');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (129,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (130,'Headband of Haste');
INSERT INTO boss_loot VALUES (130,'JAME Blaster Prototype IV');
INSERT INTO boss_loot VALUES (130,'JAME Blaster Prototype XII');
INSERT INTO boss_loot VALUES (131,'Crackerjack Sleeves');
INSERT INTO boss_loot VALUES (131,'Ring of Herodotus');
INSERT INTO boss_loot VALUES (131,'Headband of Haste');
INSERT INTO boss_loot VALUES (132,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (132,'Superior Skylight Shield');
INSERT INTO boss_loot VALUES (133,'Repair Coordination Assistant');
INSERT INTO boss_loot VALUES (134,'Solid Spiritech Mesh');
INSERT INTO boss_loot VALUES (134,'JAME Blaster Prototype IV');
INSERT INTO boss_loot VALUES (134,'JAME Blaster Prototype XII');
INSERT INTO boss_loot VALUES (135,'Chain of Concealment');
INSERT INTO boss_loot VALUES (135,'NanoCrystal (Resonance Blast)');
INSERT INTO boss_loot VALUES (135,'The HSR Detective');
INSERT INTO boss_loot VALUES (136,'Scimitar of Spetses');
INSERT INTO boss_loot VALUES (136,'Sparkling Scimitar of Spetses');
INSERT INTO boss_loot VALUES (137,'Cure for Baldness');
INSERT INTO boss_loot VALUES (138,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (139,'Penumbra Tuaq');
INSERT INTO boss_loot VALUES (140,'Blue Baby Bronto Boots');
INSERT INTO boss_loot VALUES (141,'Superior Sentinel Armor Boots');
INSERT INTO boss_loot VALUES (141,'Superior Sentinel Armor Gloves');
INSERT INTO boss_loot VALUES (141,'Superior Sentinel Armor Helmet');
INSERT INTO boss_loot VALUES (141,'Superior Sentinel Armor Pants');
INSERT INTO boss_loot VALUES (141,'Superior Sentinel Armor Sleeves');
INSERT INTO boss_loot VALUES (141,'Superior Sentinel Body Armor');
INSERT INTO boss_loot VALUES (142,'Omni-Armed Forces Armor');
INSERT INTO boss_loot VALUES (142,'Omni-Armed Forces Boots');
INSERT INTO boss_loot VALUES (142,'Omni-Armed Forces Gloves');
INSERT INTO boss_loot VALUES (142,'Omni-Armed Forces Helmet');
INSERT INTO boss_loot VALUES (142,'Omni-Armed Forces Pants');
INSERT INTO boss_loot VALUES (142,'Omni-Armed Forces Sleeves');
INSERT INTO boss_loot VALUES (143,'Eremite Macro Sensor');
INSERT INTO boss_loot VALUES (143,'Eremite Micro Sensor');
INSERT INTO boss_loot VALUES (143,'Eremite Psychic Sensor');
INSERT INTO boss_loot VALUES (144,'HUD Upgrade: Enhanced Target Acquisition');
INSERT INTO boss_loot VALUES (144,'HUD Upgrade: Personal S.T.M');
INSERT INTO boss_loot VALUES (145,'Aura Magnifier');
INSERT INTO boss_loot VALUES (145,'Cloak of the Wandering Knight');
INSERT INTO boss_loot VALUES (145,'Gaily Painted Hood');
INSERT INTO boss_loot VALUES (145,'Globe of Clarity');
INSERT INTO boss_loot VALUES (145,'Globe of Sufferance');
INSERT INTO boss_loot VALUES (145,'Heavily Padded Overcoat');
INSERT INTO boss_loot VALUES (145,'The Heavy-Headed Staff');
INSERT INTO boss_loot VALUES (145,'Hollow Bone Bracer of Merlin Ambrosius');
INSERT INTO boss_loot VALUES (145,'Chunk of Living Dragon Flesh');
INSERT INTO boss_loot VALUES (145,'Lump of Living Dragon Marrow');
INSERT INTO boss_loot VALUES (145,'Patch of Living Dragon Skin');
INSERT INTO boss_loot VALUES (145,'Piece of Living Dragon Wing');
INSERT INTO boss_loot VALUES (145,'Shard of Living Dragon Skull');
INSERT INTO boss_loot VALUES (145,'Heart of Tarasque');
INSERT INTO boss_loot VALUES (145,'Gall Stone');
INSERT INTO boss_loot VALUES (145,'Robust Backpack');
INSERT INTO boss_loot VALUES (145,'Signet Ring of the Green Knight');
INSERT INTO boss_loot VALUES (145,'Sinew of Tarasque');
INSERT INTO boss_loot VALUES (145,'Smart Hood of the Wanderer');
INSERT INTO boss_loot VALUES (145,'Smelly Butcher Gloves');
INSERT INTO boss_loot VALUES (145,'Edge of the Tarasque');
INSERT INTO boss_loot VALUES (145,'Typical Dragon Tooth Poker');
INSERT INTO boss_loot VALUES (146,'Taurus'' Ring of the Heart');
INSERT INTO boss_loot VALUES (146,'Taurus'' Spirit of Patience');
INSERT INTO boss_loot VALUES (146,'Taurus'' Spirit of Reflection');
INSERT INTO boss_loot VALUES (146,'Taurus'' Swordmaster Spirit');
INSERT INTO boss_loot VALUES (147,'Spirit Ring of Self-Education');
INSERT INTO boss_loot VALUES (147,'Spirit Training Program');
INSERT INTO boss_loot VALUES (148,'Armplates of Elimination');
INSERT INTO boss_loot VALUES (148,'Boots of Concourse');
INSERT INTO boss_loot VALUES (148,'Burden of Competence');
INSERT INTO boss_loot VALUES (148,'Cuirass of Obstinacy');
INSERT INTO boss_loot VALUES (148,'Gauntlets of Deformation');
INSERT INTO boss_loot VALUES (148,'Greaves of Malfeasance');
INSERT INTO boss_loot VALUES (148,'Helmet of Hypocrisy');
INSERT INTO boss_loot VALUES (148,'Shoulderplates of Sabotage');
INSERT INTO boss_loot VALUES (148,'Sigil of Bahomet');
INSERT INTO boss_loot VALUES (148,'Sleeves of Senseless Violence');
INSERT INTO boss_loot VALUES (148,'Star of Ardency');
INSERT INTO boss_loot VALUES (148,'Star of Enterprice');
INSERT INTO boss_loot VALUES (148,'Star of Enticement');
INSERT INTO boss_loot VALUES (148,'Star of Equanimity');
INSERT INTO boss_loot VALUES (148,'Star of Faith');
INSERT INTO boss_loot VALUES (148,'Star of Fidelity');
INSERT INTO boss_loot VALUES (148,'Star of Fortitude');
INSERT INTO boss_loot VALUES (148,'Star of Freedom');
INSERT INTO boss_loot VALUES (148,'Star of Ingenuity');
INSERT INTO boss_loot VALUES (148,'Star of Interchange');
INSERT INTO boss_loot VALUES (148,'Star of Management');
INSERT INTO boss_loot VALUES (148,'Star of Moral');
INSERT INTO boss_loot VALUES (148,'Star of Recovery');
INSERT INTO boss_loot VALUES (148,'Star of Stealth');
INSERT INTO boss_loot VALUES (148,'Sunrise Hilt');
INSERT INTO boss_loot VALUES (148,'Sunset Hilt');
INSERT INTO boss_loot VALUES (148,'Lady of Abandonment');
INSERT INTO boss_loot VALUES (148,'Lady of Hatred');
INSERT INTO boss_loot VALUES (148,'Lady of Deceit');
INSERT INTO boss_loot VALUES (148,'Lady of Pride');
INSERT INTO boss_loot VALUES (148,'Lady of Gluttony');
INSERT INTO boss_loot VALUES (148,'Lady of Anger');
INSERT INTO boss_loot VALUES (148,'Lady of Angst');
INSERT INTO boss_loot VALUES (148,'Lady of Envy');
INSERT INTO boss_loot VALUES (148,'Lady of Greed');
INSERT INTO boss_loot VALUES (148,'Lady of Chaos');
INSERT INTO boss_loot VALUES (148,'Lady of Sloth');
INSERT INTO boss_loot VALUES (148,'Lady of Lust');
INSERT INTO boss_loot VALUES (148,'Lord of Abandonment');
INSERT INTO boss_loot VALUES (148,'Lady of Hatred');
INSERT INTO boss_loot VALUES (148,'Lady of Deceit');
INSERT INTO boss_loot VALUES (148,'Lady of Pride');
INSERT INTO boss_loot VALUES (148,'Lady of Gluttony');
INSERT INTO boss_loot VALUES (148,'Lady of Anger');
INSERT INTO boss_loot VALUES (148,'Lady of Angst');
INSERT INTO boss_loot VALUES (148,'Lady of Envy');
INSERT INTO boss_loot VALUES (148,'Lady of Greed');
INSERT INTO boss_loot VALUES (148,'Lady of Chaos');
INSERT INTO boss_loot VALUES (148,'Lady of Sloth');
INSERT INTO boss_loot VALUES (148,'Lady of Lust');
INSERT INTO boss_loot VALUES (148,'High Lord of Angst');
INSERT INTO boss_loot VALUES (149,'Maar''s Blue Belt of Double Prudence');
INSERT INTO boss_loot VALUES (149,'Maar''s Red Belt of Double Power');
INSERT INTO boss_loot VALUES (149,'Maar''s Yellow Belt of Double Speed');
INSERT INTO boss_loot VALUES (149,'Notum Seed');
INSERT INTO boss_loot VALUES (149,'Novictum Seed');
INSERT INTO boss_loot VALUES (150,'Contained Anti-Matter Generator');
INSERT INTO boss_loot VALUES (150,'NanoCrystal (Shield of the Obedient Servant)');
INSERT INTO boss_loot VALUES (150,'Punishment Rod');
INSERT INTO boss_loot VALUES (150,'Slayerdroid Claw');
INSERT INTO boss_loot VALUES (151,'Breastplate of Spiritual Rites');
INSERT INTO boss_loot VALUES (151,'Breastplate of Technical Ceremonies');
INSERT INTO boss_loot VALUES (151,'Helmet of Spiritual Rites');
INSERT INTO boss_loot VALUES (151,'Helmet of Technical Ceremonies');
INSERT INTO boss_loot VALUES (152,'Left Sleeves of the Pest');
INSERT INTO boss_loot VALUES (152,'NanoCrystal (Corruption of The Pest)');
INSERT INTO boss_loot VALUES (152,'NanoCrystal (Lick of the Pest)');
INSERT INTO boss_loot VALUES (152,'Patch of Pest');
INSERT INTO boss_loot VALUES (152,'Petticoat of Pest');
INSERT INTO boss_loot VALUES (152,'Right Sleeves of the Pest');
INSERT INTO boss_loot VALUES (153,'Ring of Burning Flesh');
INSERT INTO boss_loot VALUES (154,'Joy of the Hunt');
INSERT INTO boss_loot VALUES (154,'Joy of the Race');
INSERT INTO boss_loot VALUES (154,'Killer''s Armor Trousers');
INSERT INTO boss_loot VALUES (154,'Killer''s Armor Sleeve');
INSERT INTO boss_loot VALUES (154,'Sombreous Arm Tattoo''s');
INSERT INTO boss_loot VALUES (155,'Sleeves of Boiling Blood');
INSERT INTO boss_loot VALUES (156,'Neural Interpreting Nball - Melee fighting');
INSERT INTO boss_loot VALUES (157,'Corroded Ring');
INSERT INTO boss_loot VALUES (158,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (158,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (158,'Copy of The Excalibur');
INSERT INTO boss_loot VALUES (158,'Exact Copy of The Excalibur');
INSERT INTO boss_loot VALUES (158,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (158,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (158,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (158,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (158,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (159,'Finely Refined Notum');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (160,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (160,'Lava capsule');
INSERT INTO boss_loot VALUES (161,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (161,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (161,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (161,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (161,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (161,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (161,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (162,'Virgo''s Analytical Spirit Helper');
INSERT INTO boss_loot VALUES (162,'Virgo''s Arrow Guide');
INSERT INTO boss_loot VALUES (162,'Virgo''s Modest Spirit of Faith');
INSERT INTO boss_loot VALUES (162,'Virgo''s Practical Spirit Helper');
INSERT INTO boss_loot VALUES (163,'Problem Avoiding Device');
INSERT INTO boss_loot VALUES (163,'Problem Seeking Device');
INSERT INTO boss_loot VALUES (163,'Problem Solving Device');
INSERT INTO boss_loot VALUES (164,'Predator Armband');
INSERT INTO boss_loot VALUES (164,'Predator Armor Boots');
INSERT INTO boss_loot VALUES (164,'Predator Armor Facemask');
INSERT INTO boss_loot VALUES (164,'Predator Armor Gloves');
INSERT INTO boss_loot VALUES (164,'Predator Armor Pants');
INSERT INTO boss_loot VALUES (164,'Predator Armor Vest');
INSERT INTO boss_loot VALUES (164,'Predator''s Circlet');
INSERT INTO boss_loot VALUES (165,'Spirit Ring of Self-Education');
INSERT INTO boss_loot VALUES (165,'Spirit Training Program');
INSERT INTO boss_loot VALUES (166,'Xark''s Whisker');
INSERT INTO boss_loot VALUES (167,'Gelid Blade of Inobak');
INSERT INTO boss_loot VALUES (167,'Frost Shard');
INSERT INTO boss_loot VALUES (168,'Permafrost');
INSERT INTO boss_loot VALUES (168,'Abyssal Desecrator');
INSERT INTO boss_loot VALUES (168,'Impious Dominator');
INSERT INTO boss_loot VALUES (168,'Ichor of the Immortal One');
INSERT INTO boss_loot VALUES (168,'Ichor of the Immortal One');
INSERT INTO boss_loot VALUES (168,'Mnemonic Fragment');
INSERT INTO boss_loot VALUES (168,'Constrained Gridspace Waveform');
INSERT INTO boss_loot VALUES (168,'Bloodseal of the Infernal Tyrant');
INSERT INTO boss_loot VALUES (168,'Charred Abaddon Chassis');
INSERT INTO boss_loot VALUES (168,'Third Circle of the Inner Sanctum');
INSERT INTO boss_loot VALUES (169,'Might of the Revenant');
INSERT INTO boss_loot VALUES (169,'Bloodseal of the Infernal Tyrant');
INSERT INTO boss_loot VALUES (169,'Mnemonic Fragment');
INSERT INTO boss_loot VALUES (170,'Corrupted Flesh');
INSERT INTO boss_loot VALUES (170,'Mnemonic Fragment');
INSERT INTO boss_loot VALUES (170,'Skull of Misery');
INSERT INTO boss_loot VALUES (170,'Skull of Despair');
INSERT INTO boss_loot VALUES (170,'Ring of Putrescent Flesh');
INSERT INTO boss_loot VALUES (170,'Teachings of the Immortal One');
INSERT INTO boss_loot VALUES (170,'Charred Abaddon Chassis');
INSERT INTO boss_loot VALUES (170,'Third Circle of the Inner Sanctum');
INSERT INTO boss_loot VALUES (171,'Might of the Revenant');
INSERT INTO boss_loot VALUES (171,'Mnemonic Fragment');
INSERT INTO boss_loot VALUES (171,'Abaddon Upgrade: Skill');
INSERT INTO boss_loot VALUES (172,'Maw of the Abyss');
INSERT INTO boss_loot VALUES (172,'Frost-bound Reaper');
INSERT INTO boss_loot VALUES (172,'Jeuru''s Oscillating Ligature');
INSERT INTO boss_loot VALUES (172,'Bloodshed Armband');
INSERT INTO boss_loot VALUES (172,'Inner Sanctum Knowledge (bottom half of key)');
INSERT INTO boss_loot VALUES (172,'Second Circle of the Inner Sanctum');
INSERT INTO boss_loot VALUES (172,'Charred Abaddon Chassis');
INSERT INTO boss_loot VALUES (173,'Inner Sanctum Knowledge (top half of key)');
INSERT INTO boss_loot VALUES (173,'Maw of the Abyss');
INSERT INTO boss_loot VALUES (173,'Frost-bound Reaper');
INSERT INTO boss_loot VALUES (173,'Jeuru''s Oscillating Ligature');
INSERT INTO boss_loot VALUES (173,'Bloodshed Armband');
INSERT INTO boss_loot VALUES (173,'Second Circle of the Inner Sanctum');
INSERT INTO boss_loot VALUES (173,'Charred Abaddon Chassis');
INSERT INTO boss_loot VALUES (174,'JAME Blaster Prototype IV');
INSERT INTO boss_loot VALUES (174,'JAME Blaster Prototype XII');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (175,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (175,'Codex Clavis');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (176,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (177,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (178,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (179,'Metal Armlet of the Quartet');
INSERT INTO boss_loot VALUES (180,'Truspace 900 XL - Vision');
INSERT INTO boss_loot VALUES (181,'Snake Tamer Shield');
INSERT INTO boss_loot VALUES (181,'Snake Tamer Guard');
INSERT INTO boss_loot VALUES (182,'Liquid Notum Ring');
INSERT INTO boss_loot VALUES (182,'Nelly''s Chip');
INSERT INTO boss_loot VALUES (183,'Remains of AESA 10');
INSERT INTO boss_loot VALUES (183,'Soft Ring with Fluff');
INSERT INTO boss_loot VALUES (184,'Notum Miner''s Hard Hat');
INSERT INTO boss_loot VALUES (184,'Glimmering Magnetic Ring');
INSERT INTO boss_loot VALUES (185,'Luminous Copper Band');
INSERT INTO boss_loot VALUES (185,'Crystalized Medusa Queen Hippocampus');
INSERT INTO boss_loot VALUES (185,'Mutated Eremite Leg');
INSERT INTO boss_loot VALUES (186,'Ring of the Endless Depths');
INSERT INTO boss_loot VALUES (186,'Lion''s Leather Vest');
INSERT INTO boss_loot VALUES (186,'Lion''s Leather Sleeve');
INSERT INTO boss_loot VALUES (186,'Lion''s Leather Gloves');
INSERT INTO boss_loot VALUES (186,'Lion''s Leather Pants');
INSERT INTO boss_loot VALUES (186,'Lion''s Leather Boots');
INSERT INTO boss_loot VALUES (186,'Thick Leather Wristbands');
INSERT INTO boss_loot VALUES (187,'I am the Eel');
INSERT INTO boss_loot VALUES (187,'Suzerain''s Spiritual Chief Headwear');
INSERT INTO boss_loot VALUES (188,'I am the Bear');
INSERT INTO boss_loot VALUES (188,'Gurgling River Sprite');
INSERT INTO boss_loot VALUES (188,'Expensive Gift from Earth');
INSERT INTO boss_loot VALUES (188,'Suzerain''s Military Chief Headwear');
INSERT INTO boss_loot VALUES (188,'Disco Duck Sunglasses');
INSERT INTO boss_loot VALUES (188,'Funk Flamingo Sunglasses');
INSERT INTO boss_loot VALUES (188,'Electric Boogie Sunglasses');
INSERT INTO boss_loot VALUES (189,'I am the Owl');
INSERT INTO boss_loot VALUES (189,'Advanced Nano Breed Survival Headwear');
INSERT INTO boss_loot VALUES (189,'Chip of the Eight');
INSERT INTO boss_loot VALUES (189,'Suzerain''s Political Chief Headwear');
INSERT INTO boss_loot VALUES (190,'Mutated Eremite Foetus');
INSERT INTO boss_loot VALUES (190,'Smooth Gold Alloy Ring');
INSERT INTO boss_loot VALUES (190,'Lion''s Leather Vest');
INSERT INTO boss_loot VALUES (190,'Lion''s Leather Sleeve');
INSERT INTO boss_loot VALUES (190,'Lion''s Leather Gloves');
INSERT INTO boss_loot VALUES (190,'Lion''s Leather Pants');
INSERT INTO boss_loot VALUES (190,'Lion''s Leather Boots');
INSERT INTO boss_loot VALUES (191,'Hammered Gold Ring');
INSERT INTO boss_loot VALUES (192,'Clan Ring of Salvation');
INSERT INTO boss_loot VALUES (192,'Brood Champion Gauntlets');
INSERT INTO boss_loot VALUES (193,'Professional Marksman''s Kit');
INSERT INTO boss_loot VALUES (193,'Lion''s Leather Vest');
INSERT INTO boss_loot VALUES (193,'Lion''s Leather Sleeve');
INSERT INTO boss_loot VALUES (193,'Lion''s Leather Gloves');
INSERT INTO boss_loot VALUES (193,'Lion''s Leather Pants');
INSERT INTO boss_loot VALUES (193,'Lion''s Leather Boots');
INSERT INTO boss_loot VALUES (194,'Silly Ring');
INSERT INTO boss_loot VALUES (194,'Beefeater''s Merit Board');
INSERT INTO boss_loot VALUES (194,'Captain Lotto''s Merit Board');
INSERT INTO boss_loot VALUES (194,'Omni-Tek Nano Reservoire Merit Board');
INSERT INTO boss_loot VALUES (194,'Merit Board of the Angry Men');
INSERT INTO boss_loot VALUES (194,'Standard Clan Leader Merit Board');
INSERT INTO boss_loot VALUES (194,'Technocrat Merit Board');
INSERT INTO boss_loot VALUES (194,'Merit Board of the Long Distance Runner');
INSERT INTO boss_loot VALUES (194,'Messenger Merit Board');
INSERT INTO boss_loot VALUES (194,'Front Fighter Merit Board');
INSERT INTO boss_loot VALUES (194,'Omni-Tek Shock Trooper Merit Board');
INSERT INTO boss_loot VALUES (194,'Omni-Tek Engineer Corps Merit Board');
INSERT INTO boss_loot VALUES (194,'Merit Board of the Blue Wolf');
INSERT INTO boss_loot VALUES (194,'Merit Board of the Rainbow Chrysanthemum');
INSERT INTO boss_loot VALUES (194,'Metal Fungus Merit Board');
INSERT INTO boss_loot VALUES (194,'Fly Catcher''s Specs');
INSERT INTO boss_loot VALUES (194,'Profiteer''s Helper');
INSERT INTO boss_loot VALUES (194,'The Argument');
INSERT INTO boss_loot VALUES (195,'Cold Snakeskin Sleeve');
INSERT INTO boss_loot VALUES (195,'Philosophical Slither Larvae');
INSERT INTO boss_loot VALUES (196,'Brumal Chest Symbiant of Endurance');
INSERT INTO boss_loot VALUES (197,'Philosophical Slither Larvae');
INSERT INTO boss_loot VALUES (198,'Cold Snakeskin Sleeve');
INSERT INTO boss_loot VALUES (199,'Nippy John Stiletto');
INSERT INTO boss_loot VALUES (200,'Sleeves of Gashing');
INSERT INTO boss_loot VALUES (201,'Ring of Something Extra');
INSERT INTO boss_loot VALUES (202,'Impudent Bracer');
INSERT INTO boss_loot VALUES (203,'Tiny Spider Band');
INSERT INTO boss_loot VALUES (203,'Tiny Spider Band');
INSERT INTO boss_loot VALUES (203,'Tiny Spider Band');
INSERT INTO boss_loot VALUES (204,'Bracelet of Theory');
INSERT INTO boss_loot VALUES (205,'Spirit of Saccelum');
INSERT INTO boss_loot VALUES (206,'Silken Legchopper Gloves');
INSERT INTO boss_loot VALUES (206,'This Axe Belongs to Jack');
INSERT INTO boss_loot VALUES (206,'Supporting Carbonan Holster');
INSERT INTO boss_loot VALUES (206,'Band of Beeswax');
INSERT INTO boss_loot VALUES (206,'Band of Dog Molars');
INSERT INTO boss_loot VALUES (206,'Band of Snake Skin');
INSERT INTO boss_loot VALUES (206,'Band of the Bear Claw');
INSERT INTO boss_loot VALUES (206,'Band of the Frog Tongue');
INSERT INTO boss_loot VALUES (206,'Curl of Weasel Whiskers');
INSERT INTO boss_loot VALUES (206,'Ring of Crawling Ants');
INSERT INTO boss_loot VALUES (206,'Ring of Magpie Tail Feathers');
INSERT INTO boss_loot VALUES (206,'Ring of the Dolphin Spine');
INSERT INTO boss_loot VALUES (206,'Ring of the Falcon Talon');
INSERT INTO boss_loot VALUES (206,'Ring of the Monkey Tail');
INSERT INTO boss_loot VALUES (206,'Ringlet of Black Panther Whiskers');
INSERT INTO boss_loot VALUES (207,'Communication Processing Unit Rack with 8 Empty Slots');
INSERT INTO boss_loot VALUES (207,'Communication Processing Unit ID=TKL');
INSERT INTO boss_loot VALUES (207,'Plaster Circuit - Brawl');
INSERT INTO boss_loot VALUES (207,'Reinforced NCU Component Belt');
INSERT INTO boss_loot VALUES (207,'Cold Ray Orb');
INSERT INTO boss_loot VALUES (207,'Superior Cold Ray Orb');
INSERT INTO boss_loot VALUES (209,'Fork of Ghasap (Lord Version)');
INSERT INTO boss_loot VALUES (209,'Corroded Blade');
INSERT INTO boss_loot VALUES (209,'Dreadful Pitchfork');
INSERT INTO boss_loot VALUES (209,'Corroded Ring');
INSERT INTO boss_loot VALUES (209,'Pattern of Inevitable Death');
INSERT INTO boss_loot VALUES (209,'Pattern of Imminent Death');
INSERT INTO boss_loot VALUES (210,'Ring of the Nucleus Basalis');
INSERT INTO boss_loot VALUES (211,'Ring of the Nucleus Basalis');
INSERT INTO boss_loot VALUES (212,'Ring of the Nucleus Basalis');
INSERT INTO boss_loot VALUES (212,'Belt of Justice');
INSERT INTO boss_loot VALUES (212,'Juggler''s Treat');
INSERT INTO boss_loot VALUES (213,'Severus'' Fusion Sprayer');
INSERT INTO boss_loot VALUES (213,'Severus'' Void Spinner');
INSERT INTO boss_loot VALUES (214,'Bastion of Deimos');
INSERT INTO boss_loot VALUES (214,'Deimos'' Bio-Enhanced Feedback Rifle');
INSERT INTO boss_loot VALUES (215,'Force-effect Vibro Blade');
INSERT INTO boss_loot VALUES (216,'Hellfury Assault Cannon');
INSERT INTO boss_loot VALUES (217,'Hellspinner Shock Cannon');
INSERT INTO boss_loot VALUES (217,'Augmented Cyborg Arm Armor');
INSERT INTO boss_loot VALUES (217,'Augmented Cyborg Boots');
INSERT INTO boss_loot VALUES (217,'Augmented Cyborg Chest Armor');
INSERT INTO boss_loot VALUES (217,'Augmented Cyborg Gloves');
INSERT INTO boss_loot VALUES (217,'Augmented Cyborg Helmet');
INSERT INTO boss_loot VALUES (217,'Augmented Cyborg Leg Armor');
INSERT INTO boss_loot VALUES (218,'Augmented Cyborg Arm Armor');
INSERT INTO boss_loot VALUES (218,'Augmented Cyborg Boots');
INSERT INTO boss_loot VALUES (218,'Augmented Cyborg Chest Armor');
INSERT INTO boss_loot VALUES (218,'Augmented Cyborg Gloves');
INSERT INTO boss_loot VALUES (218,'Augmented Cyborg Helmet');
INSERT INTO boss_loot VALUES (218,'Augmented Cyborg Leg Armor');
INSERT INTO boss_loot VALUES (218,'Immortal Katana');
INSERT INTO boss_loot VALUES (218,'Faded Immortal Katana');
INSERT INTO boss_loot VALUES (218,'Broken Immortal Katana');
INSERT INTO boss_loot VALUES (218,'Improved Immortal Katana');
INSERT INTO boss_loot VALUES (218,'Bonehammer');
INSERT INTO boss_loot VALUES (218,'Internal Anti-Matter Powerplant');
INSERT INTO boss_loot VALUES (218,'Sub-Dermal Vengeance Screen (Left Hand)');
INSERT INTO boss_loot VALUES (218,'Sub-Dermal Vengeance Screen (Right Hand)');
INSERT INTO boss_loot VALUES (219,'Notum Splice');
INSERT INTO boss_loot VALUES (219,'Ring of Eternal Night');
INSERT INTO boss_loot VALUES (220,'Touch of the Gripper');
INSERT INTO boss_loot VALUES (220,'Rockcrusher Gauntlets');
INSERT INTO boss_loot VALUES (221,'Touch of the Gripper');
INSERT INTO boss_loot VALUES (221,'Nematet''s Inner Eye');
INSERT INTO boss_loot VALUES (221,'Ring of Weeping Flesh');
INSERT INTO boss_loot VALUES (221,'Ring of Eternal Night');
INSERT INTO boss_loot VALUES (221,'Temporal Chalice');
INSERT INTO boss_loot VALUES (221,'Barrow Strength');
INSERT INTO boss_loot VALUES (222,'Withered Flesh');
INSERT INTO boss_loot VALUES (222,'Skull of Woe');
INSERT INTO boss_loot VALUES (222,'Barrow Strength');
INSERT INTO boss_loot VALUES (223,'Dark Memories');
INSERT INTO boss_loot VALUES (223,'Memory Loop');
INSERT INTO boss_loot VALUES (223,'Temporal Chalice');
INSERT INTO boss_loot VALUES (223,'Skull of Woe');
INSERT INTO boss_loot VALUES (223,'Skull of Lamentation');
INSERT INTO boss_loot VALUES (223,'Barrow Strength');
INSERT INTO boss_loot VALUES (223,'Ring of Eternal Night');
INSERT INTO boss_loot VALUES (223,'Ring of Memory Loss');
INSERT INTO boss_loot VALUES (224,'Guardian Tank Armor');
INSERT INTO boss_loot VALUES (224,'Guardian Circuit Board');
INSERT INTO boss_loot VALUES (224,'Bracelet of Amplified Sound');
INSERT INTO boss_loot VALUES (224,'Ring of Tattered Flame');
INSERT INTO boss_loot VALUES (225,'Purifying Rod');
INSERT INTO boss_loot VALUES (225,'Fist of Orion');
INSERT INTO boss_loot VALUES (225,'Withered Flesh');
INSERT INTO boss_loot VALUES (225,'Barrow Strength');
INSERT INTO boss_loot VALUES (226,'Stygian Desolator');
INSERT INTO boss_loot VALUES (226,'Purifying Rod');
INSERT INTO boss_loot VALUES (226,'Skull of the Ancient');
INSERT INTO boss_loot VALUES (226,'Holy Book of the Immortal');
INSERT INTO boss_loot VALUES (227,'Keeper''s Vitality');
INSERT INTO boss_loot VALUES (228,'Windcaller Robe');
INSERT INTO boss_loot VALUES (228,'Withered Flesh');
INSERT INTO boss_loot VALUES (228,'Barrow Strength');
INSERT INTO boss_loot VALUES (229,'Small Titan Message Container');
INSERT INTO boss_loot VALUES (229,'FA Super 90 Pannikin');
INSERT INTO boss_loot VALUES (231,'Piercing Evil');
INSERT INTO boss_loot VALUES (232,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (232,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (234,'Bigot''s Armband of Sacrifice');
INSERT INTO boss_loot VALUES (234,'Bigot''s Earring of Sacrifice');
INSERT INTO boss_loot VALUES (235,'Bigot''s Earring of Sacrifice');
INSERT INTO boss_loot VALUES (237,'Spirit Tech Toolbox');
INSERT INTO boss_loot VALUES (238,'Malodorous Ring');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (239,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (240,'Mark of the Fisher King');
INSERT INTO boss_loot VALUES (240,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (241,'Curse of Malahde');
INSERT INTO boss_loot VALUES (242,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (243,'Gallant Flapper Ribbon');
INSERT INTO boss_loot VALUES (244,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (245,'Shopkeeper''s Sharkskin Sleeves');
INSERT INTO boss_loot VALUES (246,'Boots of the Imaginative');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Armor Boots');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Armor Gloves');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Armor Helmet');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Armor Sleeves');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Body Armor');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Coat');
INSERT INTO boss_loot VALUES (248,'Bellum Badonis Shoulderpads');
INSERT INTO boss_loot VALUES (249,'Apprehensive Spirit Pitcher');
INSERT INTO boss_loot VALUES (250,'The Sacrificed Bracelet of Kay');
INSERT INTO boss_loot VALUES (251,'Barrel of Bacam-Xum');
INSERT INTO boss_loot VALUES (252,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (252,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (252,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (252,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (253,'Mudurlugu');
INSERT INTO boss_loot VALUES (254,'Stinging Louse');
INSERT INTO boss_loot VALUES (255,'Overcoat of the Firmament');
INSERT INTO boss_loot VALUES (255,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (255,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (255,'Copy of The Excalibur');
INSERT INTO boss_loot VALUES (255,'Exact Copy of The Excalibur');
INSERT INTO boss_loot VALUES (256,'Amused Spirit');
INSERT INTO boss_loot VALUES (256,'Boots of Stolen Comet Speed');
INSERT INTO boss_loot VALUES (256,'Pernicious Body Armor');
INSERT INTO boss_loot VALUES (257,'Vest of Torpid Sunrays');
INSERT INTO boss_loot VALUES (257,'Armplates of Meteorite Assembly');
INSERT INTO boss_loot VALUES (257,'Moon Watcher Helmet');
INSERT INTO boss_loot VALUES (257,'Shoulderpads of Asteroid Calling');
INSERT INTO boss_loot VALUES (257,'Gauntlets of Star Confabulation');
INSERT INTO boss_loot VALUES (258,'Base NCU - Type 00 (0/6)');
INSERT INTO boss_loot VALUES (258,'Nanodeck Activation Device');
INSERT INTO boss_loot VALUES (258,'Multi Colored Xan Belt Tuning Device');
INSERT INTO boss_loot VALUES (258,'Green Xan Belt Tuning Device');
INSERT INTO boss_loot VALUES (258,'Xan Weapon Upgrade Device');
INSERT INTO boss_loot VALUES (258,'Xan Defense Merit Board Base');
INSERT INTO boss_loot VALUES (258,'Xan Combat Merit Board Base');
INSERT INTO boss_loot VALUES (258,'Xan Waist Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Waist Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Waist Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Waist Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Waist Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Arm Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Arm Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Arm Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Arm Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Arm Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Right Wrist Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Right Wrist Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Right Wrist Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Right Wrist Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Right Wrist Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Ocular Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Ocular Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Ocular Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Ocular Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Ocular Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (258,'Xan Spirit of Right Wrist Offence - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Spirit of Right Wrist Weakness - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Limb Spirit of Essence - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Limb Spirit of Strength - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Limb Spirit of Understanding - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Left Limb Spirit of Weakness - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Midriff Spirit of Essence - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Midriff Spirit of Knowledge - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Midriff Spirit of Strength - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Midriff Spirit of Weakness - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Spirit of Essence - Beta');
INSERT INTO boss_loot VALUES (258,'Xan Spirit of Discerning Weakness - Beta');
INSERT INTO boss_loot VALUES (259,'Base NCU - Type 00 (0/6)');
INSERT INTO boss_loot VALUES (259,'Nanodeck Activation Device');
INSERT INTO boss_loot VALUES (259,'Multi Colored Xan Belt Tuning Device');
INSERT INTO boss_loot VALUES (259,'Green Xan Belt Tuning Device');
INSERT INTO boss_loot VALUES (259,'Xan Weapon Upgrade Device');
INSERT INTO boss_loot VALUES (259,'Xan Defense Merit Board Base');
INSERT INTO boss_loot VALUES (259,'Xan Combat Merit Board Base');
INSERT INTO boss_loot VALUES (259,'Xan Brain Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Brain Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Brain Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Brain Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Brain Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Chest Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Chest Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Chest Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Chest Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Chest Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Wrist Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Wrist Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Wrist Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Wrist Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Wrist Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (259,'Xan Brain Spirit of Computer Skill - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Brain Spirit of Offence - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Essence Brain Spirit - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Spirit of Defence - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Left Hand Spirit of Strength - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Spirit of Left Wrist Defense - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Spirit of Left Wrist Strength - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Heart Spirit of Essence - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Heart Spirit of Knowledge - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Heart Spirit of Strength - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Heart Spirit of Weakness - Beta');
INSERT INTO boss_loot VALUES (259,'Xan Spirit of Clear Thought - Beta');
INSERT INTO boss_loot VALUES (260,'Unknown Mixture');
INSERT INTO boss_loot VALUES (260,'A piece of cloth');
INSERT INTO boss_loot VALUES (260,'Base NCU - Type 00 (0/6)');
INSERT INTO boss_loot VALUES (260,'Nanodeck Activation Device');
INSERT INTO boss_loot VALUES (260,'Multi Colored Xan Belt Tuning Device');
INSERT INTO boss_loot VALUES (260,'Green Xan Belt Tuning Device');
INSERT INTO boss_loot VALUES (260,'Xan Weapon Upgrade Device');
INSERT INTO boss_loot VALUES (260,'Xan Right Arm Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Arm Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Arm Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Arm Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Arm Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Feet Symbiant, Artillery Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Feet Symbiant, Control Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Feet Symbiant, Extermination Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Feet Symbiant, Infantry Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Feet Symbiant, Support Unit Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Limb Spirit of Essence - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Limb Spirit of Strength - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Limb Spirit of Weakness - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Defensive Spirit - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Right Hand Strength Spirit - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Insight - Right Hand - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Feet Defense - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Feet Strength - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Defense - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Essence - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Essence Whispered - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Knowledge Whispered - Beta');
INSERT INTO boss_loot VALUES (260,'Xan Spirit of Strength Whispered - Beta');
INSERT INTO boss_loot VALUES (260,'Brute''s Gem');
INSERT INTO boss_loot VALUES (260,'Builder''s Gem');
INSERT INTO boss_loot VALUES (260,'Dictator''s Gem');
INSERT INTO boss_loot VALUES (260,'Explorer''s Gem');
INSERT INTO boss_loot VALUES (260,'Hacker''s Gem');
INSERT INTO boss_loot VALUES (260,'Healer''s Gem');
INSERT INTO boss_loot VALUES (260,'Master''s Gem');
INSERT INTO boss_loot VALUES (260,'Merchant''s Gem');
INSERT INTO boss_loot VALUES (260,'Protecter''s Gem');
INSERT INTO boss_loot VALUES (260,'Sniper''s Gem');
INSERT INTO boss_loot VALUES (260,'Spirit''s Gem');
INSERT INTO boss_loot VALUES (260,'Techno Wizard''s Gem');
INSERT INTO boss_loot VALUES (260,'Warrior''s Gem');
INSERT INTO boss_loot VALUES (260,'Worshipper''s Gem');
INSERT INTO boss_loot VALUES (261,'M.A.G.S. Aggression Enhancer');
INSERT INTO boss_loot VALUES (262,'Gem of the Sands');
INSERT INTO boss_loot VALUES (263,'Huzzum''s Iron Fist');
INSERT INTO boss_loot VALUES (263,'The Wizdom of Huzzum');
INSERT INTO boss_loot VALUES (264,'The Dog of War');
INSERT INTO boss_loot Values (264,'Wardog''s Heated Razor Gloves');
INSERT INTO boss_loot Values (265,'Cyborg C.O. Wrist Computer');
INSERT INTO boss_loot Values (266,'Damaged Notum Tower Shield');
INSERT INTO boss_loot Values (267,'Skawt''s Plasma Emitter');
INSERT INTO boss_loot Values (267,'Skawt''s Compact Plasma Emitter');
INSERT INTO boss_loot Values (268,'Stripped Merit Board');
INSERT INTO boss_loot Values (268,'Experimental Optic Enhancer');
INSERT INTO boss_loot Values (269,'Riker''s Resolve');
INSERT INTO boss_loot VALUES (270,'Death''s Door');
INSERT INTO boss_loot VALUES (270,'Vision of Destruction');
INSERT INTO boss_loot VALUES (270,'Vision of Hope');