DROP TABLE IF EXISTS boss_namedb;
CREATE TABLE boss_namedb (`bossid` INT PRIMARY KEY,`bossname` VARCHAR(50) NOT NULL);
INSERT INTO `boss_namedb` VALUES (1,'Afreet Ellis');
INSERT INTO `boss_namedb` VALUES (2,'Akshki'); 
INSERT INTO `boss_namedb` VALUES (3,'Alpha Skincrawler');
INSERT INTO `boss_namedb` VALUES (4,'Anansi''s Left Hand');
INSERT INTO `boss_namedb` VALUES (5,'Anansi''s Right Hand');
INSERT INTO `boss_namedb` VALUES (6,'Anansi''s Abettor');
INSERT INTO `boss_namedb` VALUES (7,'Anansi''s Favorite');
INSERT INTO `boss_namedb` VALUES (8,'Aniitaps Shadow');
INSERT INTO `boss_namedb` VALUES (9,'Apprentice Beasthandler');
INSERT INTO `boss_namedb` VALUES (10,'Aquarius');
INSERT INTO `boss_namedb` VALUES (11,'Aries');
INSERT INTO `boss_namedb` VALUES (12,'Asperous Imp');
INSERT INTO `boss_namedb` VALUES (13,'Astypalia');
INSERT INTO `boss_namedb` VALUES (14,'Atakirh');
INSERT INTO `boss_namedb` VALUES (15,'Athlar');
INSERT INTO `boss_namedb` VALUES (16,'Bane');
INSERT INTO `boss_namedb` VALUES (17,'Bending Eremite');
INSERT INTO `boss_namedb` VALUES (18,'Bigot Inmodeah');
INSERT INTO `boss_namedb` VALUES (19,'Black');
INSERT INTO `boss_namedb` VALUES (20,'Brutish Dryad');
INSERT INTO `boss_namedb` VALUES (21,'Cacophonous Imp');
INSERT INTO `boss_namedb` VALUES (22,'Cancer');
INSERT INTO `boss_namedb` VALUES (23,'Cantankerous Golem');
INSERT INTO `boss_namedb` VALUES (24,'Capricorn');
INSERT INTO `boss_namedb` VALUES (25,'Catervauling Minx');
INSERT INTO `boss_namedb` VALUES (26,'Cenobite Shadow');
INSERT INTO `boss_namedb` VALUES (27,'Cerubin The Rejected');
INSERT INTO `boss_namedb` VALUES (28,'Chimera Monitor');
INSERT INTO `boss_namedb` VALUES (29,'Chimera Trainer');
INSERT INTO `boss_namedb` VALUES (30,'Clan Modified A-4000');
INSERT INTO `boss_namedb` VALUES (31,'Clan Modified A-4001');
INSERT INTO `boss_namedb` VALUES (32,'Chimera Trainer');
INSERT INTO `boss_namedb` VALUES (33,'Colonel Frank Kaehler');
INSERT INTO `boss_namedb` VALUES (34,'Comatosed Soul');
INSERT INTO `boss_namedb` VALUES (35,'Commander Kelly Frederickson');
INSERT INTO `boss_namedb` VALUES (36,'Conflagrant Spirit');
INSERT INTO `boss_namedb` VALUES (37,'Corrupt Spirit');
INSERT INTO `boss_namedb` VALUES (38,'Crabby Golem');
INSERT INTO `boss_namedb` VALUES (39,'Cranky Golem');
INSERT INTO `boss_namedb` VALUES (40,'Creepy Spider');
INSERT INTO `boss_namedb` VALUES (41,'Crete');
INSERT INTO `boss_namedb` VALUES (42,'Cuty');
INSERT INTO `boss_namedb` VALUES (43,'Daria Marie Walzer');
INSERT INTO `boss_namedb` VALUES (44,'Daring Dryad');
INSERT INTO `boss_namedb` VALUES (45,'Dauntless Dryad');
INSERT INTO `boss_namedb` VALUES (46,'Delinquent Spirit');
INSERT INTO `boss_namedb` VALUES (47,'Devoted Spirit Hunter');
INSERT INTO `boss_namedb` VALUES (48,'Diamondine Soldier');
INSERT INTO `boss_namedb` VALUES (49,'Diamondine Trainee');
INSERT INTO `boss_namedb` VALUES (50,'Ding');
INSERT INTO `boss_namedb` VALUES (51,'Disturbing Imp');
INSERT INTO `boss_namedb` VALUES (52,'Elian Zuwadza');
INSERT INTO `boss_namedb` VALUES (53,'Enkindled Spirit');
INSERT INTO `boss_namedb` VALUES (54,'Escaped Gargantula');
INSERT INTO `boss_namedb` VALUES (55,'Fanatic Spirit Hunter');
INSERT INTO `boss_namedb` VALUES (56,'Fearless Dryad');
INSERT INTO `boss_namedb` VALUES (57,'Fiery Soldier');
INSERT INTO `boss_namedb` VALUES (58,'Forefather');
INSERT INTO `boss_namedb` VALUES (59,'Gemini');
INSERT INTO `boss_namedb` VALUES (60,'General Kaehler Jr');
INSERT INTO `boss_namedb` VALUES (61,'General Kronillis');
INSERT INTO `boss_namedb` VALUES (62,'General Nirtox');
INSERT INTO `boss_namedb` VALUES (63,'General Vivyan');
INSERT INTO `boss_namedb` VALUES (64,'George');
INSERT INTO `boss_namedb` VALUES (65,'Hawqana');
INSERT INTO `boss_namedb` VALUES (66,'High Commander Frederickson');
INSERT INTO `boss_namedb` VALUES (67,'Howling Minx');
INSERT INTO `boss_namedb` VALUES (68,'Howling Predator');
INSERT INTO `boss_namedb` VALUES (69,'Ian Warr');
INSERT INTO `boss_namedb` VALUES (70,'Incandescent Spirit');
INSERT INTO `boss_namedb` VALUES (71,'Irascible Golem');
INSERT INTO `boss_namedb` VALUES (72,'Iron Reet');
INSERT INTO `boss_namedb` VALUES (73,'Isham');
INSERT INTO `boss_namedb` VALUES (74,'Ishimkimk');
INSERT INTO `boss_namedb` VALUES (75,'Ithaki');
INSERT INTO `boss_namedb` VALUES (76,'Joo');
INSERT INTO `boss_namedb` VALUES (77,'Jukes');
INSERT INTO `boss_namedb` VALUES (78,'Lab Director');
INSERT INTO `boss_namedb` VALUES (79,'Leo');
INSERT INTO `boss_namedb` VALUES (80,'Libra');
INSERT INTO `boss_namedb` VALUES (81,'Limber Dryad');
INSERT INTO `boss_namedb` VALUES (82,'Limnos');
INSERT INTO `boss_namedb` VALUES (83,'Limping Predator');
INSERT INTO `boss_namedb` VALUES (84,'Ljotur The Lunatic');
INSERT INTO `boss_namedb` VALUES (85,'Lord Of The Void');
INSERT INTO `boss_namedb` VALUES (86,'Lost Soul');
INSERT INTO `boss_namedb` VALUES (87,'Lurking Dryad');
INSERT INTO `boss_namedb` VALUES (88,'Mantis Queen');
INSERT INTO `boss_namedb` VALUES (89,'Marcus Robicheaux');
INSERT INTO `boss_namedb` VALUES (90,'Maychwaham');
INSERT INTO `boss_namedb` VALUES (91,'Mick Nugget McMullet');
INSERT INTO `boss_namedb` VALUES (92,'Mooching Dryad');
INSERT INTO `boss_namedb` VALUES (93,'Morgan Le Faye');
INSERT INTO `boss_namedb` VALUES (94,'Morty');
INSERT INTO `boss_namedb` VALUES (95,'Mull');
INSERT INTO `boss_namedb` VALUES (96,'Neleb The Deranged');
INSERT INTO `boss_namedb` VALUES (97,'Nelly Johnson');
INSERT INTO `boss_namedb` VALUES (98,'Notum Soldier');
INSERT INTO `boss_namedb` VALUES (99,'Notum Trainee');
INSERT INTO `boss_namedb` VALUES (100,'Obediency Inspector');
INSERT INTO `boss_namedb` VALUES (101,'Omni-Pol Command Juggernaut');
INSERT INTO `boss_namedb` VALUES (102,'Oscar');
INSERT INTO `boss_namedb` VALUES (103,'Ossuz');
INSERT INTO `boss_namedb` VALUES (104,'Ownz');
INSERT INTO `boss_namedb` VALUES (105,'Pained Predator');
INSERT INTO `boss_namedb` VALUES (106,'Patricia Johnson');
INSERT INTO `boss_namedb` VALUES (107,'Peristaltic Abomination');
INSERT INTO `boss_namedb` VALUES (108,'Peristaltic Aversion');
INSERT INTO `boss_namedb` VALUES (109,'Peter Lee');
INSERT INTO `boss_namedb` VALUES (110,'Phatmos');
INSERT INTO `boss_namedb` VALUES (111,'Pisces');
INSERT INTO `boss_namedb` VALUES (112,'Pit Demon');
INSERT INTO `boss_namedb` VALUES (113,'Polly');
INSERT INTO `boss_namedb` VALUES (114,'Polymorphed Lunatic');
INSERT INTO `boss_namedb` VALUES (115,'Powa');
INSERT INTO `boss_namedb` VALUES (116,'Professor Van Horn');
INSERT INTO `boss_namedb` VALUES (117,'Punctilious Hiathlin');
INSERT INTO `boss_namedb` VALUES (118,'Putrid Eremite');
INSERT INTO `boss_namedb` VALUES (119,'R-2000 Vermin Disposal Unit');
INSERT INTO `boss_namedb` VALUES (120,'Ris Lee');
INSERT INTO `boss_namedb` VALUES (121,'Rotting Eremite');
INSERT INTO `boss_namedb` VALUES (122,'Sadistic Soul Dredge');
INSERT INTO `boss_namedb` VALUES (123,'Sagittarius');
INSERT INTO `boss_namedb` VALUES (124,'Salahpt');
INSERT INTO `boss_namedb` VALUES (125,'Scary Spider');
INSERT INTO `boss_namedb` VALUES (126,'Scorpio');
INSERT INTO `boss_namedb` VALUES (127,'Scratching Soul Dredge');
INSERT INTO `boss_namedb` VALUES (128,'Screeching Imp');
INSERT INTO `boss_namedb` VALUES (129,'Scrupulous Hiathlin');
INSERT INTO `boss_namedb` VALUES (130,'Sinful Soul Dredge');
INSERT INTO `boss_namedb` VALUES (131,'Skulking Dryad');
INSERT INTO `boss_namedb` VALUES (132,'Skylight');
INSERT INTO `boss_namedb` VALUES (133,'Slinking Dryad');
INSERT INTO `boss_namedb` VALUES (134,'Snatching Soul Dredge');
INSERT INTO `boss_namedb` VALUES (135,'Special Agent Lamb');
INSERT INTO `boss_namedb` VALUES (136,'Spetses');
INSERT INTO `boss_namedb` VALUES (137,'Splintered Girder');
INSERT INTO `boss_namedb` VALUES (138,'Stark');
INSERT INTO `boss_namedb` VALUES (139,'Steele Filar');
INSERT INTO `boss_namedb` VALUES (140,'Stumpy');
INSERT INTO `boss_namedb` VALUES (141,'Supply Master Eel');
INSERT INTO `boss_namedb` VALUES (142,'Supply Master Smug');
INSERT INTO `boss_namedb` VALUES (143,'Swirling Eremite');
INSERT INTO `boss_namedb` VALUES (144,'T.I.M.');
INSERT INTO `boss_namedb` VALUES (145,'Tarasque');
INSERT INTO `boss_namedb` VALUES (146,'Taurus');
INSERT INTO `boss_namedb` VALUES (147,'Tdecin');
INSERT INTO `boss_namedb` VALUES (148,'The Beast');
INSERT INTO `boss_namedb` VALUES (149,'The Nightheart');
INSERT INTO `boss_namedb` VALUES (150,'The Obediency Enforcer');
INSERT INTO `boss_namedb` VALUES (151,'The One (Babyface)');
INSERT INTO `boss_namedb` VALUES (152,'The Pest');
INSERT INTO `boss_namedb` VALUES (153,'Tinos');
INSERT INTO `boss_namedb` VALUES (154,'Tiunissik');
INSERT INTO `boss_namedb` VALUES (155,'Torrid Spirit');
INSERT INTO `boss_namedb` VALUES (156,'Torrith The Ancient');
INSERT INTO `boss_namedb` VALUES (157,'Tri Plumbo');
INSERT INTO `boss_namedb` VALUES (158,'Tuqusk');
INSERT INTO `boss_namedb` VALUES (159,'Turk');
INSERT INTO `boss_namedb` VALUES (160,'Tyro Beasthandler');
INSERT INTO `boss_namedb` VALUES (161,'Ushamaham');
INSERT INTO `boss_namedb` VALUES (162,'Virgo');
INSERT INTO `boss_namedb` VALUES (163,'Waning Soul');
INSERT INTO `boss_namedb` VALUES (164,'Wounded Predator');
INSERT INTO `boss_namedb` VALUES (165,'Zias');
INSERT INTO `boss_namedb` VALUES (166,'Xark the Battletoad');
INSERT INTO `boss_namedb` VALUES (167,'Inobak the Gelid');
INSERT INTO `boss_namedb` VALUES (168,'Hezak The Immortal');
INSERT INTO `boss_namedb` VALUES (169,'Dominus Facut the Bloodless');
INSERT INTO `boss_namedb` VALUES (170,'Dominus Ummoh the Pedagogue');
INSERT INTO `boss_namedb` VALUES (171,'Dominus Jiannu');
INSERT INTO `boss_namedb` VALUES (172,'Iskop the Idolator');
INSERT INTO `boss_namedb` VALUES (173,'Jeuru the Defiler');
INSERT INTO `boss_namedb` VALUES (174,'Wicked Soul Dredge');
INSERT INTO `boss_namedb` VALUES (175,'Numiel');
INSERT INTO `boss_namedb` VALUES (176,'Asanon');
INSERT INTO `boss_namedb` VALUES (177,'Ahomac');
INSERT INTO `boss_namedb` VALUES (178,'Hebial');
INSERT INTO `boss_namedb` VALUES (179,'Primus Scrap Pillager');
INSERT INTO `boss_namedb` VALUES (180,'Primus Outlaw');
INSERT INTO `boss_namedb` VALUES (181,'Distracted Snake Tamer');
INSERT INTO `boss_namedb` VALUES (182,'First Brood Champion');
INSERT INTO `boss_namedb` VALUES (183,'Second Brood Champion');
INSERT INTO `boss_namedb` VALUES (184,'Third Brood Champion');
INSERT INTO `boss_namedb` VALUES (185,'Fourth Brood Champion');
INSERT INTO `boss_namedb` VALUES (186,'Fifth Brood Champion');
INSERT INTO `boss_namedb` VALUES (187,'Sixth Brood Champion');
INSERT INTO `boss_namedb` VALUES (188,'Seventh Brood Champion');
INSERT INTO `boss_namedb` VALUES (189,'Eighth Brood Champion');
INSERT INTO `boss_namedb` VALUES (190,'Ninth Brood Champion');
INSERT INTO `boss_namedb` VALUES (191,'Tenth Brood Champion');
INSERT INTO `boss_namedb` VALUES (192,'The Hollow Island Suzerain');
INSERT INTO `boss_namedb` VALUES (193,'The Brood Mother');
INSERT INTO `boss_namedb` VALUES (194,'Hollow Island Weed');
INSERT INTO `boss_namedb` VALUES (195,'Algid Slither');
INSERT INTO `boss_namedb` VALUES (196,'Brumal Slither');
INSERT INTO `boss_namedb` VALUES (197,'Chilly Slither');
INSERT INTO `boss_namedb` VALUES (198,'Cold Slither');
INSERT INTO `boss_namedb` VALUES (199,'Nippy Slither');
INSERT INTO `boss_namedb` VALUES (200,'Gashing Soul Dredge');
INSERT INTO `boss_namedb` VALUES (201,'Iced Slither');
INSERT INTO `boss_namedb` VALUES (202,'Iniquitous Spirit');
INSERT INTO `boss_namedb` VALUES (203,'Tiny');
INSERT INTO `boss_namedb` VALUES (204,'Trup');
INSERT INTO `boss_namedb` VALUES (205,'Vile Spirit');
INSERT INTO `boss_namedb` VALUES (206,'Jack Legchopper');
INSERT INTO `boss_namedb` VALUES (207,'Trash King');
INSERT INTO `boss_namedb` VALUES (209,'Lord Ghasap');
INSERT INTO `boss_namedb` VALUES (210,'Eumenides');
INSERT INTO `boss_namedb` VALUES (211,'Vergil Aeneid');
INSERT INTO `boss_namedb` VALUES (212,'Abmouth Supremus');
INSERT INTO `boss_namedb` VALUES (213,'General Serverus');
INSERT INTO `boss_namedb` VALUES (214,'Eradicator Deimos');
INSERT INTO `boss_namedb` VALUES (215,'Techleader Praetor');
INSERT INTO `boss_namedb` VALUES (216,'Augmented Cyborg Hellfury');
INSERT INTO `boss_namedb` VALUES (217,'Prototype Inferno');
INSERT INTO `boss_namedb` VALUES (218,'Commander Jocasta');
INSERT INTO `boss_namedb` VALUES (219,'Defender Of The Three');
INSERT INTO `boss_namedb` VALUES (220,'The Curator');
INSERT INTO `boss_namedb` VALUES (221,'Nematet The Custodian Of Time');
INSERT INTO `boss_namedb` VALUES (222,'The Re-animator');
INSERT INTO `boss_namedb` VALUES (223,'Lien the Memorystalker');
INSERT INTO `boss_namedb` VALUES (224,'Guardian Of Tomorrow');
INSERT INTO `boss_namedb` VALUES (225,'Uklesh The Frozen');
INSERT INTO `boss_namedb` VALUES (226,'Aztur The Immortal');
INSERT INTO `boss_namedb` VALUES (227,'Gartua The Doorkeeper');
INSERT INTO `boss_namedb` VALUES (228,'Windcaller Yatilla');
INSERT INTO `boss_namedb` VALUES (229,'Den Smuggler Pilot');
INSERT INTO `boss_namedb` VALUES (230, 'Anansi''s Disciple');
INSERT INTO `boss_namedb` VALUES (231, 'Aniitap''s Shadow');
INSERT INTO `boss_namedb` VALUES (232, 'Akshk''i');
INSERT INTO `boss_namedb` VALUES (233, 'Bia''s Favorite');
INSERT INTO `boss_namedb` VALUES (234, 'Bigot Helozabasael');
INSERT INTO `boss_namedb` VALUES (235, 'Bigot Nzaemihiel');
INSERT INTO `boss_namedb` VALUES (237, 'Estella Fire');
INSERT INTO `boss_namedb` VALUES (238, 'Fetid Eremite');
INSERT INTO `boss_namedb` VALUES (239, 'Hebiel');
INSERT INTO `boss_namedb` VALUES (240, 'Ishimk''Imk');
INSERT INTO `boss_namedb` VALUES (241, 'Malah-Fulcifera');
INSERT INTO `boss_namedb` VALUES (242, 'Maychwyawi');
INSERT INTO `boss_namedb` VALUES (243, 'Medusa Philanderer');
INSERT INTO `boss_namedb` VALUES (244, 'Natsmaahpt');
INSERT INTO `boss_namedb` VALUES (245, 'Noxious Eremite');
INSERT INTO `boss_namedb` VALUES (246, 'Obsolete Soul Dredge');
INSERT INTO `boss_namedb` VALUES (247, 'Paxos');
INSERT INTO `boss_namedb` VALUES (248, 'Punctlious Hiathlin');
INSERT INTO `boss_namedb` VALUES (249, 'Pursued Spirit');
INSERT INTO `boss_namedb` VALUES (250, 'Pyiininnik');
INSERT INTO `boss_namedb` VALUES (251, 'Razor the Battletoad');
INSERT INTO `boss_namedb` VALUES (252, 'Sanatsimk');
INSERT INTO `boss_namedb` VALUES (253, 'Silent Spider');
INSERT INTO `boss_namedb` VALUES (254, 'Syros');
INSERT INTO `boss_namedb` VALUES (255, 'Tuq''usk');
INSERT INTO `boss_namedb` VALUES (256, 'Ushap''ing');
INSERT INTO `boss_namedb` VALUES (257, 'Waywaqa');
INSERT INTO `boss_namedb` VALUES (258, 'Ground Chief Vortexx');
INSERT INTO `boss_namedb` VALUES (259, 'Mitaar Hero');
INSERT INTO `boss_namedb` VALUES (260, '12-man');
INSERT INTO `boss_namedb` VALUES (261, 'Abandoned Hope');