apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyrbot-pvc
  namespace: tyrbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo