DROP TABLE IF EXISTS `playfields`;
CREATE TABLE `playfields` (`id` smallint(6) NOT NULL PRIMARY KEY, `long_name` varchar(100) NOT NULL, `short_name` varchar(30) DEFAULT NULL, `is_dungeon` tinyint(255) NOT NULL DEFAULT 0, UNIQUE (`short_name`));
INSERT INTO `playfields` VALUES (100, 'Needed PF-stuff', NULL, 0);
INSERT INTO `playfields` VALUES (101, 'Default Door Links', NULL, 0);
INSERT INTO `playfields` VALUES (102, 'Monster and NPC dependencies', NULL, 0);
INSERT INTO `playfields` VALUES (103, 'Shop and Item Dependencies', NULL, 0);
INSERT INTO `playfields` VALUES (104, 'One Template PF', NULL, 0);
INSERT INTO `playfields` VALUES (105, 'Morten gfx fixes', NULL, 0);
INSERT INTO `playfields` VALUES (107, 'AI graphics dependency', NULL, 0);
INSERT INTO `playfields` VALUES (109, 'LE dependencies', NULL, 0);
INSERT INTO `playfields` VALUES (110, 'Dependency EP1 Mons', NULL, 0);
INSERT INTO `playfields` VALUES (111, 'RK Quick Export Dependancy', NULL, 0);
INSERT INTO `playfields` VALUES (120, 'Camelot', 'TARA', 0);
INSERT INTO `playfields` VALUES (124, 'Tir Assembly Hall', NULL, 0);
INSERT INTO `playfields` VALUES (125, 'Smuggler''s Rearranged', NULL, 0);
INSERT INTO `playfields` VALUES (127, 'Abandoned Mall', 'SUBWAY', 1);
INSERT INTO `playfields` VALUES (128, 'Subway Junction', NULL, 1);
INSERT INTO `playfields` VALUES (152, 'Grid', 'GRID', 0);
INSERT INTO `playfields` VALUES (320, 'AutocontentMidtech(dung)', NULL, 0);
INSERT INTO `playfields` VALUES (321, 'AutocontentHITech(dung)', NULL, 0);
INSERT INTO `playfields` VALUES (322, 'Autocontentdungcave(dung)', NULL, 0);
INSERT INTO `playfields` VALUES (324, 'AutocontentClan(dung)', NULL, 0);
INSERT INTO `playfields` VALUES (331, 'ACD tarm', NULL, 1);
INSERT INTO `playfields` VALUES (341, 'ACD Grey Caves-Mines', NULL, 1);
INSERT INTO `playfields` VALUES (346, 'ACD Omnilab', NULL, 1);
INSERT INTO `playfields` VALUES (351, 'ACD Subway - Ventil', NULL, 1);
INSERT INTO `playfields` VALUES (362, 'SL ACG', NULL, 1);
INSERT INTO `playfields` VALUES (382, 'Alien ACG', NULL, 1);
INSERT INTO `playfields` VALUES (386, 'Alien Mothership', NULL, 1);
INSERT INTO `playfields` VALUES (500, 'Parnassos', 'GMPF', 0);
INSERT INTO `playfields` VALUES (501, 'Parnassos Island of Ceremony', 'ARKHQ', 0);
INSERT INTO `playfields` VALUES (505, 'Avalon', 'AV', 0);
INSERT INTO `playfields` VALUES (540, 'Old Athen', 'OA', 0);
INSERT INTO `playfields` VALUES (545, 'West Athens', 'WA', 0);
INSERT INTO `playfields` VALUES (550, 'Athen Shire', 'AS', 0);
INSERT INTO `playfields` VALUES (551, 'Wailing Wastes', 'WW', 0);
INSERT INTO `playfields` VALUES (556, 'Coast of Peace', 'CP', 0);
INSERT INTO `playfields` VALUES (560, 'Mort', 'MORT', 0);
INSERT INTO `playfields` VALUES (565, 'Newland Desert', 'NLD', 0);
INSERT INTO `playfields` VALUES (566, 'Newland City', 'NC', 0);
INSERT INTO `playfields` VALUES (567, 'Newland', 'NL', 0);
INSERT INTO `playfields` VALUES (570, 'Perpetual Wastelands', 'PW', 0);
INSERT INTO `playfields` VALUES (585, 'Aegean', 'AEG', 0);
INSERT INTO `playfields` VALUES (586, 'Wartorn Valley', 'WV', 0);
INSERT INTO `playfields` VALUES (590, 'Central Artery Valley', 'CAV', 0);
INSERT INTO `playfields` VALUES (595, 'Deep Artery Valley', 'DAV', 0);
INSERT INTO `playfields` VALUES (600, 'Varmint Woods', 'VW', 0);
INSERT INTO `playfields` VALUES (605, 'Belial Forest', 'BF', 0);
INSERT INTO `playfields` VALUES (610, 'Southern Artery Valley', 'SAV', 0);
INSERT INTO `playfields` VALUES (615, 'Southern Fouls Hills', 'SFH', 0);
INSERT INTO `playfields` VALUES (620, 'Eastern Fouls Plain', 'EFP', 0);
INSERT INTO `playfields` VALUES (625, 'Milky Way', 'MW', 0);
INSERT INTO `playfields` VALUES (630, 'Pleasant Meadows', 'PM', 0);
INSERT INTO `playfields` VALUES (635, 'Stret East Bank', 'SEB', 0);
INSERT INTO `playfields` VALUES (640, 'Tir', 'TIR', 0);
INSERT INTO `playfields` VALUES (641, 'Tir Arena', 'TA', 0);
INSERT INTO `playfields` VALUES (646, 'Tir County', 'TC', 0);
INSERT INTO `playfields` VALUES (647, 'Greater Tir County', 'GTC', 0);
INSERT INTO `playfields` VALUES (650, 'Upper Stret East Bank', 'USEB', 0);
INSERT INTO `playfields` VALUES (655, 'Andromeda', 'AND', 0);
INSERT INTO `playfields` VALUES (656, 'Coast of Tranquility', 'CT', 0);
INSERT INTO `playfields` VALUES (665, 'Broken Shores', 'BS', 0);
INSERT INTO `playfields` VALUES (670, 'Clondyke', 'CLON', 0);
INSERT INTO `playfields` VALUES (685, 'Galway County', 'GC', 0);
INSERT INTO `playfields` VALUES (687, 'Galway Shire', 'GS', 0);
INSERT INTO `playfields` VALUES (695, 'Lush Fields', 'LF', 0);
INSERT INTO `playfields` VALUES (696, 'Mutant Domain', 'MD', 0);
INSERT INTO `playfields` VALUES (700, 'Omni-1 HQ', 'OHQ', 0);
INSERT INTO `playfields` VALUES (705, 'Omni-1 Entertainment', 'ENT', 0);
INSERT INTO `playfields` VALUES (706, 'Omni Entertainment Arena', NULL, 0);
INSERT INTO `playfields` VALUES (710, 'Omni-1 Trade', 'OT', 0);
INSERT INTO `playfields` VALUES (716, 'Omni Forest', 'OF', 0);
INSERT INTO `playfields` VALUES (717, 'Greater Omni Forest', 'GOF', 0);
INSERT INTO `playfields` VALUES (730, 'Rome Red', 'RR', 0);
INSERT INTO `playfields` VALUES (735, 'Rome Blue', 'RB', 0);
INSERT INTO `playfields` VALUES (740, 'Rome Green', 'RG', 0);
INSERT INTO `playfields` VALUES (750, 'The Reck', 'RECK', 0);
INSERT INTO `playfields` VALUES (760, '4 Holes', '4HO', 0);
INSERT INTO `playfields` VALUES (790, 'Stret West Bank', 'SWB', 0);
INSERT INTO `playfields` VALUES (791, 'Holes in the Wall', 'HITW', 0);
INSERT INTO `playfields` VALUES (795, 'The Longest Road', 'TLR', 0);
INSERT INTO `playfields` VALUES (800, 'Borealis', 'BOR', 0);
INSERT INTO `playfields` VALUES (896, 'Character Creation Lab', NULL, 1);
INSERT INTO `playfields` VALUES (950, 'Omni Training', NULL, 0);
INSERT INTO `playfields` VALUES (952, 'Clan Training', NULL, 0);
INSERT INTO `playfields` VALUES (953, 'Clan Backyard', NULL, 0);
INSERT INTO `playfields` VALUES (954, 'Neutral Training', NULL, 0);
INSERT INTO `playfields` VALUES (955, 'Neutral Backyard', NULL, 0);
INSERT INTO `playfields` VALUES (1001, 'Senitel rec_centre (wine) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1002, 'medical/eating (wine) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1003, 'Wine hq (wine) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1004, 'barracks (wine) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1005, 'storage (wine) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1011, '2HO HQ (streteast) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1012, '2HO satellite (streteast) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1021, 'Omni barracks (USEB) GOLD', NULL, 0);
INSERT INTO `playfields` VALUES (1031, 'Avalon omni barracks', NULL, 0);
INSERT INTO `playfields` VALUES (1136, 'Mir shop clan', NULL, 0);
INSERT INTO `playfields` VALUES (1137, 'mir shop omni', NULL, 0);
INSERT INTO `playfields` VALUES (1180, 'ord_smarket_clan_basic', NULL, 0);
INSERT INTO `playfields` VALUES (1181, 'ord_smarket_clan_advanced', NULL, 0);
INSERT INTO `playfields` VALUES (1182, 'ord_smarket_clan_sup', NULL, 0);
INSERT INTO `playfields` VALUES (1183, 'ord_smarket_omni_basic', NULL, 0);
INSERT INTO `playfields` VALUES (1184, 'ord_smarket_omni_advanced', NULL, 0);
INSERT INTO `playfields` VALUES (1185, 'ord_smarket_omni_sup', NULL, 0);
INSERT INTO `playfields` VALUES (1186, 'ord_smarket_neut_basic', NULL, 0);
INSERT INTO `playfields` VALUES (1187, 'ord_smarket_neut_advanced', NULL, 0);
INSERT INTO `playfields` VALUES (1189, 'spec_smarket_clan_advanced', NULL, 0);
INSERT INTO `playfields` VALUES (1190, 'spec_smarket_clan_sup', NULL, 0);
INSERT INTO `playfields` VALUES (1191, 'spec_smarket_omni_advanced', NULL, 0);
INSERT INTO `playfields` VALUES (1192, 'spec_smarket_omni_sup', NULL, 0);
INSERT INTO `playfields` VALUES (1193, 'spec_smarket_neut_basic', NULL, 0);
INSERT INTO `playfields` VALUES (1211, 'basicomniapartment', NULL, 1);
INSERT INTO `playfields` VALUES (1231, 'Clan Small Clan Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (1232, 'Clan Medium Clan Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (1233, 'Clan Big Clan Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (1241, 'Neutral Small Clan Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (1242, 'Neutral Medium Clan Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (1243, 'Neutral Big Clan Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (1251, 'Omni Small Guild', NULL, 0);
INSERT INTO `playfields` VALUES (1321, 'tir clanbuilding2', NULL, 1);
INSERT INTO `playfields` VALUES (1322, 'tir clanbuilding1', NULL, 1);
INSERT INTO `playfields` VALUES (1323, 'tir clanbuilding9', NULL, 1);
INSERT INTO `playfields` VALUES (1324, 'tir clanbuilding11', NULL, 1);
INSERT INTO `playfields` VALUES (1325, 'tir clanbuilding12', NULL, 1);
INSERT INTO `playfields` VALUES (1326, 'tir clanbuilding3', NULL, 0);
INSERT INTO `playfields` VALUES (1327, 'tir clanbuilding_pod4', NULL, 1);
INSERT INTO `playfields` VALUES (1328, 'tir clanbuilding5', NULL, 1);
INSERT INTO `playfields` VALUES (1329, 'tir clanbuilding6', NULL, 1);
INSERT INTO `playfields` VALUES (1330, 'tir clanbuilding7', NULL, 1);
INSERT INTO `playfields` VALUES (1404, 'The Temple of Home', NULL, 0);
INSERT INTO `playfields` VALUES (1405, 'clanapartment', NULL, 0);
INSERT INTO `playfields` VALUES (1406, 'omniapartment', NULL, 0);
INSERT INTO `playfields` VALUES (1407, 'neutralapartment', NULL, 0);
INSERT INTO `playfields` VALUES (1410, 'items', NULL, 0);
INSERT INTO `playfields` VALUES (1421, 'avalon_building3', NULL, 1);
INSERT INTO `playfields` VALUES (1422, 'avalon_building4', NULL, 1);
INSERT INTO `playfields` VALUES (1423, 'avalon_building5', NULL, 0);
INSERT INTO `playfields` VALUES (1424, 'avalon_building2', NULL, 1);
INSERT INTO `playfields` VALUES (1426, 'Clan Registration', NULL, 1);
INSERT INTO `playfields` VALUES (1427, 'Omni registration', NULL, 1);
INSERT INTO `playfields` VALUES (1428, 'Neutral organisation', NULL, 1);
INSERT INTO `playfields` VALUES (1501, 'omnimine_hq_building_06', NULL, 0);
INSERT INTO `playfields` VALUES (1502, 'omnimine_hq_building_02', NULL, 0);
INSERT INTO `playfields` VALUES (1503, 'omnimine_hq_building_04', NULL, 0);
INSERT INTO `playfields` VALUES (1504, 'omnimine_hq_building_07', NULL, 0);
INSERT INTO `playfields` VALUES (1505, 'omnimine_hq_building_08', NULL, 0);
INSERT INTO `playfields` VALUES (1506, 'omnimine_hq_building_09', NULL, 0);
INSERT INTO `playfields` VALUES (1507, 'omnimine_hq_building10', NULL, 0);
INSERT INTO `playfields` VALUES (1510, 'Neutral Insurance building', NULL, 0);
INSERT INTO `playfields` VALUES (1511, 'Neutral Mission building', NULL, 0);
INSERT INTO `playfields` VALUES (1601, 'athens_clanhouse1 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1602, 'athens_clanhouse3 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1603, 'athens_clanhouse4 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1604, 'athens_clanhouse12 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1611, 'Swamp_house01 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1612, 'Swamp_house02', NULL, 0);
INSERT INTO `playfields` VALUES (1613, 'swamp_house03 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1614, 'Swamp_house04 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1621, 'wood_shack_01 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1622, 'wood_shack_02 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1623, 'wood_shack_03 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1624, 'wood_shack_04 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1625, 'wood_shack_05 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1626, 'wood_shack_06 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1627, 'wood_shack_07 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1641, 'lowtech_building1 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1642, 'lowtech_building2 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1643, 'lowtech_building3 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1644, 'lowtech_building4 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1645, 'lowtech_building5 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1646, 'lowtech_building6 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1647, 'lowtech_building7 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1648, 'lowtech_waterwell VP', NULL, 1);
INSERT INTO `playfields` VALUES (1651, 'rome_shopbuilding1 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1652, 'rome_simplebuilding VP', NULL, 1);
INSERT INTO `playfields` VALUES (1653, 'rome_simplebuilding1 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1661, 'rhino_house1 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1662, 'rhino_house2 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1663, 'rhino_house3 VP', NULL, 1);
INSERT INTO `playfields` VALUES (1671, 'reck_trading_outpost_bunker1 VP', NULL, 0);
INSERT INTO `playfields` VALUES (1672, 'reck_trading_outpost_bunker2 VP', NULL, 0);
INSERT INTO `playfields` VALUES (1673, 'reck_trading_outpost_bunker3 VP', NULL, 0);
INSERT INTO `playfields` VALUES (1674, 'reck_trading_outpost_bunker4 VP', NULL, 0);
INSERT INTO `playfields` VALUES (1675, 'reck_trading_outpost_bunker5 VP', NULL, 0);
INSERT INTO `playfields` VALUES (1701, 'Home VP 1 medium', NULL, 1);
INSERT INTO `playfields` VALUES (1702, 'Home VP 2 big', NULL, 1);
INSERT INTO `playfields` VALUES (1703, 'Home VP 3 small', NULL, 1);
INSERT INTO `playfields` VALUES (1711, 'Factory VP barracks', NULL, 1);
INSERT INTO `playfields` VALUES (1712, 'Factory VP factory', NULL, 1);
INSERT INTO `playfields` VALUES (1721, 'LD VP 1', NULL, 1);
INSERT INTO `playfields` VALUES (1722, 'LD VP 2', NULL, 1);
INSERT INTO `playfields` VALUES (1741, 'enigma_tree01', NULL, 0);
INSERT INTO `playfields` VALUES (1742, 'enigma_tree02', NULL, 0);
INSERT INTO `playfields` VALUES (1743, 'enigma_tree03', NULL, 0);
INSERT INTO `playfields` VALUES (1826, 'Dancing Atrox Bar', NULL, 0);
INSERT INTO `playfields` VALUES (1827, 'Omni Military Barracks', NULL, 0);
INSERT INTO `playfields` VALUES (1833, 'Cyborg Barracks', NULL, 1);
INSERT INTO `playfields` VALUES (1836, 'Baboons Nightclub', NULL, 0);
INSERT INTO `playfields` VALUES (1840, 'Rompa Bar', NULL, 0);
INSERT INTO `playfields` VALUES (1846, 'McRiid''s Office', NULL, 0);
INSERT INTO `playfields` VALUES (1862, 'The Smugglers Den', NULL, 0);
INSERT INTO `playfields` VALUES (1866, 'The HQ of Omni-Mine', NULL, 0);
INSERT INTO `playfields` VALUES (1886, 'Versailles Tower', NULL, 0);
INSERT INTO `playfields` VALUES (1887, 'Treepine Hut', NULL, 0);
INSERT INTO `playfields` VALUES (1891, 'The Happy Rebel Inn', NULL, 0);
INSERT INTO `playfields` VALUES (1892, 'Enjoy it While it Lasts', NULL, 0);
INSERT INTO `playfields` VALUES (1893, 'The Cup', NULL, 0);
INSERT INTO `playfields` VALUES (1894, 'Clan Registration Office', NULL, 0);
INSERT INTO `playfields` VALUES (1901, 'Neutral Organisation Office', NULL, 0);
INSERT INTO `playfields` VALUES (1902, 'Neuters ''R'' Us', NULL, 0);
INSERT INTO `playfields` VALUES (1913, 'Reet Retreat', NULL, 1);
INSERT INTO `playfields` VALUES (1931, 'Temple of Three Winds', NULL, 1);
INSERT INTO `playfields` VALUES (1933, 'Steps of Madness', NULL, 1);
INSERT INTO `playfields` VALUES (1941, 'Bio MARE', NULL, 0);
INSERT INTO `playfields` VALUES (1943, 'High Level ToTW', NULL, 1);
INSERT INTO `playfields` VALUES (2001, 'clan_basic_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2002, 'clan_basic_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2003, 'clan_basic_pharmasist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2004, 'clan_basic_clothes_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2005, 'clan_basic_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2006, 'clan_basic_nano_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2010, 'clan_advanced_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2011, 'clan_advanced_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2012, 'clan_advanced_pharmacist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2013, 'clan_advanced_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2014, 'clan_advanced_nano_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2020, 'clan_sup_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2021, 'clan_sup_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2022, 'clan_sup_pharmacist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2023, 'clan_sup_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2024, 'clan_sup_nano_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2030, 'omni_basic_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2031, 'omni_basic_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2032, 'omni_basic_pharmacist', NULL, 0);
INSERT INTO `playfields` VALUES (2033, 'omni_basic_clothes_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2034, 'omni_basic_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2040, 'omni_advanced_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2041, 'omni_advanced_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2042, 'omni_advanced_pharmacist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2043, 'omni_advanced_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2050, 'omni_sup_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2051, 'omni_sup_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2052, 'omni_sup_pharmacist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2053, 'omni_sup_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2060, 'neut_basic_weapon _shop', NULL, 0);
INSERT INTO `playfields` VALUES (2061, 'neut_basic_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2062, 'neut_basic_pharmacist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2063, 'neut_basic_clothes_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2064, 'neut_basic_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2070, 'neut_advanced_weapons_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2071, 'neut_advanced_armor_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2072, 'neut_advanced_pharmacist_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2073, 'neut_advanced_implants_shop', NULL, 0);
INSERT INTO `playfields` VALUES (2096, '4holes Fashion', NULL, 0);
INSERT INTO `playfields` VALUES (3000, 'Omni-1 Entertainment Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3001, 'Omni-1 Entertainment Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3002, 'Omni-1 Entertainment Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3003, 'Omni-1 Entertainment Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3004, 'Omni-1 Entertainment Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3005, 'Omni-1 Entertainment Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3006, 'Omni-1 Entertainment Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3007, 'Omni-1 Entertainment Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3008, 'Omni-1 Entertainment Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3009, 'Omni-1 Entertainment Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3010, 'Omni-1 Entertainment Backyard 11', NULL, 0);
INSERT INTO `playfields` VALUES (3011, 'Omni-1 Entertainment Backyard 12', NULL, 0);
INSERT INTO `playfields` VALUES (3012, 'Omni-1 Entertainment Backyard 13', NULL, 0);
INSERT INTO `playfields` VALUES (3013, 'Omni-1 Entertainment Backyard 14', NULL, 0);
INSERT INTO `playfields` VALUES (3014, 'Omni-1 Entertainment Backyard 15', NULL, 0);
INSERT INTO `playfields` VALUES (3015, 'Omni-1 Entertainment Backyard 16', NULL, 0);
INSERT INTO `playfields` VALUES (3016, 'Omni-1 Entertainment Backyard 17', NULL, 0);
INSERT INTO `playfields` VALUES (3017, 'Omni-1 Entertainment Backyard 18', NULL, 0);
INSERT INTO `playfields` VALUES (3018, 'Omni-1 Entertainment Backyard 19', NULL, 0);
INSERT INTO `playfields` VALUES (3019, 'Omni-1 Entertainment Backyard 20', NULL, 0);
INSERT INTO `playfields` VALUES (3020, 'Omni-1 Trade Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3021, 'Omni-1 Trade Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3022, 'Omni-1 Trade Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3023, 'Omni-1 Trade Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3024, 'Omni-1 Trade Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3025, 'Omni-1 Trade Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3026, 'Omni-1 Trade Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3027, 'Omni-1 Trade Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3028, 'Omni-1 Trade Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3029, 'Omni-1 Trade Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3030, 'Omni-1 Trade Backyard 11', NULL, 0);
INSERT INTO `playfields` VALUES (3031, 'Omni-1 Trade Backyard 12', NULL, 0);
INSERT INTO `playfields` VALUES (3032, 'Omni-1 Trade Backyard 13', NULL, 0);
INSERT INTO `playfields` VALUES (3033, 'Omni-1 Trade Backyard 14', NULL, 0);
INSERT INTO `playfields` VALUES (3034, 'Omni-1 Trade Backyard 15', NULL, 0);
INSERT INTO `playfields` VALUES (3035, 'Omni-1 Trade Backyard 16', NULL, 0);
INSERT INTO `playfields` VALUES (3036, 'Omni-1 Trade Backyard 17', NULL, 0);
INSERT INTO `playfields` VALUES (3037, 'Omni-1 Trade Backyard 18', NULL, 0);
INSERT INTO `playfields` VALUES (3038, 'Omni-1 Trade Backyard 19', NULL, 0);
INSERT INTO `playfields` VALUES (3039, 'Omni-1 Trade Backyard 20', NULL, 0);
INSERT INTO `playfields` VALUES (3040, 'Rome Blue Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3041, 'Rome Blue Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3042, 'Rome Blue Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3043, 'Rome Blue Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3044, 'Rome Blue Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3045, 'Rome Blue Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3046, 'Rome Blue Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3047, 'Rome Blue Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3048, 'Rome Blue Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3049, 'Rome Blue Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3050, 'Rome Green Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3051, 'Rome Green Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3052, 'Rome Green Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3053, 'Rome Green Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3054, 'Rome Green Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3055, 'Rome Green Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3056, 'Rome Green Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3057, 'Rome Green Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3058, 'Rome Green Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3059, 'Rome Green Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3060, 'Newland Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3061, 'Newland Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3062, 'Newland Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3063, 'Newland Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3064, 'Newland Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3065, 'Newland Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3066, 'Newland Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3067, 'Newland Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3068, 'Newland Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3069, 'Newland Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3070, 'Newland Backyard 11', NULL, 0);
INSERT INTO `playfields` VALUES (3071, 'Newland Backyard 12', NULL, 0);
INSERT INTO `playfields` VALUES (3080, 'Borealis Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3081, 'Borealis Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3082, 'Borealis Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3083, 'Borealis Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3084, 'Borealis Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3085, 'Borealis Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3086, 'Borealis Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3087, 'Borealis Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3088, 'Borealis Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3089, 'Borealis Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3100, 'Tir Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3101, 'Tir Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3102, 'Tir Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3103, 'Tir Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3104, 'Tir Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3105, 'Tir Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3106, 'Tir Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3107, 'Tir Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3108, 'Tir Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3109, 'Tir Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3110, 'Tir Backyard 11', NULL, 0);
INSERT INTO `playfields` VALUES (3111, 'Tir Backyard 12', NULL, 0);
INSERT INTO `playfields` VALUES (3112, 'Tir Backyard 13', NULL, 0);
INSERT INTO `playfields` VALUES (3113, 'Tir Backyard 14', NULL, 0);
INSERT INTO `playfields` VALUES (3114, 'Tir Backyard 15', NULL, 0);
INSERT INTO `playfields` VALUES (3115, 'Tir Backyard 16', NULL, 0);
INSERT INTO `playfields` VALUES (3116, 'Tir Backyard 17', NULL, 0);
INSERT INTO `playfields` VALUES (3117, 'Tir Backyard 18', NULL, 0);
INSERT INTO `playfields` VALUES (3120, 'Old Athen Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3121, 'Old Athen Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3122, 'Old Athen Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3123, 'Old Athen Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3124, 'Old Athen Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3125, 'Old Athen Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3126, 'Old Athen Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3127, 'Old Athen Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3128, 'Old Athen Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3129, 'Old Athen Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (3130, 'Old Athen Backyard 11', NULL, 0);
INSERT INTO `playfields` VALUES (3131, 'Old Athen Backyard 12', NULL, 0);
INSERT INTO `playfields` VALUES (3132, 'Old Athen Backyard 13', NULL, 0);
INSERT INTO `playfields` VALUES (3133, 'Old Athen Backyard 14', NULL, 0);
INSERT INTO `playfields` VALUES (3134, 'Old Athen Backyard 15', NULL, 0);
INSERT INTO `playfields` VALUES (3135, 'Old Athen Backyard 16', NULL, 0);
INSERT INTO `playfields` VALUES (3136, 'Old Athen Backyard 17', NULL, 0);
INSERT INTO `playfields` VALUES (3137, 'Old Athen Backyard 18', NULL, 0);
INSERT INTO `playfields` VALUES (3138, 'Old Athen Backyard 19', NULL, 0);
INSERT INTO `playfields` VALUES (3139, 'Old Athen Backyard 20', NULL, 0);
INSERT INTO `playfields` VALUES (3140, 'West Athen Backyard 1', NULL, 0);
INSERT INTO `playfields` VALUES (3141, 'West Athen Backyard 2', NULL, 0);
INSERT INTO `playfields` VALUES (3142, 'West Athen Backyard 3', NULL, 0);
INSERT INTO `playfields` VALUES (3143, 'West Athen Backyard 4', NULL, 0);
INSERT INTO `playfields` VALUES (3144, 'West Athen Backyard 5', NULL, 0);
INSERT INTO `playfields` VALUES (3145, 'West Athen Backyard 6', NULL, 0);
INSERT INTO `playfields` VALUES (3146, 'West Athen Backyard 7', NULL, 0);
INSERT INTO `playfields` VALUES (3147, 'West Athen Backyard 8', NULL, 0);
INSERT INTO `playfields` VALUES (3148, 'West Athen Backyard 9', NULL, 0);
INSERT INTO `playfields` VALUES (3149, 'West Athen Backyard 10', NULL, 0);
INSERT INTO `playfields` VALUES (4001, 'Jobe Research', 'RESEARCH', 0);
INSERT INTO `playfields` VALUES (4003, 'Burning Marshes', NULL, 0);
INSERT INTO `playfields` VALUES (4005, 'Inferno Burning Marshes', 'INFMARSHES', 0);
INSERT INTO `playfields` VALUES (4006, 'Penumbra', NULL, 0);
INSERT INTO `playfields` VALUES (4010, 'Garden of Redeemed Main', NULL, 0);
INSERT INTO `playfields` VALUES (4011, 'Garden_of_unredeemed', NULL, 0);
INSERT INTO `playfields` VALUES (4102, 'Beer And Booze', NULL, 1);
INSERT INTO `playfields` VALUES (4107, 'Fixer Grid', 'FGRID', 1);
INSERT INTO `playfields` VALUES (4121, 'Will To Fight', NULL, 0);
INSERT INTO `playfields` VALUES (4211, 'Maze_Acheron', NULL, 0);
INSERT INTO `playfields` VALUES (4212, 'Maze_Letha_scheol_red', NULL, 0);
INSERT INTO `playfields` VALUES (4213, 'Maze_Styx_ado_red', NULL, 0);
INSERT INTO `playfields` VALUES (4214, 'Maze_Eridan', NULL, 0);
INSERT INTO `playfields` VALUES (4215, 'Maze_Phlegethas1', NULL, 0);
INSERT INTO `playfields` VALUES (4220, 'Maze_Acheron (Unre)', NULL, 0);
INSERT INTO `playfields` VALUES (4221, 'Maze_Letha_scheol_unre', NULL, 0);
INSERT INTO `playfields` VALUES (4222, 'Maze_Styx_ado_unre', NULL, 0);
INSERT INTO `playfields` VALUES (4223, 'Maze_Eridan (Unre)', NULL, 0);
INSERT INTO `playfields` VALUES (4224, 'Maze_Phlegethas1 (Unre)', NULL, 0);
INSERT INTO `playfields` VALUES (4310, 'Nascense Frontier', 'NASCFRONTIER', 0);
INSERT INTO `playfields` VALUES (4311, 'Nascense Wilds', 'NASCWILDS', 0);
INSERT INTO `playfields` VALUES (4312, 'Nascense Swamp', 'NASCSWAMP', 0);
INSERT INTO `playfields` VALUES (4313, 'Nascense Training Ground', 'NASCTRAIN', 0);
INSERT INTO `playfields` VALUES (4314, 'Jobe Harbour Gateway', NULL, 1);
INSERT INTO `playfields` VALUES (4315, 'Jobe Market Gateway', NULL, 1);
INSERT INTO `playfields` VALUES (4316, 'Jobe Plaza Gateway', NULL, 1);
INSERT INTO `playfields` VALUES (4318, 'Nascense Portal', NULL, 0);
INSERT INTO `playfields` VALUES (4320, 'Penumbra Forest', 'PENFOREST', 0);
INSERT INTO `playfields` VALUES (4321, 'Penumbra Valley', 'PENVALLEY', 0);
INSERT INTO `playfields` VALUES (4322, 'Penumbra Hollows', 'PENHOLLOW', 0);
INSERT INTO `playfields` VALUES (4324, 'Penumbra Transit', NULL, 1);
INSERT INTO `playfields` VALUES (4327, 'Jobe Apartment Normal', NULL, 1);
INSERT INTO `playfields` VALUES (4328, 'Pandemonium Caina', 'PANDECAINA', 0);
INSERT INTO `playfields` VALUES (4329, 'Pandemonium Antenora', 'PANDEANTENORA', 0);
INSERT INTO `playfields` VALUES (4330, 'Pandemonium Ptolemea', 'PANDEPTOLEMEA', 0);
INSERT INTO `playfields` VALUES (4331, 'Pandemonium Judecca', 'PANDEJUDECCA', 0);
INSERT INTO `playfields` VALUES (4334, 'Rubi-Ka Rumble', NULL, 1);
INSERT INTO `playfields` VALUES (4335, 'Dark Ruins', NULL, 0);
INSERT INTO `playfields` VALUES (4336, 'Alappaa', 'ALAPPAA', 0);
INSERT INTO `playfields` VALUES (4337, 'Albtraum', 'ALB', 0);
INSERT INTO `playfields` VALUES (4341, 'Basic Omni org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4342, 'Basic Clan org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4343, 'Basic Neutral org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4344, 'Advanced Omni org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4345, 'Advanced Clan org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4346, 'Advanced Neutral org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4347, 'Superior Omni org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4348, 'Superior Clan org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4349, 'Superior Neutral org hq', NULL, 0);
INSERT INTO `playfields` VALUES (4350, '...remember rule no. 1', NULL, 0);
INSERT INTO `playfields` VALUES (4351, 'Swimming Pool', NULL, 0);
INSERT INTO `playfields` VALUES (4352, 'Market', NULL, 0);
INSERT INTO `playfields` VALUES (4354, 'Uncle Bazzits Workshop', NULL, 1);
INSERT INTO `playfields` VALUES (4355, 'Basic Player Market', NULL, 1);
INSERT INTO `playfields` VALUES (4356, 'Advanced Player Market', NULL, 1);
INSERT INTO `playfields` VALUES (4357, 'Superior Player Market', NULL, 1);
INSERT INTO `playfields` VALUES (4360, 'Clinique Plastique', NULL, 0);
INSERT INTO `playfields` VALUES (4363, 'Tir Night Club', NULL, 1);
INSERT INTO `playfields` VALUES (4364, 'Unicorn Outpost', 'OUTPOST', 0);
INSERT INTO `playfields` VALUES (4365, 'Sector 13', 'S13', 0);
INSERT INTO `playfields` VALUES (4366, 'Sector 28', 'S28', 0);
INSERT INTO `playfields` VALUES (4367, 'Sector 35', 'S35', 0);
INSERT INTO `playfields` VALUES (4368, 'Unicorn Outpost - Lower level', NULL, 0);
INSERT INTO `playfields` VALUES (4370, 'Sector 42', 'S42', 0);
INSERT INTO `playfields` VALUES (4374, 'Sector 10', 'S10', 0);
INSERT INTO `playfields` VALUES (4376, 'ICC Assembly Hall', NULL, 1);
INSERT INTO `playfields` VALUES (4380, 'Battle Station 20-49', NULL, 0);
INSERT INTO `playfields` VALUES (4381, 'Battle Station 50-74', NULL, 0);
INSERT INTO `playfields` VALUES (4382, 'Battle Station 75-99', NULL, 0);
INSERT INTO `playfields` VALUES (4383, 'Battle Station 100-124', NULL, 0);
INSERT INTO `playfields` VALUES (4384, 'Battle Station 125-149', NULL, 0);
INSERT INTO `playfields` VALUES (4385, 'Battle Station 150-174', NULL, 0);
INSERT INTO `playfields` VALUES (4386, 'Battle Station 175-199', NULL, 0);
INSERT INTO `playfields` VALUES (4387, 'Battle Station 200-209', NULL, 0);
INSERT INTO `playfields` VALUES (4388, 'Battle Station 215-220', NULL, 0);
INSERT INTO `playfields` VALUES (4389, 'Caina', NULL, 0);
INSERT INTO `playfields` VALUES (4390, 'Ptolemea', NULL, 0);
INSERT INTO `playfields` VALUES (4391, 'Judecca', NULL, 0);
INSERT INTO `playfields` VALUES (4468, 'Sector 7', 'S7', 0);
INSERT INTO `playfields` VALUES (4504, 'West Buggy (DONT DELETE)', NULL, 0);
INSERT INTO `playfields` VALUES (4505, 'South Buggy (DONT DELETE)', NULL, 0);
INSERT INTO `playfields` VALUES (4524, 'Elysium_pre-split', NULL, 0);
INSERT INTO `playfields` VALUES (4525, 'Jobe', 'JOBE', 0);
INSERT INTO `playfields` VALUES (4526, 'Jobe_pre-split', NULL, 0);
INSERT INTO `playfields` VALUES (4530, 'Jobe Platform', 'PLATFORM', 0);
INSERT INTO `playfields` VALUES (4531, 'Jobe Harbor', 'HARBOR', 0);
INSERT INTO `playfields` VALUES (4532, 'Jobe Market', 'MARKET', 0);
INSERT INTO `playfields` VALUES (4533, 'Jobe Plaza', 'PLAZA', 0);
INSERT INTO `playfields` VALUES (4534, 'Jobe Apartment', NULL, 0);
INSERT INTO `playfields` VALUES (4540, 'Elysium South', 'ELYSOUTH', 0);
INSERT INTO `playfields` VALUES (4541, 'Elysium West', 'ELYWEST', 0);
INSERT INTO `playfields` VALUES (4542, 'Elysium', 'ELY', 0);
INSERT INTO `playfields` VALUES (4543, 'Elysium East', 'ELYEAST', 0);
INSERT INTO `playfields` VALUES (4544, 'Elysium North', 'ELYNORTH', 0);
INSERT INTO `playfields` VALUES (4561, 'Arrival Hall Gateway', NULL, 1);
INSERT INTO `playfields` VALUES (4563, 'Hardware Dimension - Basic', NULL, 0);
INSERT INTO `playfields` VALUES (4564, 'Hardware Dimension - Advanced', NULL, 0);
INSERT INTO `playfields` VALUES (4565, 'Hardware Dimenion - Superior', NULL, 0);
INSERT INTO `playfields` VALUES (4567, 'Dimensional Shift - Basic', NULL, 0);
INSERT INTO `playfields` VALUES (4568, 'Dimensional Shift - Advanced', NULL, 0);
INSERT INTO `playfields` VALUES (4569, 'Dimensional Shift - Superior', NULL, 0);
INSERT INTO `playfields` VALUES (4571, 'Heavenly Business - Basic', NULL, 0);
INSERT INTO `playfields` VALUES (4572, 'Heavenly Business - Advanced', NULL, 0);
INSERT INTO `playfields` VALUES (4573, 'Heavenly Business - Superior', NULL, 0);
INSERT INTO `playfields` VALUES (4575, 'IPS Interior - Basic', NULL, 0);
INSERT INTO `playfields` VALUES (4576, 'IPS Interior - Advanced', NULL, 0);
INSERT INTO `playfields` VALUES (4577, 'IPS Interior - Superior', NULL, 0);
INSERT INTO `playfields` VALUES (4582, 'ICC Shuttleport', NULL, 0);
INSERT INTO `playfields` VALUES (4604, 'Arrival_hall', 'ARRIVALHALL', 0);
INSERT INTO `playfields` VALUES (4605, 'Inferno', 'INF', 0);
INSERT INTO `playfields` VALUES (4621, 'Redeemed Temple (Elysium)', NULL, 0);
INSERT INTO `playfields` VALUES (4622, 'Unredeemed Temple (ELysium)', NULL, 0);
INSERT INTO `playfields` VALUES (4623, 'Redeemed Temple (Scheol)', NULL, 0);
INSERT INTO `playfields` VALUES (4624, 'Unredeemed Temple (Scheol)', NULL, 0);
INSERT INTO `playfields` VALUES (4625, 'Redeemed Temple (Adonis)', NULL, 0);
INSERT INTO `playfields` VALUES (4626, 'Unredeemed Temple (Adonis)', NULL, 0);
INSERT INTO `playfields` VALUES (4627, 'Redeemed Temple (Penumbra)', NULL, 0);
INSERT INTO `playfields` VALUES (4628, 'Unredeemed Temple (Penumbra)', NULL, 0);
INSERT INTO `playfields` VALUES (4629, 'Redeemed Temple (Inferno)', NULL, 0);
INSERT INTO `playfields` VALUES (4630, 'Unredeemed Temple (Inferno)', NULL, 0);
INSERT INTO `playfields` VALUES (4676, 'Garden of Redeemed Nascense', NULL, 0);
INSERT INTO `playfields` VALUES (4677, 'Garden_of_unredeemed Nascense', NULL, 0);
INSERT INTO `playfields` VALUES (4678, 'Garden of Redeemed Elysium', NULL, 0);
INSERT INTO `playfields` VALUES (4679, 'Garden of Redeemed Elysium2', NULL, 0);
INSERT INTO `playfields` VALUES (4680, 'Garden_of_unredeemed Elysium', NULL, 0);
INSERT INTO `playfields` VALUES (4681, 'Garden_of_unredeemed Elysium2', NULL, 0);
INSERT INTO `playfields` VALUES (4682, 'Garden of Redeemed Scheol', NULL, 0);
INSERT INTO `playfields` VALUES (4683, 'Garden_of_unredeemed Scheol', NULL, 0);
INSERT INTO `playfields` VALUES (4684, 'Garden of Redeemed Adonis', NULL, 0);
INSERT INTO `playfields` VALUES (4685, 'Garden of Redeemed Adonis2', NULL, 0);
INSERT INTO `playfields` VALUES (4686, 'Garden_of_unredeemed Adonis', NULL, 0);
INSERT INTO `playfields` VALUES (4687, 'Garden_of_unredeemed Adonis2', NULL, 0);
INSERT INTO `playfields` VALUES (4688, 'Garden of Redeemed Penumbra', NULL, 0);
INSERT INTO `playfields` VALUES (4689, 'Garden of Redeemed Penumbra2', NULL, 0);
INSERT INTO `playfields` VALUES (4690, 'Garden_of_unredeemed Penumbra', NULL, 0);
INSERT INTO `playfields` VALUES (4691, 'Garden_of_unredeemed Penumbra2', NULL, 0);
INSERT INTO `playfields` VALUES (4692, 'Garden of Redeemed Inferno', NULL, 0);
INSERT INTO `playfields` VALUES (4693, 'Garden of Redeemed Inferno2', NULL, 0);
INSERT INTO `playfields` VALUES (4694, 'Garden_of_unredeemed Inferno', NULL, 0);
INSERT INTO `playfields` VALUES (4695, 'Garden_of_unredeemed Inferno2', NULL, 0);
INSERT INTO `playfields` VALUES (4696, 'Garden of Redeemed Pandemonium', NULL, 0);
INSERT INTO `playfields` VALUES (4697, 'Garden of unredeemed Pandemonium', NULL, 0);
INSERT INTO `playfields` VALUES (4698, 'Garden of Redeemed Scheol2', NULL, 0);
INSERT INTO `playfields` VALUES (4699, 'Garden_of_unredeemed Scheol2', NULL, 0);
INSERT INTO `playfields` VALUES (4704, 'Booster Shop (dungeon)', NULL, 0);
INSERT INTO `playfields` VALUES (4805, 'The Crypt of Home', NULL, 0);
INSERT INTO `playfields` VALUES (4833, 'Teleport Tower', NULL, 0);
INSERT INTO `playfields` VALUES (4872, 'Adonis City', 'ADOCITY', 0);
INSERT INTO `playfields` VALUES (4873, 'Adonis Abyss', 'ADO', 0);
INSERT INTO `playfields` VALUES (4877, 'Adonis Hallway', NULL, 0);
INSERT INTO `playfields` VALUES (4880, 'Scheol Upper', 'SCHEOLUPPER', 0);
INSERT INTO `playfields` VALUES (4881, 'Scheol Lower', 'SCHEOLLOWER', 0);
INSERT INTO `playfields` VALUES (4885, 'Shadow Crypt', NULL, 0);
INSERT INTO `playfields` VALUES (4894, 'Coast of Harmony', NULL, 0);
INSERT INTO `playfields` VALUES (4898, 'Broken Shores AI movie', NULL, 0);
INSERT INTO `playfields` VALUES (4899, 'Broken Shores AI Demo', NULL, 0);
INSERT INTO `playfields` VALUES (5001, 'Playa del Desierto', NULL, 0);
INSERT INTO `playfields` VALUES (5002, 'Montroyal City', NULL, 0);
INSERT INTO `playfields` VALUES (6001, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6002, 'Sunrise Station', NULL, 0);
INSERT INTO `playfields` VALUES (6003, 'The Dig Site', NULL, 0);
INSERT INTO `playfields` VALUES (6007, 'Unicorn Defence Hub', NULL, 0);
INSERT INTO `playfields` VALUES (6010, 'Serenity Islands', NULL, 0);
INSERT INTO `playfields` VALUES (6011, 'Arid Rift', 'ARID', 0);
INSERT INTO `playfields` VALUES (6012, 'Neretva Canyon', NULL, 0);
INSERT INTO `playfields` VALUES (6013, 'Central Gateway', NULL, 0);
INSERT INTO `playfields` VALUES (6014, 'Inside The Ruin', NULL, 0);
INSERT INTO `playfields` VALUES (6015, 'The Elder Hall', NULL, 0);
INSERT INTO `playfields` VALUES (6017, 'Teachers Chamber', NULL, 0);
INSERT INTO `playfields` VALUES (6020, 'Xan Hub Tower Room 1', NULL, 0);
INSERT INTO `playfields` VALUES (6021, 'Xan Tower', NULL, 0);
INSERT INTO `playfields` VALUES (6022, 'Area X', NULL, 0);
INSERT INTO `playfields` VALUES (6024, 'Sealed Antechamber', NULL, 1);
INSERT INTO `playfields` VALUES (6028, 'Santa Leet Event', NULL, 1);
INSERT INTO `playfields` VALUES (6035, 'Dark Ruins', NULL, 0);
INSERT INTO `playfields` VALUES (6036, 'Dark Ruins', NULL, 0);
INSERT INTO `playfields` VALUES (6041, 'Inside The Ruin', NULL, 0);
INSERT INTO `playfields` VALUES (6050, 'Serenity Islands', NULL, 0);
INSERT INTO `playfields` VALUES (6051, 'Serenity Islands', NULL, 0);
INSERT INTO `playfields` VALUES (6055, 'Inside The Machine', NULL, 0);
INSERT INTO `playfields` VALUES (6056, 'Dust Brigade Research Facility', NULL, 0);
INSERT INTO `playfields` VALUES (6057, 'Dust Brigade Research Facility 2', NULL, 0);
INSERT INTO `playfields` VALUES (6060, 'Profspecroom', NULL, 0);
INSERT INTO `playfields` VALUES (6061, 'Engineers Dugout', NULL, 0);
INSERT INTO `playfields` VALUES (6071, 'The Grind', NULL, 0);
INSERT INTO `playfields` VALUES (6101, 'Three Craters West', '3CW', 0);
INSERT INTO `playfields` VALUES (6102, 'Three Craters East', '3CE', 0);
INSERT INTO `playfields` VALUES (6104, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6111, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6112, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6113, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6115, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6121, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6123, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6125, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6127, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6129, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6131, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6133, 'Sauna', NULL, 0);
INSERT INTO `playfields` VALUES (6211, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (6300, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6301, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6302, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6303, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6304, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6305, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6306, 'SBC-Xpm Site Alpha-Romeo 29', NULL, 0);
INSERT INTO `playfields` VALUES (6550, 'Uturn Canyon', 'UC', 0);
INSERT INTO `playfields` VALUES (6551, 'Uturn Forest', 'UF', 0);
INSERT INTO `playfields` VALUES (6553, 'Arete', 'ARETE', 0);
INSERT INTO `playfields` VALUES (7001, 'Palmiero''s Office', NULL, 0);
INSERT INTO `playfields` VALUES (7010, 'DOJA Research', NULL, 0);
INSERT INTO `playfields` VALUES (7011, 'Omni Tek Agency', NULL, 0);
INSERT INTO `playfields` VALUES (7012, 'Clan Quest HQ', NULL, 0);
INSERT INTO `playfields` VALUES (7013, 'Antiques and more', NULL, 0);
INSERT INTO `playfields` VALUES (7015, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (7051, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (7054, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (7092, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (7101, 'Freighter headed to ICC - Andromeda', NULL, 0);
INSERT INTO `playfields` VALUES (8002, 'Phasefront Racetrack', NULL, 0);
INSERT INTO `playfields` VALUES (8004, 'Area', NULL, 0);
INSERT INTO `playfields` VALUES (8006, 'Generetic Corp. Offices', NULL, 0);
INSERT INTO `playfields` VALUES (8040, 'Foundry of Nightmares', NULL, 0);
INSERT INTO `playfields` VALUES (8045, 'Foundry of Nightmares', NULL, 0);
INSERT INTO `playfields` VALUES (8046, 'Foundry of Nightmares', NULL, 0);
INSERT INTO `playfields` VALUES (8050, 'Foundry of Nightmares', NULL, 0);
INSERT INTO `playfields` VALUES (8080, 'Santa Leet Event - Aliums', NULL, 0);
