DROP TABLE IF EXISTS playfields;
CREATE TABLE playfields (id SMALLINT PRIMARY KEY NOT NULL, long_name VARCHAR(250) NOT NULL UNIQUE, short_name VARCHAR(30) UNIQUE);
INSERT INTO playfields (id, long_name, short_name) VALUES (760, '4 Holes', '4HO');
INSERT INTO playfields (id, long_name, short_name) VALUES (655, 'Andromeda', 'AND');
INSERT INTO playfields (id, long_name, short_name) VALUES (585, 'Aegean', 'AEG');
INSERT INTO playfields (id, long_name, short_name) VALUES (540, 'Old Athen', 'OA');
INSERT INTO playfields (id, long_name, short_name) VALUES (550, 'Athen Shire', 'AS');
INSERT INTO playfields (id, long_name, short_name) VALUES (545, 'West Athens', 'WA');
INSERT INTO playfields (id, long_name, short_name) VALUES (505, 'Avalon', 'AV');
INSERT INTO playfields (id, long_name, short_name) VALUES (605, 'Belial Forest', 'BF');
INSERT INTO playfields (id, long_name, short_name) VALUES (800, 'Borealis', 'BOR');
INSERT INTO playfields (id, long_name, short_name) VALUES (665, 'Broken Shores', 'BS');
INSERT INTO playfields (id, long_name, short_name) VALUES (590, 'Central Artery Valley', 'CAV');
INSERT INTO playfields (id, long_name, short_name) VALUES (670, 'Clondyke', 'CLON');
INSERT INTO playfields (id, long_name, short_name) VALUES (556, 'Coast of Peace', 'CP');
INSERT INTO playfields (id, long_name, short_name) VALUES (656, 'Coast of Tranquility', 'CT');
INSERT INTO playfields (id, long_name, short_name) VALUES (595, 'Deep Artery Valley', 'DAV');
INSERT INTO playfields (id, long_name, short_name) VALUES (620, 'Eastern Fouls Plain', 'EFP');
INSERT INTO playfields (id, long_name, short_name) VALUES (685, 'Galway County', 'GC');
INSERT INTO playfields (id, long_name, short_name) VALUES (687, 'Galway Shire', 'GS');
INSERT INTO playfields (id, long_name, short_name) VALUES (717, 'Greater Omni Forest', 'GOF');
INSERT INTO playfields (id, long_name, short_name) VALUES (647, 'Greater Tir County', 'GTC');
INSERT INTO playfields (id, long_name, short_name) VALUES (791, 'Holes in the Wall', 'HITW');
INSERT INTO playfields (id, long_name, short_name) VALUES (695, 'Lush Fields', 'LF');
INSERT INTO playfields (id, long_name, short_name) VALUES (625, 'Milky Way', 'MW');
INSERT INTO playfields (id, long_name, short_name) VALUES (560, 'Mort', 'MORT');
INSERT INTO playfields (id, long_name, short_name) VALUES (696, 'Mutant Domain', 'MD');
INSERT INTO playfields (id, long_name, short_name) VALUES (567, 'Newland', 'NL');
INSERT INTO playfields (id, long_name, short_name) VALUES (566, 'Newland City', 'NC');
INSERT INTO playfields (id, long_name, short_name) VALUES (565, 'Newland Desert', 'NLD');
INSERT INTO playfields (id, long_name, short_name) VALUES (716, 'Omni Forest', 'OF');
INSERT INTO playfields (id, long_name, short_name) VALUES (705, 'Omni-1 Entertainment', 'ENT');
INSERT INTO playfields (id, long_name, short_name) VALUES (700, 'Omni-1 HQ', 'OHQ');
INSERT INTO playfields (id, long_name, short_name) VALUES (710, 'Omni-1 Trade', 'OT');
INSERT INTO playfields (id, long_name, short_name) VALUES (570, 'Perpetual Wastelands', 'PW');
INSERT INTO playfields (id, long_name, short_name) VALUES (630, 'Pleasant Meadows', 'PM');
INSERT INTO playfields (id, long_name, short_name) VALUES (735, 'Rome Blue', 'RB');
INSERT INTO playfields (id, long_name, short_name) VALUES (740, 'Rome Green', 'RG');
INSERT INTO playfields (id, long_name, short_name) VALUES (730, 'Rome Red', 'RR');
INSERT INTO playfields (id, long_name, short_name) VALUES (610, 'Southern Artery Valley', 'SAV');
INSERT INTO playfields (id, long_name, short_name) VALUES (615, 'Southern Fouls Hills', 'SFH');
INSERT INTO playfields (id, long_name, short_name) VALUES (635, 'Stret East Bank', 'SEB');
INSERT INTO playfields (id, long_name, short_name) VALUES (790, 'Stret West Bank', 'SWB');
INSERT INTO playfields (id, long_name, short_name) VALUES (795, 'The Longest Road', 'TLR');
INSERT INTO playfields (id, long_name, short_name) VALUES (640, 'Tir', 'TIR');
INSERT INTO playfields (id, long_name, short_name) VALUES (646, 'Tir County', 'TC');
INSERT INTO playfields (id, long_name, short_name) VALUES (650, 'Upper Stret East Bank', 'USEB');
INSERT INTO playfields (id, long_name, short_name) VALUES (600, 'Varmint Woods', 'VW');
INSERT INTO playfields (id, long_name, short_name) VALUES (551, 'Wailing Wastes', 'WW');
INSERT INTO playfields (id, long_name, short_name) VALUES (586, 'Wartorn Valley', 'WV');
INSERT INTO playfields (id, long_name, short_name) VALUES (6550, 'Uturn Canyon', 'UC');
INSERT INTO playfields (id, long_name, short_name) VALUES (6551, 'Uturn Forest', 'UF'); 
INSERT INTO playfields (id, long_name, short_name) VALUES (6102, 'Three Craters East', '3CE');
INSERT INTO playfields (id, long_name, short_name) VALUES (6101, 'Three Craters West', '3CW');
INSERT INTO playfields (id, long_name, short_name) VALUES (6553, 'Arete', 'ARETE');
INSERT INTO playfields (id, long_name, short_name) VALUES (750, 'The Reck', 'RECK');


--SL
INSERT INTO playfields (id, long_name, short_name) VALUES (4872, 'Adonis City', 'ADOCITY');
INSERT INTO playfields (id, long_name, short_name) VALUES (4873, 'Adonis Abyss', 'ADO');
INSERT INTO playfields (id, long_name, short_name) VALUES (4542, 'Elysium', 'ELY');
INSERT INTO playfields (id, long_name, short_name) VALUES (4543, 'Elysium East', 'ELYEAST');
INSERT INTO playfields (id, long_name, short_name) VALUES (4544, 'Elysium North', 'ELYNORTH');
INSERT INTO playfields (id, long_name, short_name) VALUES (4540, 'Elysium South', 'ELYSOUTH');
INSERT INTO playfields (id, long_name, short_name) VALUES (4541, 'Elysium West', 'ELYWEST');
INSERT INTO playfields (id, long_name, short_name) VALUES (4605, 'Inferno', 'INF');
INSERT INTO playfields (id, long_name, short_name) VALUES (4005, 'Inferno Burning Marshes', 'INFMARSHES');
INSERT INTO playfields (id, long_name, short_name) VALUES (4531, 'Jobe Harbor', 'HARBOR');
INSERT INTO playfields (id, long_name, short_name) VALUES (4532, 'Jobe Market', 'MARKET');
INSERT INTO playfields (id, long_name, short_name) VALUES (4530, 'Jobe Platform', 'PLATFORM');
INSERT INTO playfields (id, long_name, short_name) VALUES (4533, 'Jobe Plaza', 'PLAZA');
INSERT INTO playfields (id, long_name, short_name) VALUES (4001, 'Jobe Research', 'RESEARCH');
INSERT INTO playfields (id, long_name, short_name) VALUES (4310, 'Nascense Frontier', 'NASCFRONTIER');
INSERT INTO playfields (id, long_name, short_name) VALUES (4312, 'Nascense Swamp', 'NASCSWAMP');
INSERT INTO playfields (id, long_name, short_name) VALUES (4311, 'Nascense Wilds', 'NASCWILDS');
INSERT INTO playfields (id, long_name, short_name) VALUES (4320, 'Penumbra Forest', 'PENFOREST');
INSERT INTO playfields (id, long_name, short_name) VALUES (4322, 'Penumbra Hollow', 'PENHOLLOW');
INSERT INTO playfields (id, long_name, short_name) VALUES (4321, 'Penumbra Valley', 'PENVALLEY');
INSERT INTO playfields (id, long_name, short_name) VALUES (4329, 'Pandemonium Antenora', 'PANDEANTENORA');
INSERT INTO playfields (id, long_name, short_name) VALUES (4328, 'Pandemonium Caina', 'PANDECAINA');
INSERT INTO playfields (id, long_name, short_name) VALUES (4331, 'Pandemonium Judecca', 'PANDEJUDECCA');
INSERT INTO playfields (id, long_name, short_name) VALUES (4330, 'Pandemonium Ptolemea', 'PANDEPTOLEMEA');
INSERT INTO playfields (id, long_name, short_name) VALUES (4880, 'Scheol Upper', 'SCHEOLUPPER');
INSERT INTO playfields (id, long_name, short_name) VALUES (4881, 'Scheol Lower', 'SCHEOLLOWER');
