{
  "reload_lang": {
    "en_US": "Language changed to <highlight>{lang_code}</highlight>",
    "de_DE": "Die Sprache wurde auf <highlight>{lang_code}</highlight> geändert."
  },
  "current_lang": {
    "en_US": "My current language is <highlight>{lang_code}</highlight>",
    "de_DE": "Meine aktuelle Sprache ist <highlight>{lang_code}</highlight>."
  },
  "clear_queue": {
    "en_US": "Cleared <highlight>{count}</highlight> messages from the outgoing message queue.",
    "de_DE": "Es wurden <highlight>{count}</highlight> Nachrichten aus der ausgehenden Nachrichten warteschlange entfernt."
  },
  "runas_fail": {
    "en_US": "Error! You must have a higher access level than <highlight>{char}</highlight>.",
    "de_DE": "Error! Du musst ein höheres Rechtelevel haben als <highlight>{char}</highlight>."
  },
  "msg_sent": {
    "en_US": "Your message has been sent.",
    "de_DE": "Deine Nachricht wurde erfolgreich gesendet."
  },
  "sql_exec_success": {
    "en_US": "{count} row(s) affected.",
    "de_DE": "{count} Zeile(n) betroffen."
  },
  "sql_fail": {
    "en_US": "There was an error executing your query: {error}",
    "de_DE": "Bei der Bearbeitung deiner Anfrage ist ein Fehler aufgetreten: {error}"
  },
  "sql_blob_title": {
    "en_US": "Results ({count})",
    "de_DE": "Ergebnisse ({count})"
  },
  "expected_online": {
    "en_US": "<myname> is now <green>online</green>.",
    "de_DE": "<myname> ist wieder <green>online</green>."
  },
  "unexpected_online": {
    "en_US": "<myname> is now <green>online</green> but may have shut down or restarted unexpectedly.",
    "de_DE": "<myname> ist wieder <green>online</green>, wurde aber möglicherweise unerwartet heruntergefahren, oder neugestartet."
  },
  "shutdown": {
    "en_US": "The bot is shutting down.",
    "de_DE": "Der Bot wird heruntergefahren."
  },
  "restart": {
    "en_US": "The bot is restarting.",
    "de_DE": "Der Bot startet nun neu."
  },
  "reason": {
    "en_US": " <highlight>Reason: {reason}</highlight>",
    "de_DE": " <highlight>Der Grund hierfür: {reason}</highlight>"
  },
  "check_access": {
    "en_US": "Access level for <highlight>{char}</highlight> is <highlight>{rank_main}</highlight> ({rank_self}).",
    "de_DE": "Das Zugriffslevel für <highlight>{char}</highlight> ist <highlight>{rank_main}</highlight> ({rank_self})."
  },
  "show_output_target": {
    "en_US": "<highlight>{sender}</highlight> is showing you output for command <highlight>{cmd}</highlight>:",
    "de_DE": "<highlight>{sender}</highlight> zeigt dir den output des Befehls <highlight>{cmd}</highlight>:"
  },
  "show_output_self": {
    "en_US": "Command <highlight>{cmd}</highlight> output has been sent to <highlight>{target}</highlight>.",
    "de_DE": "Die Ausgabe des Befehls <highlight>{cmd}</highlight> wurde an <highlight>{target}</highlight> weitergeleitet."
  },
  "status_blob": {
    "en_US": [
      "Version: <highlight>Tyrbot {bot_ver}</highlight>\n",
      "Name: <highlight><myname></highlight>\n",
      "\n",
      "OS: <highlight>{os_ver}</highlight>\n",
      "Python: <highlight>{python_ver}</highlight>\n",
      "Database: <highlight>{db_type}</highlight>\n",
      "Memory Usage: <highlight>{mem_usage} KB</highlight>\n",
      "\n",
      "Superadmin: <highlight>{superadmin}</highlight>\n",
      "Buddy List: <highlight>{bl_used}/{bl_size}</highlight>\n",
      "Uptime: <highlight>{uptime}</highlight>\n",
      "Dimension: <highlight>{dim}</highlight>\n",
      "\n",
      "Org Id: <highlight>{org_id}</highlight>\n",
      "Org Name: <highlight>{org_name}</highlight>\n",
      "\n",
      "<pagebreak><header2>Bots Connected</header2>\n",
      "{bots_connected}",
      "\n",
      "<pagebreak><header2>Public Channels</header2>\n",
      "{pub_channels}",
      "\n",
      "<pagebreak><header2>Event Types</header2>\n",
      "{event_types}",
      "\n",
      "<pagebreak><header2>Access Levels</header2>\n",
      "{access_levels}",
    ],
    "de_DE": [
      "Version: <highlight>Tyrbot {bot_ver}</highlight>\n",
      "Name: <highlight><myname></highlight>\n",
      "\n",
      "Betriebssystem: <highlight>{os_ver}</highlight>\n",
      "Python: <highlight>{python_ver}</highlight>\n",
      "Datenbank: <highlight>{db_type}</highlight>\n",
      "Arbeitsspeichernutzung: <highlight>{mem_usage} KB</highlight>\n",
      "\n",
      "Superadmin: <highlight>{superadmin}</highlight>\n",
      "Freundesliste: <highlight>{bl_used}/{bl_size}</highlight>\n",
      "Onlinezeit: <highlight>{uptime}</highlight>\n",
      "Dimension: <highlight>{dim}</highlight>\n",
      "\n",
      "Org ID: <highlight>{org_id}</highlight>\n",
      "Org Name: <highlight>{org_name}</highlight>\n",
      "\n",
      "<pagebreak><header2>Bots Connected</header2>\n",
      "{bots_connected}",
      "\n",
      "<pagebreak><header2>Öffentliche Channel</header2>\n",
      "{pub_channels}",
      "\n",
      "<pagebreak><header2>Event Typen</header2>\n",
      "{event_types}",
      "\n",
      "<pagebreak><header2>Zugriffslevel</header2>\n",
      "{access_levels}",
      "\n"
    ]
  },
  "status_title": {
    "en_US": "System Info",
    "de_DE": "Systeminformationen"
  },
  "messagehub_title": {
    "en_US": "Message Hub Subscriptions ({count})"
  },
  "messagehub_info": {
    "en_US": "Destinations are listed below, along with the sources they are subscribed to."
  },
  "subscribed": {
    "en_US": "Subscribed"
  },
  "unsubscribed": {
    "en_US": "Unsubscribed"
  },
  "messagehub_edit_title": {
    "en_US": "{destination} Subscriptions ({count})"
  },
  "messagehub_already_subscribed": {
    "en_US": "Destination <highlight>{destination}</highlight> is already subscribed to source <highlight>{source}</highlight>."
  },
  "messagehub_not_subscribed": {
    "en_US": "Destination <highlight>{destination}</highlight> is not subscribed to source <highlight>{source}</highlight>."
  },
  "messagehub_invalid_subscription": {
    "en_US": "Destination <highlight>{destination}</highlight> cannot be subscribed to source <highlight>{source}</highlight>."
  },
  "messagehub_subscribe_success": {
    "en_US": "Destination <highlight>{destination}</highlight> has been subscribed to source <highlight>{source}</highlight> successfully."
  },
  "messagehub_unsubscribe_success": {
    "en_US": "Destination <highlight>{destination}</highlight> has been unsubscribed from source <highlight>{source}</highlight> successfully."
  },
  "destination_not_exist": {
    "en_US": "Destination <highlight>{destination}</highlight> does not exist."
  }
}
