{
  "reload_lang": {
    "en_US": "Language changed to <highlight>{lang_code}<end>",
    "de_DE": "Die Sprache wurde auf <highlight>{lang_code}<end> geändert."
  },
  "current_lang": {
    "en_US": "My current language is <highlight>{lang_code}<end>",
    "de_DE": "Meine aktuelle Sprache ist <highlight>{lang_code}<end>."
  },
  "clear_queue": {
    "en_US": "Cleared <highlight>{count}<end> messages from the outgoing message queue.",
    "de_DE": "Es wurden <highlight>{count}<end> Nachrichten aus der ausgehenden Nachrichten warteschlange entfernt."
  },
  "runas_fail": {
    "en_US": "Error! You must have a higher access level than <highlight>{char}<end>.",
    "de_DE": "Error! Du musst ein höheres Rechtelevel haben als <highlight>{char}<end>."
  },
  "msg_sent": {
    "en_US": "Your message has been sent.",
    "de_DE": "Deine Nachricht wurde erfolgreich gesendet."
  },
  "sql_exec_success": {
    "en_US": "{count} row(s) affected.",
    "de_DE": "{count} Zeile(n) betroffen."
  },
  "sql_fail": {
    "en_US": "There was an error executing your query: {error}",
    "de_DE": "Bei der Bearbeitung deiner Anfrage ist ein Fehler aufgetreten: {error}"
  },
  "sql_blob_title": {
    "en_US": "Results ({count})",
    "de_DE": "Ergebnisse ({count})"
  },
  "expected_online": {
    "en_US": "<myname> is now <green>online<end>.",
    "de_DE": "<myname> ist wieder <green>online<end>."
  },
  "unexpected_online": {
    "en_US": "<myname> is now <green>online<end> but may have shut down or restarted unexpectedly.",
    "de_DE": "<myname> ist wieder <green>online<end>, wurde aber möglicherweise unerwartet heruntergefahren, oder neugestartet."
  },
  "shutdown": {
    "en_US": "The bot is shutting down.",
    "de_DE": "Der Bot wird heruntergefahren."
  },
  "restart": {
    "en_US": "The bot is restarting.",
    "de_DE": "Der Bot startet nun neu."
  },
  "reason": {
    "en_US": " <highlight>Reason: {reason}<end>",
    "de_DE": " <highlight>Der Grund hierfür: {reason}<end>"
  },
  "check_access": {
    "en_US": "Access level for <highlight>{char}<end><end> is <highlight>{rank_main}<end> ({rank_self}).",
    "de_DE": "Das Zugriffslevel für <highlight>{char}<end> ist <highlight>{rank_main}<end> ({rank_self})."
  },
  "show_output_target": {
    "en_US": "<highlight>{sender}<end> is showing you output for command <highlight>{cmd}<end>:",
    "de_DE": "<highlight>{sender}<end> zeigt dir den output des Befehls <highlight>{cmd}<end>:"
  },
  "show_output_self": {
    "en_US": "Command <highlight>{cmd}<end> output has been sent to <highlight>{target}<end>.",
    "de_DE": "Die Ausgabe des Befehls <highlight>{cmd}<end> wurde an <highlight>{target}<end> weitergeleitet."
  },
  "status_blob": {
    "en_US": [
      "Version: <highlight>Tyrbot {bot_ver}<end>\n",
      "Name: <highlight><myname><end>\n",
      "\n",
      "OS: <highlight>{os_ver}<end>\n",
      "Python: <highlight>{python_ver}<end>\n",
      "Database: <highlight>{db_type}<end>\n",
      "Memory Usage: <highlight>{mem_usage} KB<end>\n",
      "\n",
      "Superadmin: <highlight>{superadmin}<end>\n",
      "Buddy List: <highlight>{bl_used}/{bl_size}<end>\n",
      "Uptime: <highlight>{uptime}<end>\n",
      "Dimension: <highlight>{dim}<end>\n",
      "\n",
      "Org Id: <highlight>{org_id}<end>\n",
      "Org Name: <highlight>{org_name}<end>\n",
      "\n",
      "<pagebreak><header2>Public Channels<end>\n",
      "{pub_channels}",
      "\n",
      "<pagebreak><header2>Event Types<end>\n",
      "{event_types}",
      "\n",
      "<pagebreak><header2>Access Levels<end>\n",
      "{access_levels}",
      "\n"
    ],
    "de_DE": [
      "Version: <highlight>Tyrbot {bot_ver}<end>\n",
      "Name: <highlight><myname><end>\n",
      "\n",
      "Betriebssystem: <highlight>{os_ver}<end>\n",
      "Python: <highlight>{python_ver}<end>\n",
      "Datenbank: <highlight>{db_type}<end>\n",
      "Arbeitsspeichernutzung: <highlight>{mem_usage} KB<end>\n",
      "\n",
      "Superadmin: <highlight>{superadmin}<end>\n",
      "Freundesliste: <highlight>{bl_used}/{bl_size}<end>\n",
      "Onlinezeit: <highlight>{uptime}<end>\n",
      "Dimension: <highlight>{dim}<end>\n",
      "\n",
      "Org ID: <highlight>{org_id}<end>\n",
      "Org Name: <highlight>{org_name}<end>\n",
      "\n",
      "<pagebreak><header2>Öffentliche Channel<end>\n",
      "{pub_channels}",
      "\n",
      "<pagebreak><header2>Event Typen<end>\n",
      "{event_types}",
      "\n",
      "<pagebreak><header2>Zugriffslevel<end>\n",
      "{access_levels}",
      "\n"
    ]
  },
  "status_title": {
    "en_US": "System Info",
    "de_DE": "Systeminformationen"
  }
}