{

  "list_blob": {
    "en_US": [
      "<pagebreak>Name: <highlight>{char}</highlight>\n",
      "Added: <highlight>{added_time}</highlight>\n",
      "By: <highlight>{banner}</highlight>\n",
      "Ends: <highlight>{end_time}</highlight>{left}\n",
      "Reason: <highlight>{reason}</highlight>\n\n"
    ],
    "de_DE": [
      "<pagebreak>Name: <highlight>{char}</highlight>\n",
      "Hinzugefuegt: <highlight>{added_time}</highlight>\n",
      "Von: <highlight>{banner}</highlight>\n",
      "Endet: <highlight>{end_time}</highlight>{left}\n",
      "Grund: <highlight>{reason}</highlight>\n\n"

    ]
  },
  "list": {
    "en_US": "Ban List ({amount})"
  },
  "not_banned": {
    "en_US": "<highlight>{char}</highlight> is not banned.",
    "de_DE": "<highlight>{char}</highlight> ist nicht gebannt."
  },
  "unbanned_target": {
    "en_US": "You have been unbanned by <highlight>{char}</highlight>.",
    "de_DE": "Du wurdest von <highlight>{char}</highlight> entbannt."
  },
  "unbanned_self": {
    "en_US": "<highlight>{char}</highlight> has been removed from the ban list.",
    "de_DE": "Du hast <highlight>{char}</highlight> entbannt."
  },
  "already_banned": {
    "en_US": "<highlight>{char}</highlight> is already banned.",
    "de_DE": "<highlight>{char}</highlight> ist bereits gebannt."
  },
  "banned_target_1": {
    "en_US": "You have been banned by <highlight>{banner}</highlight> for reason: <highlight>{reason}</highlight>. Duration: <highlight>{duration}</highlight>.",
    "de_DE": "Du wurdest von <highlight>{banner}</highlight> gebannt. Dauer: <highlight>{duration}</highlight>. Der Grund war: <highlight>{reason}</highlight>"
  },
  "banned_target_2": {
    "en_US": "You have been banned by <highlight>{banner}</highlight>. Duration: <highlight>{duration}</highlight>.",
    "de_DE": "Du wurdest von <highlight>{banner}</highlight> gebannt - Dauer: <highlight>{duration}</highlight> gebannt."
  },
  "banned_self": {
    "en_US": "<highlight>{char}</highlight> has been added to the ban list.",
    "de_DE": "<highlight>{char}</highlight> wurde gebannt."
  }
}
