{

  "list_blob": {
    "en_US": [
      "<pagebreak>Name: <highlight>{char}<end>\n",
      "Added: <highlight>{added_time}<end>\n",
      "By: <highlight>{banner}<end>\n",
      "Ends: <highlight>{end_time}<end>{left}\n",
      "Reason: <highlight>{reason}<end>\n\n"
    ],
    "de_DE": [
      "<pagebreak>Name: <highlight>{char}<end>\n",
      "Hinzugefuegt: <highlight>{added_time}<end>\n",
      "Von: <highlight>{banner}<end>\n",
      "Endet: <highlight>{end_time}<end>{left}\n",
      "Grund: <highlight>{reason}<end>\n\n"

    ]
  },
  "list": {
    "en_US": "Ban List ({amount})"
  },
  "not_banned": {
    "en_US": "<highlight>{char}<end> is not banned.",
    "de_DE": "<highlight>{char}<end> ist nicht gebannt."
  },
  "unbanned_target": {
    "en_US": "You have been unbanned by <highlight>{char}<end>.",
    "de_DE": "Du wurdest von <highlight>{char}<end> entbannt."
  },
  "unbanned_self": {
    "en_US": "<highlight>{char}<end> has been removed from the ban list.",
    "de_DE": "Du hast <highlight>{char}<end> entbannt."
  },
  "already_banned": {
    "en_US": "<highlight>{char}<end> is already banned.",
    "de_DE": "<highlight>{char}<end> ist bereits gebannt."
  },
  "banned_target_1": {
    "en_US": "You have been banned by <highlight>{banner}<end> for reason: <highlight>{reason}<end>. Duration: <highlight>{duration}<end>.",
    "de_DE": "Du wurdest von <highlight>{banner}<end> gebannt. Dauer: <highlight>{duration}<end>. Der Grund war: <highlight>{reason}<end>"
  },
  "banned_target_2": {
    "en_US": "You have been banned by <highlight>{banner}<end>. Duration: <highlight>{duration}<end>.",
    "de_DE": "Du wurdest von <highlight>{banner}<end> gebannt - Dauer: <highlight>{duration}<end> gebannt."
  },
  "banned_self": {
    "en_US": "<highlight>{char}<end> has been added to the ban list.",
    "de_DE": "<highlight>{char}<end> wurde gebannt."
  }
}