{

  "list_blob": {
    "en_US": [
      "<pagebreak>Name: <highlight>{char}<end>\n",
      "Added: <highlight>{added_time}<end>\n",
      "By: <highlight>{banner}<end>\n",
      "Ends: <highlight>{end_time}<end>{left}\n",
      "Reason: <highlight>{reason}<end>\n\n"
    ]
  },
  "list": {
    "en_US": "Ban List {amount}"
  },
  "not_banned": {
    "en_US": "<highlight>{char}<end> is not banned."
  },
  "unbanned_target": {
    "en_US": "You have been unbanned by <highlight>{char}<end>."
  },
  "unbanned_self": {
    "en_US": "<highlight>{char}<end> has been removed from the ban list."
  },
  "already_banned": {
    "en_US": "<highlight>{char}<end> is already banned."
  },
  "banned_target_1": {
    "en_US": "You have been banned by <highlight>{banner}<end> for reason: {reason}. Duration: <highlight>{duration}<end>."
  },
  "banned_target_2": {
    "en_US": "You have been banned by <highlight>{banner}<end>. Duration: <highlight>{duration}<end>."
  },
  "banned_self": {
    "en_US": "<highlight>{char}<end> has been added to the ban list."
  }
}