{
  "no_help": {
    "en_US": "Could not find help on <highlight>{topic}<end>",
    "de_DE": "Zu dem Thema <highlight>{topic}<end> konnte keine Hilfe gefunden werden."
  },
  "blob_title": {
    "en_US": "About Tyrbot {ver}",
    "de_DE": "Über Tyrbot - Version <highlight>{ver}<end>"
  },
  "about_head": {
    "en_US": [
      "Source Code: <a href='chatcmd:///start https://github.com/Budabot/Tyrbot'>https://github.com/Budabot/Tyrbot</a>\n",
      "Project Statistics: <a href='chatcmd:///start https://www.openhub.net/p/tyrbot'>https://www.openhub.net/p/tyrbot</a>\n",
      "Discord: <a href='chatcmd:///start https://discord.gg/2x9WesJ'>https://discord.gg/2x9WesJ</a>\n",
      "\n"
    ],
    "de_DE": [
      "Quellcode: <a href='chatcmd:///start https://github.com/Budabot/Tyrbot'>https://github.com/Budabot/Tyrbot</a>\n",
      "Projektstatistiken: <a href='chatcmd:///start https://www.openhub.net/p/tyrbot'>https://www.openhub.net/p/tyrbot</a>\n",
      "Discord: <a href='chatcmd:///start https://discord.gg/2x9WesJ'>https://discord.gg/2x9WesJ</a>\n",
      "\n"
    ]
  },
  "about_body": {
    "en_US": [
      "Development of Tyrbot started on 08-Feb-2018 when it received its initial commit.\n",
      "\n"
    ],
    "de_DE": [
      "Die Entwicklung des Bots hat am 08. Februar 2018 mit dem ersten commit begonnen.\n",
      "\n"
    ]
  },
  "about_special_ones": {
    "en_US": [
      "I would like to give special thanks to these people who contributed significant effort and large amounts of their time to the Tyrbot project:\n",
      "-<highlight>eli(vlad)<end> for his large contributions to Tyrbot including the news, discord, and raid modules\n",
      "-<highlight>Teeko<end> for all the time he spent testing new features, reporting bugs, and making suggestions\n",
      "-<highlight>nepherius/wafflespower<end> who was critical during the early parts of development in testing and suggesting changes\n",
      "\n"
    ],
    "de_DE": [
      "Ich würde gerne folgenden Personen dafür danken, dass sie viel Zeit und Wissen in Tyrbot investiert haben:\n",
      "-<highlight>eli(vlad)<end> für seine großen Beiträge, unter anderem das News, Discord und Raid Modul\n",
      "-<highlight>Teeko<end> für die Zeit, die er in das Testen von neuen Features, das melden von Fehlern, und das erstellen von Vorschägen\n",
      "-<highlight>nepherius/wafflespower<end> welcher in der frühen Entwicklungszeit für das testen und vorschlagen von Veränderungen extrem wichtig war\n",
      "\n"
    ]
  },
  "about_improvers": {
    "en_US": [
      "Thanks to these people who submitted PRs on GitHub to improve Tyrbot:\n",
      "<highlight>minidodo<end>\n",
      "<highlight>hughp135<end>\n",
      "<highlight>jroovers<end>\n",
      "<highlight>dustify<end>\n",
      "<highlight>equinitry<end>\n",
      "<highlight>Ilon Sjögren<end>\n",
      "\n"
    ],
    "de_DE": [
      "Ebenso möchte ich mich bei Folgenden Personen bedanken, die Tyrbot mithilfe von PR's verbessert haben:\n",
      "<highlight>minidodo<end>\n",
      "<highlight>hughp135<end>\n",
      "<highlight>jroovers<end>\n",
      "<highlight>dustify<end>\n",
      "<highlight>equinitry<end>\n",
      "<highlight>Ilon Sjögren<end>\n",
      "\n"
    ]
  },
  "about_bottom": {
    "en_US": [
      "Thanks to <highlight>Bgmofo<end> and <highlight>Weyland Yutani<end> for testing Tyrbot in its initial stages and providing valuable feedback.\n",
      "\n",
      "Lastly, to the AO community, I would like to give thanks for all the support you have given me and for allowing",
      "me to write bots for you.  It has been an experience like no other.  I wish each and every one of you the best in life.\n",
      "\n",
      "-Tyrence"
    ],
    "de_DE": [
      "Danke an <highlight>Bgmofo<end> und <highlight>Weyland Yutani<end>, für das Testen von Tyrbot,und das wertvolle Feedback, während er sich noch im Anfangsstadium befand.\n",
      "\n",
      "Schlussendlich die AO Community: Ich würde mich gerne für die ganze Unterstützung bedanken,",
      "sowie dafür, dass ich Bots für euch schreiben durfte. Es wahr eine einmalige Erfahrung. Ich wünsche euch allen das Beste im Leben.\n",
      "\n",
      "-Tyrence",
      "\n\n",
      "<highlight>Aus dem englischen Original übersetzt<end>"
    ]
  }

}