DROP TABLE IF EXISTS skills;
CREATE TABLE skills (id INT NOT NULL PRIMARY KEY, name VARCHAR(50) NOT NULL);
INSERT INTO skills (id, name) VALUES (318, '% Add. Nano Cost');
INSERT INTO skills (id, name) VALUES (319, '% Add. Xp');
INSERT INTO skills (id, name) VALUES (102, '1h Blunt');
INSERT INTO skills (id, name) VALUES (103, '1h Edged');
INSERT INTO skills (id, name) VALUES (107, '2h Blunt');
INSERT INTO skills (id, name) VALUES (105, '2h Edged');
INSERT INTO skills (id, name) VALUES (277, 'Add All Def.');
INSERT INTO skills (id, name) VALUES (276, 'Add All Off.');
INSERT INTO skills (id, name) VALUES (281, 'Add. Chem. Dam.');
INSERT INTO skills (id, name) VALUES (311, 'Add. Cold Dam.');
INSERT INTO skills (id, name) VALUES (280, 'Add. Energy Dam.');
INSERT INTO skills (id, name) VALUES (316, 'Add. Fire Dam.');
INSERT INTO skills (id, name) VALUES (279, 'Add. Melee Dam.');
INSERT INTO skills (id, name) VALUES (315, 'Add. Nano Dam.');
INSERT INTO skills (id, name) VALUES (317, 'Add. Poison Dam.');
INSERT INTO skills (id, name) VALUES (278, 'Add. Proj. Dam.');
INSERT INTO skills (id, name) VALUES (282, 'Add. Rad. Dam.');
INSERT INTO skills (id, name) VALUES (137, 'Adventuring');
INSERT INTO skills (id, name) VALUES (51, 'Aggdef');
INSERT INTO skills (id, name) VALUES (201, 'Aggressiveness');
INSERT INTO skills (id, name) VALUES (17, 'Agility');
INSERT INTO skills (id, name) VALUES (151, 'Aimed Shot');
INSERT INTO skills (id, name) VALUES (116, 'Assault Rif');
INSERT INTO skills (id, name) VALUES (22, 'Attack rating');
INSERT INTO skills (id, name) VALUES (128, 'Bio Metamor');
INSERT INTO skills (id, name) VALUES (152, 'Body Dev.');
INSERT INTO skills (id, name) VALUES (111, 'Bow');
INSERT INTO skills (id, name) VALUES (121, 'Bow Spc Att');
INSERT INTO skills (id, name) VALUES (142, 'Brawling');
INSERT INTO skills (id, name) VALUES (165, 'Break&Entry');
INSERT INTO skills (id, name) VALUES (148, 'Burst');
INSERT INTO skills (id, name) VALUES (93, 'Chemical AC');
INSERT INTO skills (id, name) VALUES (163, 'Chemistry');
INSERT INTO skills (id, name) VALUES (95, 'Cold AC');
INSERT INTO skills (id, name) VALUES (161, 'Comp. Liter');
INSERT INTO skills (id, name) VALUES (164, 'Concealment');
INSERT INTO skills (id, name) VALUES (391, 'Critical Decrease');
INSERT INTO skills (id, name) VALUES (379, 'CriticalIncrease');
INSERT INTO skills (id, name) VALUES (35, 'Damage to Pet');
INSERT INTO skills (id, name) VALUES (39, 'Damage To Pet Damage Multiplier');
INSERT INTO skills (id, name) VALUES (383, 'Decreased Nano-Interrupt Modifier %');
INSERT INTO skills (id, name) VALUES (145, 'Deflect');
INSERT INTO skills (id, name) VALUES (144, 'Dimach');
INSERT INTO skills (id, name) VALUES (536, 'Direct Nano Damage Efficiency');
INSERT INTO skills (id, name) VALUES (96, 'Disease AC');
INSERT INTO skills (id, name) VALUES (154, 'Dodge-Rng');
INSERT INTO skills (id, name) VALUES (153, 'Duck-Exp');
INSERT INTO skills (id, name) VALUES (126, 'Elec. Engi');
INSERT INTO skills (id, name) VALUES (92, 'Energy AC');
INSERT INTO skills (id, name) VALUES (155, 'Evade-ClsC');
INSERT INTO skills (id, name) VALUES (147, 'Fast Attack');
INSERT INTO skills (id, name) VALUES (97, 'Fire AC');
INSERT INTO skills (id, name) VALUES (123, 'First Aid');
INSERT INTO skills (id, name) VALUES (150, 'Fling Shot');
INSERT INTO skills (id, name) VALUES (45, 'Free deck slot');
INSERT INTO skills (id, name) VALUES (167, 'Full Auto');
INSERT INTO skills (id, name) VALUES (109, 'Grenade');
INSERT INTO skills (id, name) VALUES (689, 'Heal Reactivity');
INSERT INTO skills (id, name) VALUES (343, 'HealDelta');
INSERT INTO skills (id, name) VALUES (535, 'Healing Efficiency');
INSERT INTO skills (id, name) VALUES (110, 'Heavy Weapons');
INSERT INTO skills (id, name) VALUES (90, 'Imp/Proj AC');
INSERT INTO skills (id, name) VALUES (19, 'Intelligence');
INSERT INTO skills (id, name) VALUES (100, 'Martial Arts');
INSERT INTO skills (id, name) VALUES (127, 'Matt.Metam');
INSERT INTO skills (id, name) VALUES (130, 'Matter Crea');
INSERT INTO skills (id, name) VALUES (1, 'Max Health');
INSERT INTO skills (id, name) VALUES (221, 'Max Nano');
INSERT INTO skills (id, name) VALUES (181, 'Max NCU');
INSERT INTO skills (id, name) VALUES (478, 'MaxReflectedChemicalDmg');
INSERT INTO skills (id, name) VALUES (480, 'MaxReflectedColdDmg');
INSERT INTO skills (id, name) VALUES (477, 'MaxReflectedEnergyDmg');
INSERT INTO skills (id, name) VALUES (482, 'MaxReflectedFireDmg');
INSERT INTO skills (id, name) VALUES (476, 'MaxReflectedMeleeDmg');
INSERT INTO skills (id, name) VALUES (481, 'MaxReflectedNanoDmg');
INSERT INTO skills (id, name) VALUES (483, 'MaxReflectedPoisonDmg');
INSERT INTO skills (id, name) VALUES (475, 'MaxReflectedProjectileDmg');
INSERT INTO skills (id, name) VALUES (479, 'MaxReflectedRadiationDmg');
INSERT INTO skills (id, name) VALUES (125, 'Mech. Engi');
INSERT INTO skills (id, name) VALUES (104, 'Melee Ener.');
INSERT INTO skills (id, name) VALUES (118, 'Melee. Init.');
INSERT INTO skills (id, name) VALUES (91, 'Melee/ma AC');
INSERT INTO skills (id, name) VALUES (114, 'MG / SMG');
INSERT INTO skills (id, name) VALUES (101, 'Mult. Melee');
INSERT INTO skills (id, name) VALUES (134, 'Multi Ranged');
INSERT INTO skills (id, name) VALUES (132, 'Nano Pool');
INSERT INTO skills (id, name) VALUES (160, 'Nano Progra');
INSERT INTO skills (id, name) VALUES (168, 'Nano Resist');
INSERT INTO skills (id, name) VALUES (149, 'NanoC. Init.');
INSERT INTO skills (id, name) VALUES (364, 'NanoDelta');
INSERT INTO skills (id, name) VALUES (136, 'Perception');
INSERT INTO skills (id, name) VALUES (159, 'Pharma Tech');
INSERT INTO skills (id, name) VALUES (120, 'Physic. Init');
INSERT INTO skills (id, name) VALUES (106, 'Piercing');
INSERT INTO skills (id, name) VALUES (112, 'Pistol');
INSERT INTO skills (id, name) VALUES (21, 'Psychic');
INSERT INTO skills (id, name) VALUES (129, 'Psycho Modi');
INSERT INTO skills (id, name) VALUES (162, 'Psychology');
INSERT INTO skills (id, name) VALUES (157, 'Quantum FT');
INSERT INTO skills (id, name) VALUES (94, 'Radiation AC');
INSERT INTO skills (id, name) VALUES (133, 'Ranged Ener');
INSERT INTO skills (id, name) VALUES (119, 'Ranged. Init.');
INSERT INTO skills (id, name) VALUES (381, 'RangeInc. NF');
INSERT INTO skills (id, name) VALUES (380, 'RangeInc. Weapon');
INSERT INTO skills (id, name) VALUES (208, 'ReflectChemicalAC');
INSERT INTO skills (id, name) VALUES (217, 'ReflectColdAC');
INSERT INTO skills (id, name) VALUES (207, 'ReflectEnergyAC');
INSERT INTO skills (id, name) VALUES (219, 'ReflectFireAC');
INSERT INTO skills (id, name) VALUES (206, 'ReflectMeleeAC');
INSERT INTO skills (id, name) VALUES (218, 'ReflectNanoAC');
INSERT INTO skills (id, name) VALUES (225, 'ReflectPoisonAC');
INSERT INTO skills (id, name) VALUES (205, 'ReflectProjectileAC');
INSERT INTO skills (id, name) VALUES (216, 'ReflectRadiationAC');
INSERT INTO skills (id, name) VALUES (593, 'Regain XP Percentage');
INSERT INTO skills (id, name) VALUES (113, 'Rifle');
INSERT INTO skills (id, name) VALUES (143, 'Riposte');
INSERT INTO skills (id, name) VALUES (156, 'Run Speed');
INSERT INTO skills (id, name) VALUES (360, 'Scale');
INSERT INTO skills (id, name) VALUES (20, 'Sense');
INSERT INTO skills (id, name) VALUES (122, 'Sensory Impr');
INSERT INTO skills (id, name) VALUES (108, 'Sharp Obj');
INSERT INTO skills (id, name) VALUES (229, 'ShieldChemicalAC');
INSERT INTO skills (id, name) VALUES (231, 'ShieldColdAC');
INSERT INTO skills (id, name) VALUES (228, 'ShieldEnergyAC');
INSERT INTO skills (id, name) VALUES (233, 'ShieldFireAC');
INSERT INTO skills (id, name) VALUES (227, 'ShieldMeleeAC');
INSERT INTO skills (id, name) VALUES (232, 'ShieldNanoAC');
INSERT INTO skills (id, name) VALUES (234, 'ShieldPoisonAC');
INSERT INTO skills (id, name) VALUES (226, 'ShieldProjectileAC');
INSERT INTO skills (id, name) VALUES (230, 'ShieldRadiationAC');
INSERT INTO skills (id, name) VALUES (115, 'Shotgun');
INSERT INTO skills (id, name) VALUES (382, 'SkillLockModifier');
INSERT INTO skills (id, name) VALUES (146, 'Sneak Atck');
INSERT INTO skills (id, name) VALUES (18, 'Stamina');
INSERT INTO skills (id, name) VALUES (16, 'Strength');
INSERT INTO skills (id, name) VALUES (138, 'Swimming');
INSERT INTO skills (id, name) VALUES (131, 'Time&Space');
INSERT INTO skills (id, name) VALUES (135, 'Trap Disarm.');
INSERT INTO skills (id, name) VALUES (124, 'Treatment');
INSERT INTO skills (id, name) VALUES (141, 'Tutoring');
INSERT INTO skills (id, name) VALUES (180, 'Used NCU');
INSERT INTO skills (id, name) VALUES (139, 'Vehicle Air');
INSERT INTO skills (id, name) VALUES (166, 'Vehicle Ground');
INSERT INTO skills (id, name) VALUES (117, 'Vehicle Water');
INSERT INTO skills (id, name) VALUES (158, 'Weapon Smt');
