CREATE TABLE IF NOT EXISTS fun (type VARCHAR(20) NOT NULL,type_id INT NOT NULL, content TEXT NOT NULL);
DELETE FROM fun WHERE type = 'beer';
INSERT INTO fun (type, type_id, content) VALUES ('beer', 1, '*name* are you buying?');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 2, 'Beer! lets get this party started *name*!!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 3, 'WTF!? ... why you trying to steel my beer!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 4, 'A round of beer coming up courtesy of *name*.');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 5, '/me sneaks up and smashes a bottle over *name*''s head doing *dmg* points of melee damage! w00t drunken PvP!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 6, 'Have one on the house *name* and tell me all your problems');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 7, 'Sure, I would love to drink a few. Your place or mine?');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 8, 'Import or Domestic hun?');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 9, 'Sorry, I just ran out hun. Would you like some Rising Sun Sake instead?');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 10, 'Umm, I dont think you are of age, lets see some ID.');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 11, 'Well, by the looks of it. I think you have reached your limit for the night *name*.');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 12, 'NO!! First pay off your bar tab. You still owe me *creds* credits *name*!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 13, 'YEAH! Let''s start gathering for a Pub raid!!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 14, 'Only Leet''s are drinking beer! We need harder stuff like Wodka!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 15, 'I am a firm believer in the people. If given the truth, they can be depended upon to meet any national crisis. The great point is to bring them the real facts, and beer. - Abraham Lincoln');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 16, '24 hours in a day, 24 beers in a case. Coincidence? - Stephen Wright');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 17, 'One of the hallmarks of the baby boomer generation is that it doesn''t live like the previous generation. It hasn''t yet given up jeans and T-shirts or beer. - Ron Klugman, SVP, Coors Brewing');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 18, 'Beer is proof that God loves us and wants us to be happy. - Benjamin Franklin');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 19, 'The roots and herbs beaten and put into new ale or beer and daily drunk, cleareth, strengthen and quicken the sight of the eyes. - Nicholas Culpeper');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 20, 'Without question, the greatest invention in the history of mankind is beer. Oh, I grant you the wheel was also a fine invention, but the wheel does not go nearly as well with pizza. - Dave Barry');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 21, '[I recommend]...bread, meat, vegetables and beer. - Sophocles'' philosophy of a moderate diet');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 22, 'Alright brain, I don''t like you and you don''t like me, so just get me through this exam so I can go back to killing you slowly with beer. - Homer Simpson');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 23, 'Oh, lager beer! It makes good cheer, And proves the poor man''s worth; It cools the body through and through, and regulates the health. - Anonymous');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 24, 'Sometimes when I reflect back on all the beer I drink I feel ashamed. Then I look into the glass and think about the workers in the brewery and all of their hopes and dreams. If I didn''t drink this beer, they might be out of work and their dreams would be shattered. Then I say to myself, ''It is better that I drink this beer and let their dreams come true than be selfish and worry about my liver.'' - Jack Handy');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 25, 'Not all chemicals are bad. Without chemicals such as hydrogen and oxygen, for example, there would be no way to make water, a vital ingredient in beer. - Dave Barry');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 26, 'I would give all my fame for a pot of ale and safety. - Shakespeare, Henry V');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 27, 'Make sure that the beer - four pints a week - goes to the troops under fire before any of the parties in the rear get a drop. - Winston Churchill to his Secretary of War, 1944');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 28, 'We old folks have to find our cushions and pillows in our tankards. Strong beer is the milk of the old. - Martin Luther');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 29, 'Beer will always have a definite role in the diet of an individual and can be considered a cog in the wheel of nutritional foods. - Bruce Carlton');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 30, 'No soldier can fight unless he is properly fed on beef and beer. - John Churchill, First Duke of Marlborough');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 31, 'An oppressive government is more to be feared than a tiger, or a beer. - Confucius');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 32, 'If God had intended us to drink beer, He would have given us stomachs. - David Daye');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 33, 'He was a wise man who invented beer. - Plato');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 34, 'This is grain, which any fool can eat, but for which the Lord intended a more divine means of consumption... Beer! - Robin Hood, Prince of Thieves, Friar Tuck');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 35, 'Beer: So much more than just a breakfast drink. - Whitstran Brewery sign');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 36, 'I feel sorry for people who don''t drink. When they wake up in the morning, that''s as good as they''re going to feel all day. - Frank Sinatra');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 37, 'When I read about the evils of drinking, I gave up reading. - Henny Youngman');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 38, 'When we drink, we get drunk. When we get drunk, we fall asleep. When we fall asleep, we commit no sin. When we commit no sin, we go to heaven. Sooooo, let''s all get drunk and go to heaven! - Brian O''Rourke');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 39, 'BEER: HELPING UGLY PEOPLE HAVE SEX SINCE 3000 B.C.! - Unknown');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 40, 'To some it''s a six-pack, to me it''s a Support Group. Salvation in a can!');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 41, 'The problem with the world is that everyone is a few drinks behind. - Humphrey Bogart');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 42, 'Everybody has to believe in something.....I believe I''ll have another drink. - W.C. Fields');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 43, 'You''re not drunk if you can lie on the floor without holding on. - Dean Martin');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 44, 'God made pot. Man made beer. Who do you trust? - Restroom in The Irish Times, Washington DC');
INSERT INTO fun (type, type_id, content) VALUES ('beer', 45, 'You can''t be a real country unless you have a beer and an airline - it helps if you have some kind of a football team, or some nuclear weapons, but at the very least you need a beer. - Frank Zappa');