CREATE TABLE IF NOT EXISTS fun (type VARCHAR(20) NOT NULL, content TEXT NOT NULL);
DELETE FROM fun WHERE type = 'brain';
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: It must be inordinately taxing to be such a boob.<br> Pinky:  You have no idea.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so, Brain, but where will we find a duck and a hose at this hour?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so, but where will we find an open tattoo parlor at this time of night?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Wuh, I think so, Brain, but if we didn''t have ears, we''d look like weasels.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Are you thinking what I''m thinking, Pinky?<br> Pinky: Uh... yeah, Brain, but where are we going to find rubber pants our size?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so, Brain, but balancing a family and a career ...  oooh, it''s all too much for me.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Wuh, I think so, Brain, but isn''t Regis Philbin already married?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so, Brain, but burlap chafes me so.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Are you pondering what I''m pondering, Pinky?<br> Pinky: Sure, Brain, but how are we going to find chaps our size?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so, Brain, but we''ll never get a monkey to use dental floss.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so, Brain, but this time, you wear the tutu.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so, Brain, but culottes have a tendency to ride up so.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so, Brain, but if they called them sad meals, kids wouldn''t buy them.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so, Brain, but me and Pippi Longstocking... I mean, what would the children look like?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so, Brain, but this time, you put the trousers on the chimp.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Well, I think so, Brain, but I can''t memorize a whole opera in Yiddish.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but there''s already a bug stuck in here from last time. (pointing between teeth)');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but I get all clammy inside the tent. ');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but I don''t think Kay Ballard is in the union. ');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Yes I am.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but the Rockettes, it''s mostly girls, isn''t it?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Are you pondering what I''m pondering?<br> Pinky: I think so Brain, but pants with horizontal stripes make me look chubby.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but pantyhose are so uncomfortable in the summer time.');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but it''s a miracle that this one grew back (holding left leg).');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so Brain, but you''d have to take that whole bridge apart then, wouldn''t you?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: We are France, and soon, we are the world!<br> Pinky: Are we the children Brain?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so Brain, but how are we gonna teach a goat to dance with flippers on?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but apply north to what?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so Brain, but Snowball for windows?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Are you pondering what I''m pondering Pinky?<br> Pinky: Uh, I think so Brain, no, no, it''s too stupid. ');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: We will disguise ourselves as a cow.<br> Pinky: Narf! That was it exactly!');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Sancho Pinky, are you pondering what I''m pondering?<br> Pinky: Uh, I think so Don Cerebro, but why would Sophia Loren do a musical?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so, but what if the chicken won''t wear the nylons?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: I think so Brain, but isn''t that why they invented tube socks?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Well, I think so, Brain, but if Clark Kent wore contact lenses, wouldn''t he look just like Superman?');
INSERT INTO fun (type, content) VALUES ('brain', 'Brain: Pinky, are you pondering what I''m pondering?<br> Pinky: Well, I think so Brain, but if Mulder wore the skirt, wouldn''t Scully have to walk around naked?');