CREATE TABLE IF NOT EXISTS fun (type VARCHAR(20) NOT NULL,type_id INT NOT NULL, content TEXT NOT NULL);
DELETE FROM fun WHERE type = 'cybor';
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 1, 'I touch you on your lettuce, you massage my spinach... sexily.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 2, 'Don''t worry about it. I''m wearing a lacy black bra.My soft breasts are rising and falling, as I breath harder and harder.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 3, 'My turnips listen for the soft cry of your love. My insides turn to celery as I unleash my warm and sticky cauliflower of love.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 4, 'I ride your buttocks like they were amber waves of grains.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 5, 'We''re in my bedroom. There''s soft music playing on the stereo and candles on my dresser and night table.I''m looking up into your eyes, smiling. My hand works its way down to your crotch and begins to fondle your huge, swelling bulge.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 6, 'Noooo, i cant get my combined back on!');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 7, 'Are you ready for my fresh produce?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 8, 'Are you ready to get nasty, baby? I''m as hot as a pizza oven');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 9, 'Baby, I been havin a tough night so treat me nice aight?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 10, 'Don''t worry about it. I''m wearing a lacy black bra. My soft breasts are rising and falling, as I breath harder and harder.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 11, 'hot damn am I excited now!');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 12, 'haha, ok, u know that turns me on.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 13, 'I am completely inside of you. You are my puppet. I put on a little play.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 14, 'I am wearing a red silk blouse, a miniskirt and high heels. I work out every day, I''m toned and perfect. My measurements are 36-24-36. What do you look like?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 15, 'I can no longer resist the pizza. I open the box and unzip my pants with my other hand. As I penetrate the gooey cheese, I moan in ecstacy. The mushrooms and Italian sausage are rough, but the sauce is deliciously soothing. I blow my load in seconds. As you leave the bathroom.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 16, 'I cast Lvl. 3 Eroticism. You turn into a real beautiful woman.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 17, 'I execute standing position 12 from the Kama Sutra. Passion fills the room. Your head is close to the ceiling fan.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 18, 'I kiss you on the mouth, hard, but then gently.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 19, 'I kiss you softly on your chest.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 20, 'I lick your earlobe, and undo your watch.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 21, 'I make some toast and eat it off your ass. Land O'' Lakes butter all in your crack. Mmmm.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 22, 'I meditate to regain my mana, before casting Lvl. 8 tool of the Infinite. I spend my mana reserves to cast Mighty Thrust of the Beyondness.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 23, 'I mouth the words to you, as if in slow motion: do me, do me.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 24, 'I put my hand through ur hair, and kiss u on the neck.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 25, 'I ride your buttocks like they were amber waves of grains.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 26, 'I slip out of my pants, just for you, bloodninja.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 27, 'I smack you thick booty.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 28, 'I stomp the ground, and snort, to alert you that you are in my breeding territory.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 29, 'I take off my trenchcoat, I''m nekked beneath, with pistols on my belt.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 30, 'I take yo pants off, grunting like a troll.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 31, 'I take your hand and kiss it softly.I''m reaching back undoing the clasp. The bra slides off my body. The air caresses my breasts. My nipples are erect for you.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 32, 'I touch you on your lettuce, you massage my spinach... sexily.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 33, 'I unzip my pants...');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 34, 'I want you. Would you like to screw me?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 35, 'I was great. You loved it.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 36, 'I''m arching my back. Oh baby. I just want to feel your tongue all over me.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 37, 'I''m bending over the bed. Give it to me, baby!');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 38, 'I''m fumbling with the clasp on your bra. I think it''s stuck. Do you have any scissors?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 39, 'I''m moaning softly.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 40, 'I''m moving my buttocks back and forth, moaning. I can''t stand it another second! Take me now!');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 41, 'I''m on the bed arching for you.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 42, 'I''m pulling off your panties. My tongue is going all over, in and out nibbling on you... umm... wait a minute.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 43, 'I''m pulling up your shirt and kissing your chest.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 44, 'I''m taking hold of your blouse and sliding it off slowly.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 45, 'I''m throwing my head back in pleasure. The cool silk slides off my warm skin. I''m rubbing your bulge faster, pulling and rubbing.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 46, 'I''m touching your smooth butt. It feels so nice. I kiss your neck.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 47, 'I''m tuggin'' off your pants. I''m moaning. I want you so badly.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 48, 'I''ve got a pubic hair caught in my throat. I''m choking.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 49, 'My turnips listen for the soft cry of your love. My insides turn to celery as I unleash my warm and sticky cauliflower of love.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 50, 'my zucchinis carresses your carrots.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 51, 'No, never mind. I''m getting dressed. I''m putting on my underwear. Now I''m putting on my wet nasty blouse. I''m buttoning my blouse. Now I''m putting on my shoes.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 52, 'Now I''m unbuttoning your blouse. My hands are trembling.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 53, 'Now my manhood won''t get hard for a week.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 54, 'Oh	yeah, aight. Aight, I put on my robe and wizard hat.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 55, 'Ok baby, we got to hurry, I don''t know how long I can keep it ready for you.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 56, 'OK, now I''m going to put my... you know... thing... in your... you know... woman''s thing.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 57, 'OK. I''m pulling your sweat pants down and rubbing your hard tool.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 58, 'Oooohh yeah. I step out of the shower and I''m all wet and cold. Warm me up baby');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 59, 'Slip out of those pants baby, yeah.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 60, 'So you ready to do IT then?  You unbutton my pants, spew your load at the sight of my underwear, and your spent.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 61, 'So you''re really a 18 yr old girl right?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 62, 'Sweet, I start by rubbing your ass all around. You love this.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 63, 'Thats cool, so you wanna see my gun? I pull off my pants and show you my ''gun''.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 64, 'thats ok. ok i''m a japanese schoolgirl, what r u?');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 65, 'Then send me the picture.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 66, 'To your light bulb I am the Thomas Edison of your sex. Withought my light you would be lost in a sea of darkness.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 67, 'You wanna cyber *name*? That''ll be *creds* per min please.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 68, 'We are like two dancers, for whom the music never stops. I Kiss the top of your hand. You are taken aback by the bulge that forms pressed into your thigh.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 69, 'We''re in my bedroom.There''s soft music playing on the stereo and candles on my dresser and night table.I''m looking up into your eyes, smiling. My hand works its way down to your crotch and begins to fondle your huge, swelling bulge.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 70, 'Yeah, well I already unleashed my cauliflower, all over your olives, and up in your eyes. Now you can''t see.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 71, 'Yes! Do it, baby! Do it!');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 72, 'You bend over to harvest your radishes.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 73, 'You carress my ass, and trim my pubes...');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 74, 'You sound sexy. I bet you want me in the back of your car...');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 75, 'You start getting frisky so I put my hand down your undies.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 76, 'You''re wet already. I can smell your womanhood from here.');
INSERT INTO fun (type, type_id, content) VALUES ('cybor', 77, 'Your pants are off. I kiss you passionately-our naked bodies pressing each other.');