CREATE TABLE IF NOT EXISTS fun (type VARCHAR(20) NOT NULL, content TEXT NOT NULL);
DELETE FROM fun WHERE type = 'dwight';
INSERT INTO fun (type, content) VALUES ('dwight', 'I am faster than 80% of all snakes.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Reject a woman, and she will never let it go. One of the many defects of their kind. Also, weak arms.');
INSERT INTO fun (type, content) VALUES ('dwight', 'The eyes are the groin of the head.');
INSERT INTO fun (type, content) VALUES ('dwight', 'My feelings regenerate at twice the speed of a normal man.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Before I do anything I ask myself "Would an idiot do that?" And if the answer is yes, I do not do that thing.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Dolphins get a lot of good publicity for the drowning swimmers they push back to shore, but what you don''t hear about is the many people they push farther out to sea.');
INSERT INTO fun (type, content) VALUES ('dwight', 'There are 3 things you never turn your back on: bears, men you have wronged and dominant male turkey during mating season.');
INSERT INTO fun (type, content) VALUES ('dwight', 'How would I describe myself? Three words: hard working, alpha male, jackhammer; merciless; insatiable;');
INSERT INTO fun (type, content) VALUES ('dwight', 'I am fast. To give you a reference point I am somewhere between a snake and a mongoose; and a panther.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I grew up on a farm. I have seen animals having sex in every position imaginable. Goat on chicken, chicken on goat, couple of chickens doing a goat, couple of pigs watching.');
INSERT INTO fun (type, content) VALUES ('dwight', 'My maternal grandfather was the toughest guy I ever knew. World War Two veteran, killed twenty men and spent the rest of the war in an Allied prison camp.');
INSERT INTO fun (type, content) VALUES ('dwight', 'With the electricity we are using to keep Meredith alive we could power a small fan for two days. You tell me what''s unethical.');
INSERT INTO fun (type, content) VALUES ('dwight', 'In the wild, there is no healthcare. Healthcare is "Oh, I broke my leg!" A lion comes and eats you, your dead.');
INSERT INTO fun (type, content) VALUES ('dwight', 'In an ideal world I would have all ten fingers on my left hand and the right one would just be left for punching.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I never smile if I can help it; Showing one''s teeth is a submission signal in primates. When someone smiles at me, all I see is a chimpanzee begging for its life.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I train my major blood vessels to retract into my body on command. Also, I can retract my penis up into itself.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Women are like wolves. If you want one you must trap it. Snare it. Tame it. Feed it.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I don''t have a lot of experience with vampires, but I have hunted werewolves. I shot one once, but by the time I got to it, it had turned back into my neighbor''s dog.');
INSERT INTO fun (type, content) VALUES ('dwight', 'As of this morning, we are completely wireless here on Schrute Farms. So as soon as I find out where Mose hid all the wires, we can have power back on.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Listen up kid! I don''t like you. But because some town in Switzerland says so, you have rights.');
INSERT INTO fun (type, content) VALUES ('dwight', 'It appears that the website has become alive. This happens to computers and robots sometimes.');
INSERT INTO fun (type, content) VALUES ('dwight', 'No, don''t call me a hero. Do you know who the real heroes are? The guys who wake up every morning and go into their normal jobs, and get a distress call from the commissioner, and take off their glasses and change into capes, and fly around fighting crime. Those are the real heroes.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I saw "Wedding Crashers" accidentally. I bought a ticket for "Grizzly Man" and went into the wrong theater. After an hour, I figured I was in the wrong theater, but I kept waiting. Cause that''s the thing about bear attacks, they come when you least expect it.');
INSERT INTO fun (type, content) VALUES ('dwight', 'The Schrutes have their own traditions. We usually marry standing in our own graves. Makes the funerals very romantic, but the weddings are a bleak affair.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I overslept. Damn rooster didn''t crow.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Here''s my card. It''s got my cell number, my pager number, my home number, and my other pager number. I never take vacations, I never get sick, and I don''t celebrate any major holidays.');
INSERT INTO fun (type, content) VALUES ('dwight', '[Bringing in a dead goose] I accidentally ran over it. It''s a Christmas miracle!');
INSERT INTO fun (type, content) VALUES ('dwight', 'I know everything about film. I''ve seen over 240 of them.');
INSERT INTO fun (type, content) VALUES ('dwight', 'When you are ready to see the sales office, the sales office will present itself to you.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Just as you have planted your seed into the ground, I will plant my seed into you.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Michael always says "K-I-S-S. Keep it simple, stupid." Great advice. Hurts my feelings every time.');
INSERT INTO fun (type, content) VALUES ('dwight', '[About the tux he''s wearing] It belonged to my grandfather. He was buried in it, so... family heirloom.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Oscar went to Mexico when he was five to attend his great-grandmother''s funeral. What does that mean to an United States law enforcement officer? He''s a potential drug mule.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I was the youngest pilot in Pan Am history. When I was four, the pilot let me ride in the cockpit and fly the plane with him. And I was four, and I was great and I would have landed it, but my dad wanted us to go back to our seats.');
INSERT INTO fun (type, content) VALUES ('dwight', 'My grandfather left me a 60-acre working beet farm. I run it with my cousin Mose. We sell beets to the local stores and restaurants. It''s a nice little farm... Sometimes teenagers use it for sex.');
INSERT INTO fun (type, content) VALUES ('dwight', 'I live in a 9-bedroom farmhouse. I have my own crossbow range. It''s the perfect situation for me. Although the two bathrooms would have been nice. We just have the one... and it''s under the porch.');
INSERT INTO fun (type, content) VALUES ('dwight', 'The purse girl hits everything on my checklist: creamy skin, straight teeth, curly hair, amazing breasts. Not for me, for my children. The Schrutes produce very thirsty babies.');
INSERT INTO fun (type, content) VALUES ('dwight', 'Through concentration, I can raise and lower my cholesterol at will.');