CREATE TABLE IF NOT EXISTS fun (type VARCHAR(20) NOT NULL,type_id INT NOT NULL, content TEXT NOT NULL);
DELETE FROM fun WHERE type = 'fc';
INSERT INTO fun (type, type_id, content) VALUES ('fc', 1, '[in the same thread that topics got deleted for not agreeing with how moderation was happening] This is what I hate - This prevalant attitude that we restrict or otherwise take issue with people having differing opinions from us. --Kintaii');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 2, 'We''re more open and honest than probably pretty much any other game development team out there. --Kintaii');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 3, '[talking about the new engine] It''s done when it''s done. --Vhab');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 4, '[GM]: just don''t kill stuff they are already attacking, you aren''t a noob. you know how it goes [to person who was "kill stealing"]');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 5, 'We are never biased in any GM actions. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 6, 'A few people were suspended for being in contact with those orchestrating the exploit --Geoff Higgins, Funcom Support Manager');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 7, 'It is against policy to knowingly consort with players active in exploits. --Geoff Higgins, Funcom Support Manager');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 8, 'As far as the level of participation in said exploit, it could range anywhere from being the player who is doing the exploit (ie: hopping from org to org to disrupt the timer) to simply being grouped with the person coordinating the execution of the exploit. --Funcom Support Manager, Customer Service');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 9, '[Player]: He trained us.. [GM]: Payback after asking your team to stop');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 10, '[GM]: I''ll ban everyone 1st then sort it out..');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 11, '[Player]: You''re telling me that this guy admitted to you that he trained us. [GM]: After you messed up his play ... [Player]: But you will do nothing about him admitting to harass us by training us? I just want to make sure, for the record, that I understand how the policy is carried out. [GM]: I will do what is necessary');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 12, 'We do not suspend people for honest mistakes. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 13, 'You are mistaken in several of your details there I am afraid. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 14, 'We deal with them directly, where we have all the facts and those involved know we have all the facts. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 15, 'I can assure you that any actions taken by the GMs were apprpriate. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 16, 'Our Game Masters only ever suspend players when their actions leave us with no choice. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 17, 'We do not suspend accounts on hearsay or rumour, but only when our staff witness and can verify that exploiting was taking place. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 18, 'What is does mean is that every player involved was at least in contact with those doing the exploit, whether by game chat channels or otherwise. --Craig "Silirrion" Morrison');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 19, 'Our apologies. Your accounts have been closed due to unauthorized actives. Thank you for your understanding. --Lead GM Sojourn, Customer Satisfaction Manager');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 20, 'I disagree with everything you say in this thread...even including the idea that this is the "most stupid" idea we''ve ever had. We have done way dumber things than this. --Colin "Means" Cragg');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 21, 'Dear Arguru, You have received a warning at Anarchy Online Bulletin Board.  Reason: ------- Excessive Profanities  Joking or not, this is an inappropriate level of obscenities. Please make your point in other ways. Thank you.  --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 22, 'I usually try to be diplomatic and avoid insults, but I''m not particularly in that mood today. --Vhab');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 23, 'This sort of non-constructive trolling is not necessary to begin a thread. Should you have an issue with a particular policy, it is within forum rules to state so in a more polite manner. I have edited the objectional content in the post, you may edit it to include a calmer and more constructive criticism. --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 24, 'they''re generated, but not in a way you guys can make sense of em :) -- Vhab [talking about how FC calculates values in AO]');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 25, 'Last edited by Anarrina; Today at 18:32:45.. Reason: constantly mistyping someone else''s name in an attempt to belittle them in harassment');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 26, '"I''m sorry my reality doesn''t match the arguments you''d love to see in your hypothetical situation --Vhab" ~ "apology accepted. :) --Argure"');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 27, 'no, it doesn''t, Argure.  For someone espousing logic you are lacking some, there. --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 28, 'god, Argure, honestly.  If you''re so confident you can manage teh business, please apply for a damned job. --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 29, 'you are not at all impressing anyone with your "logic and reason" which comes across much more as "adolescent petulance" --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 30, 'then maybe you need to read the AO forums, specifically the MP forums.. and gain some education about my "bias"... --ShadowGod');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 31, 'oh for god''s sake. grow up --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 32, 'alot of players of video games dont see the big picture... heheh --ShadowGod');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 33, 'you are a poor liar. --Anarrina');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 34, '"ShadowGod, Anarrina, the !fc command needed a new batch, thanks =)" --Argure ~ "yeah.. i''m done with this now --ShadowGod" You were banned from #anarchyonline by ShadowGod (find other people to troll)');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 35, 'Argure: after your insensitive jackass stunt last night in #ao you''re no longer welcome in my channel at least. 4chan may be more suited for your childish behavior. --Vhab');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 36, 'The only way to win the game - is to quit it completely. --Artyomis');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 37, 'The account is unfortunately not eligible to be reopened. I''m sorry for any difficulty this may cause. If you''d like, you''re free to create a new account if you would like to return to the game. --GM discussing a closed account');
INSERT INTO fun (type, type_id, content) VALUES ('fc', 38, 'We do not discriminate or show favoritism towards any players, we are neutral regarding all issues. --GM Raetos');
