CREATE TABLE IF NOT EXISTS fun (type VARCHAR(20) NOT NULL, content TEXT NOT NULL);
DELETE FROM fun WHERE type = 'pirates';
INSERT INTO fun (type, content) VALUES ('pirates', 'Lord Beckett: You''re mad!<br>Jack Sparrow: well thats good cause If I wasn''t, this''d probably never work.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Barbossa: There''s not been a gathering like this in our lifetime.<br>Jack Sparrow: And I owe them all money.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Did no one come to save me just because they missed me?');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: It never would''ve worked out between us.<br>Jack Sparrow: Keep telling yourself that, darling.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: We''re going to steal a ship? That ship?<br>Jack Sparrow: Commandeer. We''re going to commandeer that ship. ');
INSERT INTO fun (type, content) VALUES ('pirates', 'Norrington: You actually were telling the truth.<br>Jack Sparrow: I do that quite a lot. Yet people are always surprised.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: Why doesn''t your compass work?<br>Jack Sparrow: ...My compass works fine.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: I''d die for her.<br>Jack Sparrow: Oh good. No worries then.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Do us a favor... I know it''s difficult for you... but please, stay here, and try not to do anything... stupid.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: [to Pintel and Ragetti] Guard the boat, mind the tide... don''t touch my dirt.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: I row over, search the ship until I find your bloody key.<br>Jack Sparrow: And if there are crewmen?<br>Will Turner: I cut down anyone in my path.<br>Jack Sparrow: [turns to Gibbs] I like it. Simple, easy to remember. ');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Me? I''m dishonest, and a dishonest man you can always trust to be dishonest. Honestly. It''s the honest ones you want to watch out for, because you can never predict when they''re going to do something incredibly... stupid. ');
INSERT INTO fun (type, content) VALUES ('pirates', 'Barbossa: How the blazes did you get off that island?<br>Jack Sparrow: When you marooned me on that god forsaken spit of land, you forgot one very important thing, mate: I''m Captain Jack Sparrow.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Tia Dalma: [hands Jack a jar of dirt]<br>Jack Sparrow: Dirt. This is a jar of dirt.<br>Tia Dalma: Yes.<br>Jack Sparrow: Is the jar of dirt going to help?<br>Tia Dalma: If ya dont want it. Give it back.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Man in Jail: The Black Pearl? I''ve heard stories. She''s been preying on ships and settlements for near ten years. Never leaves any survivors.<br>Jack Sparrow: No survivors? Then where do the stories come from, I wonder?');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: You cheated.<br>Jack Sparrow: Pirate.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Anamaria: You''re daft, lady! You both are!<br>Gibbs: Daft like Jack.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: This is the fastest ship in the Caribbean.<br>Anamaria: You can tell them that after they''ve caught us.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Pintel: You''re supposed to be dead!<br>Jack Sparrow: Am I not?');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: If you were waiting for the opportune moment, that was it.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: You''re despicable.<br>Jack Sparrow: Sticks and stones, love. I saved your life, you saved mine. We''re square.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: You seem somewhat familiar. Have I threatened you before?<br>Will Turner: I make a point of avoiding familiarity with pirates.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Barbossa: Why thank ye, Jack.<br>Jack Sparrow: You''re welcome.<br>Barbossa: Oh, not you. We named the monkey Jack.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: That''s not true. I am not obsessed with treasure.<br>Jack Sparrow: Not all treasure is silver and gold, mate.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Harbormaster: Hold up there, you. It''s a shilling to tie up your boat at the dock... and I shall need to know your name.<br>Jack Sparrow: What do you say to three shillings and we forget the name.<br>Harbormaster: Welcome to Port Royal, Mr. Smith.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: No one. He''s no one. Distant cousin of my Aunt''s nephew twice removed. Lovely singing voice. Eunuch.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: You''re pirates. Hang the code, and hang the rules. They''re more like guidelines anyway.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Elizabeth!<br>[Turns to Gibbs]<br>Jack Sparrow: Hide the rum. ');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: We are very much alike, you and I, I and you... us.<br>Elizabeth Swann: Oh. Except for a sense of honor and decency and a moral center. And personal hygiene.<br>Jack Sparrow: [Sniffs his armpit and looks back] Trifles. ');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: There will come a moment when you will have a chance to show it. To do the right thing.<br>Jack Sparrow: I love those moments. I like to wave at them as they pass by. ');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: [to Elizabeth] One word love; curiosity. You long for freedom. You long to do what you want to do because you want it. To act on selfish impulse. You want to see what it''s like. One day you won''t be able to resist.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: Oh fine! Let''s just haul out our swords and start banging away at each other! That will solve everything!');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: I''ve had it! I''ve had it with wobbly-legged, rum-soaked PIRATES!');
INSERT INTO fun (type, content) VALUES ('pirates', 'Anamaria: It was a good plan... up ''til now.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth: Well you may tell the captain that I am disinclined to acquiesce to his request.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Any man who falls behind, is left behind.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Take what ye can!<br>Mr. Gibbs: Give nothin'' back!');
INSERT INTO fun (type, content) VALUES ('pirates', 'Mr. Gibbs: Curse ya for breathin, ya slack-jawed idiot!');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: I think we''ve all arrived at a very special place... spiritually... ecumenically... grammatically');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: You didn''t beat me. You ignored the rules of engagement! In a fair fight, I''d kill you!<br>Jack Sparrow: Well, that''s not much incentive for me to fight fair then, is it?');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Why is the rum gone?');
INSERT INTO fun (type, content) VALUES ('pirates', 'Will Turner: This is either madness, or brilliance.<br>Jack Sparrow: It''s funny how often those traits coincide.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Wherever we want to go, we go. That''s what a ship is, you know. It''s not just a keel and a hull and sails; that''s what a ship needs. Not what a ship is. What the Black Pearl really is, is freedom.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: A wedding? I love weddings! Drinks all around!');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: You like pain? Try wearing a corset.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Elizabeth Swann: That''s it, then? That''s the secret grand adventure of the infamous Jack Sparrow - you spent three days lying on a beach drinking rum?<br>Jack Sparrow: Welcome to the Caribbean, love.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Now you can either accept that your father was a pirate and a good man, or me I could just leave you there to drown. Your choice.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Lord Cutler Beckett: It''s nothing personal, Jack. It''s just good business.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Send this pestilent, traitorous, cow-hearted, yeasty codpiece to the brig.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Davy Jones: You will not forestall my judgment!');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: She''s safe, just like I promised. She''s all set to marry Norrington, just like she promised. And you get to die for her, just like you promised. So we''re all men of our word really... except for, of course, Elizabeth, who is in fact, a woman.');
INSERT INTO fun (type, content) VALUES ('pirates', 'Jack Sparrow: Stop blowing holes in my ship!');