{
  "add_success": {
    "en_US": "Character <highlight>{char}<end> added as <highlight>{rank}<end> successfully.",
    "de_DE": "Der Charakter <highlight>{char}<end> wurde erfolgreich zum <highlight>{rank}<end> ernannt."
  },
  "add_fail": {
    "en_US": "Could not add character <highlight>{char}<end> as <highlight>{rank}<end>.",
    "de_DE": "Der Charakter <highlight>{char}<end> konnte nicht zum <highlight>{rank}<end> ernannt werden."
  },
  "rem_success": {
    "en_US": "Character <highlight>{char}<end> removed as <highlight>{rank}<end> successfully.",
    "de_DE": "Der Charakter <highlight>{char}<end> ist nun kein <highlight>{rank}<end> mehr."
  },
  "rem_fail": {
    "en_US": "Could not remove character <highlight>{char}<end> as <highlight>{rank}<end>.",
    "de_DE": "Dem Charakter <highlight>{char}<end> konnte der Rang <highlight>{rank}<end> nicht entfernt werden."

  }
}