{
  "add_success": {
    "en_US": "Character <highlight>{char}<end> added as <highlight>{rank}<end> successfully."
  },
  "add_fail": {
    "en_US": "Could not add character <highlight>{char}<end> as <highlight>{rank}<end>."
  },
  "rem_success": {
    "en_US": "Character <highlight>{char}<end> removed as <highlight>{rank}<end> successfully."
  },
  "rem_fail": {
    "en_US": "Could not remove character <highlight>{char}<end> as <highlight>{rank}<end>."

  }
}