{
  "add_success": {
    "en_US": "Character <highlight>{char}</highlight> added as <highlight>{rank}</highlight> successfully.",
    "de_DE": "Der Charakter <highlight>{char}</highlight> wurde erfolgreich zum <highlight>{rank}</highlight> ernannt."
  },
  "add_fail": {
    "en_US": "Could not add character <highlight>{char}</highlight> as <highlight>{rank}</highlight>.",
    "de_DE": "Der Charakter <highlight>{char}</highlight> konnte nicht zum <highlight>{rank}</highlight> ernannt werden."
  },
  "rem_success": {
    "en_US": "Character <highlight>{char}</highlight> removed as <highlight>{rank}</highlight> successfully.",
    "de_DE": "Der Charakter <highlight>{char}</highlight> ist nun kein <highlight>{rank}</highlight> mehr."
  },
  "rem_fail": {
    "en_US": "Could not remove character <highlight>{char}</highlight> as <highlight>{rank}</highlight>.",
    "de_DE": "Dem Charakter <highlight>{char}</highlight> konnte der Rang <highlight>{rank}</highlight> nicht entfernt werden."

  }
}
